### ISSUE TITLE
incorrect initial configuration

### ISSUE THREAD

**Issue by ginoromano** [music-assistant/hass-music-assistant#270] opened 2022-05-31 10:53 UTC
first of all, congratulations on your project. it is really interesting and useful.
I am having problems in the first configuration phase.
when I add the integration to home assistant it starts loading the configuration.
This upload takes a very long time until it goes into error.
in the logs it looks like this:
 Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 12:37:20 (1 occurrences)
Last logged: 12:37:20
Unable to install package music-assistant==1.1.19: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [22 lines of output] running bdist_wheel running build running build_py running egg_info writing src/greenlet.egg-info/PKG-INFO writing dependency_links to src/greenlet.egg-info/dependency_links.txt writing requirements to src/greenlet.egg-info/requires.txt writing top-level names to src/greenlet.egg-info/top_level.txt reading manifest file 'src/greenlet.egg-info/SOURCES.txt' reading manifest template 'MANIFEST.in' no previously-included directories found matching 'docs/_build' warning: no files found matching '*.py' under directory 'appveyor' warning: no previously-included files matching '*.pyc' found anywhere in distribution warning: no previously-included files matching '*.pyd' found anywhere in distribution warning: no previously-included files matching '*.so' found anywhere in distribution warning: no previously-included files matching '.coverage' found anywhere in distribution adding license file 'LICENSE' adding license file 'LICENSE.PSF' adding license file 'AUTHORS' running build_ext building 'greenlet._greenlet' extension error: command 'gcc' failed: No such file or directory [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for greenlet error: subprocess-exited-with-error × Running setup.py install for greenlet did not run successfully. │ exit code: 1 ╰─> [24 lines of output] running install /usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn( running build running build_py running egg_info writing src/greenlet.egg-info/PKG-INFO writing dependency_links to src/greenlet.egg-info/dependency_links.txt writing requirements to src/greenlet.egg-info/requires.txt writing top-level names to src/greenlet.egg-info/top_level.txt reading manifest file 'src/greenlet.egg-info/SOURCES.txt' reading manifest template 'MANIFEST.in' no previously-included directories found matching 'docs/_build' warning: no files found matching '*.py' under directory 'appveyor' warning: no previously-included files matching '*.pyc' found anywhere in distribution warning: no previously-included files matching '*.pyd' found anywhere in distribution warning: no previously-included files matching '*.so' found anywhere in distribution warning: no previously-included files matching '.coverage' found anywhere in distribution adding license file 'LICENSE' adding license file 'LICENSE.PSF' adding license file 'AUTHORS' running build_ext building 'greenlet._greenlet' extension error: command 'gcc' failed: No such file or directory [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure × Encountered error while trying to install package. ╰─> greenlet note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure. WARNING: You are using pip version 22.0.3; however, version 22.1.1 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

I have been fighting for 3 days. I can't understand what the problem is. I would be very able if you were able to help me out.

Luigi

**Comment by marcelveldt** [comment] 2022-05-31 10:55
duplicate of #268 

One of the dependencies (greenlet) can not be found nor built for your platform.
Please let me know the details of your architecture (such as processor/model etc)

**Comment by marcelveldt** [comment] 2022-05-31 15:45
@ginoromano first of all, I can't read all of above because it is not in English but do note that there's an error in there that your setup is unsupported. No idea if that is related/the cause but I thought good to mention.

Unfortunately there's not a lot I kind do. One of the requirements for Music Assistant is "databases", which in turn has a requirement called "sqlalchemy". SQLAlchemy has a requirement "greenlet" and that is failing to setup on your setup due to absent prebuilt wheels and it is not able to build because of missing compiler/dev tools.

The very strange thing however is that Home Assistant itself requires the exact same version of sqlalchemy so that package should already be installed. What you could do is check the "deps" subfolder of your "config" folder. Maybe there's some old stuff in there.

**Comment by marcelveldt** [comment] 2022-06-01 10:29
I'm afraid there is not a lot I can do to help here. You are running an unsupported configuration, as clearly stated in your screenshots (in red font even). If you're running an unsupported config such as architecture or host OS, there is a chance you run into trouble and without being rude I want to say to you that if you're technical enough to go for the supervised route instead of HA OS, you also have to deal with these kind of compatibility issues.

That said, as a last resort I have now pinned version 1.1.1. of greenlet in the manifest of Music Assistant, this may help (or not, I don't know) and that was the last thing I could try. This small fix is available in version 1.1.22 of Music Assistant, now available on HACS.

If that still doesn't work and you really want to give MA a try, I suggest you to get a supported configuration by either installing HA OS on your device or changing other bits that make the text "Unsupported" go away.

I hope you understand my point of view.

Thanks!

**Closed by marcelveldt** 2022-06-01 10:29 UTC
