### ISSUE TITLE
v1.1.5: lost some artists while browsing artists

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#185] opened 2022-05-18 10:08 UTC
Hi

I lost three artists in my artist view (when from 5550 to 547 artists). I only was browsing some detailed info in the artist tab.
Saw this error in the log:
```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/mass/panel.py:89
Integration: Music Assistant (documentation, issues)
First occurred: 12:04:41 (4 occurrences)
Last logged: 12:04:59

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/config/custom_components/mass/panel.py", line 89, in get
    data = await mass.metadata.get_thumbnail(url, size=size)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/metadata/__init__.py", line 231, in get_thumbnail
    thumbnail = await create_thumbnail(self.mass, path, size)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/images.py", line 37, in create_thumbnail
    raise FileNotFoundError(f"Image not found: {path}")
FileNotFoundError: Image not found: /media/MP3_normalized/Various/Typisch - Tachtig! CD4/Mp3/Typisch - 17 - Adam 

```

**Comment by marcelveldt** [comment] 2022-05-18 14:13
What a strange path.. You would expect either an image filename or a mp3/flac file with embedded image.
Or did the file extension got lost in translation?

**Comment by marcelveldt** [comment] 2022-05-19 06:35
I think/hope this is resolved in 1.1.7 as I can't reproduce it now.

**Comment by marcelveldt** [comment] 2022-05-19 08:21
I just reproduced this one on my dev machine by accident.

**Comment by marcelveldt** [comment] 2022-05-19 09:15
Ouch this was a stupid mistake. When you open the details page of an artist or album it will fetch the full details including metadata if that has never been done before. At that point (and only if you have multiple music providers active) it could overwrite the "in library" property. For example the artist is on disk so considered "in library" but not a favorite on Spotify. There's no predicted order in which music providers are ordered so if Spotify comes last, that wins.

I'm going to adjust the logic so that metadata refreshes may never overwrite the "in library" preference

**Comment by erkr** [comment] 2022-05-19 18:18
Keep an eye on this one for a few days. Thx!

**Closed** 2022-05-22 11:04 UTC
