### ISSUE TITLE
Integration not finding media players due to KeyError: Invalid player_id:

### ISSUE THREAD

**Issue by markusg1234** [music-assistant/hass-music-assistant#2945] opened 2024-09-19 23:58 UTC
### What version of Music Assistant has the issue?

2.2.5

### What version of the Home Assistant Integration have you got installed?

2024.9.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When Adding either a google cast or vlc media player a keyerror occurs.
This causes no media player to be found in the Music Assistant Integration.

In an earlier version of Music Assistant this problem didn't occur.

### How to reproduce

1) Select Home Assistant media players in Music Assistant and save.
2) Error occurs in Music Assistant Log.
3) No media player entities are displayed in the Music Assistant Integration. 

### Music Providers

RadioBrowser

### Player Providers

Google Nest Mini via Google Cast   
VLC media player via Telnet

### Full log output

[logfile.txt](https://github.com/user-attachments/files/17068001/logfile.txt)

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by josh208** [comment] 2024-09-20 00:28
I just want to add that I got the same error (Invalid player_id) with a DLNA mediaplayer, and an ESPHome mediaplayer. In my case I was able to select the mediaplayers in the HA Player Provider config, but then the error was logged and no players were available.

**Comment by canamman** [comment] 2024-09-20 04:15
Seeing same issue here
"
self.mass.config.set_raw_player_config_value(
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/config.py", line 619, in set_raw_player_config_value
    raise KeyError(msg)
KeyError: 'Invalid player_id: media_player.mpd'
"

**Comment by GSVil** [comment] 2024-09-20 06:03
Rolled back to 2.2.1, this broke somewhere between that and 2.2.5. I skipped a few versions, so can't really say when it broke 😊

**Comment by jd1** [comment] 2024-09-20 07:48
I had a similar issue `mashumaro.exceptions.InvalidFieldValue: Field "current_item" of type Optional[QueueItem] in PlayerQueue has invalid value` after updating to 2.2.5. Rolling back to 2.2.4 solved it.

**Comment by falcald** [comment] 2024-09-23 01:42
Same issue here:

```2024-09-22 22:41:50.051 INFO (MainThread) [music_assistant] Loaded player provider Home Assistant MediaPlayers
2024-09-22 22:41:50.121 WARNING (MainThread) [music_assistant] Exception in task Task-540 - target: <coroutine object HomeAssistantPlayers.loaded_in_mass at 0x7f7a48bcd0>: 'Invalid player_id: media_player.vlc_telnet'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/hass_players/__init__.py", line 197, in loaded_in_mass
    await self._setup_player(state, entity_registry, device_registry)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/hass_players/__init__.py", line 417, in _setup_player
    self.mass.config.set_raw_player_config_value(
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/config.py", line 619, in set_raw_player_config_value
    raise KeyError(msg)
KeyError: 'Invalid player_id: media_player.vlc_telnet'```

**Comment by pvodoz** [comment] 2024-09-23 03:00
Same issue and my logs:
`2024-09-21 19:34:55.305 INFO (MainThread) [music_assistant] Loaded player provider Home Assistant MediaPlayers
2024-09-21 19:34:55.336 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/hass_players/init.py", line 197, in loaded_in_mass
await self._setup_player(state, entity_registry, device_registry)
File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/hass_players/init.py", line 417, in _setup_player
self.mass.config.set_raw_player_config_value(
File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/config.py", line 619, in set_raw_player_config_value
raise KeyError(msg)
KeyError: 'Invalid player_id: media_player.salon'
`

Core 2024.9.2
Supervisor 2024.09.1
Operating System 13.1
Interface utilisateur 20240909.1
Music Assistant Server Current version: 2.2.5
Music Assistant Integration 2024.9.1

**Comment by maczekg** [comment] 2024-09-23 18:08
Same issue here. 
Home Assistant 2024.9.2 / docker 
Music Assistant Server 2.2.5 / docker
MAss integration 2024.9.1.
Rolled back to 2.2.4 solved the issue.

**Comment by marcelveldt** [comment] 2024-09-23 21:41
This issue should be fixed in the new beta: 2.3.0b27 - if the fix is confirmed working, we'll also roll out a patch release for stable

**Comment by OzGav** [comment] 2024-09-23 22:29
This is confirmed fixed.

**Closed by OzGav** 2024-09-23 22:29 UTC
Labels: bug, HA Integration

**Comment by markusg1234** [comment] 2024-09-24 05:17
Thankyou, can also confirm it is now working correctly.

**Comment by LumCrafter** [comment] 2024-09-24 20:16
I still seem to be getting the error? KeyError: 'Invalid player_id: media_player.vlc_telnet' 
Home Assistant 2024.9.3
Music Assistant Server 2.2.5
Mass integration 2024.9.1.
Is it because of 2024.9.3?

**Comment by OzGav** [comment] 2024-09-24 21:44
@LumCrafter it is fixed in the beta

**Comment by formatBCE** [comment] 2024-09-30 20:51
But no patch release for stable? @OzGav

**Comment by marcelveldt** [comment] 2024-09-30 20:56
We'll publish a patch for stable soon

**Comment by formatBCE** [comment] 2024-09-30 20:58
Love you guys.
