### ISSUE TITLE
Parsing local files stopped after a few minutes

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#113] opened 2022-05-10 09:14 UTC
I have a large local collection and just configured them in. The parsing stopped after ca 2 minutes with these errors:
![image](https://user-images.githubusercontent.com/4363599/167593493-50f6c8fb-726c-4e9e-adb6-c954c7216a26.png)
Clearly my ID3 tags are not fit to import (many files skipped). But here the detailed log:
```
...
2022-05-10 11:00:55 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Type O Negative/Type o negative - Out of fire.mp3
2022-05-10 11:01:07 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Behemoth/2004 -Demigod/01 - Behemoth - Sculpting the throne ov Seth.mp3
2022-05-10 11:01:07 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Behemoth/2004 -Demigod/01 - Behemoth - Sculpting the throne ov Seth.mp3
2022-05-10 11:01:07 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Behemoth/2004 -Demigod/01 - Behemoth - Sculpting the throne ov Seth.mp3
2022-05-10 11:01:25 ERROR (MainThread) [music_assistant.mass] Job [Library sync of albums for provider Filesystem] failed with error 'NoneType' object has no attribute 'musicbrainz_id'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 397, in _library_items_sync
    db_item = await controller.add_db_item(prov_item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 121, in add_db_item
    if album.artist.musicbrainz_id and album.artist.provider != "database":
AttributeError: 'NoneType' object has no attribute 'musicbrainz_id'
2022-05-10 11:01:25 ERROR (MainThread) [music_assistant.mass] Job [Library sync of tracks for provider Filesystem] failed with error 'NoneType' object has no attribute 'musicbrainz_id'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 397, in _library_items_sync
    db_item = await controller.add_db_item(prov_item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/tracks.py", line 145, in add_db_item
    or await self.mass.music.albums.add_db_item(track.album)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 121, in add_db_item
    if album.artist.musicbrainz_id and album.artist.provider != "database":
AttributeError: 'NoneType' object has no attribute 'musicbrainz_id'
2022-05-10 11:01:26 WARNING (MainThread) [music_assistant.mass.metadata] Unable to get musicbrainz ID for artist Madonna !
2022-05-10 11:01:30 WARNING (MainThread) [music_assistant.mass.metadata] Unable to get musicbrainz ID for artist Original Soundtrack !
2022-05-10 11:01:36 WARNING (MainThread) [music_assistant.mass.metadata] Unable to get musicbrainz ID for artist  !
2022-05-10 11:01:36 ERROR (MainThread) [music_assistant.mass.audiodb] Failed to retrieve artist-mb.php
2022-05-10 11:01:36 ERROR (MainThread) [music_assistant.mass] Job [Library sync of artists for provider Filesystem] failed with error .
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 390, in _library_items_sync
    db_item = await controller.get(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/media_controller.py", line 68, in get
    return await self.add(details)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/artists.py", line 67, in add
    db_item = await self.add_db_item(item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/artists.py", line 120, in add_db_item
    assert artist.musicbrainz_id
AssertionError
```

**Comment by marcelveldt** [comment] 2022-05-10 09:16
duplicate of #108 
I'm going to work on the files provider this afternoon. I need to proper guard it for the not so happy flow cases where a tag is missing etc. To be continued!

Thanks for the patience and help testing!!

**Comment by erkr** [comment] 2022-05-10 09:19
I will disable the local files till you have a new version 👍

**Comment by erkr** [comment] 2022-05-10 09:30
Additional observation that could be useful for your planned rework. Several skipped files are logged with the same error 2 are 3 times:
```
2022-05-10 11:00:43 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Linkin Park/Reanimation/Linkin Park - 20 - Krwlng.mp3
2022-05-10 11:00:43 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Linkin Park/Reanimation/Linkin Park - 20 - Krwlng.mp3
2022-05-10 11:00:43 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Linkin Park/Reanimation/Linkin Park - 20 - Krwlng.mp3
2022-05-10 11:00:44 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Boyz II Men/Legacy/Boyz II Men - 13 - Pass you by.mp3
2022-05-10 11:00:44 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Boyz II Men/Legacy/Boyz II Men - 13 - Pass you by.mp3
2022-05-10 11:00:44 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Boyz II Men/Legacy/Boyz II Men - 13 - Pass you by.mp3
2022-05-10 11:00:53 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Manowar/manowar - sign of the hammer/8-Guyana (cult of the Damned).mp3
2022-05-10 11:00:53 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Manowar/manowar - sign of the hammer/8-Guyana (cult of the Damned).mp3
2022-05-10 11:00:53 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Manowar/manowar - sign of the hammer/1-All men play on.mp3
2022-05-10 11:00:53 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Albums/Manowar/manowar - sign of the hammer/1-All men play on.mp3
```

**Comment by nagyrobi** [comment] 2022-05-10 09:31
Same here, just for extra feedback here's my log:

```
2022-05-10 11:17:54 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 726, in queue_stream_prepare
    next_item = self._items[start_from_index]
TypeError: list indices must be integers or slices, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/stream.py", line 136, in serve_queue_stream
    start_streamdetails = await queue.queue_stream_prepare()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 728, in queue_stream_prepare
    raise QueueEmpty() from err
music_assistant.models.errors.QueueEmpty
2022-05-10 11:18:39 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 726, in queue_stream_prepare
    next_item = self._items[start_from_index]
TypeError: list indices must be integers or slices, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/stream.py", line 136, in serve_queue_stream
    start_streamdetails = await queue.queue_stream_prepare()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 728, in queue_stream_prepare
    raise QueueEmpty() from err
music_assistant.models.errors.QueueEmpty
2022-05-10 11:19:24 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 726, in queue_stream_prepare
    next_item = self._items[start_from_index]
TypeError: list indices must be integers or slices, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/stream.py", line 136, in serve_queue_stream
    start_streamdetails = await queue.queue_stream_prepare()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 728, in queue_stream_prepare
    raise QueueEmpty() from err
music_assistant.models.errors.QueueEmpty
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/BLACK EYED PEAS - SHUT UP.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/BLACK EYED PEAS - SHUT UP.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/BLACK EYED PEAS - SHUT UP.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/50 Cent - In the club.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/50 Cent - In the club.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/50 Cent - In the club.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/OUTLANDISH - WALOU.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/OUTLANDISH - WALOU.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/OUTLANDISH - WALOU.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/WAYNE WONDER - BOUNCE ALONG.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/WAYNE WONDER - BOUNCE ALONG.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/WAYNE WONDER - BOUNCE ALONG.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/Shaggy - Strenght of a woman.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/Shaggy - Strenght of a woman.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/Shaggy - Strenght of a woman.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/Jay - Z feat Beyonce - Bonnie & Clyde.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/Jay - Z feat Beyonce - Bonnie & Clyde.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/Jay - Z feat Beyonce - Bonnie & Clyde.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/OBIE TRICE - THE SETUP.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/OBIE TRICE - THE SETUP.mp3
2022-05-10 11:24:32 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Beat/OBIE TRICE - THE SETUP.mp3
2022-05-10 11:24:33 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Tuborg - Smash Mouth - Walking On The Sun.mp3
2022-05-10 11:24:33 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Tuborg - Smash Mouth - Walking On The Sun.mp3
2022-05-10 11:24:33 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Tuborg - Smash Mouth - Walking On The Sun.mp3
2022-05-10 11:24:33 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Connex - NSK feat A. Andreescu - De Mii de Ori.mp3
2022-05-10 11:24:33 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Connex - NSK feat A. Andreescu - De Mii de Ori.mp3
2022-05-10 11:24:33 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Connex - NSK feat A. Andreescu - De Mii de Ori.mp3
2022-05-10 11:24:34 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/elite - Louis Armstrong and Ella Fitzgerald -  Dancing Cheek to Chee.mp3
2022-05-10 11:24:34 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/elite - Louis Armstrong and Ella Fitzgerald -  Dancing Cheek to Chee.mp3
2022-05-10 11:24:34 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/elite - Louis Armstrong and Ella Fitzgerald -  Dancing Cheek to Chee.mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/064 - New Radicals - You Get What You  Give.mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/064 - New Radicals - You Get What You  Give.mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/064 - New Radicals - You Get What You  Give.mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/murfatlar - BINO - Mama Leone.mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/murfatlar - BINO - Mama Leone.mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/murfatlar - BINO - Mama Leone.mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/one - Meredith Brooks - Bitch.MP3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/one - Meredith Brooks - Bitch.MP3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/one - Meredith Brooks - Bitch.MP3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/coca cola - One Track Mind - I Like You (ADs Soundtrack).mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/coca cola - One Track Mind - I Like You (ADs Soundtrack).mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/coca cola - One Track Mind - I Like You (ADs Soundtrack).mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/la coste - Natasha Thomas & Sugar Daddy - It' s over now.mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/la coste - Natasha Thomas & Sugar Daddy - It' s over now.mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/la coste - Natasha Thomas & Sugar Daddy - It' s over now.mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Coca Cola-Joey Diggs - Always Coca-Cola.MP3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Coca Cola-Joey Diggs - Always Coca-Cola.MP3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Coca Cola-Joey Diggs - Always Coca-Cola.MP3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Ursus - Shirley Bassey - Where Do I Begin (Love Story).mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Ursus - Shirley Bassey - Where Do I Begin (Love Story).mp3
2022-05-10 11:24:35 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Ursus - Shirley Bassey - Where Do I Begin (Love Story).mp3
2022-05-10 11:24:36 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Connex - Nina Simone- Sinnerman (The Thomas Crown Affair).mp3
2022-05-10 11:24:36 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Connex - Nina Simone- Sinnerman (The Thomas Crown Affair).mp3
2022-05-10 11:24:36 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Connex - Nina Simone- Sinnerman (The Thomas Crown Affair).mp3
2022-05-10 11:24:36 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Allianz - Tiriac - Clannad - I Will Find You.mp3
2022-05-10 11:24:36 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Allianz - Tiriac - Clannad - I Will Find You.mp3
2022-05-10 11:24:36 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Allianz - Tiriac - Clannad - I Will Find You.mp3
2022-05-10 11:24:36 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Connex - Let's All Get Drunk - Afroman.mp3
2022-05-10 11:24:36 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Connex - Let's All Get Drunk - Afroman.mp3
2022-05-10 11:24:36 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Connex - Let's All Get Drunk - Afroman.mp3
2022-05-10 11:24:36 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/orange - Weezer - Islands In The Sun.mp3
2022-05-10 11:24:36 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/orange - Weezer - Islands In The Sun.mp3
2022-05-10 11:24:36 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/orange - Weezer - Islands In The Sun.mp3
2022-05-10 11:24:37 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Orange - Blur - The Universal.mp3
2022-05-10 11:24:37 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Orange - Blur - The Universal.mp3
2022-05-10 11:24:37 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Orange - Blur - The Universal.mp3
2022-05-10 11:24:37 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Primola - Nemos - Mir.mp3
2022-05-10 11:24:37 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Primola - Nemos - Mir.mp3
2022-05-10 11:24:37 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Primola - Nemos - Mir.mp3
2022-05-10 11:24:37 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Orange - Frou Frou - Must Be Dreaming.mp3
2022-05-10 11:24:37 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Orange - Frou Frou - Must Be Dreaming.mp3
2022-05-10 11:24:37 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/Orange - Frou Frou - Must Be Dreaming.mp3
2022-05-10 11:24:37 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/izvorul alb - Enya - Orinoco Flow.mp3
2022-05-10 11:24:37 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/izvorul alb - Enya - Orinoco Flow.mp3
2022-05-10 11:24:37 WARNING (MainThread) [music_assistant.mass.music.filesystem] Skipping track due to invalid ID3 tags: /media/Reklámzene/izvorul alb - Enya - Orinoco Flow.mp3
2022-05-10 11:24:38 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/process.py", line 103, in write
    await self._proc.stdin.drain()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 197, in _drain_helper
    await waiter
BrokenPipeError
2022-05-10 11:24:38 ERROR (MainThread) [music_assistant.mass] Job [Library sync of tracks for provider Filesystem] failed with error 'NoneType' object has no attribute 'musicbrainz_id'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 397, in _library_items_sync
    db_item = await controller.add_db_item(prov_item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/tracks.py", line 145, in add_db_item
    or await self.mass.music.albums.add_db_item(track.album)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 121, in add_db_item
    if album.artist.musicbrainz_id and album.artist.provider != "database":
AttributeError: 'NoneType' object has no attribute 'musicbrainz_id'
2022-05-10 11:24:38 ERROR (MainThread) [music_assistant.mass] Job [Library sync of albums for provider Filesystem] failed with error 'NoneType' object has no attribute 'musicbrainz_id'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 397, in _library_items_sync
    db_item = await controller.add_db_item(prov_item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 121, in add_db_item
    if album.artist.musicbrainz_id and album.artist.provider != "database":
AttributeError: 'NoneType' object has no attribute 'musicbrainz_id'
2022-05-10 11:24:39 WARNING (MainThread) [music_assistant.mass.metadata] Unable to get musicbrainz ID for artist Reamonn !
```
I think tracks with missing ID3 tags shouldn't be skipped. They are worth adding to an "Uncategorized" collection so they can still be played.

**Comment by erkr** [comment] 2022-05-10 09:31
Do you want some of these files to check what goes wrong?!

**Closed** 2022-05-10 20:48 UTC
