### ISSUE TITLE
Impossible to update MA from 2022.7.2

### ISSUE THREAD

**Issue by SeByDocKy** [music-assistant/hass-music-assistant#769] opened 2022-07-30 09:51 UTC
### What version of Music Assistant has the issue?

2022.7.2

### The problem

3 or 4  days ago a 2022.7.3 patch appeared as update... Unfortunatly after pressing the button, nothing was done and from now got an error "unknow error" when trying to update to the 2022.7.4.

I deleted the integration and even the mass folder... but in hacs I can't still update or completly delete MA to a full reinstall.

### How to reproduce

from a HAssio/odroid being from MA 2022.7.2 to 2022.7.4

### Relevant log output

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:1076
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 11:02:18 AM (1 occurrences)
Last logged: 11:02:18 AM

<Integration music-assistant/hass-music-assistant> GitHub returned 404 for https://api.github.com/repos/music-assistant/hass-music-assistant/git/trees/patch-2022.7.3

### What version of Home Assistant Core are your running

2022.7.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment] 2022-07-30 10:16
A number of people are having thi issue. It is likely an issue in HACS. Here are the soluwiong posted on discord:
-----------------------------------------
I deleted all MA files except the dreaded init.py, and got a config error on startup. I did show the update notification for the new beta. I clikced that, and lo and behold, it seems to have updated correctly now!
-----------------------------------------
I had this exact issue yesterday and reported above - my fix was to disable HACS, reboot, reenable HACS and refresh cache - I could then see the MA page in HACS and update. Looks like your method did this manually ..
-----------------------------------------

**Comment by SeByDocKy** [comment] 2022-07-30 10:24
> A number of people are having thi issue. It is likely an issue in HACS. Here are the solutions posted on discord:
> 
> ===========================
> 
> I deleted all MA files except the dreaded init.py, and got a config error on startup. I did show the update notification for the new beta. I clikced that, and lo and behold, it seems to have updated correctly now!
> 
> ===========================
> 
> I had this exact issue yesterday and reported above - my fix was to disable HACS, reboot, reenable HACS and refresh cache - I could then see the MA page in HACS and update. Looks like your method did this manually ..
> 
> ===========================

I tried last solution... still gor error :(

**Comment by FrankJaco** [comment] 2022-07-30 10:35
I noticed this issue too, but figured it was perhaps self-induced as I was playing around with different versions manually installing them etc.  But one thing that I did notice is for me it was ONLY when trying to upgrade from the companion that the issue occured. Upgrading via a PC with a Chrome browser worked just fine.  I wonder if the others that experienced the problem were using the companion App as well? And if so, perhaps this is a clue?

**Comment by SeByDocKy** [comment] 2022-07-30 10:38
> I noticed this issue too, but figured it was perhaps self-induced as I was playing around with different versions manually installing them etc. But one thing that I did notice is for me it was ONLY when trying to upgrade from the companion that the issue occured. Upgrading via a PC with a Chrome browser worked just fine. I wonder if the others that experienced the problem were using the companion App as well? And if so, perhaps this is a clue?

I tried for both :( ( .... still the error :(.... If I remove completly HACS maybe it can solve the problem ?

**Comment by SeByDocKy** [comment] 2022-07-30 11:26
I remived HACS and reinstall everything.... Still fucked :( .... I remove the mass folder... and the same panel in HACS asking to upgrade with the for ever error message :(

**Comment by SeByDocKy** [comment] 2022-07-30 14:07
seems I have a missing xxxxxxxxxx.hacs file in /config/.storage/hacs folder ..... If anyone  can share one of MA with me, I can maybe fix my problem

**Comment by OzGav** [comment] 2022-07-30 23:13
I see a bunch of these in my folder so not sure which one you would need.

**Comment by SeByDocKy** [comment] 2022-07-31 07:12
> I see a bunch of these in my folder so not sure which one you would need.

Ok when you click in HACS on music assistant, it opened a page with all information of the integration. Look to the URL of this opened page should be something like : https://xxxxxxxx.duckdns.org/hacs/repository/yyyyyyyyyy

The  .hacs file in  /config/.storage/hacs folder   is the yyyyyyyyyyy.hacs.

I hope I was clear enough :)

**Comment by OzGav** [comment] 2022-07-31 07:16
Unfortunately I don't know how HACS works but I see http://192.168.1.165:8123/hacs/repository/476357279 and there is no 476357279.hacs

**Comment by OzGav** [comment] 2022-07-31 07:21
Here is the entry from `hacs.repositories` in case that helps:

```
    "476357279": {
      "repository_manifest": {
        "name": "Music Assistant",
        "render_readme": true,
        "zip_release": true,
        "filename": "mass.zip",
        "hide_default_branch": true,
        "homeassistant": "2022.7.0"
      },
      "authors": [
        "@marcelveldt"
      ],
      "category": "integration",
      "description": "Turn your Home Assistant instance into a jukebox, hassle free streaming of your favorite media to Home Assistant media players.",
      "domain": "mass",
      "downloads": 1128,
      "etag_repository": "W/\"47511fec14eb4779bddf7b5f6ff910b4fd18a5468a86ef86bc1975a9e7cadd66\"",
      "full_name": "music-assistant/hass-music-assistant",
      "last_updated": "2022-07-30T18:25:08Z",
      "stargazers_count": 251,
      "topics": [
        "music-library",
        "music-player"
      ],
      "config_flow": true,
      "default_branch": "main",
      "installed_commit": "54ac0b3",
      "installed": true,
      "last_commit": "54ac0b3",
      "last_version": "2022.7.4",
      "manifest_name": "Music Assistant",
      "open_issues": 12,
      "published_tags": [
        "2022.7.4",
        "2022.7.3",
        "2022.7.2",
        "2022.7.1",
        "2022.7.0"
      ],
      "pushed_at": "2022-07-30T18:25:08",
      "releases": true,
      "version_installed": "2022.7.4",
      "last_fetched": 1659247564.307553
    },
```

**Comment by SeByDocKy** [comment] 2022-07-31 10:32
> 

Thanks, maybe it will help me :) ... I will check that :)

**Comment by libby2cm** [comment] 2022-08-01 19:24
There is definitely an issue here.  I tried installing 2022.8.0b2 first, and got the invalid HA version error.  I uninstalled it, installed 2022.7.4, worked fine.  Was prompted for update back to 2022.8.0b2, which i did, then got the HA version error again.

**Comment by marcelveldt** [comment] 2022-08-01 19:26
There is no issue. The error is very clear.

**MA version 2022.8 is compatible with HA version 2022.8**

So either upgrade HA to 2022.8 or wait and stay on MA stable 2022.7...

**Comment by libby2cm** [comment] 2022-08-04 23:49
@marcelveldt unfortunately, your implementation is not.  New patch out today, 2022.8.1, and mass is broke again.  Also, end user can't control when we get prompted to update.  If there is a breaking change in your code to necessitate hard coding a dependency to a version, fine, create a tag or branch tied to that release.  

This plugin 'seizes' my devices too, so every time this happens it breaks my cast entities.  Ripping this thing out for a last time.

**Comment by OzGav** [comment] 2022-08-05 02:34
Keeping in mind that Marcel has provided this impressive component for free and does it all in his free time I am sure he will fix this issue very soon for everyone. As it doesn’t sound like we will be hearing from you again I am closing this issue.

**Comment by HFeenstra** [comment] 2022-08-05 08:34
> A number of people are having this issue. It is likely an issue in HACS. Here are the solutions posted on discord:
> 
> ===========================
> 
> I deleted all MA files except the dreaded init.py, and got a config error on startup. I did show the update notification for the new beta. I clikced that, and lo and behold, it seems to have updated correctly now!
> 
> ===========================
> 
> I had this exact issue yesterday and reported above - my fix was to disable HACS, reboot, reenable HACS and refresh cache - I could then see the MA page in HACS and update. Looks like your method did this manually ..
> 
> ===========================

Hello, Can we please reopen this issue?
I have the exact same error. I tried all the above suggestions, reload page, clear cache, removed the whole mass folder and re-added it to it, disabled, reboot and enabled hacs and so on.

So far I have not seen this behaviour with other integrations. 
I have Home Assistant 2022.8.1 installed and can update other hacs integrations, no problem; but this one I can not update to the latest mass 2022.8.1 version.

I have no intention at all to yell or scream at the makers of this add on :) 
Hopefully someone can get me in some direction to get this fixed.

**Comment by marcelveldt** [comment] 2022-08-05 08:44
@libby2cm I suggest you to uninstall Music Assistant now and never ever install it back nor I do want to see you again on the support channels until you change your tone of voice. This is FREE software I create in my spare time and yes, that allows me to make mistakes because well, private life comes in between, busy jobs and I do not have a whole team of testers. You should be ashamed of yourself!

@HFeenstra can you please open a new issue or contact me on discord ?
I fixed the version check mess for real this morning in the 2022.8.1 patch release but I can't fix the broken HACS installs unfortunately. I believe this is a HACS issue btw because its data is just corrupt. A couple of users had success in repairing that.

**Comment by HFeenstra** [comment] 2022-08-05 09:25
@marcelveldt thanks for the update. 
Sure I will look for you on discord. You use your name also on Discord?

**Comment by SeByDocKy** [comment] 2022-08-05 09:34
I have also exactly the same problem ..... :( still stucked in MA 2022.7.2 :(

**Comment by marcelveldt** [comment] 2022-08-05 10:37
> I have also exactly the same problem ..... :( still stucked in MA 2022.7.2 :(

I'm looking into HACS data structure to find out why this is happening, still can't find a lot to work with.
The issue lies somewhere in the hacs data files within the .storage folder

**Comment by marcelveldt** [comment] 2022-08-05 14:13
Reopened the issue because this issue was created by @SeByDocKy (before it got hijacked by that guy who doesn't know how community efforts work).

@SeByDocKy has also created an issue at HACS but the author of HACS is enjoying his holidays atm so we're on our own for this. It has something to do with the hacs database get corrupted somehow. I've looked into it today for a bit but could not quickly find something to work with...

The hacs database is in the .storage (hidden) subfolder of the HA config folder.
A few files that are prefixed with hacs are there including a folder with some cached info of the repositories.

Without knowing exactly which file is responsible for what I think the only 2 ways to get out of this state is:

1) Restore a backup from right before the misery. Update HA + MA after that.

2) Uninstall HACS and delete all traces from the config folder. After that reinstall HACS again. Downside is that you will need to install all custom components again which you may have installed.

**Comment by SeByDocKy** [comment] 2022-08-05 14:14
> > I have also exactly the same problem ..... :( still stucked in MA 2022.7.2 :(
> 
> I'm looking into HACS data structure to find out why this is happening, still can't find a lot to work with. The issue lies somewhere in the hacs data files within the .storage folder

Yes exactly.... I don't know for wich but the ./storage/repository/476357279.hacs file ...

**Comment by marcelveldt** [comment] 2022-08-05 14:20
Also remove/rename these:

![Schermafbeelding 2022-08-05 om 16 19 44](https://user-images.githubusercontent.com/6389780/183096518-e63ba76e-6172-42db-885d-148558db4c8d.png)

and this:
![Schermafbeelding 2022-08-05 om 16 20 40](https://user-images.githubusercontent.com/6389780/183096708-5ce484e6-68c1-4acb-b17c-3d0171d8a45c.png)

**Comment by libby2cm** [comment] 2022-08-06 06:59
@marcelveldt , thank you, working fine for me now.. I appreciate your efforts on this and the plugin in general.  

Also, since I was starting clean, I attempted to reproduce @SeByDocKy 's issue, but could not, starting with 7.2 and upgrading thru 8.1.. I had no issues.  Since it seems to be a hacs corruption issue as you mentioned, I suppose I expected this.

**Comment by SeByDocKy** [comment] 2022-08-06 07:51
Yes it's a hacs corruption ... this is why I opened an issue in hacs...  It's not related at all with MA...

**Comment by OzGav** [comment] 2022-08-07 07:58
If everyone is now ok on 2022.8.x I will close this. Or @SeByDocKy as this is yours please feel free to close if it is resolved for you.

**Closed** 2022-08-10 11:59 UTC
Labels: upstream issue
