### ISSUE TITLE
squeeze players stop playing

### ISSUE THREAD

**Issue by H30lth** [music-assistant/hass-music-assistant#2009] opened 2024-03-16 07:16 UTC
### What version of Music Assistant has the issue?

2.0.0b111

### What version of the Home Assistant Integration have you got installed?

2.0.0b111

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

A track will loop 4 seconds of play the. Restart the track or play for a while then stop.

### How to reproduce

Play audio from plex spotify and YouTube services to slimproto devices

### Music Providers

Plex spotify youtube

### Player Providers

Players with issues. Picoreplayer and squeezelite windows.  Playing separately and in group produces same issue.

### Relevant log output

2024-03-16 15:09:03.970 ERROR (ThreadPoolExecutor-0_24) [music_assistant] Error doing task: Task was destroyed but it is pending!

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment] 2024-03-16 08:01
You haven't listed the correct integration version. I use a picoreplayer with Spotify and it works fine.  Have you rolled back to see if this behaviour is still present? You haven't advised what does work correctly. Please follow the instructions in the template and provide a LOT of information explaining what you have tried from the troubleshooting pages, what has worked, and what hasn't worked. Attempt to narrow down the problem yourself and let us know what you have tried.

**Comment by H30lth** [comment] 2024-03-16 09:27
I can't provide what I don't have

**Comment by H30lth** [comment] 2024-03-16 09:28
If you look you will also see I have outlined the players affected.

**Comment by OzGav** [comment] 2024-03-16 10:27
And supply the full log. A single line is not useful at all.And I assume you are thumbs downing your disappointment with your initial post.

**Comment by WJ4IoT** [comment] 2024-03-16 13:44
More or less same problems. Because I run both HA and MA in a Docker container I was able to tackle my problems to pull the latest MA image. For me the "problems" started with HACS asking to refresh the MA integration (twice or so, which I did).  My MA integration was only a few days installed and after all refresh my first impression is it works flawlessly (again).

**Comment by OzGav** [comment] 2024-03-16 20:35
@H30lth we need some more followup or we will have to close tbis

**Comment by WJ4IoT** [comment] 2024-03-16 23:08
I do not want to hijack this issue but after I installed Spotify I also experience that my music stops. This is however after some time. When I look at the log (now 60+ k lines) I see a lot of errors due to Spotify it starts with:

```
2024-03-16 20:42:46.075 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-03-16 20:45:26.539 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as 1126007149
2024-03-16 20:45:26.539 INFO (MainThread) [music_assistant] Loaded music provider Spotify
2024-03-16 20:46:20.488 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "<string>", line 39, in __mashumaro_from_dict__
  File "<string>", line 39, in <listcomp>
  File "<string>", line 31, in __mashumaro_from_dict__
ValueError: Argument for music_assistant.common.models.media_items.ProviderMapping.__mashumaro_from_dict__ method should be a dict instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 68, in add_item_to_library
    item = Artist.from_item_mapping(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 301, in from_item_mapping
    return cls.from_dict(
           ^^^^^^^^^^^^^^
  File "<string>", line 41, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "provider_mappings" of type set[ProviderMapping] in Artist has invalid value {'item_id': '252', 'provider_domain': 'library', 'provider_instance': 'library', 'available': True}
2024-03-16 20:46:25.485 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "<string>", line 39, in __mashumaro_from_dict__
  File "<string>", line 39, in <listcomp>
  File "<string>", line 31, in __mashumaro_from_dict__
ValueError: Argument for music_assistant.common.models.media_items.ProviderMapping.__mashumaro_from_dict__ method should be a dict instance

During handling of the above exception, another exception occurred:
```
I will remove Spotify for the moment to see if this works better (will hear that 4 sure tomorrow morning when girlfriend does not have music). I will leave the PiCorePlayer running . 

Some detail:
Hardware: NUC7i7BNH (Ubuntu 22.04.4 LTS 12Gb)
HA version:  2024.3.1 (contaIner)
MA Version:  2.0.0b111 (container)
MA integration: 2024.3.1 (installed with HACS)
Providers: Tune-In Radio, Spotify
Players: Slimproto (PiCorePlayer on Pi2), UPnP/DNLA (Audio Pro C5A) both on Ethernet 
How to reproduce: Clueless, music just stops after x minutes no specific errors in MA log

**Comment by WJ4IoT** [comment] 2024-03-19 11:02
Another update:

What did I try so far?

- Updated to latest versions (see details).
- Timed better when music stops: ~29 minutes.
- Changed connection with different cable/port/switch without solving problem.
- removed music provider Slimproto from HA, music continued till 29 minute moment.
- removed MA integration from HA and restarted old LMS container and selected same TunIn Station (NPO 2 in NL), music now does not stop after 29 minutes
**- Also notice in this setup (LMS) that my router (Unifi UDM _minion_) show info upload/download and in the details the Wired Experience does not go more or less directly back to grey (see attachment). This might be related to the root cause of my problem.**

![MA](https://github.com/music-assistant/hass-music-assistant/assets/17813643/5b421965-7ca8-48a1-9a7b-ffbd86c016d2)

For the moment (to remain peace in the house) I will revert back to LMS but I am willing to test things again.

Some detail:
Hardware: NUC7i7BNH (Ubuntu 22.04.4 LTS 12Gb)
Router: UDM (minion)
HA version: 2024.3.1 (container)
MA Version: 2.0.0b116 (container)
MA integration: 2024.3.3 (installed with HACS)
Providers: Tune-In Radio, Spotify
Players: Slimproto (piCorePlayer v8.2.0 on Pi2), UPnP/DNLA (Audio Pro C5A) both on Ethernet

**Comment by melwinek** [comment] 2024-03-20 07:00
I have the same problem when playing the radio via SlimProto. The PiCorePlayer logs show "error reading from socket: Connection reset by peer". So MA disconnects the connection. In MA and HA it looks like it's still playing.

**Comment by OzGav** [comment] 2024-03-20 13:11
@WJ4IoT Your issue seems to be repeatable. Please restart MA then do whatever you do to make the playback stop at the 29min mark and then DOWNLOAD AND ATTACH the FULL log from MA SETTINGS>>CORE

**Comment by OzGav** [comment] 2024-03-20 13:14
@melwinek What you are describing is NOT the same. Your error is different to that reported here. Please go through the troubleshooting page CAREFULLY and if you get to the end without resolution open a new issue with all the required info. Yours sounds like a network or player problem.

**Comment by OzGav** [comment] 2024-03-22 01:40
@WJ4IoT Please try again with b118

**Comment by marcelveldt** [comment] 2024-03-26 14:25
these issues are resolved in b124 and confirmed fixed by others

**Closed by marcelveldt** 2024-03-26 14:25 UTC
Labels: bug, More info
