### ISSUE TITLE
Artist Metadata Download

### ISSUE THREAD

**Issue by Chacsam** [music-assistant/hass-music-assistant#3297] opened 2024-12-12 16:47 UTC
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.12.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In music assistant server, my artist metadata (artwork) does not download.
If I manually update the metadat, it does download pictures and updates, but I would have to manually update each artist one-by-one and I have many.

### How to reproduce

just look at artsit page or any artists

### Music Providers

file system (local on local disk)
spotify

### Player Providers

google cast

### What version of Home Assistant Core are your running

2024.12.2

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment] 2024-12-12 23:15
Duplicate of https://github.com/music-assistant/hass-music-assistant/issues/3230

**Closed by OzGav** 2024-12-12 23:15 UTC
Labels: triage
