### ISSUE TITLE
V1.1.3: log flooded again

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#178] opened 2022-05-16 17:08 UTC
Today I noticed that, about one hour after the update to HassOS8.0, the log got flooded again with websocket errors. This happens as long I cast music:
```
[547859019088] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
18:50:29 – (ERROR) Home Assistant WebSocket API - message first occurred at 16:31:15 and shows up 1650 times
[547859019088] Client exceeded max pending messages [2]: 2048
18:50:25 – (ERROR) Home Assistant WebSocket API - message first occurred at 16:43:49 and shows up 15320 times
```
I rebooted and the loggings are gone for now. I will monitor if they come back.
Don't understand what goes wrong. But for some reason the MA network load can't be handled when it happens

**Comment by marcelveldt** [comment] 2022-05-16 19:09
Are you sure these issues are at all related to MA ? Do note that the whole HA frontend communicaties over websockets.
I really can't reproduce it on my system(s).

There's one to thing to rule out if it's HA: Open the MA frontend panel and press F12 to open the developer tools on the browsers and open the console tab. Because I'm still more-or-less in beta stage I'm currently printing everything that happens on the debug console so you should see the websocket events come in in realtime. If your websocket errors are related to MA you should a lot of command or events happening at the same time.

**Comment by erkr** [comment] 2022-05-16 19:17
Sure I do understand it's not necessarily a MA error. Tried to express that in my remarks:
> Don't understand what goes wrong. But for some reason the MA network load can't be handled when it happens

But I will try the F12 when it happens again. After the reboot it's running for hours now without these errors!
(found some others for you😉)

**Comment by marcelveldt** [comment] 2022-05-16 19:18
Keep 'em coming, thanks for your patience and help testing!

**Comment by erkr** [comment] 2022-05-16 19:21
Thanks, Your project is definitely worth it 👍

**Comment by erkr** [comment] 2022-05-16 19:54
I opened a related issue for core ca 2 months ago. These errors sporadically occurred for months, so without MA. I think MA triggers an existing core websocket issue (the flooding).
Issue: https://github.com/home-assistant/core/issues/68030

**Comment by marcelveldt** [comment] 2022-05-16 20:00
I doubt that but but your test with the browser debug console will rule that out.

**Comment by erkr** [comment] 2022-05-18 09:29
Just observed these logs again. They started while casting (local media in this case). 
```
[546367893712] Client exceeded max pending messages [2]: 2048
11:22:54 – (ERROR) Home Assistant WebSocket API - message first occurred at 11:17:38 and shows up 1349 times
[547036448992] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
11:22:50 – (ERROR) Home Assistant WebSocket API - message first occurred at 09:46:32 and shows up 143 times
```
In the Chrome console I see these events when it happens:
![image](https://user-images.githubusercontent.com/4363599/169006757-6338d7cf-d195-4ba0-a9da-fd73cba6b493.png)

Probably not the cause of the errors but they trigger them to surface I guess

**Comment by erkr** [comment] 2022-05-18 09:57
Here is a snapshot of the the debug log, at the moment I started casting the local track (line 4 in the log), and where the client errors started (line 37). Same happens with the next track (started line 69 and errors line 78)
[client_errors.zip](https://github.com/music-assistant/hass-music-assistant/files/8715217/client_errors.zip)
:

**Comment by marcelveldt** [comment] 2022-05-18 14:23
If MA is the cause for that "Client exceeded max pending messages" error you would have seen 1000s of messages in the browser console at that point. Was that the case ? Or just sporadic events when something happened.

Something on your setup is either causing very many events or really a lot state changes.
The websocket API can't keep up with all the messages. Now the question is what is causing it...

**Comment by erkr** [comment] 2022-05-18 15:27
I indeed don't say MA misbehaves, but it certainly trips the limit on my setup. Did you have a look in client_errors.log as well?
This log suggests bursts of congestions. Examples of actions that where immediately followed by a burst of "Client exceeded max pending messages" errors:
`2022-05-18 11:11:02 INFO (MainThread) [music_assistant.mass] Finished job [Add spotify://artist/040Fqhc0l7a4MPeDx6cneh to database] in 2.62 seconds.`
`2022-05-18 11:13:48 INFO (MainThread) [music_assistant.mass] Finished job [Add file://track/variouspuurnederlands01acdaendemunnikstilinmijlivemp3 to database] in 0.94 seconds.`
Is it possible that these database actions in MA (with seconds in duration) holds up Websocket handling somehow?

**Comment by marcelveldt** [comment] 2022-05-18 15:36
No that should not be possible unless something is doing I/O within the eventloop. I properly guarded the code for that and I actually monitor it while debugging but just in case I'll have another look later today. Maybe there's a bug in one of the libraries in use to open the files or read metadata. I really would like to know what is causing bursts of events and/or state changes within a few seconds.

I'll do some stress testing with local files later today.
BTW: the duration of these tasks are just the total amount of time it took to process the task, most of the time is waiting on metadata providers

**Comment by erkr** [comment] 2022-05-18 16:55
Yes I really hope you can find this one. The nasty thing is that it not happens all the time. The last hours it worked without a single error

**Comment by marcelveldt** [comment] 2022-05-19 07:37
Good news. I did one more sweep of code hunting yesterday evening and actually found a small situation where I/O was being performed in the async code. It was in the file system provider while enumerating the listings from disk. In your case with 10.000 tracks I guess that could explain a small lockup.

Anyway, I guarded that last piece of code and the fix is in the 1.1.7 release.
So, fingers crossed I hope you will never ever see this error again (at least not caused by me haha)

**Comment by erkr** [comment] 2022-05-19 11:07
Great news you found something that can be related 😀
I propose to keep this issue open a few days. With v1.1.7 these errors didn't pop up anymore! I will continue testing, but this looks very promising 🙏

**Comment by erkr** [comment] 2022-05-20 15:55
This missing the track look-up issue https://github.com/music-assistant/hass-music-assistant/issues/191#issuecomment-1132750975 triggered these loggings again.
They then continued to happed. After a reboot they where gone.

**Comment by marcelveldt** [comment] 2022-05-20 16:13
I have never been able to reproduce this issue and I think I'm a bit out of options. I can do one more sweep but normally these kind of errors are caused by something emitting a lot of events or state changes. I will ask around if there are some more options to find out what is causing it.

**Comment by erkr** [comment] 2022-05-20 16:27
I really appreciate your efforts! My system seems sensitive for these errors, and MA is definitely not the only integration that can triggers there errors (a particular version of the MQTT broke did it as well)
Since your last change or the errors are not flooding anymore. But the failed album look up again triggers it, but at a significant lower frequency. Strange is that ounce these errors emerge, only a restart stops them.
Do you know by chance if there is a way to map the [...] number in the error to an integration/add on...?!

**Comment by marcelveldt** [comment] 2022-05-20 23:26
small question... did these warning appear when the full scan was running perhaps ?
because that emits a lot of events indeed

**Comment by erkr** [comment] 2022-05-21 08:46
I checked the cpu load: according this the scan stopped ca 12:06:
![image](https://user-images.githubusercontent.com/4363599/169643747-ed8e2640-dd9a-4b6b-b2df-f4e3a33b7afb.jpeg)
Errors started around 12:28 when I was selecting an album that causes lookup errors. That also gave more cpu activity (red arrow)

**Comment by marcelveldt** [comment] 2022-05-21 09:45
cpu load is expected while the scan is running so no surprises there.

**Comment by erkr** [comment] 2022-05-21 09:51
That was not what I tried to convey. 
- At 12:06 cpu load dropped (scan completed).
- at 12:28, when the lookup error occurred, the CPU load restarted again, also after the error, until I restarted HA (red arrow)

It is possible the error triggered new database activity?

**Comment by marcelveldt** [comment] 2022-05-21 09:54
Sorry (dikke vingers) I press enter while my message wasn't ready yet. The CPU load when a full item is requested is also normal. As long as it calms down after. I fixed the error with the first time lookup in .15 btw so maybe give that a test drive ?

Other than that I'm clueless and I will discuss this a bit with other HA devs how to debug

**Comment by erkr** [comment] 2022-05-21 09:55
Sweeping code is not energizing, so I try to narrow down what task could be active during the errors

**Comment by marcelveldt** [comment] 2022-05-21 10:03
The problem is that I have not been able to reproduce this issue ever nor did it get reported by others. Only difference is that you have a very large music collection on disk.

Even though I'm intrigued by it and I want to know what's going on :-)

The "websocket flooding" messages can be caused by 2 conditions:
1) A rogue component that has an insane amount of state changes and/or events. We're talking about 100s of events in seconds here.

2) A component (HA core or integration) that is doing blocking I/O within the event loop, causing things to lock for 100s of millisonds or even worse, seconds. 

I suspect you are victim of number 2, you have some component (custom integration ?) that is blocking the eventloop from time to time. When the eventloop is locked all actions get stalled, including state changes and event messages. So for example Music Assistant that is doing a scan on your 10.000 songs collection causing an event even 100ms (more or less).

What I do not understand is that we only see the result of that issue and not the issue itself. The HA core is very robust guarded against this kind of pitfalls and even logs integrations that lockup the eventloop.

To be continued...

**Comment by erkr** [comment] 2022-05-21 10:23
Thanks for the very clear explanation. During the re-scan of the database, the log remains clean. It's running now for v1.1.3 for half an hour, behaving very nicely (cpu, memory)

> A rogue component that has an insane amount of state changes and/or events. We're talking about 100s of events in seconds here.

I agree that would cause more symptoms like an unresponsive ui. That is not the case. Besides megabytes of logs, I don't see other side effects.

When the rescan is completed I'm going to replay exactly the same scenario. Presuming the lookup exception itself is resolved, it will at least test if retrieving extra metadata triggers the issue again. If not I propose to close the issue. Under normal usage it works great 👍

**Comment by erkr** [comment] 2022-05-21 11:13
With 1.1.13 The pending errors didn't reproduce when looking up albums 👍

**Comment by erkr** [comment] 2022-05-21 11:17
> I suspect you are victim of number 2, you have some component (custom integration ?) that is blocking the eventloop from time to time

If there is one misbehaving, I suspect ZHA at first. I regularly have ZHA related time-out errors related to the communication with the Zigbee dongle

**Comment by erkr** [comment] 2022-05-21 11:19
Close this issue?

**Comment by marcelveldt** [comment] 2022-05-21 11:21
I leave it up to you. You may leave it open for a few days or reopen if it may happen again

**Comment by erkr** [comment] 2022-05-21 11:58
I think you did a marvelous job😎. Will close the issue. Thanks👍

**Comment by erkr** [comment] 2022-05-21 12:26
Speaking of the devil. Just navigate trough my artists and albums. Loading these lists takes considerable time (7 and 4 seconds to open the list of 7500 tracks and 1600 albums). Somewhere doing this the flooding was triggered again 🤨

**Comment by marcelveldt** [comment] 2022-05-21 12:28
OK, in that case I know where the issue is. It's just the length of the list that needs to be converted to json.
I'm going to adjust that so that the list is sent as smaller chunks. That also solves your other request #207

**Comment by erkr** [comment] 2022-05-21 13:12
Great, I love to test that change 😀

**Comment by erkr** [comment] 2022-05-22 10:12
V1.1.14 seems to have fixed the trigger when adding tracks to the queue 👍

**Closed** 2022-05-22 10:12 UTC

**Comment by erkr** [comment] 2022-05-22 10:21
damn, just when thinking these are solved, they are back🥹

**Comment by marcelveldt** [comment] 2022-05-22 10:31
I created a fake library yesterday with 800.000 tracks, artists and albums to test my speedup changes. Didn't spot the issue once. So, I hate tho say this but I guess the issue is completely unrelated to MA.

Still, from Home Assistant perspective I'd like to know what's going on and I'm going to think about a way to log whatever is flooding your websocket queue.

**Comment by erkr** [comment] 2022-05-22 10:36
If there is anything I can do to assist in diagnosing, let me know. 
Today it took much longer to trigger the issue, but once triggered the errors keep flooding the log as long I'm playing music.

There is a '[Number]' at the start the logging. Hope this somehow relates to the part causing the errors. I don't have the knowledge to match that.

**Comment by marcelveldt** [comment] 2022-05-22 10:59
Well, my theory is that you have a component on your setup causing too many state changes.
I don't think (and hope) there's a relation to MA other than it might cause just that additional cpu usage to expose it.

I'll let you know once I find out how to better debug this one

**Comment by erkr** [comment] 2022-05-22 11:02
That works be great, thanks

**Comment by erkr** [comment] 2022-05-23 13:26
Not seen yet in v1.1.15

**Comment by erkr** [comment] 2022-05-26 11:38
Also not seen in v1.1.16 and v1.1.18. It really seems fixed😊

**Comment by marcelveldt** [comment] 2022-05-26 12:04
OK, That would be really nice because I was out of options :-)

**Comment by erkr** [comment] 2022-05-26 12:28
Thank you for all the support. I'm very happy it is give😀

From a HA side, there is little to no help from the logging to trace where they come from. I have an issue open in Ha.core to keep it under attention. More user suffer from these errors.
