### ISSUE TITLE
Window shake in artist/content view

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2519] opened 2024-06-20 05:33 UTC
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In some situations, the content of the center frame will "shake" . 

### How to reproduce

I'm not quite certain yet, still working on the test case. The behavior is unusual enough that I thought this warranted reporting. Here is a video of what it looks like : 
https://github.com/music-assistant/hass-music-assistant/assets/57333073/5b6f4519-f738-46fc-995b-587d7b28791c

I have seen it both in the browser and in the Android app.

This may be related to having an empty album. I'm not quite sure how that happened. It's stored on my Plex server. I will try to isolate the issue with the file system provider.

### Music Providers

Plex

### Player Providers

Chromecast

### Full log output

[log.txt](https://github.com/user-attachments/files/15909086/log.txt)

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment] 2024-06-20 06:33
We have some existing report about this somewhere. Its that the UI keeps continuously refreshing over and over.
So far I have not been able to reproduce it so if somebody can found out what actually trigger this, it would be amazing.

**Comment by OzGav** [comment] 2024-06-20 06:33
Related to https://github.com/music-assistant/hass-music-assistant/issues/2326

**Comment by madbrain76** [comment] 2024-06-20 06:44
Yes, it definitely sounds like the same issue - just different words being used to describe it.

I'm still trying to reproduce it, but so far haven't found a pattern. I'm examining the Plex server library to see where that empty artist could have come from.

Is that case ever supposed to occur in MA - an artist with no albums or tracks ?
Or artist having an album, but no tracks ?

**Comment by ulflulfl** [comment] 2024-07-07 12:48
This seems to be caused if the artist cannot be detected (e.g. missing musicbrainz ID), the sync(?) code then goes in a loop ...

Using 2.1.0.b13 on Firefox/Edge/Win11/Linux Mint

I've seen this "flickering" appearing for files I tagged myself (Picard does not work well with "one album in one file", so I need to tag these with Mp3Tag manually). Artists that was tagged by Picard don't show this issue.

I've also noticed that the flickering only appears on the artist page but not on the album or the track specific pages.

To reproduce this, I took an existing mp3, stripped off all tags and only added the tags for title "Titel" and artist "Interpret". Then I played around adding more tags (album, year, disc, ...). The artist "Interpret" with a flickering page appeared. At one point in time after I added some more "common" tags, the flickering was gone for a moment but reappeared after a few minutes (and a few clicks on the "refresh list").

Suddenly I've seen in the logs MANY times in a row (keeping the artist page of "Interpret" open for a while):
---------------
...
2024-07-07 11:36:06.151 DEBUG (MainThread) [music_assistant.webserver] Handling command music/artists/get_artist
2024-07-07 11:36:06.168 DEBUG (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Interpret
 - using lookup-album(s): Album
 - using lookup-track(s): Titel

2024-07-07 11:36:06.308 DEBUG (MainThread) [music_assistant.music.artist] updated Interpret in database: 84
2024-07-07 11:36:06.635 DEBUG (MainThread) [music_assistant.music.artist] updated Interpret in database: (id 84)
2024-07-07 11:36:06.657 DEBUG (MainThread) [music_assistant.webserver] Handling command music/artists/get_artist
2024-07-07 11:36:07.048 DEBUG (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Interpret
 - using lookup-album(s): Album
 - using lookup-track(s): Titel

2024-07-07 11:36:07.285 DEBUG (MainThread) [music_assistant.music.artist] updated Interpret in database: 84
2024-07-07 11:36:07.498 DEBUG (MainThread) [music_assistant.music.artist] updated Interpret in database: (id 84)
...
---------------
... of course it cannot find the "Album" with "Titel" and there is no MUSICBRAINZ_ARTISTID - but it probably shouldn't try it again and again in a short row ;-)

After I've added a fake MUSICBRAINZ_ARTISTID, the flickering was gone!


So it seems the "sync code" has a problem if it cannot detect the artist and then get into some kind of loop. Reproducing this with an mp3 that is tagged with an "Not Existing" artist tag should be easy, but beware that the flickering doesn't show up all the time quickly/stably, but a bit playing with the tags and sometimes wait a few minutes (for the sync to trigger in?) will show it up.

**Comment by OzGav** [comment] 2024-07-09 01:18
Please check if this has been fixed in beta 14

**Comment by ulflulfl** [comment] 2024-07-09 05:48
I've checked with 2.1.0b14 and every artist I tried so far shows no flickering - seems the bug is fixed!

Thanks for your effort!

**Closed** 2024-07-09 07:28 UTC
Labels: bug, frontend, Fix to be Confirmed

**Comment by madbrain76** [comment] 2024-08-09 09:05
Verified fixed. Thank you !
