### ISSUE TITLE
Casting using Chromecast  to JBL BoomBox 3 WiFi plays for a few seconds and stops with an error

### ISSUE THREAD

**Issue by techadrian** [music-assistant/hass-music-assistant#2951] opened 2024-09-22 09:27 UTC
### What version of Music Assistant has the issue?

stable,beta

### What version of the Home Assistant Integration have you got installed?

2024.7.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Casting to JBL Boombox 3 Wi-Fi stops after a few seconds, then speaker looks disconnected in the web interface.
Any other casting application to that speaker eq Youtube Music on Android, Spotify on Android, Youtube Music on Desktop,  Youtube from Chrome on Windows from Desktop, Spotify from Windows Desktop in Chrome Browser, Spotify Windows client...works with no issues
Other devices in my home connected to the same network working with no issues : Google Home Mini Speaker, Xiaomi Mi Smart Clock (two of them), Google Chromecast TV dongles (two of them), Google Chromecast 3, 

### How to reproduce

Play any song via Chromecast  to a JBL Boombox 3 Wi-Fi from MusicAssitant

### Music Providers

youtube music, filesystem

### Player Providers

Chromecast

### Full log output

2024-09-22 09:13:25.270 INFO (MainThread) [music_assistant] Loaded music provider YouTube Music
2024-09-22 09:13:27.156 INFO (MainThread) [music_assistant.music] Sync task for YouTube Music completed
2024-09-22 09:13:27.156 INFO (MainThread) [music_assistant.metadata] Starting metadata scanner
2024-09-22 09:13:27.158 INFO (MainThread) [music_assistant.metadata] Metadata scanner finished.
2024-09-22 09:15:20.344 ERROR (Thread-8) [pychromecast.socket_client] [JBL Boombox 3 Wi-Fi(10.1.1.162):8009] Error reading from socket.
2024-09-22 09:15:20.344 WARNING (Thread-8) [pychromecast.socket_client] [JBL Boombox 3 Wi-Fi(10.1.1.162):8009] Error communicating with socket, resetting connection
2024-09-22 09:15:20.352 ERROR (Thread-8) [pychromecast.socket_client] [JBL Boombox 3 Wi-Fi(10.1.1.162):8009] Failed to connect to service MDNSServiceInfo(name='JBL-Boombox-3-Wi-Fi-dd7b82f44610618daceef042ebf09ff5._googlecast._tcp.local.'), retrying in 5.0s

[core.log](https://github.com/user-attachments/files/17089078/core.log)

### What version of Home Assistant Core are your running

2024.7.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment] 2024-09-22 09:56
That isn’t the full log. Please follow the template instructions

**Comment by techadrian** [comment] 2024-09-22 10:00
@OzGav  Apologies, full log attached after this morning upgrade to latest beta. 

[
[core.log](https://github.com/user-attachments/files/17089073/core.log)
](url)

**Comment by marcelveldt** [comment] 2024-09-23 21:40
Looks like we're loosing connection to the speaker completely. Do you also have the cast integration setup within HA ?
Try to disable that for a while and see if MA keeps up. Some of these cast players crash if they get too many socket connections.

**Comment by techadrian** [comment] 2024-09-24 06:26
Hi @marcelveldt ,

Cast integration in HA is disabled since I installed MA (eq about 2 - 3 weeks ago ).

**Comment by marcelveldt** [comment] 2024-09-24 06:35
> Hi @marcelveldt ,
> 
> Cast integration in HA is disabled since I installed MA (eq about 2 - 3 weeks ago ).

OK, thanks for letting me know. So there is something else causing it. I'll have a look at the code if we're throttling the commands to the cast players well enough.

**Comment by techadrian** [comment] 2024-10-07 05:26
Hi,
If there is anything I can do to help to diagnose this issue , let me know.

Thanks

**Comment by Peyto79** [comment] 2024-10-21 06:43
Hi, 
I have the same issue with a JBL Authentics 500.
Using Chromecast: Music stops after few seconds. Device becomes unavailable for another couple of seconds. (Chromecast disabled in HASS)
Using Airplay: Device showing up, but Playback not possible at all. Play Button does nothing.
Using DLNA: Everything works, but stopping Music is not possible. Music plays endless until I use the hardware button on the device.

It almost seems that JBL is not using any standard correctly.

My Apple Homepods and Sonos Players work normally with Airplay.

**Comment by techadrian** [comment] 2024-10-21 06:55
I can confirm  @Peyto79 's radio statement.  Radio is the only thing I can stream  via  Chromecast to my JBL BoomBox 3 Wifi also .  Youtube and Files have the same behaviour as previously stated...streaming stops in a few seconds and speaker becomes unavailable

**Comment by marcelveldt** [comment] 2024-10-25 00:10
I have added an option to force the mp3 codec on Google Cast players. Available in the player settings. Most probably that will fix this issue.

**Comment by Peyto79** [comment] 2024-10-25 11:15
@marcelveldt 
Installed newest release and I can confirm that it works now! 
My JBL Authentics 500 plays now also files (not only Radio) with Chromecast. 
Thank you very much!!!

**Comment by OzGav** [comment] 2024-10-26 10:12
Closing on the basis of the above report.

**Closed by OzGav** 2024-10-26 10:12 UTC
Labels: bug, Fix to be Confirmed, Chromecast

**Comment by techadrian** [comment] 2024-11-01 18:56
Thank you so much !!!! All good now !!!!!
