### ISSUE TITLE
Comma in ID3 tag cause unexpected database entries.

### ISSUE THREAD

**Issue by FrankJaco** [music-assistant/hass-music-assistant#711] opened 2022-07-23 13:28 UTC
### What version of Music Assistant has the issue?

 2022.7.0   (also 6b10)

### The problem

Punctuation marks in folder names and/or MP3 metadata cause unexpected database entries.
Example 1:  Commas 

Folder name:  “Blood, Sweat & Tears”
MP3 Album Artist metatdata:  “Blood, Sweat & Tears”

![image](https://user-images.githubusercontent.com/79318542/180606852-2b899c17-a052-4fe0-8638-476af96773d1.png)
![image](https://user-images.githubusercontent.com/79318542/180606863-9ca57459-6af7-4ad6-8331-3a06818ccfef.png)

Results in two Artist folders:  “Blood” and “Sweat & “Tears”
![image](https://user-images.githubusercontent.com/79318542/180606874-10309146-a101-4c42-a95e-e3c52119c273.png)
![image](https://user-images.githubusercontent.com/79318542/180606884-59db8fd2-0687-45c4-89f3-ef04770b83f6.png)

Example 2:  Ampersand
Two folders created by MusicBrainz:
Two different MP3 Album Artists in metatdata:
![image](https://user-images.githubusercontent.com/79318542/180606909-da47a6bb-9674-40ac-8597-f0e7252cc638.png)
![image](https://user-images.githubusercontent.com/79318542/180606928-2d51182d-59ba-40e9-a1e3-56ed33c342c7.png)
![image](https://user-images.githubusercontent.com/79318542/180606942-266af1ef-ab74-4bab-a1c4-c59a8992990e.png)

Shows up as one folder in MA “Browse” and one Artist.
![image](https://user-images.githubusercontent.com/79318542/180606966-965dc90f-2c6d-4d70-b9cf-127a2f726216.png)
![image](https://user-images.githubusercontent.com/79318542/180606987-2fa4f57a-ffa4-453a-98de-64e9b55a10f2.png)

### How to reproduce

Create folders and metadata as in examples above

### Additional information

The previous Ampersand fix seems to have caused this new condition.

Note that I entirely deleted the database file and let MA build a new one. The behaviour is the same.

### What version of Home Assistant Core are your running

2022.7.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment] 2022-07-23 13:37
1) Hmmm, I did not realize there exist album names with a comma in there. For now just edit the Id3 tag and remove the comma please. I will provide a fix later.

2) Not sure if that is a bug perse.... The browse feature just shows the directory listing so you most probably only have one folder there. As for the artist being merged into one: In that case you probably have set the musicbrainz artist id to the same for both entries ?

**Comment by FrankJaco** [comment] 2022-07-23 13:55
I absolutely can edit the ID3 tag.   Just be aware that this punctuation 
came directly out of MusicBrainz/Picard, so I am pretty certain it will 
affect other people. Blood, Sweat and Tears is not the only band out 
there with commas. You might want to consider it as a low priority bug 
to be fixed at a later time when you get MA where you want it.

And...  Actually the two folders ARE in the file system.  The image 
where I should the two folders is via samba directly to the media/music 
folder. It is only the MA browse/filesystem feature that doesn't show 
the two folders.

I certainly can live with these issues but wanted to report them.  It is 
really strange that MA's browse filesystem doesn't see the above as two 
different folders! Strange as it is, it is true.


fj

**Comment by erkr** [comment] 2022-07-23 17:02
Thanks for the well the well documented report.

**Comment by marcelveldt** [comment] 2022-07-23 22:47
@FrankJaco sure these need fixing. My point about editing the tag for now was just temporary until I release a fix.
I've decided to remove all that splitter logic and only accept the splitter used by Musicbrainz Picard, which is the semicolon. 
That also seems to be the common standard for multi-item fields in ID3.

Huh it is really strange that you don't see 2 folders because MA is literally iterating over the folders in the browse view.
I'll see if I can reproduce that one, thanks!

**Comment by FrankJaco** [comment] 2022-07-24 11:35
Hey Marcel,

The missing folder issue appears to be my error.  I made the assumption 
that the folders would be listed in alphabetical order. For example 
"Buckethead" would be listed directly above "Buckethead and Friends". 
But on closer examination both folders were present in MA's Browse 
feature.  Strange order though.  Why is is roughly in alphabetical 
order, but not?  I think this should be changed to a feature request.  
Some kind of sort features for the Browse/Filesystem or at least make it 
alphabetical.

fj

**Comment by marcelveldt** [comment] 2022-07-25 09:45
How strange, there is a "sort" on the directory listing because the OS itself returns a really strange order. I'll double check that.

Fix for the comma issue will be in the 2022.7.1 patch release!

**Comment by marcelveldt** [comment] 2022-07-25 21:06
I've just released patch version 2022.7.1 which should fix both issues (the comma and the sort order).
If you still experience any issues after updating to 2022.7.1 please let us know, thanks!

**Closed by marcelveldt** 2022-07-25 21:06 UTC
Labels: bug
