### ISSUE TITLE
Music Assistant Crashing After Youtube Music Cookie Setup

### ISSUE THREAD

**Issue by grainsoflight** [music-assistant/hass-music-assistant#3229] opened 2024-11-26 05:09 UTC
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Music Assistant runs for less than 2 minutes before crashing. The issue seems to have started after youtube switched to cookie authorization. Removal of MA server and data and resintallation did not fix the issue, it started crashing again as soon as I entered the cookie info back in.

### How to reproduce

Add Youtube music cookie. Wait for info from youtube music to load on the album/artists/etc tabs, soon after addon will crash.

### Music Providers

Youtube Music

### Player Providers

Didnt make it far enough to select a player

### Full log output

[d5369777_music_assistant_2024-11-26T05-07-27.796Z.log](https://github.com/user-attachments/files/17912934/d5369777_music_assistant_2024-11-26T05-07-27.796Z.log)

### Additional information

Supervisor 2024.11.4

Cookie obtained from Brave browser

### What version of Home Assistant Core are your running

2024.11.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment] 2024-11-26 06:31
@MarvinSchenkel

**Comment by grainsoflight** [comment] 2024-11-26 07:45
Im attempting to try the cookie from other browsers, but Im getting a lot of errors that say I dont have a youtube premium account. I do, and I did get the cookie from the playlist page after logging in, just like the tutorial.

**Comment by OzGav** [comment] 2024-11-27 07:23
Please confirm that if you do nothing with YouTube then MA works without problem. If that is the case then confirm that with the YouTube provider added not configured that MA works without problem. 
if the above is true then restart MA and then download and attach the log. Then attempt to authenticate YT. Download the log each time you do something until the server crashes. When that occurs go to the HA supervisor logs and shows what it says there.

**Comment by grainsoflight** [comment] 2024-11-27 07:57
It randomly stopped crashing and now runs with youtube music configured, but all of the youtube music content is greyed out and unselectable.

**Comment by grainsoflight** [comment] 2024-11-27 08:02
I also continue to get an error saying that I dont have youtube premium

**Comment by OzGav** [comment] 2024-11-27 08:13
Then this is a duplicate of https://github.com/music-assistant/hass-music-assistant/issues/3138 So please continue over there

**Closed by OzGav** 2024-11-27 08:13 UTC
Labels: More info, triage
