### ISSUE TITLE
Players lost when re-opening the configurator

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#111] opened 2022-05-10 09:01 UTC
Hi

Reopened the configurator (to add the local files option)  and notices that my previous selection of players seems lost:
![image](https://user-images.githubusercontent.com/4363599/167591273-21713053-6e9b-4715-bd28-63632803819d.png)

Note 1: At the moment of configuring these players where not avaliable
Note 2: I checked the Core.config_entries after re-adding them and they where added properly (no doubles):
```
                    "player_entities": [
                        "media_player.audio57keuken",
                        "media_player.audio57woonkmr",
                        "media_player.audio57serre",
                        "media_player.everywhere_57"
```
Best Eric

**Comment by marcelveldt** [comment] 2022-05-10 09:03
duplicate of #104 ?

**Comment by erkr** [comment] 2022-05-10 09:07
Could be, I lost all, not the latest

**Closed** 2022-05-10 21:01 UTC
Labels: bug
