### ISSUE TITLE
Volume sliders of speakers added to initial speaker are greyed out, can't control those volumes

### ISSUE THREAD

**Issue by harryfine** [music-assistant/hass-music-assistant#2874] opened 2024-09-04 22:43 UTC
### What version of Music Assistant has the issue?

2.3.0b19

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Selected music, in this case radio browser station.  Selected Office speaker.  Then clicked on paper clip to add additional speakers.  Added 3 speakers.  Clicked Apply.  Went back to main screen and pressed Play.  Music played in all speakers, but volume could only be controlled globally or on the Office speaker.  The other three were grayed out.
![Sliders](https://github.com/user-attachments/assets/4294bf78-3ca9-4b65-8635-612820602aaa)

### How to reproduce

As above

### Music Providers

Radio browser, Tidal and NAS

### Player Providers

Sonos

### Full log output

[Log.txt](https://github.com/user-attachments/files/16881799/Log.txt)

### Additional information

Music started from Addon.  

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment] 2024-09-04 22:57
Looks like the other speakers are still "off" - they should be turn ON when joining them to another player.
So your solution here is turning them ON in the UI - our task is to do that automatically when you sync them

**Comment by harryfine** [comment] 2024-09-04 23:04
What is the significance of on and off vs attached and detached? Why not always on? Why make the user confirm on/off status?

⁣Harry Fine
647-970-6378​

**Comment by harryfine** [comment] 2024-09-04 23:12
You are correct.  I turned them on and now volume sliders work.  But why this step?  I've wondered that since the first version I saw of MA.

**Comment by OzGav** [comment] 2024-09-04 23:13
Maybe you don’t want all of them playing but you always want them in the group?

**Comment by harryfine** [comment] 2024-09-04 23:15
But they play even when they are off but selected?

**<Maybe you don’t want all of them playing but you always want them in the group?>**

**Comment by OzGav** [comment] 2024-09-04 23:30
OK then it sounds like the issue is actually speakers play even though turned off. What happens when you turn one on then off again? Does it stop?

**Comment by harryfine** [comment] 2024-09-05 01:36
If you turn them off they disappear from the group and no longer play that selection. 
But what is the value of on/off when you have pair and unpair?

⁣Harry Fine
647-970-6378​

**Comment by marcelveldt** [comment] 2024-09-07 12:59
That is a bug, it should turn them on when you pair them. That is apparently working (as you hear sound) but the UI does not get updated. This will get looked at in due course

**Comment by OzGav** [comment] 2024-10-15 03:26
This has been fixed in the upcoming changes to the groups functionality. Watch for the next beta

**Comment by OzGav** [comment] 2024-10-19 00:33
Beta 30 has been released.

**Closed by OzGav** 2024-10-19 00:33 UTC
Labels: bug, frontend, Fix to be Confirmed, Groups
