### ISSUE TITLE
Home Assistant MediaPlayer entities missing

### ISSUE THREAD

**Issue by bkwar201** [music-assistant/hass-music-assistant#2183] opened 2024-05-02 02:53 UTC
### What version of Music Assistant has the issue?

2.0.0b143

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Home Assistant MediaPlayer - Device/Speaker discovery in dropdown list not complete. 
   - Also do not see zone 2+'s in UPnP Provider discovery

Name: Living Room Zone 1 < Is seen and can be selected
Entity: media_player.living_room_denon_z1
Integration: Denon AVR Network Receivers 

Name: Garage Zone 1 < Is seen and can be selected
Entity: media_player.garage_denon_z1
Integration: Denon AVR Network Receivers 

Name: Garage Zone 2 **< Is NOT seen by MA**
Entity: media_player.garage_denon_z2
Integration: Denon AVR Network Receivers 

### How to reproduce

Have tried with a 3rd receiver not yet ready to be online constantly and see the same thing. Only Zone 1 shows up.

### Music Providers

n/a
Music plays just fine to all zones/endpoints/players that populate.

### Player Providers

-UPnP/DLNA
-Home Assitatn MediaPlayers

### Full log output

2024-04-30 20:52:15.388 INFO (MainThread) [music_assistant] Starting Music Assistant Server (b5214bc3e2c74212999cce860d5833f1) version 2.0.0b143 - HA add-on: True - Safe mode: False
2024-04-30 20:52:15.393 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-04-30 20:52:15.612 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-04-30 20:52:15.711 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.0.1 with libsoxr support
2024-04-30 20:52:15.712 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.69.4:8097
2024-04-30 20:52:15.716 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-04-30 20:52:15.956 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2024-04-30 20:52:15.956 INFO (MainThread) [music_assistant] Loaded music provider Music Assistant
2024-04-30 20:52:15.956 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-04-30 20:52:15.956 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-04-30 20:52:15.960 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-04-30 20:52:15.961 INFO (MainThread) [music_assistant] Loaded music provider Tune-In Radio
2024-04-30 20:52:15.962 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider
2024-04-30 20:52:16.007 INFO (MainThread) [music_assistant] Loaded plugin provider Home Assistant
2024-04-30 20:52:16.061 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-04-30 20:52:16.357 INFO (MainThread) [music_assistant] Loaded player provider Airplay
2024-04-30 20:52:16.956 INFO (MainThread) [music_assistant] Loaded player provider Home Assistant MediaPlayers
2024-04-30 20:52:17.011 INFO (MainThread) [music_assistant.players] Player registered: media_player.garage_denon/Garage Zone 1
2024-04-30 20:52:19.990 INFO (MainThread) [music_assistant] Loaded music provider Plex Media Server Library
2024-04-30 20:52:26.543 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-04-30 20:53:33.963 INFO (MainThread) [music_assistant.music] Sync task for Plex Media Server Library completed
2024-04-30 23:52:15.631 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-04-30 23:52:20.762 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-04-30 23:53:35.001 INFO (MainThread) [music_assistant.music] Sync task for Plex Media Server Library completed
2024-05-01 02:52:15.634 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-01 02:52:20.753 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-05-01 02:53:27.482 INFO (MainThread) [music_assistant.music] Sync task for Plex Media Server Library completed
2024-05-01 05:52:15.632 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-01 05:52:20.750 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-05-01 05:53:29.647 INFO (MainThread) [music_assistant.music] Sync task for Plex Media Server Library completed
2024-05-01 08:52:15.634 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-01 08:52:20.758 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-05-01 08:53:27.213 INFO (MainThread) [music_assistant.music] Sync task for Plex Media Server Library completed
2024-05-01 11:52:15.635 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-01 11:52:20.827 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-05-01 11:53:36.114 INFO (MainThread) [music_assistant.music] Sync task for Plex Media Server Library completed
2024-05-01 14:52:15.635 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-01 14:52:20.766 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-05-01 14:53:28.429 INFO (MainThread) [music_assistant.music] Sync task for Plex Media Server Library completed
2024-05-01 17:52:15.637 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-01 17:52:20.775 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-05-01 17:53:36.687 INFO (MainThread) [music_assistant.music] Sync task for Plex Media Server Library completed
2024-05-01 19:24:02.173 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/queue/repeat: "`repeat_mode` of type `<enum 'RepeatMode'>` is required."
2024-05-01 19:30:08.872 INFO (MainThread) [music_assistant.players] Player registered: uuid:f64d5fcb-e530-1ae3-0080-000678cefe0e/Living Room
2024-05-01 19:30:08.937 INFO (MainThread) [music_assistant.players] Player registered: uuid:08cd5ac2-1473-17f7-0080-000678b65662/Garage
2024-05-01 20:52:15.642 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-01 20:52:20.774 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-05-01 20:53:26.458 INFO (MainThread) [music_assistant.music] Sync task for Plex Media Server Library completed
2024-05-01 21:35:51.199 INFO (MainThread) [music_assistant] Loaded player provider Home Assistant MediaPlayers
2024-05-01 21:35:51.261 INFO (MainThread) [music_assistant.players] Player registered: media_player.garage_denon_z1/Garage Zone Denon 1
2024-05-01 21:35:51.262 INFO (MainThread) [music_assistant.players] Player registered: media_player.living_room_denon_z1/Living Room Denon Zone 1
2024-05-01 21:35:51.266 INFO (MainThread) [music_assistant.players] Player removed: Garage Zone 1
2024-05-01 21:36:03.415 INFO (MainThread) [music_assistant.players] Player removed: Living Room
2024-05-01 21:36:03.415 INFO (MainThread) [music_assistant.players] Player removed: Garage

### What version of Home Assistant Core are your running

2024.5.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment] 2024-05-02 03:37
You have ticked the box saying you have read the docs but haven’t explained why the fourth last section here isn’t the reason https://music-assistant.io/faq/troubleshooting/

**Comment by bkwar201** [comment] 2024-05-03 01:50
> You have ticked the box saying you have read the docs but haven’t explained why the fourth last section here isn’t the reason https://music-assistant.io/faq/troubleshooting/

I assume you mean this section? If so i am not using MA to discover via UPnP for zone 2, i assume this is a limitation to the Denon itself, which is why i added it via the HA Denon integration/addon. It is the HA's entity* of zone 2 that is not showing up in the HA Players dropdown selection list to select for a desired destination.
Honestly i am not sure what Music Assistant is using to qualify if a entity should/should not show up in the dropdown list for the Player Entities.

From the Troubleshooting:
The second zone of my amplifier is not seen by MA or MA won't turn on my amplifier

MA is an INPUT to your amplifier. So you need to power on your amplifier and then select the INPUT that MA is streaming to (e.g. Airplay, DLNA, Chromsecast). For this reason MA does not see the amplifier zones it only sees the compatible inputs of the amplifier.

Some amplifiers may auto turn on when a signal is detected so check the amplifier options. If this functionality is not available then you will need to power on the amplifier via another means. The power icons that are seen beside the players must be seen as starting and stopping the stream to the player not as physically powering on or off the device.

**Comment by OzGav** [comment] 2024-05-03 02:09
I would say this will be dependent on the HA integration then. Since they are not real players (just zones of an amplifier) they may be getting filtered out

**Comment by OzGav** [comment] 2024-05-05 10:55
I am closing this as I believe it is expected behaviour as per the docs. If you have any additional info that invalidates that then we can reopen.

**Closed by OzGav** 2024-05-05 10:55 UTC
Labels: triage
