### ISSUE TITLE
V1.1.14: several artist missing

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#213] opened 2022-05-22 16:02 UTC
I'm missing several artists compared to older versions:
![image](https://user-images.githubusercontent.com/4363599/169704554-c79461a7-0e1b-4b77-a6a5-50d4eae6a1d6.jpeg)

And the list now:
![image](https://user-images.githubusercontent.com/4363599/169704575-598a1d06-df72-4a3a-bb80-e89086c7dd5d.jpeg)

The local Collection didn't change. For example AC/DC is missing. I have many AC/DC tracks:
![image](https://user-images.githubusercontent.com/4363599/169704825-5956f8ab-9f24-465d-ab07-07810c8ada1f.jpeg)

**Comment by darrenblanchard** [comment] 2022-05-22 17:14
I am seeing a similar behavior as well, I have two provider's configured spotify and filesystem, artist that appear in spotify don't always appear if you have a filesyststem entry for the same artist, my workaround has been to locate an album by the artist and select the artist name from the album, then select the heart to "add to library" and they then appear.

I put in a feature request to see if they will add the ability to see artist that are hidden but have records in the database. I can see why you would not want every artist from every spotify sone that is in a playlist. It would be nice to either override that if you have a filesystem album by the same artist or a quick way to manually add them.

BTW the albums appear on the library list for these artist for me just not the Artist itself.

**Comment by marcelveldt** [comment] 2022-05-22 18:03
@erkr please make sure that the "albumartist" ID3 tag is set on your songs. Songs without the albumartist tag set will fallback to "Various Artists" for obvious reasons. Previous reasons did not have this fallback causing in albums being allocated to the wrong artists.

Please do me a favor and double check the ID3 tags if the "albumartist" field is set. If it's set and the artist still doens;t show up in the library, we have a bug :-)


@darrenblanchard hmm, that might be discovery I have to test. Are these missing artists "followed" on Spotify? If they are they really should show up in the library listing

**Comment by erkr** [comment] 2022-05-22 18:10
I will check the tags for the albumartist tag. Wel possible they are missing. From earlier info I understood both the artist and album name tags where the only mandatory tags?!

**Comment by marcelveldt** [comment] 2022-05-22 18:32
title and album are mandatory ID3 tags. 
artist tag on the song = song artist(s)
albumartist = artist of album

In the previous versions I incorrectly assumed a missing albumartist is the songartist which is obvious incorrect and lead to errors. I still allow the album to be missing on a song but that can lead to other issues (as you also experienced) so I'm starting to think I shouldn't workaround bad ID3 tags and instead let users fix their ID3 tags (if I log properly what's going on)...

**Comment by erkr** [comment] 2022-05-22 18:51
Yes I agree. Working around bad tags always fails for some cases. 
With a log that guides what was wrong really helps👍

**Comment by erkr** [comment] 2022-05-22 19:18
> @erkr please make sure that the "albumartist" ID3 tag is set on your songs.

Hi, 
Checked a few AC/DC albums. Yes albumartist  and the other relevant tags are set properly.
Example 1 :
![image](https://user-images.githubusercontent.com/4363599/169711739-64ee3f74-4a81-4a67-a41a-78e6a81f56a5.png)
Example 2 (not all tracks refer the right album):
![image](https://user-images.githubusercontent.com/4363599/169711697-9babba7e-5e5d-4088-9741-3f9c7427d53d.png)

Both these albums are correctly listed in the albums tab:
![image](https://user-images.githubusercontent.com/4363599/169711884-dcd3b6a9-2c44-4529-965b-1ac2bed507ef.png)

But AD/DC is not listed under the artists tab though!:
![image](https://user-images.githubusercontent.com/4363599/169711929-479c6d05-98b7-4c74-a5ed-498ede39e3e9.png)

Best Eric

**Comment by marcelveldt** [comment] 2022-05-22 19:29
I've just followed the lead of @darrenblanchard and I think he's right with the assumption this happens when an artist already got added in the db by a streaming provider (without being a favorite). Basically it's a race condition between the multiple music providers. No idea why it only comes to the surface now.

Anyways, fix is on the way

**Comment by erkr** [comment] 2022-05-22 19:33
Amazing how fast you fixed all issues :-)

**Comment by marcelveldt** [comment] 2022-05-22 19:36
haha, yes I'm working towards that first stable release. Squash those bugs is the motto.

**Comment by marcelveldt** [comment] 2022-05-23 06:39
Fix for this is in 1.1.15. I'm not sure if a db rebuild is needed or that it will auto correct itself.
If it doesn't resolve itself, please delete the music_assistant.db file in the config folder and reload the integration.

**Comment by marcelveldt** [comment] 2022-05-23 06:42
Looks like a full scan is needed. If you want to avoid that, I can write a small fix to prevent a full scan

**Comment by erkr** [comment] 2022-05-23 07:30
No problem to rebuild 👍

**Comment by erkr** [comment] 2022-05-23 09:41
Yep my artist are back:
![image](https://user-images.githubusercontent.com/4363599/169791254-9a3e0cea-275e-4199-a1e1-102c24eeb587.jpeg)

I see several double albums. I will check later today if that is caused by my Id3 tags. I think that is the case

**Comment by marcelveldt** [comment] 2022-05-23 10:01
Note that (as discussed) the parser is now way more strict. So a track with album but without albumartist tag would mean the album gets created as "various artists" album. Previously I tried to workaround that but that was not waterproof so the conclusion is that I will not fix any wrong tags :-)

Please let me know if that is indeed the cause of your duplicate albums

**Comment by erkr** [comment] 2022-05-23 18:15
Yes you are right. The double albums are the result of missing 'albumartist' tags. So for me to solve ;-)

For others reading; this results in two albums with the same name:
![image](https://user-images.githubusercontent.com/4363599/169881623-556f0a32-762e-4d74-abc7-240c168039c1.png)
One album refers to the correct artist and one album refers to various artists. The latter one contains the tracks that didn't have the 'albumartist' tag.

**Closed** 2022-05-23 18:15 UTC
