### ISSUE TITLE
Deezer not working anymore

### ISSUE THREAD

**Issue by Black-Smokey** [music-assistant/hass-music-assistant#1383] opened 2023-07-21 11:20 UTC
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

Deezer plugin is be able to setup, load the playlist but keep loading when playlist opened and needs to show the numbers. Other plugin (radio) is working as it should be.

Reinstalled the plugin, reconfigured Deezer but it didnt solve the problem.

![image](https://github.com/music-assistant/hass-music-assistant/assets/106400115/ae3b38c6-6b63-4c07-9ad1-e38456db82c0)

### How to reproduce

Install latest version and try it out with Deezer

### What version of Home Assistant Core are your running

2023.07.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by Black-Smokey** [comment] 2023-07-21 11:39
Restore backup (previous version) did fixed te controls via Music Assistant. The Service mass.quee_command is still broken

**Comment by marcelveldt** [comment] 2023-07-21 15:26
the issue is confirmed and a fix is on the way

**Comment by Un10ck3d** [comment] 2023-07-23 20:46
This should be fixed in the new beta 60 :slightly_smiling_face:

**Comment by Black-Smokey** [comment] 2023-07-23 20:49
Thank you guys! Appreciate all the hard work. I am gonna try Beta 60 when its available.

**Closed** 2023-07-23 21:27 UTC
Labels: triage

**Comment by Black-Smokey** [comment] 2023-07-23 21:29
I can confirm that Beta 60 fixed the issue (and 2023.6.0b3 fixed the command issue). Great work!
