### ISSUE TITLE
Tons of errors in 141 release

### ISSUE THREAD

**Issue by mfabiani53** [music-assistant/hass-music-assistant#2155] opened 2024-04-23 11:11 UTC
### What version of Music Assistant has the issue?

2.0.0b141

### What version of the Home Assistant Integration have you got installed?

2024.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Error in latest beta 141

### How to reproduce

Installing latest beta 141

### Music Providers

Qobuz and remote filesystem

### Player Providers

Chromecast and Sonos

### Full log output

see below

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment] 2024-04-23 11:49
Can you please remove that pasted log and ATTACH it as per the instructions. It's very difficult to read issues like this

**Comment by mfabiani53** [comment] 2024-04-23 12:02
Sorry, not so expert... how i can do it?

**Comment by mfabiani53** [comment] 2024-04-23 12:05
[2024-04-23 094651.349 INFO (MainThr.txt](https://github.com/music-assistant/hass-music-assistant/files/15076449/2024-04-23.094651.349.INFO.MainThr.txt)

**Comment by mfabiani53** [comment] 2024-04-23 12:05
Hope i did right..

**Comment by marcelveldt** [comment] 2024-04-23 13:05
Thanks for the log - I now know what the issue is

**Comment by marcelveldt** [comment] 2024-04-23 18:51
So, I've been busy for a few hour siwth your report but I cant for the life figure out how you got into this state.
Have you been going back and forth with backups or whatever ? I just can't reproduce it not find how to get into this state.

The only way forward would be to completely start with a fresh database, so a reinstall of everything.
Before you do there is one little thing to try/test and that is clearing the cache...

Go to settings --> Core tab --> Cache controller --> click the "clear cache" button.

**Comment by marcelveldt** [comment] 2024-04-29 18:50
this is fixed in beta 142

**Comment by OzGav** [comment] 2024-04-29 22:08
@mfabiani53 please confirm this is fixed.

**Comment by OzGav** [comment] 2024-05-01 21:56
Closing assuming fixed after no follow-up

**Closed by OzGav** 2024-05-01 21:56 UTC
Labels: bug, More info
