### ISSUE TITLE
Music / playing info out of sync using external snapcast & spotify

### ISSUE THREAD

**Issue by chatziko** [music-assistant/hass-music-assistant#2402] opened 2024-06-02 12:27 UTC
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I'm experiencing a weird issue in which the music being played becomes out of sync with the currenly playing info displayed in MA. What is strange is that it happens only with Snapcast / Spotify combination, and only when using an __external snapserver__.

It starts at various moments, but finally I found a simple way to reproduce it with 100% success rate (at least in my setup).

### How to reproduce

- Configure the snapcast provider to use an __external server__
  - Tested with both snapserver v0.28 and v0.27.
  - Using a vanilla `snapserver.conf` with no special options
- Start playing a spotify album or playlist
- When the first track starts playing, use the seek slider to seek to the __middle__ of the track.
- Wait until the second half of the track finishes.
- When the __next__ track starts, the audio plays from the beginning (as expected) but in the currently playing info the slider looks as if the second track started from the middle of the song (as did the first after the seek).

### Music Providers

- Spotify: problem
- Filesystem: no problem

### Player Providers

- Snapcast (external): problem
- Snapcast (builtin): no problem

### Full log output

[log.txt](https://github.com/user-attachments/files/15525248/log.txt)

### What version of Home Assistant Core are your running

2024.5.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by SantiagoSotoC** [comment] 2024-06-13 22:32
Try to use the ip of the snapserver and not a hostname as this has been a problem in the past

**Comment by chatziko** [comment] 2024-06-14 15:00
Thanks for the tip, it doesn't seem to make a difference.

On the other hand, although in previous tests I could reproduce the problem with 100% success rate, with MA 2.0.6 it seems to happen only with certain spotify albums, but not others. Pretty strange...

**Comment by OzGav** [comment] 2024-06-14 15:10
Have you tried any other music providers?

**Comment by chatziko** [comment] 2024-06-14 15:13
Just the filesystem provider, no problem with that.

**Comment by chatziko** [comment] 2024-06-14 15:26
> Just the filesystem provider, no problem with that.

Actually I take this back. I had tried it several times, I'm sure, but now I tried it a few more and I managed to reproduce the issue with the filesystem provider (which will likely make it easier to spot the issue). It doesn't happen with all songs, but it does happen.

**Comment by chatziko** [comment] 2024-06-14 15:45
Some more info: I did several tests with the same filesystem album. Only 2 out of the 8 songs reproduce the problem, and the behaviour of each song is always the same, either it always works, or it always reproduces the problem.

Moreover, as with my initial experiments, the issue only appears with an external snapserver (configured with either IP or hostname). With the internal snapserver the problem never appears.

**Comment by SantiagoSotoC** [comment] 2024-06-14 17:40
It's so weird because we don't treat the embedded different than the external, I will try to reduce the amount of times that stream is created, maybe that will help.

**Comment by chatziko** [comment] 2024-06-14 18:35
Sure, I could maybe setup a local dev environment and try it there. Let me know what you want me to test.

**Comment by SantiagoSotoC** [comment] 2024-06-14 19:22
When I have the changes I will let you know here, thanks

**Comment by SantiagoSotoC** [comment] 2024-06-27 21:31
@chatziko Did you notice that it happens more with v0.28 than with v0.27 ? Because for the next beta we are going to use v0.28 because the debian repo was updated, and I noticed that it happens a lot.

**Comment by chatziko** [comment] 2024-06-28 11:00
I tried both just to see whether it's specific to one version, but I'm mostly using v0.28 so I can't compare the frequency between the versions.

**Comment by SantiagoSotoC** [comment] 2024-07-01 02:56
Off topic question but since you are using version 28 did you notice that the streams are not removed from snapcast ?

**Comment by chatziko** [comment] 2024-07-01 06:52
Not sure whether this is what you mean, but I just opened snapweb and I see two old streams there (MA has been idle since yesterday), see below. First time I see this, but I rarely open snapweb, so maybe I didn't notice it.

![image](https://github.com/music-assistant/hass-music-assistant/assets/362089/c77bbec8-4bbb-4474-847f-a4a187a63704)

**Comment by SantiagoSotoC** [comment] 2024-07-01 16:06
Yes, that's what I meant, it shouldn't happen, thank you.

**Comment by SantiagoSotoC** [comment] 2024-07-01 20:37
Can you try using crossfade and see if you get the information out of sync ?

**Comment by SantiagoSotoC** [comment] 2024-07-01 22:12
Well I found the error, snapcast is detecting silence in the stream between song and song. there is a parameter dryout_ms that solves it.
I don't know how many ms would be adequate, a song can have a lot of silence in the middle and this error appears again, a large number introduces latency.

@marcelveldt  Any suggestions ?

**Comment by OzGav** [comment] 2024-07-09 02:24
@chatziko Please confirm this has been fixed in beta 14

**Comment by chatziko** [comment] 2024-07-09 07:29
Thanks @SantiagoSotoC for working on this!

I haven't tested it yet, but trying to understand what `dryout_ms` does, I noticed that this option has been actually __removed__ from snapserver v0.28! Check [this commit](https://github.com/badaix/snapcast/commit/f8773087609cb6eeef349349ca46365d9fd37a09#diff-c8318e5fcd09e2ab5ea34db7a93c59e7f3e79a92737987b1669ae144fec7b226) (whose title is wrong, it removes dryout_ms not chunk_ms). In the current snapserver code there is no mention of dryout_ms whatsoever.

So it seems unlikely that this change will fix the problem. But on the positive side this change was made between 0.27 and 0.28, so it's a sign that you're looking at the correct direction.

**Comment by SantiagoSotoC** [comment] 2024-07-09 12:07
> Thanks @SantiagoSotoC for working on this!
> 
> I haven't tested it yet, but trying to understand what `dryout_ms` does, I noticed that this option has been actually __removed__ from snapserver v0.28! Check [this commit](https://github.com/badaix/snapcast/commit/f8773087609cb6eeef349349ca46365d9fd37a09) (whose title is wrong, it removes dryout_ms not chunk_ms). In the current snapserver code there is no mention of dryout_ms whatsoever.
> 
> So it seems unlikely that this change will fix the problem. But on the positive side this change was made between 0.27 and 0.28, so it's a sign that you're looking at the correct direction. 
> 
> 

Yes, I removed the dryout, in this beta

**Comment by chatziko** [comment] 2024-07-09 12:19
Oh cool, I'll try to test it tonight.

**Comment by chatziko** [comment] 2024-07-10 09:28
After a couple of hours of playing, the info seems to stay in sync, well done @SantiagoSotoC !

**Comment by chatziko** [comment] 2024-07-10 09:29
Something probably unrelated: when I click the "next" button several times while playing (say to skip 5 songs), I often get in the UI the error `Player <player_name> is not available`, and in the log I see:
```
2024-07-10 11:23:46.071 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/next: Player ma_living is not available
2024-07-10 11:23:46.300 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/next: Player ma_living is not available
2024-07-10 11:23:46.544 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/next: Player ma_living is not available
```
I think I've seen this in the past, now it likely happened more often cause I pressed next a lot while testing. Have you seen this error?

**Comment by OzGav** [comment] 2024-07-10 09:44
I will close this as the original issue has been resolved. See what @SantiagoSotoC says about the above.

**Closed by OzGav** 2024-07-10 09:44 UTC
Labels: bug, Snapcast, Fix to be Confirmed

**Comment by marcelveldt** [comment] 2024-07-11 18:45
Nope doesn't sound familiar

**Comment by SantiagoSotoC** [comment] 2024-07-11 19:08
@chatziko  I can't reproduce the error, are you playing in a group ?
