### ISSUE TITLE
Port disappearing from Integration URL

### ISSUE THREAD

**Issue by GekoCH** [music-assistant/hass-music-assistant#2333] opened 2024-05-19 14:36 UTC
### What version of Music Assistant has the issue?

2.0.0b141

### What version of the Home Assistant Integration have you got installed?

2024.5.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I'm running a docker version of the  MA Server:
`docker run -d --name=music_assistant --network host --privileged -v /home/music-assistant:/data ghcr.io/music-assistant/server`
Now I used the Adresse: http://192.168.1.123:8095 to integrate this server as a new device in HA withe the MA integration.
The URL is accesible from HA.

But I get the Error: "Failed setup, will retry"

In the log I see:
```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:147
First occurred: 4:04:17 PM (42 occurrences)
Last logged: 4:29:59 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/client.py", line 297, in fetch_initial_state
    await self._player_queues.fetch_state()
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/player_queues.py", line 228, in fetch_state
    for queue in await self._get_player_queues():
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/player_queues.py", line 223, in _get_player_queues
    for item in await self.client.send_command("player_queues/all")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/client.py", line 254, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.InvalidCommand: Invalid command: player_queues/all
```

### How to reproduce

as described above

### Music Providers

*

### Player Providers

Chromecast Player

### What version of Home Assistant Core are your running

2024.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment] 2024-05-19 21:28
Confirm the server is running and you are able to access the UI?

**Comment by GekoCH** [comment] 2024-05-20 04:50
> Confirm the server is running and you are able to access the UI?

Yes of course i can access the server form any device on my network and also play the music over the UI zo my audio device, but HA gives me the above error...

**Comment by OzGav** [comment] 2024-05-20 05:45
That normally occurs when the frontend hasn't started yet which is why I asked. I would remove the integration from HA, remove from HACS, restart HA, then re-add from HACS, re-add the integration.

**Comment by GekoCH** [comment] 2024-05-20 17:52
> That normally occurs when the frontend hasn't started yet which is why I asked. I would remove the integration from HA, remove from HACS, restart HA, then re-add from HACS, re-add the integration.

hmm still no success but in the mean time I get this error as well:
```
Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mass/config_flow.py", line 245, in async_step_manual
    await self.async_set_unique_id(self.server_info.server_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2182, in async_set_unique_id
    raise data_entry_flow.AbortFlow("already_in_progress")
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_in_progress
```

**Comment by GekoCH** [comment] 2024-05-20 17:56
ah interesting now it seems to work. I first added the Integration with this url:
http://192.168.1.123:8095
however I get the error: "Failed setup, will retry"
I then hit the configuration Icon (the gear) and saw that the "URL of  Music Assistant Server:" was only: http://192.168.1.123
Without the port. so I added the port and now it seems to work...
lets see how long this last..

**Comment by GekoCH** [comment] 2024-05-20 19:01
aaarg now its back again 
<img width="281" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/3285638/81634bb7-f11f-49c3-9b6d-d76c9021481a">

When I add :8095 again it works for a few minutes even an hour maybe... why is set back to only the url without port automatically?

**Comment by OzGav** [comment] 2024-05-21 00:42
Yes good question. I think I have heard of another person with this problem but as I recall it is after a restart. Are you rebooting or restarting anything?

**Comment by GekoCH** [comment] 2024-05-21 04:08
> Yes good question. I think I have heard of another person with this problem but as I recall it is after a restart. Are you rebooting or restarting anything?

no I'm not it just randomly puts it back that's so weird...

**Comment by OzGav** [comment] 2024-05-21 06:16
Ok I will change the title and add this to be looked at.

**Comment by D3LZ-D3LZ-D3LZ** [comment] 2024-06-08 11:20
I have the same issue, Music assistant shows failed setup, click configure, port is missing, add the port and it works again for an hour or so. 
I'm running Music assistant on Unraid.

**Comment by marcelveldt** [comment] 2024-06-15 05:37
See this duplicated issue:
https://github.com/music-assistant/hass-music-assistant/issues/2310

Most important is that you need to check the base URL in the webserver settings

**Comment by D3LZ-D3LZ-D3LZ** [comment] 2024-06-19 11:03
> See this duplicated issue: #2310
> 
> Most important is that you need to check the base URL in the webserver settings

I have checked and the IP and Port are in there and correct, I even tried adding the port to the end of the Base URL with the same result. 

![image](https://github.com/music-assistant/hass-music-assistant/assets/78247180/ff438adf-02f8-401a-ba67-398cb47ee935)

**Comment by katsaplias** [comment] 2024-08-06 15:36
I have the same problem
the integration keeps resetting to the default URL of my docker installation and when I replace it with the URL:port format it connects again for a while

**Comment by iw1gfv** [comment] 2024-08-31 10:39
also I  have the same problem.
The integration keeps losing the port and when I replace it with the URL:port format it connects again for a while

**Comment by fluxor99232** [comment] 2024-09-21 08:59
Music Assistant now needs to be reconfigured multiple times a day in order to keep functioning because the port keeps disappearing. Is there nothing that can be done?

**Comment by OzGav** [comment] 2024-09-23 00:36
Sorry but this will be addressed when priorities allow.

**Comment by D3LZ-D3LZ-D3LZ** [comment] 2024-09-23 02:11
> > See this duplicated issue: #2310
> > Most important is that you need to check the base URL in the webserver settings
> 
> I have checked and the IP and Port are in there and correct, I even tried adding the port to the end of the Base URL with the same result.
> 
> ![image](https://private-user-images.githubusercontent.com/78247180/341042987-ff438adf-02f8-401a-ba67-398cb47ee935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTc0MDMsIm5iZiI6MTcyNzA1NzEwMywicGF0aCI6Ii83ODI0NzE4MC8zNDEwNDI5ODctZmY0MzhhZGYtMDJmOC00MDFhLWJhNjctMzk4Y2I0N2VlOTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDAyMDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYjlhYTk3ZDVmZWZmNjY1MjIwOTlhOGUwZWNhZmU0NGRlYTU0ZjllZjE0NmQyYmJmN2Q4YzNjODEwMjc3OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vJ021IbViTWS-rd3gt22i7tPduxvoQGorJLGDYQ68ro)

I am no longer having this issue, I assumed it had been fixed, Maybe adding the port to the base URL did fix it after a restart of music assistant. As that is the only thing I changed.

**Comment by fluxor99232** [comment] 2024-10-14 10:38
So will the Home Assistant integration of Music Assistant ever be functional again? It's been almost have a year...

**Comment by OzGav** [comment] 2024-10-14 13:13
For users running docker without complicated network setups this problem is not appearing. To summarise:

Make sure that the base URL is correct (if its not, HA will not correctly connect and you run into major problems).

TCP port 8095 is the default and recommended but you are free to adjust it - just dont forget about the base URL then.

Bind address: Unless you really know what you are doing dont mess with this. However, if you want to protect the webinterface, you can bind it to a specific interface. Configuring it wrong will lock you out. Under normal circumstances it should just be set to 0.0.0.0 (bind to all interfaces)

This is what the settings should look like:
![image](https://github.com/user-attachments/assets/304ab484-c2e2-48e0-b2a4-67553f44539b)

Furthermore, looking back up at the other replies, the INTEGRATION URL should also have the port on the end of it:

![image](https://github.com/user-attachments/assets/80b766f1-b84d-4d90-a446-66557f5f6ee4)


If having setup the options above you still have problems then reply with DETAILED information about how you have installed MA. If you are using complicated installs, for example using Kubernetes, then expect that that the core team will not help as we don't have time to troubleshoot things that we don't use and we expect that if you are going to use advanced installs that you know how to fix any problems with them.

**Comment by Someguitarist** [comment] 2024-10-14 13:30
Thank you so much for taking a look at this.  I can confirm that this does not fix the issue, as that was actually one of the first things I've tried.  I am not using a complicated docker set up as I don't know that much about docker.  Just regular Ubuntu and 'docker compose up -d' on the standard compose file.  Interestingly, for me I didn't have the issue until recently, so maybe I can roll back a few versions and see where it started for me.  

Also of note, I had mine set to 'http://0.0.0.0:8095' and it wasn't working, so I set both the settings in MA and the settings in the HA integration to 'http://192.168.50.135:8095' just to see if it wanted the local IP instead of 0.  Upon a restart I immediately got 'Failed setup, will retry: Failed to connect to music assistant server http://0.0.0.0' even though I don't have '0.0.0.0' in either of those settings.

If you'd like, I can provide images of both setting pages and log files.  It looks like whatever I put into the HA integration doesn't seem to hold over a period of 30 minutes or so, or if I force reboot HA.

**Comment by OzGav** [comment] 2024-10-14 13:57
@Someguitarist can you remove the integration, remove from HACS, restart HA, install from HACS, install the integration and then use the correct IP you have above of 192.168.50.135:8095 and see if that resolves things

**Comment by Someguitarist** [comment] 2024-10-14 14:06
Okay, awesome.  I think that might have done it.  This time it came up with the correct IP and port number by default.  It's survived an additional reboot so far and still has all of the information intact.  What's interesting is I'd also done this before, the only difference this time is that I full brought the server down and restarted after removing the integration and removing HACs.  It's possibly that I didn't restart the MA server as well after changing the IP perhaps, or maybe something was caught in docker?

Tentatively resolved though!  Thanks for your help.  I'll update at the end of the day if it's still connected!

![MA1](https://github.com/user-attachments/assets/70a6c924-7ec9-43a1-b504-d3ed240e64f7)
![MA2](https://github.com/user-attachments/assets/bd0336b2-f2d3-475c-9b56-bc42a5392f85)

**Comment by Someguitarist** [comment] 2024-10-14 20:14
For me this is still working, so I'd think this can be marked as closed.

Thanks for your help @OzGav !!!

**Comment by OzGav** [comment] 2024-10-14 21:41
I will give this another day

**Comment by Someguitarist** [comment] 2024-10-15 22:06
Just wanted to pop back in to mention that after a day I've had zero disconnect issues.  Still working for me, thanks!

**Closed** 2024-10-15 22:20 UTC
Labels: HA Integration
