### ISSUE TITLE
Server update: duplicate column name: external_ids

### ISSUE THREAD

**Issue by jurgenhaas** [music-assistant/hass-music-assistant#1671] opened 2023-12-07 07:34 UTC
### What version of Music Assistant has the issue?

2023.12.0

### The problem

Just updated to the latest version of the server and while starting it, the database migration kicks in but fails with an error `duplicate column name: external_ids`, details see below.

### How to reproduce

Updated from beta 75 to beta 77

### Relevant log output

2023-12-07 07:28:24.635 INFO (MainThread) [music_assistant] Starting Music Assistant Server (6f94f41b08ff4f88ab8bf72e2b8b088f) version 2.0.0b77 - uvloop: False
2023-12-07 07:28:24.673 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.3.74:8095
2023-12-07 07:28:24.685 INFO (MainThread) [music_assistant.music] Performing database migration from 25 to 27
2023-12-07 07:28:24.685 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2023-12-07 07:28:24.686 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 107, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 666, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_ids

### What version of Home Assistant Core are your running

2023.12.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by jurgenhaas** [comment] 2023-12-07 07:42
You mean the plugin in HA? Why should that be interfering here. Isn't the MA server stand-alone?

**Comment by Dunkelschunkel** [comment] 2023-12-07 07:51
I have the same issue. I even created an issue here. That needs to be closed.
@jurgenhaas i believe reinstalling the whole music assistant addon in home assistant will do the trick even so you'll need to set it up again.

**Comment by Dunkelschunkel** [comment] 2023-12-07 07:55
I know, the hardest part for me will be the Spotify integration.

**Comment by Dunkelschunkel** [comment] 2023-12-07 08:23
@OzGav thanks for the tip

**Comment by OzGav** [comment] 2023-12-07 09:26
> Unfortunately, deleting the plugin in HA and restarting the MA server doesn't help at all. I now deleted all data on the MA server and started again, now it's working.

For any future readers…no the integration is fine it is the MA addon that has had the DB corrupted due to an interruption during the database schema migration. You can either restore from a backup or delete and install the MA addon

**Comment by Dunkelschunkel** [comment] 2023-12-07 10:07
@OzGav totaly forgot about backups in HA. Even so I have used it extensively in the past. Restoring and updating right now. Will be posting any updates.

**Comment by Dunkelschunkel** [comment] 2023-12-07 11:04
@OzGav 
Unfortunately I am able to reproduce it reliably upgrading from b75 to b77. 
Steps I took:

- restoring backup from b75
- starting b75
- opening MA and verifying everything is working
- stopping MA b75
- updating MA to b77 
- waiting for the update to settle
- starting MA b77
- observing log
- [MA Log.log](https://github.com/music-assistant/hass-music-assistant/files/13599122/MA.Log.log) attached
- Checking MA I can see, that providers and players are missing

If there is anything I can help you with, please let me now

Dunkelschunkel

**Comment by jazzyisj** [comment] 2023-12-07 12:12
Same issue here.  No providers, no players after update.

**Comment by Dunkelschunkel** [comment] 2023-12-07 12:43
I already tried the fresh install as well. Including deleting the old one. 
Thanks

**Comment by Dunkelschunkel** [comment] 2023-12-07 13:31
I am sorry, i meant deleting it, doing a fresh install and then restoring a  backup. That did not to fix the issue.

**Comment by OzGav** [comment] 2023-12-07 13:33
> Same issue here, I waited several hours to "let the DB settle", however the log showed no signs of any extra items in there to indicate anything was happening. Will try to roll back my DB to last nights backup and try again...

Try that. You seem to have a different DB error to the others I have seen

**Comment by Dunkelschunkel** [comment] 2023-12-07 13:34
For me this is no problem. Just have Spotify and running on HAOS

**Comment by krisnoble** [comment] 2023-12-07 13:59
Just another data point - I had exactly the same error (external ids) from 75 to 77, although I did restart the add-on because I didn't realise (IMO stuff like this should be really explicit in the patch notes), restoring last night's backup gets things working again but then trying to install 77 on top gets me the following which is different again:

```
2023-12-07 13:53:59.108 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2023-12-07 13:54:00.952 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=IndexError('No item with that key')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 107, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 674, in _setup_database
    if mbid := item["mbid"]:
               ~~~~^^^^^^^^
IndexError: No item with that key
```

**Comment by antonyslater** [comment] 2023-12-07 14:03
> > Same issue here, I waited several hours to "let the DB settle", however the log showed no signs of any extra items in there to indicate anything was happening. Will try to roll back my DB to last nights backup and try again...
> 
> Try that. You seem to have a different DB error to the others I have seen

I have deleted the Cache and Library DB files and restarted, this appears to have cleared whatever issue I was having... my library is now rebuilding based on the 11k plus mp3/flac files I have... Fingers crossed but looking promising at this time.

**Comment by Dunkelschunkel** [comment] 2023-12-07 15:54
b73 no errors in log --> Update to 77 leads to posted failure
b74 no errors in log --> Update to 77 leads to posted failure
b75 errors in log --> Update to 77 leads to posted failure
```
2023-12-07 16:29:22.104 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/webserver.py", line 122, in _handle_catch_all
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/slimproto/cli.py", line 252, in _handle_jsonrpc
    cmd_result = await self._handle_request(command_msg["params"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/slimproto/cli.py", line 571, in _handle_request
    cmd_result = handler(player_id, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/slimproto/cli.py", line 598, in _handle_players
    players.append(player_item_from_mass(start_index + index, mass_player))
                                         ~~~~~~~~~~~~^~~~~~~
TypeError: can only concatenate str (not "int") to str
```
b76 no errors in log --> Update to 77 successful. 

```
2023-12-07 16:43:40.912 INFO (MainThread) [music_assistant] Starting Music Assistant Server (35953d19ce9146cea4f29a9d938781f1) version 2.0.0b77 - uvloop: False
2023-12-07 16:43:40.960 INFO (MainThread) [music_assistant.cache] Performing database migration from 26 to 27
2023-12-07 16:43:41.358 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.179.4:8095
2023-12-07 16:43:41.429 INFO (MainThread) [music_assistant.music] Performing database migration from 26 to 27
2023-12-07 16:43:41.810 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2023-12-07 16:43:42.478 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.4 with libsoxr support
2023-12-07 16:43:42.478 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8096 - base url: http://192.168.179.4:8096
2023-12-07 16:43:43.187 WARNING (MainThread) [music_assistant.streams] Received unhandled POST request to /jsonrpc.js from 192.168.179.4
headers: <CIMultiDictProxy('Host': '192.168.179.4:8096', 'User-Agent': 'HomeAssistant/2023.12.0 aiohttp/3.9.1 Python/3.11', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'Content-Length': '120', 'Content-Type': 'text/plain; charset=utf-8')>

2023-12-07 16:43:43.193 WARNING (MainThread) [music_assistant.streams] Received unhandled POST request to /jsonrpc.js from 192.168.179.4
headers: <CIMultiDictProxy('Host': '192.168.179.4:8096', 'User-Agent': 'HomeAssistant/2023.12.0 aiohttp/3.9.1 Python/3.11', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'Content-Length': '113', 'Content-Type': 'text/plain; charset=utf-8')>

2023-12-07 16:43:43.200 WARNING (MainThread) [music_assistant.streams] Received unhandled POST request to /jsonrpc.js from 192.168.179.4
headers: <CIMultiDictProxy('Host': '192.168.179.4:8096', 'User-Agent': 'HomeAssistant/2023.12.0 aiohttp/3.9.1 Python/3.11', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'Content-Length': '120', 'Content-Type': 'text/plain; charset=utf-8')>

2023-12-07 16:43:44.812 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2023-12-07 16:43:44.813 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2023-12-07 16:43:44.820 INFO (MainThread) [music_assistant] Loaded music provider URL
```
I am now running b77 with my old library and no problems. I restored b76 an update from there.

**Comment by OzGav** [comment] 2023-12-08 13:55
As we believe these error were caused by an interruption of MA during the database migration we will close this and monitor in future updates.

**Closed by OzGav** 2023-12-08 13:55 UTC
Labels: triage

**Comment by Dunkelschunkel** [comment] 2023-12-08 14:03
I'll stick with it and hope for the best. Just stating that leaving plenty of time in between the updates.

**Comment by krisnoble** [comment] 2023-12-08 19:42
For anyone like me who rolled back I've just updated from my restored b75 to b78 with no issues 👍🏻 I did have to go in to each player and set the volume, shuffle/repeat and crossfade settings back how I like them but that seems to be all. Thanks Marcel for the fixes!

**Comment by Dunkelschunkel** [comment] 2023-12-08 19:47
Big thanks from me as well. I've read the release notes from b78 and there were some pr relating to db migration
