### ISSUE TITLE
Queue system doesn't work properly - Counts for Queue and Played not accurate - Count for queue alone not accurate

### ISSUE THREAD

**Issue by harryfine** [music-assistant/hass-music-assistant#2782] opened 2024-08-20 13:34 UTC
### What version of Music Assistant has the issue?

2.2.0b11

### What version of the Home Assistant Integration have you got installed?

2024.8.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In this and previous versions of the addon, finding an album for example, and hitting play and then checking queue either right away or after a few songs has played, results in counts (queue and played) that are wrong and I can't make sense of it.

For instance, I just added the Pointer Sisters from my local library, it shows 14 in the Queue, I count 26.  After the first song played, the Played went to 2 (yes, not 1),  And the total in Queue counter still shows 26, including the 2 on the right side under Played.

### How to reproduce

I've tried with Tidal albums, tried with local albums.  It happens with local music.  Tidal SEEMS ok but needs more observation.

### Music Providers

Tidal and local NAS, it happens on local from my NAS, perhaps not on Tidal.  Need more obsercation.

### Player Providers

Sonos

### Full log output
[ma_log.txt](https://github.com/user-attachments/files/16682848/ma_log.txt)

### Additional information

Sorry for pasting the log output.  FYI - I saved the output to a text file.  Using linux mint.  Opened with Nemo (default file manager), dragged file to this spot but it does not stick.

You will note from the attached picture that there are different song or album graphics, but I've checked the tags of ALL pointer sisters songs, all in the same folder, and they all have Point Sisters as artist, and Best of the Pointer Sisters as album.

![2024-08-20_09-32](https://github.com/user-attachments/assets/9ef2e0dd-a0f5-4e8d-8de5-9a19016b1e9c)

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by harryfine** [comment] 2024-08-20 13:37
Also I'm pretty sure that sometimes when a song ends, TWO songs will be added to the Played counter instead of one song.

**Comment by harryfine** [comment] 2024-08-20 14:52
Finally, it seems that it is not working properly with Tidal either.  I've been letting the music play.  The screenshot here shows there are 13 played, and yes, there are 13 in the right hand list.  But it also shows that there are 5 songs left in the queue.  But the list has about 25 songs.

![2024-08-20_10-50](https://github.com/user-attachments/assets/443ed943-685b-4972-b63c-8d652e190330)

**Comment by OzGav** [comment] 2024-08-20 20:51
Please edit your original post and remove the pasted log and attach it

**Comment by harryfine** [comment] 2024-08-20 21:07
As I indicated in the notes, I attempted to do that. Did you read my notes? Drag and drop didn't work, and there was no button to browse for the file. This is the second time you've pressed me on this issue on two separate bug reports. If that's the hill you want to die on, I will stop donating financially (I have donated twice), and stop trying to troubleshoot issues. 

⁣Harry Fine
647-970-6378​

**Comment by OzGav** [comment] 2024-08-20 22:12
No I did not see that one sentence in the hundreds of lines I was scrolling through. I have edited your post and attached it.

**Comment by OzGav** [comment] 2024-08-20 22:14
Do you have any more player types to try? If not you can install the snapcast provider and try that. I can't reproduce this but I don't have any Sonos speakers

**Comment by marcelveldt** [comment] 2024-08-21 00:11
This may be browser related, we are noticing a bunch of issues with firefox lately, any chance you are using that browser ?

**Comment by harryfine** [comment] 2024-08-21 00:26
Yes. I will try a different browser. 

⁣Harry Fine
647-970-6378​

**Comment by marcelveldt** [comment] 2024-08-21 11:20
reproduced this issue, fixed in 2.2.0

**Comment by OzGav** [comment] 2024-08-22 10:54
@harryfine please close this if it has been fixed.

**Closed** 2024-08-22 11:00 UTC
Labels: bug, More info, Fix to be Confirmed
