### ISSUE TITLE
Problems with resuming play to Sonos One with Beta 2.3.0rc3

### ISSUE THREAD

**Issue by gtothill** [music-assistant/hass-music-assistant#3072] opened 2024-10-25 01:07 UTC
### What version of Music Assistant has the issue?

2.3.0rc3

### What version of the Home Assistant Integration have you got installed?

2024.10.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Firstly - outstanding software. Thanks to everyone who has worked on it!
I have recently experienced the problem of tracks being skipped using the current stable release and so I switched to the Beta stream. This resolved the track skipping issue but I have found another problem. When a device external to MA starts to stream to the Sonos One speakers, the MA stream stops and MA correctly reports that an external source is streaming to the Sonos, and what is playing. However, if I try and resume playing from MA it does not do so and throws an error.  The only way I have found of giving MA back 'access' to the speaker is restarting the MA server.  This does not happen with the stable release. 
I just don't know enough about this particular technology to be able to start to debug so I thought I should report it.

### How to reproduce

1) Play something from MA server to Sonos One.
2) Stream something to the Sonos from another source (say Alexa). Music and radio sources both exhibit this issue.
3) Try and resume the original stream from MA >> Not possible to stream again from MA.

### Music Providers

On MA side: Spotify >> Sonos and Plex >> Sonos

### Player Providers

Sonos One Speakers and Sonos Play 5 speakers

### Full log output

[music-assistant (1).log](https://github.com/user-attachments/files/17514371/music-assistant.1.log)

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by gtothill** [comment] 2024-10-25 01:08
Sorry - I just checked. This is an issue with all my Sonos hardware - not just the Sonos One's.

**Comment by OzGav** [comment] 2024-10-25 10:38
Which Sonos provider? What happens if you reload the provider (look in the overflow menu in MA settings)

**Comment by gtothill** [comment] 2024-10-25 15:38
> Which Sonos provider? What happens if you reload the provider (look in the overflow menu in MA settings)

Thanks for the reply OzGav. The provider is the SONOS provider @ music-assistant (not the SONOS S1).

As you suspected, reloading the provider cures the problem until another external stream seizes the Sonos.

I can also confirm that, on my setup, this now occurs with the stable release as well.

Regards,

**Comment by marcelveldt** [comment] 2024-10-25 16:00
We are not full external source aware yet. We are slowly making progress of making MA more aware of handling situations where the speaker/device is also controlled by other sources/platforms but for now we only support the "happy flow" where MA is the happy flow. Expect some updates to improve this in the next update(s).

To fix this particular issue: Ensure that you "power off" the player in MA before starting any other media outside of MA. That will at least wipe the active session. That is not a full solution (because it still will not allow you to switch between the external source to MA) but that will at least get you to start the MA playback again after the 3rd party source stopped.

**Comment by gtothill** [comment] 2024-10-25 17:47
Perfect - thanks for the explanation. MA is an absolutely perfect solution for us - we have Home Assistant tablets in two rooms. The only issue is that the kids will ask Alexa to play their music and as things stand that disables MA. Looking forward to any progress and in the meanwhile thanks to you and all the developers.

**Comment by gtothill** [comment] 2024-10-25 17:50
Just one last thought - there was a stable version where this didn’t happen, although I understand that might have just been a vagary of that particular build and my environment.

**Comment by OzGav** [comment] 2024-10-25 20:32
Closing due to expected behaviour

**Closed by OzGav** 2024-10-25 20:32 UTC
Labels: triage
