### ISSUE TITLE
Failure to Play - Throttling Issue

### ISSUE THREAD

**Issue by gadget2010** [music-assistant/hass-music-assistant#2610] opened 2024-07-11 14:13 UTC
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

Add on only

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

![Screenshot 2024-07-11 13 31 16](https://github.com/music-assistant/hass-music-assistant/assets/140326921/b5c74463-e789-49dc-bb22-df797c008178)
When trying to play music I get the following message.    get_throttling_function_name: could not find match for multiple (See attached image) 

### How to reproduce

Try to play music

### Music Providers

Youtube Music

### Player Providers

Youtube Music

### What version of Home Assistant Core are your running

2024.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by MarvinSchenkel** [comment] 2024-07-11 14:51
Duplicate of #2607

**Closed by MarvinSchenkel** 2024-07-11 14:51 UTC
Labels: triage
