### ISSUE TITLE
Queue reloading in Radio Mode

### ISSUE THREAD

**Issue by rVlad93** [music-assistant/hass-music-assistant#1848] opened 2024-01-30 00:11 UTC
### What version of Music Assistant has the issue?

2.0.0b90

### The problem

When the queue is in Radio mode and last item it loops at loading the new songs every time the new ones were loaded.  I'm using YTmusic provider. 

https://github.com/music-assistant/hass-music-assistant/assets/60452666/5e4ea953-462e-49ea-a3b6-02affa7655b2

### How to reproduce

Activate radio mode
Select last item in the list

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment] 2024-01-30 07:46
What command did you us eto start the queue in the first place ? HA automation or MA frontend ?
It is also strange because in radio mode you shouldnt be able to reach the end as it shouuld keep refilling

**Comment by OzGav** [comment] 2024-02-05 04:13
We will close this soon due to no followup

**Comment by rVlad93** [comment] 2024-02-05 23:14
It was for the MA frontend. Sorry about the late reply.

**Comment by OzGav** [comment] 2024-02-05 23:23
Do you have another provider to try? This might be YT specific.

**Comment by marcelveldt** [comment] 2024-04-20 10:00
I just reproduced this one and fixed it. Available in the next beta (b139)

**Comment by OzGav** [comment] 2024-04-20 12:23
confirmed fixed

**Closed by OzGav** 2024-04-20 12:23 UTC
Labels: bug
