### ISSUE TITLE
media_player.join not working

### ISSUE THREAD

**Issue by JDogg016** [music-assistant/hass-music-assistant#3134] opened 2024-11-05 13:41 UTC
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

2024.10.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Running the action to join two Sonos MA Speakers has no effect:

```
action: media_player.join
data:
  group_members:
    - media_player.ma_gym_overhead_speaker_sonos
    - media_player.ma_gym_tv_speaker_sonos
target:
  entity_id: media_player.ma_gym_tv_speaker_sonos
```

### How to reproduce

Just try to run an action to join Sonos speakers in HA (or through Node Red).

### Music Providers

N/A

### Player Providers

Sonos

### What version of Home Assistant Core are your running

2024.10.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment] 2024-11-05 14:46
Are you certain they are both MA provided entities? Can those exact same two speakers be joined in the MA UI?

**Comment by JDogg016** [comment] 2024-11-05 16:21
Yes.  I confirmed the correct naming convention (as, admittedly, it can get confusing).  The funny thing is I can run an action to 'unjoin' them from one another.  

When I join the two Speakers in the Sonos App I can confirm the speakers join in MA (in about 30 seconds).  When I join the speakers in MA, they show as joined in the Sonos App about 30 seconds later.

Also, if they are previously joined (ie. through MA or the Sonos App), I receive the following message upon attempting to join them in Node-Red: Player Gym TV Speaker is already synced to another player on its own, you need to unsync it first before you can join other players to it."

**Comment by OzGav** [comment] 2024-11-05 22:06
The last error would seem to be correct if the player is already synced? Please review the HA log after trying the join action.

Also please format any code snippets so we can see that it isn’t a typo (edit your original post please)

**Comment by JDogg016** [comment] 2024-11-05 22:54
Formatted the code snippet.  Also, I assume you mean the HA Core log (under System)?  After performing the action, there is nothing in the Log (maybe I need to turn on debug logging)?  Also, there is nothing in the logbook for the devices at issue.

**Comment by OzGav** [comment] 2024-11-05 23:21
OK looks like I can recreate this. It will be looked into further soon.

**Comment by OzGav** [comment] 2024-11-06 15:37
This will be fixed in the next update

**Comment by OzGav** [comment] 2024-11-09 12:38
confirmed fixed

**Closed by OzGav** 2024-11-09 12:38 UTC
Labels: bug, HA Integration, Fix to be Confirmed

**Comment by JDogg016** [comment] 2024-12-18 14:50
Is this only fixed in the HA version or the HACS version?  In the HACS version, the error message is gone, but you nothing happens when you join speakers?

**Comment by OzGav** [comment] 2024-12-18 20:35
https://github.com/music-assistant/hass-music-assistant/issues/3293

**Comment by ronluna** [comment] 2024-12-19 19:33
Not sure if there is something missing here but I can't get the MA players to Join of unjoin  running the latest HA and MA. 

This won't join and no error in MA logs
'''
action: media_player.join
data:
  group_members:
    - media_player.master_bath_sc4_c7
    - media_player.master_bed_sc3_c5
target:
  entity_id: media_player.master_bed_sc3_c5
'''

This won't unjoin and no error in MA logs
'''
action: media_player.unjoin
data:
  group_members:
    - media_player.master_bath_sc4_c7
    - media_player.master_bed_sc3_c5

'''

any ideas?

**Comment by OzGav** [comment] 2024-12-19 19:52
Again https://github.com/music-assistant/hass-music-assistant/issues/3293
