### ISSUE TITLE
Youtube Music won't play

### ISSUE THREAD

**Issue by Lansenou** [music-assistant/hass-music-assistant#1465] opened 2023-08-09 20:15 UTC
### What version of Music Assistant has the issue?

v2023.6.0b3

### The problem

Very similiar to #1378 except that I'm using a newer version which should be fixed.

When attempting to play a playlist or track through the YouTube Music provider the add-on seems to connect to the device (Sonos Beam, Sonos One SL or HK Citation ONE) but shortly after the player returns to Idle state. An error is thrown in the Add-on logs.

### How to reproduce

Fresh install of addon (I've tried it through HACS but also directly via the add on store without having the HACS intergration installed)
Set up YT Music connection
Attempt to cast playlist/track to any Google Nest Mini
Error occurs

### Relevant log output

2023-08-09 21:58:57.352 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 473, in serve_queue_item_stream
    streamdetails = await get_stream_details(self.mass, queue_item=queue_item)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 268, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 498, in get_stream_details
    url = await self._parse_stream_url(stream_format=stream_format, item_id=item_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 797, in _parse_stream_url
    signature = await self._decipher_signature(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 823, in _decipher_signature
    self._cipher = await asyncio.to_thread(_decipher)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 818, in _decipher
    cipher = pytube.cipher.Cipher(js=ytm_js)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 399, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 305, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 290, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
2023-08-09 21:58:57.397 ERROR (Thread-36) [pychromecast.controllers.media] Exception thrown when calling load failed callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pychromecast/controllers/media.py", line 745, in _fire_load_failed
    listener.load_media_failed(item, error_code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Listener' object has no attribute 'load_media_failed'
2023-08-09 21:58:57.398 WARNING (Thread-36) [music_assistant.providers.chromecast] Load media failed: 10 - error code: 104

### Additional information

Music Assistant BETA
Current version: 2.0.0b70

### What version of Home Assistant Core are your running

2023.08.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by qupterra** [comment] 2023-08-10 00:26
The issue is in PyTube (similar to an issue that occurred a month ago) [PyTube issue for RegexMatchError](https://github.com/pytube/pytube/issues/1750 )

**Comment by rodgers86** [comment] 2023-08-10 07:07
Exact same issue here. Started about 24hours ago 

Running latest Music Assistant on latest HA Supervised.

no issues playing other sources like tts or radio.

**Comment by OzGav** [comment] 2023-08-10 10:58
Yes appears Google has changed something again. It is being looked into.

**Comment by MarvinSchenkel** [comment] 2023-08-11 05:37
Should be fixed in the next release

**Comment by StephanFastxl** [comment] 2023-08-14 12:10
> Should be fixed in the next release

Which release should it be fixed? I have 2.0.0.b70 but i can't play youtube music. Thx!

**Comment by OzGav** [comment] 2023-08-14 12:38
71

**Comment by OzGav** [comment] 2023-08-15 00:46
beta 71 is released. Let us know if this is not fixed

**Closed by OzGav** 2023-08-15 00:46 UTC
Labels: bug

**Comment by nehasjains** [comment] 2023-08-15 02:32
Not working for me just installed beta 71

**Comment by OzGav** [comment] 2023-08-15 04:03
You need to be more descriptive than “not working” and post the relevant logs

**Comment by nehasjains** [comment] 2023-08-15 05:52
I just tried to play my save playlisys from YouTube. After selecting play. The Playlist gets loaded but a second it stops. Please find the logs below
2023-08-15 11:18:40.407 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 473, in serve_queue_item_stream
    streamdetails = await get_stream_details(self.mass, queue_item=queue_item)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 268, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 498, in get_stream_details
    url = await self._parse_stream_url(stream_format=stream_format, item_id=item_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 797, in _parse_stream_url
    signature = await self._decipher_signature(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 823, in _decipher_signature
    self._cipher = await asyncio.to_thread(_decipher)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 818, in _decipher
    cipher = pytube.cipher.Cipher(js=ytm_js)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W
2023-08-15 11:18:49.506 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 473, in serve_queue_item_stream
    streamdetails = await get_stream_details(self.mass, queue_item=queue_item)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 268, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 498, in get_stream_details
    url = await self._parse_stream_url(stream_format=stream_format, item_id=item_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 797, in _parse_stream_url
    signature = await self._decipher_signature(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 823, in _decipher_signature
    self._cipher = await asyncio.to_thread(_decipher)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 818, in _decipher
    cipher = pytube.cipher.Cipher(js=ytm_js)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W

**Comment by MarvinSchenkel** [comment] 2023-08-15 09:14
And yet again, Google changed something before we had beta 71 released. Beta 72 will include the fix for this particular error.

**Comment by nehasjains** [comment] 2023-08-15 09:16
Thank you....

**Comment by MarvinSchenkel** [comment] 2023-08-15 12:19
> Thank you....

Please check again with beta 72.

**Comment by nehasjains** [comment] 2023-08-15 12:54
Sure, but beta 72 is not showing yet...

**Comment by nehasjains** [comment] 2023-08-15 13:19
> > Thank you....
> 
> Please check again with beta 72.

Thank you.... working now...👌😊
