### ISSUE TITLE
Some tracks are marked with the wrong artist / artwork after 2.2 upgrade

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2792] opened 2024-08-22 23:23 UTC
### What version of Music Assistant has the issue?

2.2.1

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After upgrading to 2.2.1, several Qobuz tracks from Jean-Michel Jarre are showing as being from Andreas Staier.
The lone file system provider track I have, a WAV file with zero metadata in it, also shows as being from Andreas Staier.

### How to reproduce

1. Install MA 2.2.1
2. In the Qobuz app, favorite 4 tracks from the "Planet Jarre" album from Jean-Michel Jarre, and other Jarre albums
3. Add Qobuz provider to MA
4. Create a playlist that includes the 4 tracks from step 2, and also other tracks from Jarre albums, which are not favorited
5. Review the playlist content . It shows this.

![image](https://github.com/user-attachments/assets/5518dbdd-5d8f-47af-8e06-9c1b947a280f)

As you can see, tracks 1, 3, 4, and 5 are all shown as being authored by Andreas Staier. / Jean-Michel Jarre . That would be an unusual collaboration to be sure !  The tracks are actually all from Jean-Michel Jarre.
The album artwork shown is the correct one, though.

This was not the case in 2.1.x .

6. Add the file system (remote) provider, pointing it to a directory containing a single chants.wav file that has no metadata
7. Go to the track view in MA
8. Looks for the file called "chants" which is the name of the WAV file in my FS provider with no meta data
9. This is what appears :

![image](https://github.com/user-attachments/assets/16988b5b-bfaf-48f9-acde-376a021935a9)

It is also shown as being authored by Andreas Staier, and it has a picture of Andreas Staier in the artwork as well.

There should be no artwork and no artist name, since there is no metadata for this WAV file.

This was also behaving correctly in 2.1.x .

### Music Providers

Qobuz
File system (remote)

### Player Providers

N/A

### Full log output

[ma.log](https://github.com/user-attachments/files/16720022/ma.log)

### Additional information

I can reproduce this issue at will by rolling back to 2.1.x from an add-on backup in HA . Upgrading again to 2.2.x shows the regression.

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by madbrain76** [comment] 2024-08-22 23:31
Here is what the playlist looks like after rolling back to 2.1.4 from backup .

![image](https://github.com/user-attachments/assets/40c2cdbd-8e85-4ed9-ad37-aedbb7ff358d)

And here is what the WAV file looks like in 2.1.4 :

![image](https://github.com/user-attachments/assets/71d07a7b-8db6-48b0-8c09-a8aeee3770bc)

Both are correct.

**Comment by marcelveldt** [comment] 2024-08-23 01:42
Please let me know exactly which of these files exist on your local disk and in what structure they're in.

**Comment by madbrain76** [comment] 2024-08-23 01:50
There is only a single WAV file in my FS (remote) provider directory.

![image](https://github.com/user-attachments/assets/c3acb4af-3438-44b9-bb72-bcbad863c909)

This WAV file was created by me in Powerdirector. It has no metadata, and does not exist in Qobuz.

Here is the configuration for the file system (remote) provider.

![image](https://github.com/user-attachments/assets/07509b85-70e9-4ed0-a770-3eb2b53e7f54)

Every other track comes from Qobuz.

I'm not aware of any other local files. I have not tried to inspect the files in MA itself on the HAOS VM.

**Comment by madbrain76** [comment] 2024-08-23 01:55
BTW, even after deleting the "file system (remote)" music provider completely, the problem from steps 1-5 remains.

The main reason I reported the issue with both the Qobuz and FS (remote) providers together is that they are listing the same wrong artist, Andreas Staier, on tracks from each music provider.

**Comment by OzGav** [comment] 2024-08-23 02:17
2.2.2 has been released which does fix a bug with provider removal. I wonder if you have been affected by that?

**Comment by OzGav** [comment] 2024-08-23 02:19
Where does Andreas Staier come from. Do you have him in the library also?

**Comment by madbrain76** [comment] 2024-08-23 02:27
> 2.2.2 has been released which does fix a bug with provider removal. I wonder if you have been affected by that?

I'm still on 2.2.1 . It seems I'm getting upgrade notifications on time delay.
Do you have a reference to the bug in question ?

I believe I was indeed affected by an issue with provider removal. MA showed a "spinning" icon. I worked around it by restarting the add-on. I did not want to pollute this bug with this issue, which I believe is unrelated.

The problem as I described it in the original post did not involve provider removal. I started with both Qobuz and FS providers in 2.1.4 . I then upgraded to 2.2, and saw the reported problem. No provider removal was involved to see the issue. I can still rollback to 2.1.4 ABC upgrade again, and reproduce.

**Comment by madbrain76** [comment] 2024-08-23 02:30
> Where does Andreas Staier come from. Do you have him in the library also?

Yes. I have him favorited in Qobuz. And that translates to him showing up in the MA library under artists.

**Comment by marcelveldt** [comment] 2024-08-23 06:37
Super strange, I'm trying to reproduc eit but so far without luck. I have favorited the same tracks and artists in Qobuz.
Make me wonder if it has somehow to do with that tag-less file.

**Comment by madbrain76** [comment] 2024-08-23 06:40
If there is a way to remove my Qobuz and FS credentials, I'm happy to give you a backup of my add-on.

I can also try restoring a backup from a few days ago when I did not have the FS provider at all, only Qobuz, and then do the migration again.

**Comment by marcelveldt** [comment] 2024-08-23 06:53
> If there is a way to remove my Qobuz and FS credentials, I'm happy to give you a backup of my add-on.

Well basically I only need to investigate the library and cache db's, which contain no credentials at all.
So if you unzip the backup, you should be able to extract the two .db files from there and send me with discord PM ?

**Comment by madbrain76** [comment] 2024-08-23 09:59
@marcelveldt check your PM . I'm madbrain there (once in a while, anyway).

**Comment by dmcc** [comment] 2024-08-23 12:52
In case it's useful: I'm also seeing something like this (unusual "collaborations" on songs 😁 ) and I'm not using Qobuz.

My setup is just Chromecast + Filesystem (local).

**Comment by sfnis** [comment] 2024-08-23 16:29
I have Plex as my only provider, and its happening to me too.  It was fine in the previous version, its not affecting functionally, but its sort of funny.   

![MH - MAD](https://github.com/user-attachments/assets/e4321dea-daa0-431b-998a-36076b3f7850)

![mh-2](https://github.com/user-attachments/assets/8dce3ab5-94a2-40bd-974e-94d7d467c181)

![PearlJam](https://github.com/user-attachments/assets/26c6213b-42ec-46dc-bd41-fdcb7992c253)

**Comment by bj61251** [comment] 2024-08-24 13:26
I'm also seeing this issue, where albums are being attributed to two completely unrelated artists. Currently loading plex, and local file system as sources (they're virtually the same thing in my case). 

![Screenshot_20240824-092251](https://github.com/user-attachments/assets/2b2f7813-6844-4c05-aed2-a603ae0a8243)

**Comment by bj61251** [comment] 2024-08-24 15:06
So a bit more info, in my case all of the problematic albums seemed to be coming from the local file system provider. I just deleted that music provider, and all of the bad tracks disappeared. Not sure if that'll help others or not, but I figured it's worth mentioning.

**Comment by dutchmendesign** [comment] 2024-08-24 15:47
Same here!
Upgrade 2.2.1 to 2.2.2  It was a mess so i reinitialize DB.
After new scan some artist names are still messed up and for some also metadata artist.jpg is swapped with cover.jpg.
Music provider: NAS
Will try a fresh reinstall now....

**Comment by dutchmendesign** [comment] 2024-08-24 18:54
It looks like there is something getting messed up when artist = album.
In my case: Artist 'Bloc Party' with album 'Bloc Party'.
Franz Ferdinand - Franz Ferdinand
The Doors -The Doors 
Weezer - Weezer

**Comment by OzGav** [comment] 2024-08-24 20:32
@dutchmendesign yes Marcel has identified this issue and will fix it soon https://discord.com/channels/753947050995089438/1098863590926204949/1276822113029984278

**Comment by OzGav** [comment] 2024-08-25 21:38
The artwork issue when artist name = album name should be fixed in 2.3.0 beta 4

**Comment by marcelveldt** [comment] 2024-08-28 22:52
this one should be entirely fixed with 2.3.0b8 although I cant repair any already mangled entries - either restore a backup first and then upgrade to 2.3.0b8 or initiate a full library scan (or just refresh the wrong items manually)

Only issue left is a small glicth in the album tracks listings where the wrong album is shows but this is just a UI glitch that will be fixed in the next beta.

**Comment by OzGav** [comment] 2024-08-29 21:13
@w00master make sure your share is mapped to the Music level of that drive.

A full db reset is achieved by going to MA SETTINGS>>CORE>>MUSIC CONTROLLER>> ADVANCED but hold off on that until after the next beta as some more fixes have been made.

**Comment by w00master** [comment] 2024-08-29 21:17
Thanks @OzGav. That said, what do you mean re: "make sure your share is mapped to the Music level of that drive."

Are you referring to Plex library being Mapped to D:\daapd\Music instead of D:\daapd\Music\Van Halen\ ?

or are you saying the \Music directory needs to be in the root directory of the drive?

if it's the former, I"m all set.  Just wanted to be sure I understood.  Re: full reset - thank you. I'll hold off until the update comes.

**Comment by OzGav** [comment] 2024-08-29 21:37
@w00master I didn’t know if you were using Plex. So disregard in that case. However, unless there is a specific reason we recommend you skip the middleman and use the local provider in which case you should map that provider to d://daapd/Music

**Comment by w00master** [comment] 2024-08-29 22:16
Thanks @OzGav  I've disabled Plex Music and enabled Network Share.  I'm still unfortunately seeing the same issue - but will wait for the next update to see if this fixes it.  If not will try the full reload.

**Comment by madbrain76** [comment] 2024-08-30 01:47
@w00master Did you try removing the music provider and adding it back ? That had solved it for me earlier when I ran into the issue.

**Comment by OzGav** [comment] 2024-08-30 12:56
@w00master please try with beta 16

**Comment by w00master** [comment] 2024-08-30 13:13
Thanks @OzGav  and everyone.  Before updating to beta 16 - (did this yesterday) - I removed the Plex provider (instead of just disabling it) and just entirely went only with Filesystem (remote) and it appears that has fixed the issue.  Unsure what Plex did or MA's provider of Plex did, but removing it entirely got the tagging back in order.

Currently updating to beta 16.  Thanks everyone.

**Closed** 2024-08-30 13:37 UTC
Labels: bug, Fix to be Confirmed

**Comment by jpbaril** [comment] 2024-09-17 20:28
@OzGav This does not seem to be resolved, I still have the issue.

Since around beginning of August metadata constantly get mixed up.
I have reset the database 3 times since then and the issue always reappear.
At first it was almost all my library that was incorrect, but in the last few versions it happens here and there for a few albums and tracks.
Last time I did reset was yesterday and I again have wrong metadata shown.
I was/am on server version 2.2.5 with HA integration 2024.9.1.

![Capture d’écran du 2024-09-17 15-57-34](https://github.com/user-attachments/assets/f3e799a6-4590-4807-b123-21fe5c237590)
As you can see, the correct artist should be "Ska-P", yet it is shown as "Crosby, Stills, Nash & Young".

**Comment by OzGav** [comment] 2024-09-17 21:10
@jpbaril how have you tagged your music?

**Comment by OzGav** [comment] 2024-09-17 21:30
It does really matter what it looks like elsewhere. The track naming suggests to me that it isnt tagged correctly. Please post a screen capture of all the tags from Picard of the second track

**Comment by jpbaril** [comment] 2024-09-17 21:42
Well, I retagged the whole artist folder in the meantime so it would not be truthful anymore for this issue.

**Comment by OzGav** [comment] 2024-09-17 21:52
Then you should remove both artists ska-p and CSNY so these albums also get removed and then resync

**Comment by mcwieger** [comment] 2024-11-12 15:09
Same issue here for many artists. All music in my library is organized according to Musicbrainz convention (..\Artist\Album\Tracks) and tagged with Picard, so totally clean.

**Comment by OzGav** [comment] 2024-11-13 08:52
@mcwieger do a database reset and see what happens after that. MA SETTINGS>>CORE>> MUSIC CONTROLLER >> ADVANCED

**Comment by mcwieger** [comment] 2024-11-18 10:27
I refreshed my entire library. All ok.

However, now I added a new album (Lovely Creatures: The Best Of Nick Cave And The Bad Seeds) which includes one track that is performed with Kylie Minogue. This is not in the Artist tag though, this just shows Nick Cave & The Bad Seeds.
The track was already present in my collection on another album though.

Result: the album that was added now shows in the library as:
Album: Lovely Creatures: The Best Of Nick Cave And The Bad Seeds
Artist: Nick Cave & The Bad Seeds + Kylie Minogue (although she is nowhere in any tag in this album)

My entire collection has Musicbrainz IDs. The Track ID of both songs are identical. Could it be that if there is a similar Track ID (or other Musicbrainz ID) on two different albums, this "contamination" takes place?

**Comment by OzGav** [comment] 2024-11-18 11:02
I think if you look at the MB ARTIST ID you will find two listed. You should at least as this is what is in the MB database. https://musicbrainz.org/recording/8f9dc0f3-b592-4b28-a7af-4358e7df30e8/

**Comment by mcwieger** [comment] 2024-11-18 12:45
I queried the artist in my MA database and somehow it updated the name of the artist to 'Nick Cave & The Bad Seeds + Kylie Minogue', where it should be 'Nick Cave & The Bad Seeds'. So now it shows up everywhere with the new name, which explains the issue I have here.

I can easily update the name in the db now, but that does not explain why this artist got this name in the first place.

Is there a log I can look at for this?

**Comment by OzGav** [comment] 2024-11-18 12:48
The explanation will be in the tags. You will need to wait until a fix is rolled out for this problem.

**Comment by mcwieger** [comment] 2024-11-18 14:07
There's clearly an issue with recordings that have multiple artists. I have a database of 20.000+ tracks and a query on track_artists only gives me 24 tracks with multiple artists (should be maaaany more).
A random check on one of these shows that the track 'It takes two' shows 'Tina Turner & Rod Stewart & Tina Turner' as the artist.

After investigating a few of the tracks, it shows that this issue occurs whenever two versions of the same track are present in the library, but with two different artists.

- One of the tracks had artist Tina Turner
- The other 'Rod Stewart & Tina Turner'.
- This becomes 'Tina Turner & Rod Stewart & Tina Turner'
- In addition, the name of the artist 'Rod Stewart' becomes 'Tina Turner & Rod Stewart' (but the description of the artist refers to Rod Stewart), as MA thinks this name in the Artist tag is correct for the first-mentioned Musicbrainz Artist Id of this track (which is Rod Stewart).

So here's your way to reproduce it:
- Add the same song to the library twice
- Make sure they both contain both Musicbrainz Artist IDs of contributing artists
- Make sure they both have different Artist tags (e.g. change the order of both)
- Possibly change the order of the Musicbrainz Artist IDs in the file, could be that this contributes to the issue
- Expected bug is to find that at least one of the Artists is being stored incorrectly AND that both Artist tags are shown for the both tracks

**Comment by mcwieger** [comment] 2025-01-15 11:18
Bump to make sure the issue does not go to stale. Could the issue be reproduced with the info from my previous post?

**Comment by OzGav** [comment] 2025-01-15 11:21
This wont go stale because its closed! This is known and is on the backlog. https://github.com/orgs/music-assistant/projects/2/views/1?pane=issue&itemId=84259501

**Comment by mcwieger** [comment] 2025-04-25 07:25
Marked as Done in the backlog, but still encountering the issue on server version 2.5.1.

Deleted the database, cache and all other files in the persistent Docker folder and the issue is still there.

**Comment by OzGav** [comment] 2025-04-25 07:40
You need to open a new issue as your problem is different to the OP
