### ISSUE TITLE
Sonos Stereo pair drops right channel for last second(s) of track.

### ISSUE THREAD

**Issue by dragon2611** [music-assistant/hass-music-assistant#1855] opened 2024-01-31 09:18 UTC
### What version of Music Assistant has the issue?

2024.1.0

### The problem

Since Yesterday (So I think after updating to b90) I've had multiple instances where the right audio channel drops for the last 1-2 seconds of the track when playing to a Sonos Stereo pair from Spotify.

This has happened with both play:1s and the Ikea symfonisk g2 bookshelf speakers.

Crossfade is disabled.

### How to reproduce

Queue a playlist with multiple tracks, it doesn't seem to happen all the time and to be noticable you'd need to be playing something that plays audio right up until the end of the track.

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment] 2024-01-31 10:03
When you say it doesn’t happen all the time do you mean with the exact same track sometimes it doesn’t happen?

What happened when you tried the other stereo pair?

**Comment by dragon2611** [comment] 2024-01-31 10:37
No, I meant there are other songs that seem to have music right until the end of the track and those didn't seem to do it.

It happened on both the Play:1's and the symfonisk speakers which are different stereo pairs, I was not using grouped playback at the time.

**Comment by OzGav** [comment] 2024-02-01 01:23
OK this will get looked at in due course

**Comment by marcelveldt** [comment] 2024-02-20 20:55
Can you please re-test this in beta 103 ? I couldn't find anything really nor could I reproduce this but I may have found something that could potentially induce it. Long shot, but you never know.

**Comment by OzGav** [comment] 2024-02-22 13:00
We will close this soon due to no followup

**Comment by dragon2611** [comment] 2024-02-22 17:30
Sorry I've not had a chance to test this yet, I had meant to do so earlier today but ended up being busy most of the day and never did get around to putting any music on.

**Comment by dragon2611** [comment] 2024-02-23 09:16
@marcelveldt It looks like it still occurs.

**Comment by marcelveldt** [comment] 2024-02-23 09:30
I'm afraid we can't help you then. You are the only one reporting this from the many people. I have Sonos stereo pairs as well and never ever experienced such a thing, ever. Maybe it's your music source? What content are you playing?

**Comment by dragon2611** [comment] 2024-02-23 09:43
The last occurrence was on one of the earlier tracks of https://open.spotify.com/album/72jVD2T2lMuoS8DLHbFS2r?si=3CsdXecQRmaoSrtg36RD2Q

**Comment by marcelveldt** [comment] 2024-02-27 09:47
So, I have been listening to the album you linked above all morning and there was not a single dropout of any of the channels. I was listening to a Sonos stereo pair. No crossfade.

I'm afraid we can't help you with this one as you seem to be the only one reporting this issue and I am not able to reproduce it in any way.

Dropouts can occur when bandwidth is limited. Check your wifi capacity, especially stereo pairs add a fraction more traffic to your network. If you have the possibility, try if connecting a stereo pair wired makes any difference to test the theory of this being a bandwidth/connectivity issue. 

Also note that if you connect one of your speakers wired, this will enable SonosNet which is a dedicated wireless signal for Sonos speakers which is not always an improvement. If you have good WiFi, I always recommend to disable SonosNet as its bandwidth is rather limited and its not very smart.

**Closed** 2024-02-27 10:13 UTC
Labels: bug, More info
