### ISSUE TITLE
[Remote File Provider] Quote character not accepted in password

### ISSUE THREAD

**Issue by DutchJaFO** [music-assistant/hass-music-assistant#2266] opened 2024-05-12 19:24 UTC
### What version of Music Assistant has the issue?

2.0.2 STABLE

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I cannot add a 'remote share provider' with a password that contains a (single) quote character.
The reported error is "unterminated quoted string"
Changing the password to something that does not contain this character fixed it.

### How to reproduce

Create a user with a password that has a single quote on your NAS.
For example  Pass"w0rd!
Add a file provider in MA using this user and password combination.

The provider won't be added as it will refuse the password.

### Music Providers

File system (Remote Share)

### Player Providers

none

### Full log output

2024-05-12 20:59:26.067 INFO (MainThread) [music_assistant.providers.filesystem_smb] Mounting //192.168.0.42/MijnMuziek/Artists to /tmp/filesystem_smb--3UBR8ntP
2024-05-12 20:59:26.070 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/save: Connection failed for the given details: SMB mount failed with error: /bin/sh: 1: Syntax error: Unterminated quoted string

### Additional information

Changing the password to something that doesn't contain the quote fixed the problem.
However as it may not be viable to change passwords this is a work-around.

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment] 2024-05-12 23:09
Is this not a duplicate of this https://github.com/music-assistant/hass-music-assistant/issues/2234

**Comment by MelHarbour** [comment] 2024-06-25 09:11
It's the same bug. The special character you're using (") is a special case of the other issue. I recommend closing this one in favour of the other.

**Comment by OzGav** [comment] 2024-06-25 12:00
Will do

**Closed by OzGav** 2024-06-25 12:00 UTC
Labels: duplicate, triage

**Comment by OzGav** [comment] 2024-06-29 12:06
@DutchJaFO this will be fixed in the next update.

**Comment by Jc2k** [comment] 2024-06-29 12:34
We probably still need additional percent encoding for symbols that aren't valid in uris - like a username or password with an @ for example. Hoping to add that this weekend. But next update should remove the /bin/sh escaping from the picture entirely, which is the source of that error message.
