### ISSUE TITLE
"Currently playing" not updating in queue flow mode

### ISSUE THREAD

**Issue by johnboiles** [music-assistant/hass-music-assistant#2940] opened 2024-09-18 21:02 UTC
### What version of Music Assistant has the issue?

2.2.5

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Sometimes, in queue flow mode, despite playing normally, the track in MA doesn't update -- it just shows the same track having been playing for a long time. When this happens the playlist continues to progress in the player just fine.

<img width="1370" alt="image" src="https://github.com/user-attachments/assets/8d2bf2ca-20e6-42f3-982a-d9f2db812a93">

Could this be somehow related to the player not reporting it's playback position?

I'm also having this issue #2893, perhaps there's a shared root cause.

### How to reproduce

I'm playing a playlist via automation. Not sure on repro steps yet as it seems to only happen sometimes.

### Music Providers

Apple Music

### Player Providers

ESPHome Media Player (using https://github.com/gnumpi/esphome_audio)

### Full log output

[music-assistant (3).log](https://github.com/user-attachments/files/17050258/music-assistant.3.log)

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment] 2024-09-18 21:42
Oof, please disable verbose logging. It makes the log super hard to read and its only needed on special request. Debug level is verbose enough,  verbose is really only needed to zoom into a specific issue but it also comes with some side effects due to the added overhead.

**Comment by johnboiles** [comment] 2024-09-18 22:22
I have verbose logging on to try to investigate #2893 (the ffmpeg logs are useful to understand what the streamer is doing). That's the worse issue since it interrupts our office music ~4x per day

**Comment by johnboiles** [comment] 2024-09-18 22:27
Here's the log with `VERBOSE` filtered out (via `grep -v " VERBOSE " /Users/johnboiles/Downloads/music-assistant.3.log > /Users/johnboiles/Downloads/music-assistant.3-debug.log`)

[music-assistant.3-debug.log](https://github.com/user-attachments/files/17051046/music-assistant.3-debug.log)

**Comment by OzGav** [comment] 2024-09-27 12:47
Do you have other player types you can try? (I assume this is using the HA provider)

**Comment by marcelveldt** [comment] 2024-10-01 08:50
> Here's the log with `VERBOSE` filtered out (via `grep -v " VERBOSE " music-assistant.3.log > music-assistant.3-debug.log`)
> 
> [music-assistant.3-debug.log](https://github.com/user-attachments/files/17051046/music-assistant.3-debug.log)

Thanks for that but at the same time I recommend to **disable verbose logging** (especially at global level) as it comes with some side effects. Only enable it on a PER PROVIDER base when asked specifically by one of the developers. It can cause issue son its own because the code acts a bit different when running in verbose mode (and per definition not nice to performance). So just a tip to not leave it enabled at all times or like you say, investigate the issue where the music stops. I would turn it on only on the stream controller.

That said. I think all these issues are related. So issue https://github.com/music-assistant/hass-music-assistant/issues/2893 is related to this one. If streaming fails under the hood, the queue controller has no more way to calculate where we are in the stream to show the correct song info.

If flow mode is enabled we stitch together all songs as one long stream of audio and we depend on the players accuracy of elapsed (total)time together with a calculation of how many exact bytes we processed of pcm audio per song. 

Somehow we are recently experiencing some issues with Spotify (since we had to update our librespot fork due to spotify changes to the auth api) which we're trying to tackle. Let's see if the fixes from yesterday (in b29) solve this

**Comment by OzGav** [comment] 2024-10-05 10:47
You can install the Snapcast provider and try streaming to a browser tab

**Comment by GSVil** [comment] 2024-10-13 20:01
Please don't close this issue, its still the same with my ESP32 Media Players. Songs skipping over and over, resume playing after broadcast not working, broadcasts repeating over and over. I usually have restart Music Assistant Server, or reboot the esp32 to get stability back.

**Comment by OzGav** [comment] 2024-10-14 05:49
OK this will get looked at eventually but HA media players aren't a high priority at the moment.

**Comment by GSVil** [comment] 2024-10-14 11:04
> OK this will get looked at eventually but HA media players aren't a high priority at the moment.

Thank you OzGav. I'm not that knowledgeable, but let me know if you need help testing or getting logs etc. I'm able to reproduce the issue every time.

**Comment by marcelveldt** [comment] 2024-10-21 09:22
> > OK this will get looked at eventually but HA media players aren't a high priority at the moment.
> 
> Thank you OzGav. I'm not that knowledgeable, but let me know if you need help testing or getting logs etc. I'm able to reproduce the issue every time.

Can you test this on the latest beta ?

**Comment by GSVil** [comment] 2024-10-21 16:56
> > > OK this will get looked at eventually but HA media players aren't a high priority at the moment.
> > 
> > 
> > Thank you OzGav. I'm not that knowledgeable, but let me know if you need help testing or getting logs etc. I'm able to reproduce the issue every time.
> 
> Can you test this on the latest beta ?

OK, I'll give it a shot.

**Comment by GSVil** [comment] 2024-10-21 17:58
OK playback appears to be better with a stream from spotify working without to much hiccups and you can see it playing and progressing nicely, skipping to next song also working nicely. But status updates after TTS is still not happening, causing the same TTS to repeat multiple times. If you monitor the HA version of the ESP32 it actually changes state to Idle after the TTS completes, but if you monitor the MA version of the ESP32 the status stays "Playing" even after the TTS completes. So if you are streaming spotify on the ESP32 and you interrupt it with an TTS announcement, music will pause, the announcement will happen, and then a few seconds later the same announcement and so on. After 60sec (also seen in the logs) MA will start playing the spotify stream again and everything is back to normal until you send a new TTS.  I've tried this with youtube and PLEX streams as well, all have the same issue. So just to recap, what I did to reproduce:
1) Start Spotify stream to ESp32 Media Player
2) Skip a few songs
3) Send a TTS announcement
4) Checked both the HA and MA versions of the ESP32, the one updates the other does not.
5) Wait for MA to recover after 60sec.
6) Repeat the test...
![Screenshot 2024-10-21 194139](https://github.com/user-attachments/assets/1aadca02-d008-4295-b26f-ed7f24631312)
[music-assistant.log](https://github.com/user-attachments/files/17465116/music-assistant.log)

**Comment by marcelveldt** [comment] 2024-10-22 22:19
So I have chased down the issues with ESPHome to the media player component and the HTTP client its using.
This is for now unsolvable until the new media player component for ESPHome is released.

We have never recommended ESPHome for music playback with MA (as that is never where it was invented for) but at this time I'd say its just plain broken. There is a new media player component in the making (I have no clue about ETA) which fixes these issues.

For now I'd say to load snapcast or squeezelite32 on the ESP32 devices if you want working playback.

**Closed by marcelveldt** 2024-10-22 22:19 UTC
Labels: bug, HA Player

**Comment by GSVil** [comment] 2024-10-23 11:50
> So I have chased down the issues with ESPHome to the media player component and the HTTP client its using. This is for now unsolvable until the new media player component for ESPHome is released.
> 
> We have never recommended ESPHome for music playback with MA (as that is never where it was invented for) but at this time I'd say its just plain broken. There is a new media player component in the making (I have no clue about ETA) which fixes these issues.
> 
> For now I'd say to load snapcast or squeezelite32 on the ESP32 devices if you want working playback.
> 
> One final note: Things may improve if you set "static content length" in the player settings for http profile.

Setting the http profile to "block' also works for better streaming, but unfortunately it does not help with the status that is not being updated after an TTS (this is my biggest issue). I so have squeezelite devices, but what I'm doing is to repurposing  the speakers that are attached to my voice-assistants. Why not, I think its a great idea to use them for assist, music and announcements.

**Comment by rvandet** [comment] 2024-12-06 17:49
I have the same issue - queue not updating - when i play from a NAS.

**Comment by rvandet** [comment] 2024-12-06 17:59
In MA, go to settings, players. 
Select the player you are using (the one with the issue).
Switch off "Flow mode" and see if your problem is solved.

**Comment by rvandet** [comment] 2024-12-07 10:15
Ah, now it sometimes stops after 10s.

**Comment by rvandet** [comment] 2024-12-07 19:02
To me, it seems that the queue is perfect IF you hit the Next button (inFlow mode), because then the number playing is displayed correctly.
So, if  the application would select the Next command, would this queuing mechanismn function correctly?

**Comment by de666** [comment] 2024-12-31 10:57
I experience the same issue with DLNA player in queue flow mode, queue status not updating at all, it sticks to the end of the first song while the music keep playing the next tracks.

Music Assistent server 2.3.3
Provider: Subsonic
Player DLNA in queue flow mode

Working correctly with Squeezelite player in queue flow mode (with Subsonic provider)

**Comment by OzGav** [comment] 2024-12-31 14:37
@de666 please review the docs and take particular note of the following 

> Due to the very inconsistent implementation of this protocol by manufacturers, some players will work great and others will simply not work at all or need workarounds.

and 

> If your device supports a different protocol then use that instead of raising an issue
