### ISSUE TITLE
(MainThread) [music_assistant.providers.slimproto--XRreVpTF.cli] No handler for login 

### ISSUE THREAD

**Issue by DoDoR** [music-assistant/hass-music-assistant#1867] opened 2024-02-03 15:55 UTC
### What version of Music Assistant has the issue?

2.0.0b90

### The problem

Music Assistant, Won't work, can't start the app. 

### How to reproduce

Start 

### Relevant log output

2024-02-03 17:26:24.239 WARNING (MainThread) [music_assistant.providers.slimproto--XRreVpTF.cli] No handler for login (player:  - args: [] - kwargs: {})
2024-02-03 17:26:27.243 WARNING (MainThread) [music_assistant.providers.slimproto--XRreVpTF.cli] No handler for subscribe (player:  - args: ['client'] - kwargs: {})
2024-02-03 17:26:27.314 WARNING (MainThread) [music_assistant.providers.slimproto--XRreVpTF.cli] No handler for playerpref
2024-02-03 17:26:27.329 WARNING (MainThread) [music_assistant.providers.slimproto--XRreVpTF.cli] No handler for login (player:  - args: [] - kwargs: {})
2024-02-03 17:26:30.328 WARNING (MainThread) [music_assistant.providers.slimproto--XRreVpTF.cli] No handler for subscribe (player:  - args: ['play,stop,pause,playlist,mixer,sync'] - kwargs: {})
2024-02-03 17:26:39.470 WARNING (MainThread) [music_assistant.providers.slimproto--XRreVpTF.cli] No handler for login (player:  - args: [] - kwargs: {})
2024-02-03 17:26:42.473 WARNING (MainThread) [music_assistant.providers.slimproto--XRreVpTF.cli] No handler for subscribe (player:  - args: ['client'] - kwargs: {})
2024-02-03 17:26:42.517 WARNING (MainThread) [music_assistant.providers.slimproto--XRreVpTF.cli] No handler for playerpref
2024-02-03 17:26:42.530 WARNING (MainThread) [music_assistant.providers.slimproto--XRreVpTF.cli] No handler for login (player:  - args: [] - kwargs: {})
2024-02-03 17:26:45.530 WARNING (MainThread) [music_assistant.providers.slimproto--XRreVpTF.cli] No handler for subscribe (player:  - args: ['play,stop,pause,playlist,mixer,sync'] - kwargs: {})

### Additional information

Current version: 2.0.0b90 (Changelog)
2024.1.6
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0

### What version of Home Assistant Core are your running

2024.1.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment] 2024-02-04 04:35
Please provide way more information about what the problem is, what you have tried to fix it, what does work, what doesn’t work, what worked in the past.

**Comment by DoDoR** [comment] 2024-02-04 09:13
Hi OzGav,

 

Thanks for the quick response

 

I downloaded the latest version via HACS and install it via Devices & Services And this is where everything got stuck

 

The add-on server is not starting : 

 

I tried running it directly vis Start unfadingly it is not working 

 



 



 

Attach the log: 

 

 

2024-02-04 10:44:01.650 INFO (MainThread) [music_assistant] Starting Music Assistant Server (99b91edb75994d96b7eb08ec57438142) version 2.0.0b92 - uvloop: False

2024-02-04 10:44:01.669 INFO (MainThread) [music_assistant.cache] Initializing cache controller...

2024-02-04 10:44:01.751 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095

2024-02-04 10:44:02.013 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.

2024-02-04 10:44:03.447 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.4 with libsoxr support

2024-02-04 10:44:03.447 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8096 - base url: http://192.168.86.24:8096

2024-02-04 10:44:04.696 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider

2024-02-04 10:44:04.697 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider

2024-02-04 10:44:04.697 INFO (MainThread) [music_assistant] Loaded music provider URL

2024-02-04 10:44:04.698 INFO (MainThread) [music_assistant] Loaded player provider SONOS

2024-02-04 10:44:04.699 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider

2024-02-04 10:44:04.700 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player

2024-02-04 10:44:04.700 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider

2024-02-04 10:44:04.704 INFO (MainThread) [music_assistant.music] Sync task for URL completed

2024-02-04 10:44:04.740 INFO (MainThread) [music_assistant.providers.slimproto] Started SLIMProto server on port 3483

2024-02-04 10:44:04.742 INFO (MainThread) [music_assistant.providers.slimproto.cli] Registering jsonrpc endpoints on the webserver

2024-02-04 10:44:04.745 INFO (MainThread) [music_assistant] Loaded player provider Chromecast

2024-02-04 10:44:04.753 INFO (MainThread) [music_assistant.providers.slimproto.cli] Starting (telnet) CLI on port 9090

2024-02-04 10:44:04.764 INFO (MainThread) [music_assistant] Loaded player provider Slimproto

2024-02-04 10:44:04.812 INFO (MainThread) [music_assistant.players] Player registered: e4:5f:01:07:b3:37/squeezeplay: e4:5f:01:07:b3:37

2024-02-04 10:44:05.087 INFO (MainThread) [music_assistant.players] Player registered: b8:27:eb:33:f3:48/squeezeplay: b8:27:eb:33:f3:48

2024-02-04 10:44:05.324 INFO (MainThread) [music_assistant.players] Player registered: RINCON_949F3E24072801400/Unnamed Room

2024-02-04 10:44:05.330 WARNING (MainThread) [soco.events_asyncio] Could not bind to 192.168.86.24:1400: [Errno 98] Address already in use

2024-02-04 10:44:05.741 INFO (MainThread) [music_assistant] Loaded player provider Airplay

2024-02-04 10:44:05.840 INFO (MainThread) [music_assistant.players] Player registered: aa:aa:91:7c:65:94/squeezeplay: aa:aa:91:7c:65:94

2024-02-04 10:44:05.872 INFO (MainThread) [music_assistant.players] Player registered: aa:aa:79:2a:34:62/TV – סלון+

2024-02-04 10:44:05.887 INFO (MainThread) [music_assistant.players] Player registered: aa:aa:dc:50:26:e0/TV – חדר שינה+

2024-02-04 10:44:05.965 INFO (MainThread) [music_assistant.players] Player registered: aa:aa:c5:49:de:58/Living Room 🎻

2024-02-04 10:44:06.123 INFO (MainThread) [music_assistant.players] Player registered: 5041a1f7-44f8-3371-b7a5-1c2bdba35c5a/חדר שינה מרתף

2024-02-04 10:44:06.653 INFO (MainThread) [music_assistant.players] Player registered: uuid:6bf01d4b-7361-601c-7d0e-e45f0107b337/Living Room 🎻-UPnP/AV

2024-02-04 10:44:08.786 INFO (MainThread) [music_assistant.players] Player registered: aa:aa:75:5f:ea:b0/Bedroom 🛌

2024-02-04 10:44:25.137 WARNING (MainThread) [music_assistant.providers.slimproto.cli] No handler for login (player:  - args: [] - kwargs: {})

2024-02-04 10:44:28.046 WARNING (MainThread) [music_assistant.providers.slimproto.cli] No handler for login (player:  - args: [] - kwargs: {})

2024-02-04 10:44:28.143 WARNING (MainThread) [music_assistant.providers.slimproto.cli] No handler for subscribe (player:  - args: ['client'] - kwargs: {})

2024-02-04 10:44:28.222 WARNING (MainThread) [music_assistant.providers.slimproto.cli] No handler for playerpref

2024-02-04 10:44:28.240 WARNING (MainThread) [music_assistant.providers.slimproto.cli] No handler for login (player:  - args: [] - kwargs: {})

2024-02-04 10:44:31.054 WARNING (MainThread) [music_assistant.providers.slimproto.cli] No handler for subscribe (player:  - args: ['client'] - kwargs: {})

2024-02-04 10:44:31.151 WARNING (MainThread) [music_assistant.providers.slimproto.cli] No handler for playerpref

2024-02-04 10:44:31.171 WARNING (MainThread) [music_assistant.providers.slimproto.cli] No handler for login (player:  - args: [] - kwargs: {})

2024-02-04 10:44:31.242 WARNING (MainThread) [music_assistant.providers.slimproto.cli] No handler for subscribe (player:  - args: ['play,stop,pause,playlist,mixer,sync'] - kwargs: {})

2024-02-04 10:44:34.174 WARNING (MainThread) [music_assistant.providers.slimproto.cli] No handler for subscribe (player:  - args: ['play,stop,pause,playlist,mixer,sync'] - kwargs: {})

2024-02-04 10:49:09.554 INFO (MainThread) [music_assistant.players] Player registered: uuid:a4c11431-53ee-98ed-59ba-b827eb33f348/Bedroom 🛌-UPnP/AV

 

System version:  

 

Core

2024.1.6

Supervisor

2023.12.1

Operating System

11.4

Frontend

20240104.0

**Comment by OzGav** [comment] 2024-02-04 09:22
Do you have the slimproto integration running on HA or an LMS server on your network? If so, you must disable or remove those for MA to work

**Comment by DoDoR** [comment] 2024-02-04 15:10
Hi, I remove all relevant  LMS from the network unfortunately not working yet:

Can you advice ? 

 

 

 

 2024-02-04 16:53:10.307 WARNING (MainThread) [soco.events_asyncio] Could not bind to 192.168.86.24:1400: [Errno 98] Address already in use

 

Thx

Doron’

**Comment by OzGav** [comment] 2024-02-05 04:04
The logs you initially supplied shows the addon is starting. So why exactly do you think it is not working?

**Comment by OzGav** [comment] 2024-02-14 06:18
We will close this soon due to no followup

**Comment by DoDoR** [comment] 2024-02-14 06:34
Sorry I didn't update, I was able to run the app, I restored the system and it worked. Thanks!!Sent from Doron Revivi MobileOn 14 Feb 2024, at 8:18, OzGav ***@***.***> wrote:﻿
We will close this soon due to no followup

**Closed** 2024-02-14 06:37 UTC
Labels: More info, triage
