### ISSUE TITLE
Opening the web UI defaults to settings view

### ISSUE THREAD

**Issue by pgale** [music-assistant/hass-music-assistant#2491] opened 2024-06-16 16:12 UTC
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When opening MA on any of my devices and web browsers, the loading page defaults to the settings page and not the home page. I believe this was a known issue but I can't find it anywhere now.

### How to reproduce

open the MA home page.

### Music Providers

n/a

### Player Providers

n/a

### Full log output

[log.txt](https://github.com/user-attachments/files/15858969/log.txt)

### What version of Home Assistant Core are your running

2024.6.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment] 2024-06-17 07:19
It will only do that if you dod not yet setup the music and player provider(s) - so question is: did you setup your music providers and player providers in the settings ?

**Comment by pgale** [comment] 2024-06-17 07:54
I have Sonos and Snapcast players providers and a filesystem (remote share) to my NAS with locally stored MP3 library setup.

![image](https://github.com/music-assistant/hass-music-assistant/assets/513044/4209a2a7-a265-4acc-8333-e077d2865544)

That screen shot is from the HA integration by clicking on the MA menu item. If I also navigate to the root of the MA URL, it also redirects to the `/#/settings/providers` page. It has ALWAYS done this since I installed MA. I have also tried to navigate to the URL on start `https://xxxxxxx.com/#/home` and it redirects to the settings page.

I have also tried the IP address `http://192.168.0.154:8095/#/home` and it redirects the first time in the browser session. If I then use that URL for a second time in the session, it shows the home page.

I can share a video of this behaviour if that helps at all?

**Comment by marcelveldt** [comment] 2024-06-17 09:23
This is a very old bug so I'm wondering if you are 100% certain you are running the last version ?

**Comment by pgale** [comment] 2024-06-17 09:25
Yes definitely:
![image](https://github.com/music-assistant/hass-music-assistant/assets/513044/2d9d832d-f845-4057-87fa-a78b6e83e55d)

**Comment by pgale** [comment] 2024-06-17 09:26
Is it worth removing the add-on and reinstalling?
It would have to scan my music collection again though.

**Comment by asinla** [comment] 2024-06-19 16:31
I have the same issue. It went away for a couple of versions but now it's back in this latest version.

**Comment by erkr** [comment] 2024-06-19 16:49
Yes the old issue is back. I see this happening intermittently. Seems it depends on the  the load time

**Comment by pgale** [comment] 2024-06-19 17:01
Interesting- my devices are quite slow but I also see it on my iPhone 15 pro and iPads/super fast PC.

**Comment by OzGav** [comment] 2024-07-09 01:25
@pgale Please check again with beta 14

**Comment by marcelveldt** [comment] 2024-07-09 20:25
fixed in b15

**Comment by OzGav** [comment] 2024-07-10 22:55
@marcelveldt reported again here https://community.home-assistant.io/t/music-assistant-2-0-your-music-your-players/727626/663

**Comment by gwithers105** [comment] 2024-07-11 03:06
I'm seeing this behavior as well with b15.  I never saw it on previous beta versions but I am experiencing it now.  If I select the home icon from the provider page, it takes me to the home page but it is completely blank except for the player and the lower nav bar.  A refresh on this home page will take you back to the providers page.  Refresh enough times on the providers page and it will state that you have not setup any music or player providers.  Refresh again and it recognizes the setup once again.  This is on a system with Sonos and Slimproto player providers and local files and Spotify music providers.  The setup play music fine.

**Comment by OzGav** [comment] 2024-07-13 22:43
@gwithers105 please see if this is still an issue with 2.1.0rc1

**Comment by gwithers105** [comment] 2024-07-13 22:49
RC1 appears to solve the issue with the home page not loading properly.  I
will test a bit more in depth later but all looks good at the moment

**Comment by OzGav** [comment] 2024-07-14 23:01
Exactly which player providers and music providers have you installed? Feel free to post a screenshot of your settings page

**Comment by OzGav** [comment] 2024-07-14 23:39
Also reported here https://github.com/orgs/music-assistant/discussions/2624#discussioncomment-10045873

**Comment by gwithers105** [comment] 2024-07-15 00:17
Here is a screen grab of the providers I use on my install

![image](https://github.com/user-attachments/assets/7f82cb85-8b15-418b-8187-4570e2fcbbbf)

**Comment by marcelveldt** [comment] 2024-07-15 21:34
This really should not be happening - the redirect to settings will only occur if no providers are setup.
Did you try force refreshing the browser to rule out its a cached copy of the frontend perhaps

**Comment by gwithers105** [comment] 2024-07-15 21:44
Yes, I have cleared the browser cache.  Just to be sure, I have also spun up a fresh VM and tried on that as well.  The same behavior is seen where the setup page appears after a refresh of the home page is initiated.

**Comment by sdoowo200leldls** [comment] 2024-07-17 00:33
I too am experiencing this issue on 2.1.0rc2 and tried clearing browser cache, restarting the MA add-on, and restarting HA but no success.

![image](https://github.com/user-attachments/assets/1082d6e4-9688-40db-b179-71ac7069e78b)

**Comment by harryfine** [comment] 2024-07-17 19:34
I cleared the browser cache in the core, and I cleared the browser cache on both Firefox and Chrome.  I reinstalled the addon.  I'm using 2.1.0rc2, and I still have it take me to the settings page on launch.

**Comment by abuttino** [comment] 2024-07-19 13:24
Same issue

![Screenshot_20240719-062426.png](https://github.com/user-attachments/assets/798e67a3-f52d-47ed-9b43-ee512199bf3e)

**Comment by tbrasser** [comment] 2024-07-20 12:04
Same, also on RC3

**Comment by harryfine** [comment] 2024-07-20 21:58
Sane with me in RC3, and that's after clearing the core cache

**Comment by abuttino** [comment] 2024-07-20 22:45
> Sane with me in RC3, and that's after clearing the core cache

How do you clear the core cache? Been looking for a long time and no search results help.

**Comment by harryfine** [comment] 2024-07-20 22:58
Going to settings, go into core, you'll see something called cache controller.

⁣Harry Fine
647-970-6378​

**Comment by marcelveldt** [comment] 2024-07-21 22:32
> Also, sometimes settings page even loads showing no providers, pretty sure this is related: 

Yes that is related because redirecting to the settings only happens when there are no providers loaded.
So there must be some kind of race condition.

**Comment by marcelveldt** [comment] 2024-07-22 00:01
Added one more tweak to this - available in 2.1.0 stable (and 2.2.0 b0)

**Comment by tbrasser** [comment] 2024-07-22 09:31
Still hapening unfortunately

**Comment by OzGav** [comment] 2024-07-22 10:08
Have you tried clearing the MA cache?

**Comment by harryfine** [comment] 2024-07-22 12:07
Yes, cleared the MA cache.

-----Original Message-----
From: OzGav ***@***.***>
Reply-To: music-assistant/hass-music-assistant
***@***.***>
To: music-assistant/hass-music-assistant
***@***.***>
Cc: harryfine ***@***.***>, Comment ***@***.***>
Subject: Re: [music-assistant/hass-music-assistant] Opening the web UI
defaults to settings view (Issue #2491)
Date: 2024-07-22 06:09:16 AM

Have you tried clearing the MA cache?
—
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2].
You are receiving this because you commented.Message ID: <music-
***@***.***>


[1] view it on GitHub
    https://github.com/music-assistant/hass-music-assistant/issues/2491#issuecomment-2242585871
[2] unsubscribe

**Comment by gwithers105** [comment] 2024-07-22 12:38
After installing 2.2.0 b0, clearing the MA core cache, and clearing the local browser cache, sadly the problem still persists.  All requests to MA are still being forwarded to the settings provider page.  Selecting other pages from the bottom nav bar does properly go to those pages but a refresh on any page results in being sent to the providers setup page.

**Comment by abuttino** [comment] 2024-07-22 13:02
Unfortunately I have the same outcome.

**Comment by marcelveldt** [comment] 2024-07-22 19:53
Did you try a different browser ? This REALLY can not happen anymore, unless your browser is still hosting an outdated version of the frontend. Please also confirm that if you visit the settings page that you don't see that message that no providers have been setup

**Comment by pgale** [comment] 2024-07-22 19:57
Seems to be fixed on my devices. At least I've not seen a recurrence yet :)

**Comment by sdoowo200leldls** [comment] 2024-07-22 20:01
This is still happening to me regardless of browser or device. I cleared browser cache and cache in the cache controller MA module.

![image](https://github.com/user-attachments/assets/c65fec94-ec02-4993-97c8-4ddaad36b710)
![image](https://github.com/user-attachments/assets/7964f49d-32e9-42d8-9f6a-7bd41230f6e5)

**Comment by gwithers105** [comment] 2024-07-22 20:36
This is still an issue as far as my testing can show.  My testing includes clearing the local cache for each browser, clearing the MA controller cache, trying three browsers (Chrome, Edge, and Firefox), two different operating systems (Windows 11 and Android 14), as well as a fresh Windows "clone" VM that has never accessed MA before just to be sure that no cached front end files remain somehow.  In all scenarios, the problem persists. 

I still have a test environment with the 2.0.7 general release and that does not have this problem in all of these test scenarios. I even updated the test environment from 2.0.7 to 2.1.0 and the problem does not show itself.  The interesting thing is that if I add the general release to my production HA installation, the general release 2.1.0 install shows the same problem with the unwanted redirects that the beta does even though the general release on my test HA instance does not show the problem.  So the problem seems to be persistent in HA.  So even though the problem may be fixed in MA, uninstalling the add-on, rebooting and reinstalling the add-on doesn't seem to clean up whatever the issue was/is.  So it might be that the MA add-on in HA is keeping the issue around.  What the problem is in this context is not something I can say much about but some MA "stuff" seems to be hanging around and isn't being cleaned up.

**Comment by OzGav** [comment] 2024-07-22 21:30
Can everyone thumbs up this post if you are seeing this with the addon and thumbs down if you are running in docker and see this.

**Comment by gwithers105** [comment] 2024-07-23 02:35
I'm not sure but my theory might be rubbish.  I just installed a MA container via docker and that is also doing the same thing.  If it was a problem with HA holding onto some info from past versions then this new docker installation should not have the same problem as it is fresh and brand new every time you run it (assuming you prune it after downloading it and don't bother with a permanent data folder).  Both the beta and the 2.1.0 version suffer the same problem with page redirects.  That said, when I open up the inspection window in Chrome, I get this potentially telling message in the console.  Even though I have music providers and player providers setup and functioning, it still thinks it isn't done onboarding.


![Image](https://github.com/user-attachments/assets/163642eb-311f-431f-bf81-0db121511dd8)

**Comment by gwithers105** [comment] 2024-07-23 15:05
I have done quite a few more testing iterations and it appears that b14 works properly as far as detecting completed "onboarding" and every version since has the incorrectly determined "onboarding" issue.  So starting with b15, through the various RC versions, 2.1.0, as well as 2.2.0b0, they all have this incomplete onboarding issue.  At least, when it does redirect you, it is doing so because MA thinks it should be doing that because that is what it should do if onboarding is not complete.  So what detects completed onboarding is the question.

**Comment by Geweldich** [comment] 2024-07-27 16:45
Maybe it would be an idea to add a manual override for this behavior? Perhaps not the nicest solution, but a quick one that’s sure to increase the WAF of MA.

**Comment by VitaminTe** [comment] 2024-07-27 18:07
I'm experiencing the same issue and it exists on multiple devices with multiple browsers despite clearing cache and going through the suggested trouble shooting steps.  I'm running 2.2.0b0.

**Comment by rothmichaela** [comment] 2024-07-27 18:59
Same issue here, having cleared the MA cache, multiple browsers, etc. Also happens on iOS HA app.

**Comment by kdober** [comment] 2024-07-28 01:14
Hi, I'm new to MA. I installed it a few days ago and I ended up here when looking for this issue.
I'm on stable 2.1.0 and providers are set up (and working fine to my knowleadge)
However, every time I open MA it goes to settings.
![image](https://github.com/user-attachments/assets/245ad8db-0dc5-41e5-8333-8ba6619e7bbc)

**Comment by gwithers105** [comment] 2024-07-28 01:26
Yep, that is happening to a lot of people.  At the moment, there isn't anything you can do to rectify the issue as far as I know.  It appears that there is something not quite right with the way MA determines if setup (onboarding) has been completed.  Since it seems to get this aspect wrong, it continues to redirect you to the setup area.  I assume the idea behind this is to help streamline the initial setup of MA but when it doesn't work as intended, you get what you are seeing.

**Comment by erkr** [comment] 2024-07-29 16:02
Hi,
I originally didn't have the issue with v2.1.0.
Today I did a fresh install of MA server (other reason) and now it happens for me as well.

Only tune-in provider. And chromecast players configured.

Can't be cache as it was working before the reinstall of the same version

**Comment by gmn42** [comment] 2024-07-31 21:46
Just adding my report.  New MA user, same problem.  Originally had it on 2.1.0, then tried beta 2.2.0b0 with no change.  Even tried the current dev branch, still no help.

I have the MA, Youtube and Radio sources added, and I use the "Home Assistant MediaPlayers" player (but had the same trouble when I tried using the Sonos player provider).

**Comment by Vacationland105** [comment] 2024-08-01 01:18
The offending code that seems to bring this behavior about is line 76 through 84 in the frontend App.vue file.  It was part of commit d094555 and showed up in "frontend" version 2.6.4.  At least from my testing, this is the inflection point between the problem being present and not and it is reproducible.  I can install b14 (pre frontend version 2.6.4) and there is no issue. Installing anything after that and the problem with redirects is present.  I can go back and forth between the versions with clean containers and the behavior follows again and again.

![image](https://github.com/user-attachments/assets/631e1888-8b42-4930-aac5-775a3765c1ae)

So you comment @erkr got me thinking.  Perhaps if I started with a clean docker install of 2.1.0b14 (which has a frontend version before the commit above), along with a persistent data volume, and I successfully completed onboarding.  Could I then update to a later version but not run into the issue with an incorrectly determine onboarding status because I had already done that and that info was stored in the persistent data volume.  The answer is a YES.  So the problem is indeed that a fresh install of any version after 2.1.0b14 gets stuck with a persistent incomplete onboarding value and thus the permanent redirect to the settings page.  So if you have a good install and you upgrade to a new version by reusing your DB, then the problem does not show up.  So indeed it is something about the initial setup being held as incomplete. This would explain why not everyone sees this issue as most people do NOT start with a fresh install and rebuild their providers and music library with every update.

**Comment by OzGav** [comment] 2024-08-01 02:35
Awesome work @Vacationland105 ! @marcelveldt please see above

**Comment by zakird1** [comment] 2024-08-01 20:56
Nice find @Vacationland105. However, for those of us who are new to MA and must do a fresh install, is there any workaround to this or do we just need to patiently wait for a new code update to be released?

**Comment by Vacationland105** [comment] 2024-08-01 21:26
I am not sure if you are using Home Assistant to run MA but if you are using docker, you would first install the 2.1.0b14 version, complete the onboarding by adding at least one music and player provider, and then upgrade to any version after and it will work.  Docker can be a tough road if you are not familiar with it however.  In Home Assistant, it seems to only want to install the most recent versions, so that won't work.

**Comment by MelHarbour** [comment] 2024-08-02 10:19
@marcelveldt rather than relying on a value that gets put into the config, wouldn't it just be easier to count the number of configured providers and if that's zero then redirect to Settings?

**Comment by Geweldich** [comment] 2024-08-03 22:35
Perhaps useless to mention considering the changelogs and the status of this issue, but the  latest stable HA add-on (2.1.1) is still showing the behavior. I would be very interested in a workaround.

**Comment by mwdle** [comment] 2024-08-04 00:02
> Perhaps useless to mention considering the changelog and the status of this issue, but the latest stable HA add-on (2.1.1) is still showing this behavior. I would be very interested in a workaround.

+1

**Comment by harryfine** [comment] 2024-08-04 01:40
+2

⁣Harry Fine
647-970-6378​

**Comment by sdoowo200leldls** [comment] 2024-08-04 01:45
+3

**Comment by Vacationland105** [comment] 2024-08-04 01:57
Yeah, I believe the issue is with the [frontend](https://github.com/music-assistant/frontend) bit of MA and that part hasn't seen any changes in two weeks.  So, one should expect this issue to remain at least until changes are seen in this part of MA.  
![image](https://github.com/user-attachments/assets/b34c43db-e13c-4dfd-864f-a8ccf80c5c86)

**Comment by CultusMechanicus** [comment] 2024-08-04 09:59
Potentially a dumb question, but is [this](https://github.com/music-assistant/server/blob/0cb1355bf44c79d0412c0757ac4d6a3a7704f8b0/music_assistant/common/models/api.py#L61) supposed to hardcoded? Because it looks like the model always reports `onboard_done` as `false`

**Comment by snakedm** [comment] 2024-08-05 15:47
I've the same problem!
New MA user, with YTmusic provider and chromecast player provider

**Comment by DarkTearStudios** [comment] 2024-08-07 04:20
Any Update on this? New user to MA and honestly this its kinda stupid that it does this. I see that the cause/solution has been pointed out above by @Vacationland105. 
I'm using the addon on ha, so cant just install an older version, setup, then upgrade.

**Comment by OzGav** [comment] 2024-08-07 04:21
@DarkTearStudios I suggest you edit your post

**Comment by marcelveldt** [comment] 2024-08-07 10:02
> Potentially a dumb question, but is [this](https://github.com/music-assistant/server/blob/0cb1355bf44c79d0412c0757ac4d6a3a7704f8b0/music_assistant/common/models/api.py#L61) supposed to hardcoded? Because it looks like the model always reports `onboard_done` as `false`

Yes

**Comment by marcelveldt** [comment] 2024-08-07 10:09
Please be patient folks. It is holiday season so develop pace slow. This issue is caused by a race condition and will be looked at shortly

**Comment by marcelveldt** [comment] 2024-08-07 10:09
> @marcelveldt rather than relying on a value that gets put into the config, wouldn't it just be easier to count the number of configured providers and if that's zero then redirect to Settings?

That is already how it works today

**Comment by Bytelink5616** [comment] 2024-08-09 17:44
I had no problem with it until I updated it and now seeing the same problem using ytube music and remote sharing as music providers and chromecast as players.

**Comment by ptrnmgr** [comment] 2024-08-12 09:57
for me it's fixed after today's MA update

**Comment by erkr** [comment] 2024-08-12 11:00
Yes for me as well

**Closed** 2024-08-12 11:01 UTC
Labels: bug, frontend

**Comment by Bytelink5616** [comment] 2024-08-12 12:30
Me too

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Vacationland105** [comment] 2024-08-12 14:18
Looks all good on my end as well.
