### ISSUE TITLE
Add support for running MA on FreeBSD/TrueNAS

### ISSUE THREAD

**Issue by skellycode** [music-assistant/hass-music-assistant#481] opened 2022-06-21 06:32 UTC
### What version of Music Assistant has the issue?

2022.6.4

### The problem

When adding the Music Assistant integration into HA for the first time and adding my Spotify credentials, the following error is raised in the Integrations Screen of the WebUI:

"Retrying setup: Setup failed of provider spotify: Unable to locate Libespot for platform FreeBSD"

Is there a dependency on Libespot that requires installation which isn't outlined in the documentation? :)

### How to reproduce

Install Music Assistant on HA Core on a FreeBSD system with the Spotify option included

### Relevant log output

`2022-06-21 15:54:31 ERROR (MainThread) [custom_components.mass] Setup failed of provider spotify: Unable to locate Libespot for platform FreeBSD
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 372, in _register_provider
    if await provider.setup():
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/music_assistant/music_providers/spotify.py", line 71, in setup
    token = await self.get_token()
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/music_assistant/music_providers/spotify.py", line 485, in get_token
    tokeninfo = await asyncio.wait_for(self._get_token(), 5)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/music_assistant/music_providers/spotify.py", line 511, in _get_token
    await self.get_librespot_binary(),
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/music_assistant/music_providers/spotify.py", line 717, in get_librespot_binary
    raise RuntimeError(
RuntimeError: Unable to locate Libespot for platform FreeBSD

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/custom_components/mass/__init__.py", line 106, in async_setup_entry
    await mass.setup()
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/music_assistant/mass.py", line 84, in setup
    await self.music.setup()
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 62, in setup
    await self._register_provider(prov_cls(self.mass, prov_conf), prov_conf)
  File "/usr/local/share/homeassistant/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 375, in _register_provider
    raise SetupFailedError(
music_assistant.models.errors.SetupFailedError: Setup failed of provider spotify: Unable to locate Libespot for platform FreeBSD`

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant Core

**Comment by marcelveldt** [comment] 2022-06-21 06:49
You're running an unsupported configuration I'm afraid. We use a special fork of librespot which I cross compile myself and include into the library. You are the first user with FreeBSD so far. It's not very common to have HA core running directly on FreeBSD. I can have a look how easy it is to build librespot for freebsd and adjust the code...

**Comment by erkr** [comment] 2022-06-21 09:29
Shall we convert this to a discussion then? E.g. "Support Music Assistant on FreeBSD"

**Comment by marcelveldt** [comment] 2022-06-21 09:31
> @marcelveldt : Shall we convert this to a discussion then? E.g. "Support Music Assistant on FreeBSD"

Leave here for now, maybe there is an easy fix. I will check. if it's not an easy fix, it should be a feature request.

**Comment by marcelveldt** [comment] 2022-06-23 05:43
OK thanks, I will install that as a virtual appliance then in Virtualbox so I can test.
Any special instructions for me to follow to install HA ?

**Comment by skellycode** [comment] 2022-06-23 12:29
@marcelveldt if you navigate to the “Plugins” page on TrueNAS you’ll be able to get a HA jail up and running with only a couple of clicks 😊

**Comment by GamerClassN7** [comment] 2022-06-24 06:53
HI, I have same problem on officinal ova image :/ are there any news about the issue ?

**Comment by marcelveldt** [comment] 2022-06-24 06:54
I'm looking at it, expect an update within a few days

**Comment by GamerClassN7** [comment] 2022-06-24 06:54
That was quick thanks :)

**Comment by GamerClassN7** [comment] 2022-06-30 07:58
After last update still not working unfortunately :(

**Comment by marcelveldt** [comment] 2022-07-06 19:05
Just released 2022.7 beta 0 which incudes support for FreeBSD
This issue should therefore be fixed in that release. If you still experience any issues, please re-open this ticket or open a new one. Thanks!

**Comment by erkr** [comment] 2022-07-11 15:18
Hm not starting HA, looks like your Spotify user login failed, but that should not block HA to start.

**Comment by marcelveldt** [comment] 2022-07-11 15:23
1) Free Spotify accounts are not supported.
2) I really doubt your HA not starting is caused by MA, I think that will have another cause.

**Comment by GamerClassN7** [comment] 2022-07-12 14:07
> not starting HA, looks like your Spotify user login still failed, but that should not block HA to start. Not really progress🫣
1) I have Spotify account in premium 3 month period could that be an issue ? 
2) Hello, If I disable component before reboot HA reboot successfully so maybe some compatibility issue with other addons ? also interesting not boot problem only occur if I fil in Spotify credentials if Music assistant is installed and no credentials filled in reboots works as expected.

**Comment by marcelveldt** [comment] 2022-07-25 19:31
I have been looking at this and I came to the conclusion this is not going to happen.

1) Home Assistant does not support FreeBSD 
2) A lot of dependencies for both HA and MA are not available for FreeBSD or do not have any prebuilt packages available
3) The TrueNAS HomeAssistant plugin is end of life.

Sorry to tell you but TrueNAS is not and never will be a supported platform for Music Assistant (and even Home Assistant).
I strongly suggest you to activate the virtual machines feature on your TrueNAS and simply run HAOS from there. Things will be so much easier then.

**Closed by marcelveldt** 2022-07-25 19:31 UTC
Labels: More info, triage

**Comment by GamerClassN7** [comment] 2022-07-29 08:15
Thanks for advice i will try to do that :)
