### ISSUE TITLE
music-assistant exited code 132 (installation with docker)

### ISSUE THREAD

**Issue by Africa67** [music-assistant/hass-music-assistant#2110] opened 2024-04-10 18:11 UTC
### What version of Music Assistant has the issue?

2.0.0b130

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

from version 2.0.0b130 onwards the docker container creates the following error, "music-assistant exited code 132", while version 2.0.0b129 is ok. 
Music assistant server keeps restarting endlessly giving the same error.

### How to reproduce

installazione MA Server su docker (debian12)

### Music Providers

nessuno

### Player Providers

non è un problema di lettori

### What version of Home Assistant Core are your running

2024.4.2

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment] 2024-04-10 21:04
I can't spot any changes (perhaps maybe a dependency upgrade) that could explain this nor have we received any other reports about this. Did you also try to restart your docker host completely as well as any other running containers to rule out some sort of conflict ? Maybe also try with a clean data volume just as a test to rule out some sort of data corruption ?

**Comment by Africa67** [comment] 2024-04-11 05:30
No system updates, and I also tested with completely empty "data" folder. I have to test with MA only, but I don't understand the conflict, since it works correctly with version 2.0.0b29.

**Comment by marcelveldt** [comment] 2024-04-11 06:59
You are the only one reporting this problem so that is why you need to do some extra tests to rule out other causes.
That it worked with b129 can just be a coincidence.

**Comment by Africa67** [comment] 2024-04-11 10:31
It can't be a coincidence. I have installed and followed MA 2.0 since it was born and up until version b129 I never had any problems. From b130 onwards it no longer worked. I tried backwards starting from b125, which worked, up to b129, which worked. As soon as I installed the b130 it didn't work anymore.
What tests can I do to help?

**Comment by OzGav** [comment] 2024-04-11 12:06
I think you need to look at your hardware/OS setup. When no one else is experiencing this problem it points to something with your particular environment. I see you are running HA core on an Intel platform. If you used Proxmox for example you could run HAOS and perhaps solve your issue. If you don't want to do that then google the error code. My quick look suggested it could be an incompatibility with the underlying OS you are using. As Marcel said there were dependencies updated in beta130 which can't be avoided.

**Comment by marcelveldt** [comment] 2024-04-11 15:21
I've inspected the changelog completely what changed between 129 and 130 and there literally is nothing that would explain this, except maybe, just maybe, the dependency upgrade or orjson or Pillow as those are relying on OS and cpu specific instructions. 

So, going to ask this again. Did you test with a fresh install on beta 130 (so no data persisted) ?
Did you test with all other containers (or running processes that may interfere) shutdown as a test ?
Did you reboot the entire docker host ?

What kind of hardware is it ? Recent Intel cpu ? Or somewhat dated maybe ?

Does it crash right after start ? There is no logging at all generated ?
In that case it might be python itself in the docker container that couldn't even start.

Do I understand it correctly that you are running Home Assistant Core directly on the Debian host ?
That is a bit uncommon. You either have a docker host that just runs the bare minimal requirements to run the docker images (or virtualization engine) OR you run the apps on the docker host, combining them may bring you in trouble, let alone the added overhead of administrating it.

**Comment by Africa67** [comment] 2024-04-11 19:18
I checked and in fact my processor does not support avx. (Intel(R) Atom(TM) CPU N2600 @ 1.60GHz).
Could there be another way to make the evolution of MA2.0 compatible with older machines too? 
The machine with 2 GB of RAM performs very well with everything installed on it.

**Comment by OzGav** [comment] 2024-04-11 21:58
Ok that is also less than the required RAM for running anything more than just MA. Surprised it lasted this long…

**Comment by marcelveldt** [comment] 2024-04-12 09:04
> I checked and in fact my processor does not support avx. (Intel(R) Atom(TM) CPU N2600 @ 1.60GHz).
Hmm, that is a 12 years old CPU - my best guess is that is that one of our dependencies now requires some new instruction set (such as avx) that your cpu is lacking.

**Comment by Africa67** [comment] 2024-04-12 11:03
So nothing can be done to maintain compatibility with older machines that do not support AVX instructions, functioning up to version 129?

**Comment by OzGav** [comment] 2024-04-13 02:56
We don't have control over the dependencies unfortunately. Dell Optiplex or similar mini computers can generally be found pretty cheaply. I just bought one with 16GB RAM and a 256GB SSD for $110.

**Comment by Africa67** [comment] 2024-04-13 07:12
Too bad, I really liked MA 2.0. I will stop at version 129. For now I have no intention of renewing the machine. Thank you.

**Comment by marcelveldt** [comment] 2024-04-15 15:20
> So nothing can be done to maintain compatibility with older machines that do not support AVX instructions, functioning up to version 129?

Well, at this point we do not even know WHAT broke your system. Is it a dependency within our code ? Some combination of factors ? docker version ?

So, I just wanted to ask if you are 100% confident that it stopped working between 129 and 130 ?

**Comment by marcelveldt** [comment] 2024-04-15 15:23
Also, do you have any docker log output when you try to start it ?
Because just a little bit of logging could even help finding out the root cause. Without more info, its like searching for a needle in an haystack

**Comment by Africa67** [comment] 2024-04-15 18:59
I really don't know how to find docker errors. I tried with "docker container logs music-assistant -f" but it always stops on this info "DEBUG (ThreadPoolExecutor-0_11) [soco.data_structures_entry] soco.data_structures_entry imported".
I'm not gripped, almost fast, on Linux". If you can give me a tip on how to catch the error I could be more helpful.
However, I confirm that the problem is from version 130 onwards. I also tried with the latest 136.
The problem is not the Docker version. I updated the whole system only after having the error.

**Comment by agners** [comment] 2024-04-15 19:25
Can you share the output of `cat /proc/cpuinfo`?

**Comment by Africa67** [comment] 2024-04-16 05:52
I put the result of the query in the attached file. Thank you.
[cpuinfo.txt](https://github.com/music-assistant/hass-music-assistant/files/14987414/cpuinfo.txt)

**Comment by marcelveldt** [comment] 2024-04-16 21:06
> I really don't know how to find docker errors. I tried with "docker container logs music-assistant -f" but it always stops on this info "DEBUG (ThreadPoolExecutor-0_11) [soco.data_structures_entry] soco.data_structures_entry imported".

OK, that is interesting because that means that at least its partially starting and then crashes.

I could introduce a safe mode option that doesn't load any providers by default so you can see if at least the core starts with that and then enable stuff one by one until it crashes

**Comment by cociweb** [comment] 2024-04-22 20:09
@Africa67 I'm just so curious:
1) Can you please remove sonos player provider on b129 and try to update to >b130?
2) you've  mentioned that you emptied the data 'folder'. Maybe something went wrong at db upgrade on earlier release. Can you please delete (after a backup) the whole data volume and create a totally fresh setup from scratch?

To be clear: can you also please attach your docker-compose.yml file or your docker command?

**Comment by marcelveldt** [comment] 2024-04-22 22:43
In beta 140 I have added an option to start in safe mode. This will mean that only the Music Assistant core controllers are loaded and nothing else, so no providers will be started, including none of their dependencies (such as soco).

If that starts well, you can start any of the providers by clicking "reload" in the settings (click in the 3 dots).
I hope this will bring something to light which dependency is causing the troubles!
If the core even does not start with safe on, its one of our main dependencies.

You can enable safe mode by running the container with this environmental variable:
MASS_SAFE_MODE

set its value to a boolean true value, like "1" or "true"

**Comment by Africa67** [comment] 2024-04-23 17:35
I tested version 141 with safe mode. All services are OK except SONOS.
As soon as SONOS starts, the server goes into error.
But I tried to restart with version 129 (working) and the SONOS service is deactivated. Starting again with the 141 with SONOS deactivated, without safe mode, the same error occurs.

**Comment by marcelveldt** [comment] 2024-04-24 21:48
Are you also running Home Assistant on this same machine ?
It would be very interesting to see if that also crashes when you try to add the Sonos integration (which is using the same soco package as MA does)

**Comment by Africa67** [comment] 2024-04-24 21:58
I tried adding SONOS integration, I got the setup message and then the "no devices found on the network" message. No problem in HA.

**Comment by marcelveldt** [comment] 2024-04-25 13:40
Thanks for testing that. Would you feel comfortable testing the new HA beta as well ? 2024.5.0b0

**Comment by Africa67** [comment] 2024-04-27 14:20
> Grazie per averlo testato. Ti sentiresti a tuo agio nel testare anche la nuova beta HA? 2024.5.0b0

HA I prefer not to touch I don't have backup copies to rely on

**Comment by OzGav** [comment] 2024-04-29 22:09
@Africa67 please confirm this is fixed.

**Comment by marcelveldt** [comment] 2024-05-03 13:18
> Nothing done. Installed version 143 but crashes. It starts and stops and then restarts.

OK, in that case make sure you don't use the Sonos provider. So start in safe mode, remove sonos provider and after that it should work.

Let's close this duplicate issue report and track progress in one single issue:
https://github.com/music-assistant/hass-music-assistant/issues/2142

**Closed by marcelveldt** 2024-05-03 13:18 UTC
Labels: related, More info
