### ISSUE TITLE
Select folder to play

### ISSUE THREAD

**Issue by gugaspinto** [music-assistant/hass-music-assistant#454] opened 2022-06-19 13:34 UTC
It will be great if we can select a folder to play.
Great work... 
Congratulations
GP

**Comment by marcelveldt** [comment] 2022-06-19 13:36
This is a duplicate of this feature request: https://github.com/music-assistant/hass-music-assistant/discussions/413
Please add your vote there, thanks!

**Closed by marcelveldt** 2022-06-19 13:36 UTC
