### ISSUE TITLE
Ha-addon: KeyError: 'verify_ssl'

### ISSUE THREAD

**Issue by skrashevich** [music-assistant/hass-music-assistant#2575] opened 2024-07-06 03:58 UTC
### What version of Music Assistant has the issue?

2.1.0b11

### What version of the Home Assistant Integration have you got installed?

2024.7.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

2024-07-06 06:50:42.373 ERROR (MainThread) [music_assistant] Error loading provider(instance) Home Assistant: 'verify_ssl'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/server.py", line 429, in load_provider_config
    await self._load_provider(prov_conf)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/server.py", line 591, in _load_provider
    provider = await prov_mod.setup(self, prov_manifest, conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/hass/__init__.py", line 53, in setup
    await prov.handle_async_init()
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/hass/__init__.py", line 176, in handle_async_init
    await self.hass.connect(ssl=bool(self.config.get_value(CONF_VERIFY_SSL)))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/common/models/config_entries.py", line 189, in get_value
    config_value = self.values[key]
                   ~~~~~~~~~~~^^^^^
KeyError: 'verify_ssl'

### How to reproduce

just start the add-on :)

### Music Providers

.

### Player Providers

.

### Full log output

_No response_

### Additional information

Introduced in https://github.com/music-assistant/server/commit/13e596fb80228d817681f31b349c5373ba39dd89
probably, forgot to duplicate configEntry to line 119

### What version of Home Assistant Core are your running

2024.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment] 2024-07-06 06:40
Thanks it has been already identified and is being investigated.

**Comment by OzGav** [comment] 2024-07-06 11:45
This will be fixed in beta 11

**Comment by udochrist** [comment] 2024-07-06 12:46
Just updated to beta 11 and the verify_ssl is still shown when I configure music assistant.

**Comment by collateral87** [comment] 2024-07-06 13:03
i can confirm that the problem is still here in beta11

**Comment by marcelveldt** [comment] 2024-07-06 13:42
It's fixed in b12 not b11

**Comment by OzGav** [comment] 2024-07-06 14:23
confirmed fixed

**Closed by OzGav** 2024-07-06 14:23 UTC
Labels: bug, Fix to be Confirmed
