### ISSUE TITLE
Error in message on start of HA / Music Assistant

### ISSUE THREAD

**Issue by manfredwilhelm** [music-assistant/hass-music-assistant#966] opened 2022-10-27 21:32 UTC
### What version of Music Assistant has the issue?

2022.8.4

### The problem

Music Assistant runs in error after Setup / Start

### How to reproduce

install via HACS, restart HA, add new Integration, config Integration and the error is shown: 

Failed to set up
Check the logs 

### Relevant log output

Error setting up entry Music Assistant for mass
11:20:31 PM – (ERROR) mass (custom integration) - message first occurred at 11:19:03 PM and shows up 2 times
This version of Music Assistant is compatible with Home Assistant version 2022.8, and you are running 2022.10.5. You may run into compatibility issues. Please check if there's a newer (beta) version available of Music Assistant.
11:20:31 PM – (WARNING) mass (custom integration) - message first occurred at 11:19:02 PM and shows up 2 times

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:190
Integration: mass (documentation, issues)
First occurred: 11:19:03 PM (2 occurrences)
Last logged: 11:20:31 PM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 197, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 190, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/mass.py", line 79, in setup
    await self.database.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 43, in setup
    await self._migrate()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 186, in _migrate
    await self.__create_database_tables()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 220, in __create_database_tables
    await self.execute(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 181, in execute
    return await self._db.execute(query, values)
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 163, in execute
    return await connection.execute(query, values)
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 274, in execute
    return await self._connection.execute(built_query)
  File "/usr/local/lib/python3.10/site-packages/databases/backends/sqlite.py", line 131, in execute
    query_str, args, context = self._compile(query)
  File "/usr/local/lib/python3.10/site-packages/databases/backends/sqlite.py", line 188, in _compile
    compiled._ad_hoc_textual,
AttributeError: 'SQLiteCompiler' object has no attribute '_ad_hoc_textual'

### What version of Home Assistant Core are your running

2022.10.5

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment] 2022-10-27 22:39
Any chance you tried installing the 2022.11 version first which is for HA 2022.11 ONLY ?
Only way to recover from this is by either restoring a backup before the HACS upgrade or simply install the HA 2022.11 beta and the MA version 2022.11.0 version...

**Comment by marcelveldt** [comment] 2022-10-28 07:42
duplicate of https://github.com/music-assistant/hass-music-assistant/issues/965

**Closed** 2022-10-28 07:42 UTC
Labels: triage

**Comment by manfredwilhelm** [comment] 2022-10-28 11:03
Ok, i try to install HA 2022.11 beta. Or wait a few days for the 2022.11 release.

**Comment by OzGav** [comment] 2022-10-28 11:09
That is up to you. Both will work
