### ISSUE TITLE
Snapcast: TTS and local files do not play to the end

### ISSUE THREAD

**Issue by rich33584** [music-assistant/hass-music-assistant#2690] opened 2024-07-27 09:47 UTC
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

TTS and local files stop early. They only play about 75% and then stop . Files less than about 4 seconds do play to the end.

### How to reproduce

You can reproduce by going to the integration and selecting a player. Browse media, then either play a local file or choose text to speech. Type in a message or play a local file that will be at least 5-6 seconds. It will stop before the entire file/message has played.
Video showing tts:
https://youtube.com/shorts/rj-SRbg7wfc?feature=share

### Music Providers

Local files/TTS
Radio does not stop.
Spotify plays tracks to the end.

### Player Providers

Snapcast
I have not tried other players but will try a chromecast player later and report back.

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16398886/music-assistant.log)

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment] 2024-07-27 10:18
Can you provide the exact steps in detail that you are using as it looks from the video that you are doing something unusual.

**Comment by rich33584** [comment] 2024-07-27 11:21
> Can you provide the exact steps in detail that you are using as it looks from the video that you are doing something unusual.
> 
> I don't know why you are using Piper to generate the TTS and I don't know why it looks like you are sending to a voice satellite? Hard to tell what I am seeing in the video though.

In the video, I go to the integration. Select a player then browse media. From there go to text to speech. Enter a message that will be about 5-6 seconds and play the message

**Comment by OzGav** [comment] 2024-07-29 02:46
I cannot reproduce this. Please try with a different player and let us know how you go.

**Comment by rich33584** [comment] 2024-07-29 08:59
> I cannot reproduce this. Please try with a different player and let us know how you go.

Chromecast does operate properly. So just seems to be a Snapcast player issue.
I dont have any other players to test with.

**Comment by OzGav** [comment] 2024-07-29 09:04
@SantiagoSotoC I wasn’t able to replicate this with my Snapcast setup. Any ideas?

**Comment by SantiagoSotoC** [comment] 2024-07-31 19:23
I didn't try it now, but I remember some of this but it was when tts support was added, I can add a little delay when a ttl is finished playing, so it doesn't change stream so fast.
@rich33584 you can try changing the buffer size and see if that affects the duration of the tts

**Comment by rich33584** [comment] 2024-07-31 20:44
Buffer size didn't help. To be clear, it also does this playing local
files. Mp3 or wav. Not just tts. It seems to play either about 75% through,
then stop.

**Comment by SantiagoSotoC** [comment] 2024-07-31 21:52
But there was no change? Increasing does not worsen the problem ?

**Comment by rich33584** [comment] 2024-07-31 22:00
> But there was no change? Increasing does not worsen the problem ?

No, The longer the file, the longer it plays. To about 75% completion. Maybe its reporting the caching of the file as finished playing? I dont know if I am explaining what I am thinking correctly...Maybe as the file is being transferred to the device its reporting the finished transfer as finished playing? This is nowhere near my area of expertise...

**Comment by OzGav** [comment] 2024-08-01 00:38
Please explain exactly how you are playing the music files. Also detail how your HA and MA installation is setup as well as information about your network setup. No one else is reporting this problem.

**Comment by rich33584** [comment] 2024-08-01 23:47
Home assistant is installed on a bare metal machine. No VM or docker or
anything.  Network is just a standard wireless network.
I am running v28.0 of the Snapcast client on my Wyoming satellite.
Local files I usually play with the play media in Home assistant. TTS is
handled by Chime TTS.

**Comment by OzGav** [comment] 2024-08-01 23:49
OK there is no working solution for a combined voice satellite and media player to my knowledge

**Comment by rich33584** [comment] 2024-08-02 22:37
Ok, Ill try and figure this out. It worked well for months, then all the
sudden started this.
Thanks!

**Comment by OzGav** [comment] 2024-08-02 22:40
Ok we will close this. If you find more info to suggest something in MA is broken we can reopen

**Comment by rich33584** [comment] 2024-08-02 22:56
Ok, thanks.

**Comment by SantiagoSotoC** [comment] 2024-08-15 13:23
This does happen, I just tried to use piper and google ttl from ma and it only reprocesses the beginning.

**Comment by rich33584** [comment] 2024-08-15 13:44
Ok, I was about to install HA on a PI so I could test and see if there was something in my installation causing this. Ill hold off.
Have you tried a local file? Going into the MA integration and playing it from there?

**Comment by SantiagoSotoC** [comment] 2024-08-15 15:05
Only with the ttl from ha, I didn't test a local file, but it should be the same. it's not a snapcast problem, it's most likely because of how we handle the pause. I assume that if ffmpeg ends snapcast ends, we would have to add a delay, at least for that kind of files

**Comment by rich33584** [comment] 2024-08-15 22:44
Thanks for continuing to look into this. I greatly appreciate it.

**Comment by whc2001** [comment] 2024-09-30 13:42
I have also encountered this issue using Snapcast. Have you tried using an external Snapserver instance and check its log? For me it seems like the reason is the stream silence detection of Snapserver keeps switching between `playing` and `idle`. I tried to fork the server repo and add `idle_threshold` to the stream parameter with a long enough value (like 60000 ms) and seems like the problem is gone.

**Comment by OzGav** [comment] 2024-09-30 13:44
@SantiagoSotoC please see above

**Comment by SantiagoSotoC** [comment] 2024-09-30 17:04
I try it, but it is not documented in snapcast for TCP, only for Jack

**Comment by whc2001** [comment] 2024-09-30 17:07
> I try it, but it is not documented in snapcast for TCP, only for Jack

Seems like the TCP endpoint is inheriting the ASIO endpoint, which supports the `idle_threshold` option. I have written more information in #2987.

**Comment by SantiagoSotoC** [comment] 2024-10-01 20:31
I uploaded it to the “snapcast_add_idle_threshold” branch of the repo server, @whc2001 can you try it in the dev addon ?

**Comment by SantiagoSotoC** [comment] 2024-10-01 21:32
Adding idle_threshold certainly improves the situation, no longer cuts audios in half, but short audios are still a problem.

**Comment by whc2001** [comment] 2024-10-01 22:06
> I uploaded it to the “snapcast_add_idle_threshold” branch of the repo server, @whc2001 can you try it in the dev addon ?

Have you changed anything else beside that? I have to use an external Snapserver since the built-in one does not offer adjustment of some configurations (which could cause errornous behaviours of the ESP32 snapclient port I am using). With that branch I am getting something like this in the log:
```
2024-10-01 18:02:45.483 INFO (MainThread) [snapcast.control.server] stream MusicAssistant--5047 not found, synchronize
2024-10-01 18:02:45.483 INFO (MainThread) [snapcast.control.server] stream MusicAssistant--5047 not found, synchronize
...
2024-10-01 18:02:45.500 INFO (MainThread) [snapcast.control.server] stream MusicAssistant--5047 not found, synchronize
2024-10-01 18:02:45.500 INFO (MainThread) [snapcast.control.server] stream MusicAssistant--5047 not found, synchronize
2024-10-01 18:02:45.502 ERROR (MainThread) [music_assistant] Error doing task: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1027, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/app/venv/lib/python3.12/site-packages/snapcast/control/protocol.py", line 54, in data_received
    self.handle_data(item)
  File "/app/venv/lib/python3.12/site-packages/snapcast/control/protocol.py", line 61, in handle_data
    self.handle_notification(data)
  File "/app/venv/lib/python3.12/site-packages/snapcast/control/protocol.py", line 73, in handle_notification
    self._callbacks.get(data.get('method'))(data.get('params'))
  File "/app/venv/lib/python3.12/site-packages/snapcast/control/server.py", line 432, in _on_stream_update
    self._streams[data.get("id")].callback()
  File "/app/venv/lib/python3.12/site-packages/snapcast/control/stream.py", line 79, in callback
    self._callback_func(self)
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/providers/snapcast/__init__.py", line 519, in stream_callback
    self._set_childs_state(player_id, player.state)
TypeError: SnapCastProvider._set_childs_state() takes 2 positional arguments but 3 were given
2024-10-01 18:02:45.544 INFO (MainThread) [music_assistant.snapcast] Connection to SnapServer lost, reason: SnapCastProvider._set_childs_state() takes 2 positional arguments but 3 were given. Reloading provider in 5 seconds.
2024-10-01 18:02:50.567 WARNING (MainThread) [music_assistant] Error while unload provider Snapcast: 'NoneType' object has no attribute 'state'
2024-10-01 18:02:50.580 INFO (MainThread) [music_assistant.snapcast] Started connection to Snapserver 10.8.4.7:1705
2024-10-01 18:02:50.580 INFO (MainThread) [music_assistant] Loaded player provider Snapcast
```

**Comment by whc2001** [comment] 2024-10-01 22:17
I saw you pushed some more fix, and with that the disconnect is gone. However the announcement stream is still being removed early:
```
2024-10-01 18:15:18.667 DEBUG (MainThread) [snapcast.control.server] group found: Snapgroup (ESP32SC-Bedroom, 07093865-ec6a-5936-bd00-c93d87054c53)
2024-10-01 18:15:18.667 DEBUG (MainThread) [snapcast.control.server] stream found: Snapstream (default)
2024-10-01 18:15:18.667 DEBUG (MainThread) [snapcast.control.server] stream found: Snapstream (MusicAssistant--5139)
2024-10-01 18:15:18.667 DEBUG (MainThread) [snapcast.control.server] client found: Snapclient 0.0.3 (ESP32SC-Bedroom, CC:8D:A2:8C:AB:1A)
2024-10-01 18:15:18.667 DEBUG (MainThread) [snapcast.control.server] group found: Snapgroup (ESP32SC-Bedroom, 07093865-ec6a-5936-bd00-c93d87054c53)
2024-10-01 18:15:18.668 DEBUG (MainThread) [snapcast.control.server] stream found: Snapstream (default)
2024-10-01 18:15:18.668 DEBUG (MainThread) [snapcast.control.server] stream found: Snapstream (MusicAssistant--5139)
2024-10-01 18:15:18.668 DEBUG (MainThread) [snapcast.control.server] client found: Snapclient 0.0.3 (ESP32SC-Bedroom, CC:8D:A2:8C:AB:1A)
2024-10-01 18:15:18.668 DEBUG (MainThread) [snapcast.control.server] group found: Snapgroup (ESP32SC-Bedroom, 07093865-ec6a-5936-bd00-c93d87054c53)
2024-10-01 18:15:31.434 DEBUG (MainThread) [music_assistant.snapcast] Finished streaming to tcp://10.8.4.7:5139
2024-10-01 18:15:31.437 DEBUG (MainThread) [snapcast.control.server] stream MusicAssistant--5139 updated
2024-10-01 18:15:31.438 DEBUG (MainThread) [snapcast.control.server] stream MusicAssistant--5139 updated
2024-10-01 18:15:31.439 DEBUG (MainThread) [snapcast.control.server] stream MusicAssistant--5139 updated
2024-10-01 18:15:31.440 DEBUG (MainThread) [snapcast.control.server] stream MusicAssistant--5139 updated
2024-10-01 18:15:31.440 DEBUG (MainThread) [snapcast.control.server] stream MusicAssistant--5139 updated
2024-10-01 18:15:31.441 DEBUG (MainThread) [snapcast.control.server] stream MusicAssistant--5139 updated
2024-10-01 18:15:31.442 DEBUG (MainThread) [snapcast.control.server] stream MusicAssistant--5139 updated
2024-10-01 18:15:31.443 DEBUG (MainThread) [snapcast.control.server] stream MusicAssistant--5139 updated
2024-10-01 18:15:31.448 DEBUG (MainThread) [snapcast.control.server] stream found: Snapstream (default)
2024-10-01 18:15:31.448 DEBUG (MainThread) [snapcast.control.server] client found: Snapclient 0.0.3 (ESP32SC-Bedroom, CC:8D:A2:8C:AB:1A)
2024-10-01 18:15:31.448 DEBUG (MainThread) [snapcast.control.server] group found: Snapgroup (ESP32SC-Bedroom, 07093865-ec6a-5936-bd00-c93d87054c53)
```

```
Oct 01 22:15:18 C612-Snapcast snapserver[4362]: PcmStream: MusicAssistant--5139, sampleFormat: 48000:16:2
Oct 01 22:15:18 C612-Snapcast snapserver[4362]: Silence threshold percent: 0, silence threshold amplitude: 0
Oct 01 22:15:18 C612-Snapcast snapserver[4362]: Chunk duration: 20 ms, frames: 960, size: 3840
Oct 01 22:15:18 C612-Snapcast snapserver[4362]: TcpStream host: 0.0.0.0, port: 5139, is server: 1
Oct 01 22:15:18 C612-Snapcast snapserver[4362]: Start: MusicAssistant--5139, type: tcp, sampleformat: 48000:16:2, codec: flac
Oct 01 22:15:18 C612-Snapcast snapserver[4362]: Init - compression level: 2
Oct 01 22:15:18 C612-Snapcast snapserver[4362]: New client connection
Oct 01 22:15:18 C612-Snapcast snapserver[4362]: State changed: MusicAssistant--5139, state: idle => playing
Oct 01 22:15:18 C612-Snapcast snapserver[4362]: onStateChanged (MusicAssistant--5139): playing
Oct 01 22:15:19 C612-Snapcast snapserver[4362]: getNextMessage: Time, size: 8, id: 1053, refers: 0
Oct 01 22:15:19 C612-Snapcast snapserver[4362]: onMessageReceived: Time, size: 8, id: 1053, refers: 0, sent: 997,631023, recv: 3099307,157037
Oct 01 22:15:20 C612-Snapcast snapserver[4362]: getNextMessage: Time, size: 8, id: 1054, refers: 0
Oct 01 22:15:20 C612-Snapcast snapserver[4362]: onMessageReceived: Time, size: 8, id: 1054, refers: 0, sent: 998,631029, recv: 3099308,157266
Oct 01 22:15:20 C612-Snapcast snapserver[4362]: Saving config
Oct 01 22:15:21 C612-Snapcast snapserver[4362]: getNextMessage: Time, size: 8, id: 1055, refers: 0
Oct 01 22:15:21 C612-Snapcast snapserver[4362]: onMessageReceived: Time, size: 8, id: 1055, refers: 0, sent: 999,631029, recv: 3099309,157156
...
Oct 01 22:15:31 C612-Snapcast snapserver[4362]: getNextMessage: Time, size: 8, id: 1065, refers: 0
Oct 01 22:15:31 C612-Snapcast snapserver[4362]: onMessageReceived: Time, size: 8, id: 1065, refers: 0, sent: 1009,631029, recv: 3099319,156939
Oct 01 22:15:31 C612-Snapcast snapserver[4362]: Stream.RemoveStream("MusicAssistant--5139")
Oct 01 22:15:31 C612-Snapcast snapserver[4362]: Error during async wait: Operation canceled
Oct 01 22:15:31 C612-Snapcast snapserver[4362]: State changed: MusicAssistant--5139, state: playing => idle
Oct 01 22:15:31 C612-Snapcast snapserver[4362]: onStateChanged (MusicAssistant--5139): idle
Oct 01 22:15:31 C612-Snapcast snapserver[4362]: TCP session outstanding async_writes: 2
Oct 01 22:15:32 C612-Snapcast snapserver[4362]: getNextMessage: Time, size: 8, id: 1066, refers: 0
Oct 01 22:15:32 C612-Snapcast snapserver[4362]: onMessageReceived: Time, size: 8, id: 1066, refers: 0, sent: 1010,631003, recv: 3099320,157461
Oct 01 22:15:33 C612-Snapcast snapserver[4362]: getNextMessage: Time, size: 8, id: 1067, refers: 0
Oct 01 22:15:33 C612-Snapcast snapserver[4362]: onMessageReceived: Time, size: 8, id: 1067, refers: 0, sent: 1011,631003, recv: 3099321,157420
Oct 01 22:15:33 C612-Snapcast snapserver[4362]: Saving config
Oct 01 22:15:34 C612-Snapcast snapserver[4362]: getNextMessage: Time, size: 8, id: 1068, refers: 0
Oct 01 22:15:34 C612-Snapcast snapserver[4362]: onMessageReceived: Time, size: 8, id: 1068, refers: 0, sent: 1012,631014, recv: 3099322,157384
Oct 01 22:15:35 C612-Snapcast snapserver[4362]: getNextMessage: Time, size: 8, id: 1069, refers: 0
Oct 01 22:15:35 C612-Snapcast snapserver[4362]: onMessageReceived: Time, size: 8, id: 1069, refers: 0, sent: 1013,631014, recv: 3099323,157506
Oct 01 22:15:36 C612-Snapcast snapserver[4362]: getNextMessage: Time, size: 8, id: 1070, refers: 0
```

**Comment by SantiagoSotoC** [comment] 2024-10-01 22:25
I am trying to fix the status in ma, which was now assumed to be because the snapcast status was going back and forth

**Comment by SantiagoSotoC** [comment] 2024-10-01 22:25
What option can't you configure in the embedded one ?  It is something that can be easily added

**Comment by whc2001** [comment] 2024-10-01 22:27
> I am trying to fix the status in ma, which was now assumed to be because the snapcast status was going back and forth

Great, I'll test it when you are done. Currently seems like even the non-announcement (song selected in MASS WebUI) is having problem of finishing early (and it seems to break repeat-one)

**Comment by SantiagoSotoC** [comment] 2024-10-01 22:28
> > I am trying to fix the status in ma, which was now assumed to be because the snapcast status was going back and forth
> 
> Great, I'll test it when you are done. Currently seems like even the non-announcement (song selected in MASS WebUI) is having problem of finishing early (and it seems to break repeat-one), which does not happen in the previous version

 I'll let you know, the idea was just to change what you told me, but I found some free time.

**Comment by whc2001** [comment] 2024-10-01 22:29
> What option can't you configure in the embedded one ? It is something that can be easily added

Mainly the `sampleformat`, `chunk_ms`, and `buffer` with the allowed value smaller than 500. Here is what I am using for the external server:

![image](https://github.com/user-attachments/assets/36e853ac-9da1-4c72-8685-665829c6a70a)

But I mean really the ESP32 port is not very stable. I will get a real Snapclient later to test.

**Comment by SantiagoSotoC** [comment] 2024-10-01 22:32
> > What option can't you configure in the embedded one ? It is something that can be easily added
> 
> Mainly the `sampleformat`, `chunk_ms`, and `buffer` with the allowed value smaller than 500. Here is what I am using for the external server:
> 
> ![image](https://private-user-images.githubusercontent.com/16266909/372670446-36e853ac-9da1-4c72-8685-665829c6a70a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MjIwOTksIm5iZiI6MTcyNzgyMTc5OSwicGF0aCI6Ii8xNjI2NjkwOS8zNzI2NzA0NDYtMzZlODUzYWMtOWRhMS00YzcyLTg2ODUtNjY1ODI5YzZhNzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDIyMjk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNWRkNmM3ODgzZmIwNTAwY2ZkYTBlYTNiNjUyNTRmOTYzOTk0OTk4YjBhNTU2ZTYxMDk0NTRkOWRlNThhYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IYPGIwl4AEteKX-uZgZvTGYEbjTQ3VDsQV1i9Cid46M)
> 
> But I mean really the ESP32 port is not very stable. I will get a real Snapclient later to test.

The sample format, no matter how you change it, ma overwrites it. 
I can add the chunks_ms and allow values less than 500 or leave it as a number.

**Comment by whc2001** [comment] 2024-10-01 22:33
> > > What option can't you configure in the embedded one ? It is something that can be easily added
> > 
> > 
> > Mainly the `sampleformat`, `chunk_ms`, and `buffer` with the allowed value smaller than 500. Here is what I am using for the external server:
> > ![image](https://private-user-images.githubusercontent.com/16266909/372670446-36e853ac-9da1-4c72-8685-665829c6a70a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MjIwOTksIm5iZiI6MTcyNzgyMTc5OSwicGF0aCI6Ii8xNjI2NjkwOS8zNzI2NzA0NDYtMzZlODUzYWMtOWRhMS00YzcyLTg2ODUtNjY1ODI5YzZhNzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDIyMjk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNWRkNmM3ODgzZmIwNTAwY2ZkYTBlYTNiNjUyNTRmOTYzOTk0OTk4YjBhNTU2ZTYxMDk0NTRkOWRlNThhYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IYPGIwl4AEteKX-uZgZvTGYEbjTQ3VDsQV1i9Cid46M)
> > But I mean really the ESP32 port is not very stable. I will get a real Snapclient later to test.
> 
> The sample format, no matter how you change it, ma overwrites it. I can add the chunks_ms and allow values less than 500 or leave it as a number.

Ahh so that one does not really matter then. I have to twiddle around the other two to get a stable stream happening. With adjustable values I think I can then ditch the external server.

**Comment by SantiagoSotoC** [comment] 2024-10-01 23:17
Well I'll leave it for today, tomorrow I'll continue, but try in your modified version just send a ttl with a “Hi” and see if it works, because it didn't work for me.

**Comment by rich33584** [comment] 2024-10-01 23:30
Thanks to all of you for continuing to work on this.

**Comment by whc2001** [comment] 2024-10-02 12:25
> Well I'll leave it for today, tomorrow I'll continue, but try in your modified version just send a ttl with a “Hi” and see if it works, because it didn't work for me.

Hmmm interesting, it's working for me using the built-in TTS (haven't tested throughly, but setting Piper's length factor to 0.25 and speaking "hi" still works for me), but with ChimeTTS custom integration I have to enable `cache` when sending request, or the following error happens:
```
2024-10-02 08:20:24.631 DEBUG (MainThread) [snapcast.control.server] client found: Snapclient 0.0.3 (ESP32SC-Bedroom, CC:8D:A2:8C:AB:1A)
2024-10-02 08:20:24.631 DEBUG (MainThread) [snapcast.control.server] group found: Snapgroup (ESP32SC-Bedroom, 07093865-ec6a-5936-bd00-c93d87054c53)
2024-10-02 08:20:24.633 DEBUG (MainThread) [snapcast.control.group] set stream to MusicAssistant--5061 on ESP32SC-Bedroom
2024-10-02 08:20:24.633 DEBUG (MainThread) [music_assistant.snapcast] Start streaming to tcp://10.8.4.7:5061
2024-10-02 08:20:34.726 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: Unable to retrieve info for http://10.8.4.5:8123/media/local/sounds/temp/chime_tts/2fbiq3vr.mp3?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIyYTM3YWVjMWM1MzQ0YTQ1YTMxMTI4ZTI3ZDM4NTg2YiIsInBhdGgiOiIvbWVkaWEvbG9jYWwvc291bmRzL3RlbXAvY2hpbWVfdHRzLzJmYmlxM3ZyLm1wMyIsInBhcmFtcyI6W10sImlhdCI6MTcyNzg3MTYyNCwiZXhwIjoxNzI3OTU4MDI0fQ.LLPaDlQToNGnfRZzQclgjp4l56nq6QspNzOzx2XeuYI: Server returned 404 Not Found
```
For the extreme situation, with a 119ms audio file it's almost unable to hear anything, but it still makes a click.

**Comment by SantiagoSotoC** [comment] 2024-10-02 12:29
I will revert the changes and just leave what you propose, so we don't change too much at once, but I will leave it as an option to be configured with 60000 by default

**Comment by SantiagoSotoC** [comment] 2024-10-02 13:14
Well, @whc2001 you can test it now, the problem of short tts is still there but it is a very special use case, most probably it will be fixed, looking for the ideal value of the idle_threshold and updating the state with a callback as it was done before

**Comment by whc2001** [comment] 2024-10-02 13:31
> Well, @whc2001 you can test it now, the problem of short tts is still there but it is a very special use case, most probably it will be fixed, looking for the ideal value of the idle_threshold and updating the state with a callback as it was done before

Got it, I just realized there is a mistake in the original code, fixing it right now

**Comment by whc2001** [comment] 2024-10-02 13:35
@SantiagoSotoC Does this look good to you? Haven't tested it yet gonna do it later
https://github.com/whc2001/server/commits/snapcast_add_idle_threshold/

**Comment by SantiagoSotoC** [comment] 2024-10-02 13:41
It lacks some things, if you want to do the pr and I finish it

**Comment by whc2001** [comment] 2024-10-02 13:46
> It lacks some things, if you want to do the pr and I finish it

Great thanks!
https://github.com/music-assistant/server/pull/1691

**Comment by OzGav** [comment] 2024-10-18 05:23
@SantiagoSotoC @whc2001 Can this be closed or are you waiting for it to get to stable?

**Comment by OzGav** [comment] 2024-10-18 11:06
I will close it if you tell me it is fixed!

**Comment by whc2001** [comment] 2024-10-18 11:08
> I will close it if you tell me it is fixed!

Ah got it, I think maybe wait until it's released and tested a bit?

**Comment by OzGav** [comment] 2024-10-19 00:34
Beta 30 has been released.

**Comment by OzGav** [comment] 2024-10-20 00:33
@rich33584 Are you able to check if this is fixed in the beta?

**Comment by rich33584** [comment] 2024-10-20 14:02
> @rich33584 Are you able to check if this is fixed in the beta?

The automations with TTS are working good. For some reason I cant get anything to work when choosing the player in the integration and going to Browse Media. It just instantly goes to Idle.
The TTS automations are way more important to me and they are working good. Thanks. 
Maybe the other issue is on my end..
![player](https://github.com/user-attachments/assets/ec771540-a219-4839-90cd-06499026c1fe)

**Comment by SantiagoSotoC** [comment] 2024-10-20 14:28
> > @rich33584 Are you able to check if this is fixed in the beta?
> 
> The automations with TTS are working good. For some reason I cant get anything to work when choosing the player in the integration and going to Browse Media. It just instantly goes to Idle. The TTS automations are way more important to me and they are working good. Thanks. Maybe the other issue is on my end.. ![player](https://private-user-images.githubusercontent.com/71353473/378194643-ec771540-a219-4839-90cd-06499026c1fe.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzQ2OTYsIm5iZiI6MTcyOTQzNDM5NiwicGF0aCI6Ii83MTM1MzQ3My8zNzgxOTQ2NDMtZWM3NzE1NDAtYTIxOS00ODM5LTkwY2QtMDY0OTkwMjZjMWZlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE0MjYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YjQ2Y2EyOTM0ODc0NTI2MzU5NGI2Yjk4MjllZDE0OWY3YjYxMDdhOWJhMTI1MzA2ODg1YWEyOGE3ODBkYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D6uBpo8hOMBKxVyPK43gMMD-sZpJlkVBPUacpgNkSH0)

The text is long ? short TTS are still a problem.

**Comment by rich33584** [comment] 2024-10-20 14:47
After further testing, the clips need to be around 5-6 seconds long and they play fine. Shorter ones are still an issue as you said.
Not sure if that would be an issue in real world use anyway.
Thanks!

**Comment by whc2001** [comment] 2024-10-20 14:48
> > > @rich33584 Are you able to check if this is fixed in the beta?
> > 
> > 
> > The automations with TTS are working good. For some reason I cant get anything to work when choosing the player in the integration and going to Browse Media. It just instantly goes to Idle. The TTS automations are way more important to me and they are working good. Thanks. Maybe the other issue is on my end.. ![player](https://private-user-images.githubusercontent.com/71353473/378194643-ec771540-a219-4839-90cd-06499026c1fe.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzQ2OTYsIm5iZiI6MTcyOTQzNDM5NiwicGF0aCI6Ii83MTM1MzQ3My8zNzgxOTQ2NDMtZWM3NzE1NDAtYTIxOS00ODM5LTkwY2QtMDY0OTkwMjZjMWZlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE0MjYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YjQ2Y2EyOTM0ODc0NTI2MzU5NGI2Yjk4MjllZDE0OWY3YjYxMDdhOWJhMTI1MzA2ODg1YWEyOGE3ODBkYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D6uBpo8hOMBKxVyPK43gMMD-sZpJlkVBPUacpgNkSH0)
> 
> The text is long ? short TTS are still a problem.

I tested the latest `main` branch and things are working for me at least. The release time after TTS has finished is a bit long to my liking but that's off topic.


https://github.com/user-attachments/assets/5b6f0a06-baed-4268-9d52-faccf1243948

**Comment by marcelveldt** [comment] 2024-10-20 18:42
While I was doing some tweaks for TTS yesterday I could 10% reproduce this issue with snapcast players.
Short audio clips (TTS or something else) simply do not play. I think its safe to assume this is a snapcast limitation.

**Comment by OzGav** [comment] 2024-10-20 20:39
I have added a note to the docs about short announcements

**Comment by SantiagoSotoC** [comment] 2024-10-21 14:36
About snapweb an issue has been opened in their repo, it may take a while to fix it.
https://github.com/badaix/snapweb/issues/108

**Comment by SantiagoSotoC** [comment] 2024-10-21 18:00
> While I was doing some tweaks for TTS yesterday I could 100% reproduce this issue with snapcast players.
> Short audio clips (TTS or something else) simply do not play. I think its safe to assume this is a snapcast limitation. 

Adding a minimum time between creating a stream and destroying it does not solve the problem ?

**Comment by marcelveldt** [comment] 2024-10-22 22:04
> Adding a minimum time between creating a stream and destroying it does not solve the problem ?

I didnt look further into it, I just notice dit while testing something else.

**Comment by OzGav** [comment] 2024-10-23 23:03
@rich33584 2.3.0rc1 is released. Please test again

**Comment by SantiagoSotoC** [comment] 2024-10-23 23:11
> @rich33584 2.3.0rc1 is released. Please test again

Now even one letter should work

**Closed** 2024-10-24 14:51 UTC
Labels: bug, related, Snapcast, Fix to be Confirmed

**Comment by whc2001** [comment] 2024-10-24 14:57
Tested without any problem and seems like the delay after short announcement is partially mitigated. Thanks everyone! Looking forward for this to be released so I can finally uninstall the dev version
