### ISSUE TITLE
Empty artists resulting in flickering UI and many requests

### ISSUE THREAD

**Issue by mvdwetering** [music-assistant/hass-music-assistant#2326] opened 2024-05-18 15:53 UTC
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

not installed

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I noticed that when I view an Artist page/screen that for some artists the screen is "wiggling" up and down. In the video "Abba" is having the issue and another artist not. There are several artists that have this behavior, but most seem ok.

I noticed that all artists that show this behavior have no songs ("nummers" in the video) or albums linked. Searching more it seems that these artists are not in my normal music library, but in a to-be-tagged directory. So my guess is that they were added when I initially installed MA and selected the whole file share by accident so it dragged in all music from the remote share instead of only my curated selection. I removed (or edited) that remote share to import from the correct path, but I suspect there are leftovers like these empty artists.

I enabled debug logging to get a bit more insight and it shows output like the excerpt below. There were many more of these lines. It seems to be about 20 per 500ms. I gues these are related to the progressbar that is slightly visible in the video. Not sure if these are actual requests to MusicBrainz, but it seems to be spamming something.
```

2024-05-18 17:23:11.113 DEBUG (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Abba
 - using lookup-album(s): none
 - using lookup-track(s): none

2024-05-18 17:23:11.137 DEBUG (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Abba
 - using lookup-album(s): none
 - using lookup-track(s): none

2024-05-18 17:23:11.159 DEBUG (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Abba
 - using lookup-album(s): none
 - using lookup-track(s): none
```

https://github.com/music-assistant/hass-music-assistant/assets/732514/2c73184b-cb0f-433b-9d8d-b5863144feee

### How to reproduce

Not sure how I got these, other than already mentioned in the description

### Music Providers

Remote share

### Player Providers

Got Cast and DLNA configured

### Full log output

Note that at the start you can see when I started with the wrong configuration so it was dragging in stuff from the "Untagged" folder, which I later fixed. 

[ma.log](https://github.com/music-assistant/hass-music-assistant/files/15365933/ma.log)

### What version of Home Assistant Core are your running

2024.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzSteve1996** [comment] 2024-05-21 02:34
This is happening for me as well. An example is a Coldplay song where the ALBUMARTIST = Coldplay and CONTRIBUTING ARTISTS = Coldplay ; Rihanna. Coldplay art / info shows up in Artist screen OK. Rihanna shows up as well as a separate artist but no art or info and when entering Rihanna it is flickering as above along with the Refresh icon with a red dot. I even created a 'Rihanna' folder with art work which did show up but still flickering. Just my 10c worth that may help. When I get home I will check out the debug logs.

**Comment by Extrapilot1** [comment] 2024-05-29 05:53
Just high level, I see this for entries (i.e. artists) that have either no songs/albums associated, or where there is some inconsistency (i.e. still still pending, or misassigned as Various Artists. That may well itself be a bug, where I ran ever song/album/artist I have through MusicBrainz and ID3 tagged them all. And for example, I would see a U2 album where Album name AND the Artist name was correct, but the album artwork showed as VA... Sometimes, refreshing that via the Artist link seems to reassign in. But it seems that the jittering is a refresh process that is not returning new info, and it keeps trying (list is redrawing but with offset for some reason).

**Comment by OzGav** [comment] 2024-06-11 23:16
@mvdwetering please confirm this is fixed in 2.1.0b4

**Comment by Extrapilot1** [comment] 2024-06-12 00:08
So far, I haent seen recurrence. Hard to know (prove a negative)- as it is possible additional scraping has filled previously-empty entries (artists for example). I do find it strange that despite having created art via MusicBrainz for the entire catalog, it isnt represented or captured vis refresh- seems to require my actual navigation to an artist or album to cause the system to read the file system info. Even if that is a different core issue, there is crossover.

**Comment by OzGav** [comment] 2024-06-12 06:41
What you are describing is likely this issue https://github.com/music-assistant/hass-music-assistant/issues/2384 so closing this one. If I’m mistaken we can reopen

**Closed by OzGav** 2024-06-12 06:41 UTC
Labels: bug, frontend, Fix to be Confirmed

**Comment by Thyraz** [comment] 2024-06-13 09:24
I noticed that flickering too in the past and it's gone for me in the latest beta. 🙂👍

**Comment by Thyraz** [comment] 2024-06-13 10:26
@OzGav I now also updated my second test instance to 2.1.0b4.
While my main instance is running in Home Assistant as an Add-On, this second instance is running in docker.

In this docker instance (I double checked it's running 2.1.0b4 now), the problem with the "wiggling" shown in the video above is present.
Do you know if there's something different from the frontend-side in the docker version?

**Comment by OzGav** [comment] 2024-06-14 06:43
@Thyraz I think there can be dependency differences. Update to the latest version again and see if it persists.

**Comment by Thyraz** [comment] 2024-06-14 06:46
@OzGav I just noticed, that it still happens on the other instance too.
Just with different artists.
Updating to 2.1.0b5 didn't solve this.

I also asked Marcel if he can reproduce it, or if it might be useful it I try to debug the root cause:
https://discord.com/channels/753947050995089438/753947050995089442/1251059921546383450

**Comment by marcelveldt** [comment] 2024-06-14 08:29
I still cant reproduce this (on the current/later version of backend and frontend).
What I see in your reports and videos is some endless loop is somehow triggered. I'll try to see if I can enforce it somehow. 

If you have any pointers to better reproduce the issue for me that would be great.

BTW, as an fyi; the issue that any leftover.orphaned artists could be left in the db was resolved a while ago.

**Comment by marcelveldt** [comment] 2024-06-14 08:32
And just like that I reproduced it - Looking for the fix.

**Comment by marcelveldt** [comment] 2024-06-14 12:44
Fixed in next update

**Comment by Thyraz** [comment] 2024-06-15 14:20
@marcelveldt should this been fixed with 2.1.0beta6?
If so, it's something different that happens on my side, as I still see it with the artists it happened before.

In this case, I'll try to provide you more info the next days ...

**Comment by marcelveldt** [comment] 2024-06-15 14:22
> @marcelveldt should this been fixed with 2.1.0beta6? If so, it's something different that happens on my side, as I still see it with the artists it happened before.
> 
> In this case, I'll try to provide you more info the next days ...

Yes, the many requests issue has been fixed. If there is something else that could be but then I need reproduction steps

**Comment by Thyraz** [comment] 2024-06-16 20:57
@marcelveldt I guess it's something in the backend and I haven't looked at the server code or debugged it so far, only the frontend.
So I'll try to get into the server component over the next days and see if I can debug it to give more details.

It is definitely another issue producing an request loop.
Here's a screenshot showing a lot media_item_updated events.

<img width="730" alt="screenshot" src="https://github.com/music-assistant/hass-music-assistant/assets/170099/b35bcb95-5b12-4c1f-bff3-f753192b10d9">

**Comment by marcelveldt** [comment] 2024-06-20 06:36
> It is definitely another issue producing an request loop. Here's a screenshot showing a lot media_item_updated events.

Yes it is but its another one than the previous one.
I really need to know if you can find the common factor that triggers the issue. Without a reproduction scenario this is very difficult to investigate.

This has all signs of a race condition but it might as well be a bug in the frontend.

**Comment by Thyraz** [comment] 2024-07-15 20:53
fixed in latest betas 👍
