### ISSUE TITLE
Cannot enter anything in the input search field

### ISSUE THREAD

**Issue by jzarca01** [music-assistant/hass-music-assistant#1276] opened 2023-05-31 09:02 UTC
### What version of Music Assistant has the issue?

2.0.0b31 and newer

### The problem

Since 2.0.0b31 i cannot use the search field anymore on my mobile.
It focuses, the keyboard appears, but the field is not populated

I'm using the latest home assistant app on an iphone, but the problem is the same using the mobile browser

It worked well on 2.0.0b30

### How to reproduce

Use an iphone, log into your HA instance, select music assistant, try to search for anything using the search bar

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by jzarca01** [comment] 2023-05-31 09:35
Downgraded to b30, it works

https://github.com/music-assistant/hass-music-assistant/assets/9349451/a5195743-f398-4819-a2e0-86ca659b1a64

**Comment by jzarca01** [comment] 2023-05-31 09:40
Updated to b32, still have issues

https://github.com/music-assistant/hass-music-assistant/assets/9349451/09885b2a-7765-4838-9721-7eddfe4f39bf

**Comment by OzGav** [comment] 2023-06-12 05:43
Is this still a prpblem with b35?

**Comment by jzarca01** [comment] 2023-06-12 07:57
Unfortunately yes

**Comment by LDannijs** [comment] 2023-06-22 11:08
I've got the same problem here. Got a dashboard with an Ipad and can only type 1 letter and then nothing else.

**Comment by jzarca01** [comment] 2023-06-28 08:59
Ok so I got to figure out where the issue comes from

iPad Air, iOS 12 : same issue
iPhone 11, iOS 14: same issue
iPhone XR, iOS 15: it works fine
iPhone 11, iOS 15: it works fine

The issue comes from Safari. Now how can we fix it ?

**Comment by jzarca01** [comment] 2023-06-29 08:33
Tried on firefox mobile, latest version, ios 14: doesnt work either

**Comment by OzGav** [comment] 2023-06-29 09:16
I think all browsers on IOS use the same engine. So it looks like an IOS version problem….

**Comment by jzarca01** [comment] 2023-07-06 08:16
from what I could check, differences are mostly css https://caniuse.com/?compare=ios_saf+14.5-14.8,ios_saf+15.4,ios_saf+16.5&compareCats=all

it should be possible to implement a workaround using polyfills and shims

**Comment by OzGav** [comment] 2023-07-10 09:45
I'm adding this to the backlog for the devs to have a look at. Not sure of the priority as it seems is just affecting older IOS devices?

**Comment by marcelveldt** [comment] 2023-07-20 19:03
We rely on vuetify for the frontend so this seems to be an issue in the vuetify library.
Anyways, I have updated to the latest version now in beta59 of the server so maybe you can check if that fixes things.

**Comment by marcelveldt** [comment] 2023-07-21 23:23
If the search field is still not working in the latest beta, can you let me know if other textfield are working correctly ? For example in the settings.

**Comment by jzarca01** [comment] 2023-07-22 18:28
Hi @marcelveldt thanks for taking part in this discussion. Unfortunately, even with the latest version (b59 as of now) the issue persists... Same thing happens in the settings when I try to enter a custom music provider url, after the first letter I cannot type anything else

**Comment by marcelveldt** [comment] 2023-07-22 19:25
Well, this is clearly a compatibility issue in the older Safari engine. Is there no way for you to update iOS on the affected devices ? We could try to create a bug report on the Vuetify project(vuetifyjs.com)  because the textboxes are from their library but I have no idea about chances that it gets fixed.

**Comment by LDannijs** [comment] 2023-07-22 19:54
> Well, this is clearly a compatibility issue in the older Safari engine. Is there no way for you to update iOS on the affected devices ?

I'm personally running an iPad air 2, so no more updates for that one :/

**Comment by OzGav** [comment] 2023-07-24 01:02
I am removing from the backlog. Raising an issue with Vuetify appears to be the way ahead?

**Comment by marcelveldt** [comment] 2023-07-24 22:02
The iPad Air 2 is almost 10 years old. Although Apple giving support for a long period of time (my 5 year old iphone was still going strong until I recently replaced it for a somewhat newer version), that is not indefinitely.

We cant support devices older than 5 years, I'm really sorry but we're using modern web frameworks here which only support the most recent browsers and Safari is know to have compatibility issues. One thing to try is report the bug to either Apple or Vuetify but I'm not so sure about the outcome. 

We've updated our vuetify version in most recent releases so small hope that included a fix for this bug. If not, it might be worth a shot to create small reproduce snippet with the vuetify textbox on some platform like codepen and address an issue report with the vuetify project.

**Comment by LDannijs** [comment] 2023-07-25 07:01
I was using the original V1 version of Music Assistant and text boxes used to work on that. That said, I do understand V2 is built on newer frameworks and that older devices aren't fully supported for that. Thanks for the insight and let's hope it'll be fixed!

**Comment by marcelveldt** [comment] 2023-07-25 08:59
Well, I think we're several updates of both Vuetify and perhaps also Safari ahead so things like this may break, especially on older devices.

**Closed** 2023-10-23 13:07 UTC
Labels: bug, upstream issue

**Comment by Miroslave11** [comment] 2024-09-14 07:32
Hello,
I have the same problem

version of Music Assistant 2.2.3
version of the Home Assistant Integration 2024.9.1
HW: IPad Air 2 SW 15.8.3.
in IPad installed official Home Assistant application

description:
In search: I can not write anything into search field
In artists: /show iput for search: I can write only one letter into search field
In tracks: /show iput for search: I can write only one letter into search field
In playlists: /show iput for search: I can write only one letter into search field

Is any chance to fix it?
