### ISSUE TITLE
All tracks shown as Disc N / Track N

### ISSUE THREAD

**Issue by ngilles** [music-assistant/hass-music-assistant#2898] opened 2024-09-11 14:11 UTC
### What version of Music Assistant has the issue?

2.2.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The latest version of Music Assistant shows all tracks as being numbered the same as the disc number:
Most tracks show up as Disc 1 / Track 1 ... but in multi-disc albums, all tracks from the second disc show up as Disc 2 / Track 2

Note: I have not checked for N > 2 at this point.

### How to reproduce

Point MA to music library with correctly tagged files which include track and disc numbers. After scanning is complete, navigate to any album.

### Music Providers

filesystem

### Player Providers

N/A

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment] 2024-09-11 21:06
> The important thing here is that it is evident in stable but not in betA

sounds like we forgot to merge a patch to stable then

**Comment by OzGav** [comment] 2024-09-11 22:34
This was the previous fix https://github.com/music-assistant/server/pull/1598/files

**Comment by OzGav** [comment] 2024-09-12 00:01
I just started my 2.2.2 server and the problem is there as well

**Comment by OzGav** [comment] 2024-09-14 09:42
This seems fixed in 2.2.4

**Closed** 2024-09-14 10:09 UTC
Labels: bug, Fix to be Confirmed
