### ISSUE TITLE
HA Browse media - tracks empty

### ISSUE THREAD

**Issue by fliespl** [music-assistant/hass-music-assistant#1283] opened 2023-06-04 20:51 UTC
### What version of Music Assistant has the issue?

v2

### The problem

Music Assistant properly displays items in tracks: https://ss.codeone.pl/ss-2023-06-04-22-49-09-1685911749-uZ6Xy8YN.png
while browsing in media shows: https://ss.codeone.pl/ss-2023-06-04-22-49-55-1685911795-RarewMPJ.png

Strangely - it works for playlists: https://ss.codeone.pl/ss-2023-06-04-22-50-15-1685911815-bpc9uiEI.png

### How to reproduce

Unsure - no special setup needed on my end.

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by fliespl** [comment] 2023-06-04 21:09
https://ss.codeone.pl/ss-2023-06-04-23-08-55-1685912935-vfNp73Mg.png

Websocket debug if it helps.

**Comment by OzGav** [comment] 2023-06-04 21:20
As per my other response check your tags. In that first image I see “unknown artist”

**Comment by fliespl** [comment] 2023-06-05 06:13
@OzGav I have only uploaded part of screen. Here's more and many tracks are tagged properly: https://ss.codeone.pl/ss-2023-06-05-08-12-57-1685945577-RoLbQYi3.png

Yet list in HA media browser is empty.

**Comment by OzGav** [comment] 2023-06-05 11:15
The HA media browser is not related to music assistant?

**Comment by fliespl** [comment] 2023-06-05 20:38
Maybe I am not explaining myself correctly, but will give it another go:

https://ss.codeone.pl/ss-2023-06-05-22-34-31-1685997271-DNmEZ0IQ.png

Going into "Media" tab, I get 5 new items from Music Assistant from which I should be able to choose tracks.

In my case, tracks / albums / artists are  empty and radio stations & playlists are showing items correctly (in mass I can see some items in either tab).

Is it also related to missing "album artist"? And if so - shouldn't "use album artist" be enough in advanced settings to work?

**Comment by OzGav** [comment] 2023-06-06 13:45
Thanks for the report. This has been confirmed and marked to be fixed but probably low priority as the focus is on the core MA functionally

**Comment by fliespl** [comment] 2023-06-07 20:16
@OzGav that's understandable. Keep up the great work! You are awesome. And Mass is amazing too :)

**Comment by marcelveldt** [comment] 2023-07-20 19:25
I can't reproduce this one on server version beta59 / HA integration 2023.6.0b2 
Does this issue still exist ?

**Comment by OzGav** [comment] 2023-07-24 00:49
This is fixed in my setup. @fliespl if we don't hear back soon we will assume this has been resolved. Thanks for the report.

**Comment by GitJamz** [comment] 2023-07-24 10:53
I seem to have similar, if not the same issue..

My Home Assistant is running on a VM. It has a SMB share setup to another network share, where I have my music (mapped to /media on Home Assistant).

From within the native "Media" application of Home Assistant I can browse to my SMB share and access it without problems.
With Music Assistant I can only see a Playlist, all other stuff such as Tracks,Albums,Artists are empy - as well as going to the "Browse" Section for (local disk).

To be mentioned, I just updated my Home Assistant first time in about 6 months today. In the process I of course had to update to the Beta version of Music Assistant as you know, to get it to work with the latest versions of Home Assistant. 
Before this update the SMB share was working without issues in Music Assistant. So this share is correctly setup at least for the older version of Music Assistant, but no longer working  now. 
(Also new version also broke my Sonos speakers that are no longer chooseable in the "Players" list, however they are in native Home Assistant..)

**Comment by OzGav** [comment] 2023-07-24 12:46
Firstly please confirm you have added a local file system provider in MA to access /media

**Comment by GitJamz** [comment] 2023-07-24 12:58
> Firstly please confirm you have added a local file system provider in MA to access /media

No.. Where is the instructions to do that? Cant find any option for it either..

As I said it worked fine in previous versions, but if there's a step I've missed here I apologize.

**Closed** 2023-07-30 12:26 UTC
Labels: More info
