### ISSUE TITLE
V1.1.5: several errors while casting

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#189] opened 2022-05-18 13:37 UTC
Although everything seems to play fine, there are several errors in my logging:
```
Failed to cast media http://192.168.178.47:8095/media_player.audio57woonkmr.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
14:19:12 – (ERROR) Google Cast
search - 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.spotify.com/v1/search?q=AC/DC+Stick+Around&type=track&limit=25&market=from_token&country=from_token')
14:11:11 – (ERROR) /usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/spotify.py - message first occurred at 14:06:14 and shows up 5 times
Error doing job: Task exception was never retrieved
14:10:39 – (ERROR) Music Assistant (custom integration) - message first occurred at 13:01:58 and shows up 24 times
Job [Analyze audio for ProviderType.FILESYSTEM_LOCAL://track/albumsacdcfulldiscographyaddcletthereberock07hellaintabadplacetobemp3] failed with error 'NoneType' object has no attribute 'decode'.
13:49:38 – (ERROR) /usr/local/lib/python3.9/site-packages/music_assistant/mass.py - message first occurred at 13:06:04 and shows up 3 times
Job [Add file://album/acdcacdclivespecialcollectorsedition to database] failed with error 'NoneType' object has no attribute 'name'.
13:38:09 – (ERROR) /usr/local/lib/python3.9/site-packages/music_assistant/mass.py - message first occurred at 13:38:08 and shows up 2 times
```

**Comment by marcelveldt** [comment] 2022-05-18 13:42
![Schermafbeelding 2022-05-18 om 15 42 14](https://user-images.githubusercontent.com/6389780/169053064-db10cce2-39e4-4278-aff3-1f9d90ad26db.png)

lol

**Comment by erkr** [comment] 2022-05-18 14:14
Yep, I will try report all possible exceptions possible ;-)

**Comment by marcelveldt** [comment] 2022-05-18 23:40
I think/hope this is fixed in 1.1.7. At least I couldn't reproduce it in 1.1.7

**Comment by erkr** [comment] 2022-05-19 06:10
Will give it a test today. Amazing how fast things are fixed 👍

**Comment by erkr** [comment] 2022-05-19 10:59
Not seen them till now, will close this issue 👍

**Closed** 2022-05-19 10:59 UTC
