### ISSUE TITLE
State of player not reflected

### ISSUE THREAD

**Issue by rVlad93** [music-assistant/hass-music-assistant#1999] opened 2024-03-14 14:17 UTC
### What version of Music Assistant has the issue?

2.0.0b108

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Music playing but the state is not reflected properly because play button is displayed instead of the pause button.

https://github.com/music-assistant/hass-music-assistant/assets/60452666/bfddcd7f-deba-4f24-a402-2999e7ed5141

### How to reproduce

Leave a playlist playing for a while.

### Music Providers

YT Music

### Player Providers

AirPlay

### What version of Home Assistant Core are your running

2024.3.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment] 2024-03-14 21:42
Have you tried other player providers to see if they work correctly?

**Comment by ammgws** [comment] 2024-03-15 05:48
I am also running into this, difference to OP in setup is:

Music Providers:  Open Subsonic
Player Providers: Home Assistant MediaPlayer

**Comment by OzGav** [comment] 2024-03-15 05:55
When you open the player list what is the status shown there?

**Comment by OzGav** [comment] 2024-03-15 12:13
Have you tried clearing the browser cache as well?

**Comment by marcelveldt** [comment] 2024-03-16 01:39
Please re-test this with b110 please, if still an issue, I'd like to receive the full log after you have attempted playback

**Comment by OzGav** [comment] 2024-03-17 01:35
We need some followup here or we will have to close this

**Comment by rVlad93** [comment] 2024-03-17 01:40
Unfortunately after the last release the play button when selecting a playlist or an artist, not the one in between the media buttons. doesn't do anything. I'll post it as a new issue. Sent from my Galaxy
-------- Original message --------From: OzGav ***@***.***> Date: 17/03/2024  01:35  (GMT+00:00) To: music-assistant/hass-music-assistant ***@***.***> Cc: rVlad93 ***@***.***>, Author ***@***.***> Subject: Re: [music-assistant/hass-music-assistant] State of player not
  reflected (Issue #1999) 
We need some followup here or we will have to close this

**Comment by ammgws** [comment] 2024-03-17 01:52
I cannot reproduce anymore, but sadly cannot recall if it was resolved prior to upgrading to b110 or not.

**Comment by OzGav** [comment] 2024-03-17 01:53
Ok will close this and I will look at the blue play button

**Closed by OzGav** 2024-03-17 01:53 UTC
Labels: More info, triage

**Comment by OzGav** [comment] 2024-03-17 01:57
@rVlad93 The blue play button works fine for me. Try clearing your browser cache

**Comment by rVlad93** [comment] 2024-03-17 02:30
> Ok will close this and I will look at the blue play button

My fault. Player got disconnected and there another one available.
