### ISSUE TITLE
Overlay play buttons not displaying on larger touch devices

### ISSUE THREAD

**Issue by justinwoodland** [music-assistant/hass-music-assistant#3043] opened 2024-10-17 21:47 UTC
### What version of Music Assistant has the issue?

2.2.9

### What version of the Home Assistant Integration have you got installed?

2024.10.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

On a small screen there are overlay touch controls to play a songs/artists/playlists/etc. These are disabled on devices/browsers over a certain width unless hovered over with a mouse.

This is an issue with larger touch devices (tablets, home-assistant wall kiosk) as it requires more clicks when a device does not have a mouse.

Can the play overlay be changed to show based on whether it is a touch device instead of based on browser width? Or a setting to always show overlay buttons?

### How to reproduce

Load music assistant in browser on a computer.
Reduce the browser width down to a 'phone' width. Play overlay buttons appear.

Increase the browser width up to a tablet/computer width. Play buttons disappear unless hovered.

### Music Providers

N/A

### Player Providers

N/A

### What version of Home Assistant Core are your running

2024.10.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Alternative

**Comment by marcelveldt** [comment] 2024-10-22 06:11
That the buttons display on hover is a bug. That they do not display when on mobile devices is by design.
They are available in the fullscreen player.

**Comment by OzGav** [comment] 2024-10-23 00:58
This is fixed in beta 34

**Closed by OzGav** 2024-10-23 00:58 UTC
Labels: enhancement, frontend
