### ISSUE TITLE
[BUG]  Error - Chromecast 192.168.1.197:32071 is connecting

### ISSUE THREAD

**Issue by jazzyisj** [music-assistant/hass-music-assistant#2048] opened 2024-03-22 17:54 UTC
### What version of Music Assistant has the issue?

2.0.0.b118

### What version of the Home Assistant Integration have you got installed?

2024.3.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Occasionally when starting play on Google Cast speakers this error occurs in the HA log and MASS play does not start.  Seems to happen more with speaker groups than individual speakers.

Moreso than the actual error (I understand cast speakers can be kooky), the issue is that I most often I call mass.play_media from a hass script and when the mass.play_media call fails with this error, the `continue_on_error` parameter in the service call is not respected and the rest of the script does not run.

Calling the same script again with the same parameters no other changes is usually successful with no errors.

```
    - service: mass.play_media
      target:
        entity_id: media_player.inside_speakers
      data:
        media_id: "All Out 70s"
        media_type: playlist
        enqueue: replace
      continue_on_error: true #MASS script does not continue if mass fails
```

This is the error from the HA log.
```
2024-03-22 13:18:22.165 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281470730760384] Chromecast 192.168.1.197:32071 is connecting...
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 611, in _service_handler
    response = await self._async_start_run(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 569, in _async_start_run
    script_result = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 600, in _async_run
    return await self.script.async_run(script_vars, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1600, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1140, in async_run
    await super().async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 435, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 487, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 535, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 485, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 723, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mass/media_player.py", line 517, in _async_play_media_advanced
    await self.mass.players.play_media(
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/players.py", line 293, in play_media
    await self.client.send_command(
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/client.py", line 178, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.MusicAssistantError: Chromecast 192.168.1.197:32071 is connecting...
```

### How to reproduce

Happens intermittently when calling mass.play_media on Google Cast speakers from a script.

### Music Providers

Youtube, Spotify, Tune-In

### Player Providers

Chromecast

### Full log output

[ha-log.txt](https://github.com/music-assistant/hass-music-assistant/files/14726603/ha-log.txt)

### Additional information

This has been an issue for a while, it is not something that has popped up with any recent updates.

### What version of Home Assistant Core are your running

2024.3.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment] 2024-03-22 20:34
This sounds like a HA issue not MA. It also sounds like you have a network problem if the player won’t connect. Lastly I assume you haven’t shown the complete script?

**Comment by marcelveldt** [comment] 2024-03-23 09:14
Can you please attach the full log file from the Music Assistant server itself as well ?
In the MA interface, navigate to settings, Core tab and press download logfile. Drag and drop the file here.

**Comment by jazzyisj** [comment] 2024-03-23 14:57
@OzGav 

- Possibly HA?  But I've never had an issue with `continue_on_error` failing anywhere else and I use it quite a bit in my scripts and automations.

- I've not any other issues network wise with any cast speakers with HA or otherwise.  I have several in several flavours and use them extensively for media and tts.  No VLANS, lots of bandwidth, strong WIFI connections.  

- I don't think the script itself is the issue. here   I can also reproduce the error calling mass.play_media directly from Dev Tools - Services.  I've also commented out most of the script when testing the error.   I've also recently had the same result (`continue_on_error` not respected ) with another mass error (music_assistant.common.models.errors.MusicAssistantError: Execution of stop timed out after 10.0 s).  

That being said, here is the full script.
https://github.com/jazzyisj/home-assistant-config/blob/master/scripts/media/media_play.yaml

I can add that while this error does happen seemingly randomly at various times even on single cast speakers, I can usually reproduce it when playing mass media on one speaker group and then calling `mass.play_media` on another speaker group.  I often have to do this several times using various groups to eventually get the error as it often works as expected with no error.

Also, if I turn the new speaker group ON before calling mass.play_media (in script or dev tools) it seems to reduce the probability of getting this error.   I discovered this because in my media play script I turn the player volumes to 0 and turn them on before calling mass.play_media to avoid the awful "Google Bloops" that sound when turning a cast speaker on with the volume turned up.  I then set the volume to the desired level after the player(s) are all turned on.  (see media_play.yaml above).

https://github.com/jazzyisj/home-assistant-config/blob/master/scripts/media/media_player/turn_media_player_on.yaml

Again, while this communication error is slightly bothersome and may not be fixable, I so think the issue with continue_on_error not being respected and the rest of the script not running is the bigger problem here.

@marcelveldt 

- Is the file under **Full log output** here not what you are looking for?  If it's not I'm seriously misunderstanding something. It does open in a browser window instead of downloading and I'm saving it from there.  Is that the issue?  Here's another attempt.

[mass log.txt](https://github.com/music-assistant/hass-music-assistant/files/14731986/mass.log.txt)

**Comment by marcelveldt** [comment] 2024-03-23 22:21
Yes that is the correct log and as you can see there clearly is something wrong communicating to one or more of your cast devices, you see almost all commands failing somehow.

What cast devices do you have exactly ? And what sort of commands are you sending with automations/script ?
Some cast devices get unstable when there's too many commands being sent. 
Do you have these devices also setup in the HA cast integration or only MA (as that adds up to the number of connections)

**Comment by jazzyisj** [comment] 2024-03-24 09:32
- 2 Nest Hubs
- 3 Google/Nest Minis
- 1 Google Home
- 3 Chromecast devices.  

Yes, they are set up in HA as well as MA.

> And what sort of commands are you sending with automations/script ?

Power, pause, and volume commands - the script is linked above, but as I mentioned I have discovered I can reproduce the error calling mass.play_media directly on it's own in dev_tools playing a playlist on one cast group and then calling it again in dev_tools with another cast group,.  I believe the error log above was produced after causing the error in dev-tools rather than my script.

So I don't think that would be the issue causing the MA error and definitely not what is causing MA to exit the script entirely and not continue the script execution after the error, behaviour which I've now seen with 2 different MA errors.

**Comment by marcelveldt** [comment] 2024-03-24 18:00
Does it perhaps only happen with cast groups ?

**Comment by jazzyisj** [comment] 2024-03-24 19:46
It might actually be just with cast groups.  I just did some testing starting media on all of my single cast devices over and over and could not reproduce the error.   I got the error on my second try with groups.  I will watch and make a note here if I do happen to notice it occur with just a single player., but  I'm usually playing media using groups.

Side note:  6 simultaneous streams pegs the processor, memory, and swap at 100% :-)

**Comment by marcelveldt** [comment] 2024-03-26 09:54
Found the issue, should be fixed in beta 124

**Comment by marcelveldt** [comment] 2024-03-26 09:55
> Side note:  6 simultaneous streams pegs the processor, memory, and swap at 100% :-)

What hardware are you running MA on? I guess 6 streams a is a bit too much for a pi or likewise hardware

**Comment by jazzyisj** [comment] 2024-03-26 14:49
HA Blue.  Wasn't a complaint or unexpected, just an observation.  I've never seen all 3 at 100% before.  I'm also running Frigate on a couple of cams as well so I'm pushing my Blue pretty hard.  Looking to upgrade to something with a little more juice in the near future.

**Comment by marcelveldt** [comment] 2024-03-27 12:54
Did you check if this was fixed in b125 ?

**Comment by jazzyisj** [comment] 2024-03-28 09:27
Doesn't look like it.   I've also updated to the new HA beta (2024.4.0b0).  There has been some improvements to the trace viewer so you can see the error in there now, which is pretty cool!   You can also see where the script does not continue after the error as well.

<img width="403" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/44064559/c8097d82-3a06-47ea-ab5e-619330d913cc">

<img width="596" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/44064559/70922df4-c969-4a5c-8b14-78efe3449eff">

**Comment by marcelveldt** [comment] 2024-03-28 22:09
Please reproduce the issue with pure standalone service calls to rule out issue sin your script.
Also make sure that you're not multiple cast players at the exact same time, or doing multiple calls to the same player at the same time.

Is it still raising that "chromecast is connecting" error ?

**Comment by marcelveldt** [comment] 2024-03-28 22:10
BTW: your error description is wrong here. Continue on error is a HA feature to try to continue to the next call in the list. It has nothing to do with MA. It cant continue with the next call because the whole thing exploded.

**Comment by jazzyisj** [comment] 2024-03-29 00:56
I tried to acknowledge that I was referencing 2 issues at once here.  Probably a bad idea.  Anyway, I guess I wondered if you should be able to catch whatever error is happening here and return to HA gracefully to allow the continue_on_error to take effect.  Python isn't my bag so I'm not sure.  But I've never not had it work since it came into play except with MA.  I believe MA may be the only integration where I'm calling a non-HA service that has failed so perhaps that is the difference?

As for the chromecast error, my groups definitely all have overlapping players in the groups. I tried calling with dev-tools using the same parameters as above just switching out the group entity_id and got the error right away (first call successful, second call with different group but with overlapping players produced the error).  I showed the call using my script to show the continue_on_error issue as well.  This is definitely happening with direct calls from dev-tools.  These are the parameters I've been using for these tests in dev-tools (with various group entity id's).

```
service: mass.play_media
target:
  entity_id: media_player.inside_speakers_2
data:
  media_id: "All Out 70s"
  media_type: playlist
  enqueue: replace
```

I've just tried again, and the error happened on first call.  The group and all it's members definitely turned on, google bloops and all.  The state was definitely off before the mass.play_media call and this is the group state after the error.
<img width="1240" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/44064559/1149982a-0e09-4e9e-aa1e-59ec7b168e41">

I grabbed this MA log right after the error.

[mass log.txt](https://github.com/music-assistant/hass-music-assistant/files/14797302/mass.log.txt)

I again tried the exact same service call in dev-tools right after I saved the log above and everything worked as expected.  Tried it a second and third time with different groups (overlapping players) and all good in the the hood.  Then tried it a few more times in rapid succession, calling it again and again with different groups before the stream even started playing and there was no error.   I then tried it a couple more times after a few minutes for shits and giggles and randomly got the error again.

**Comment by jazzyisj** [comment] 2024-03-29 01:00
I'm was on b127 for the tests above.

**Comment by OzGav** [comment] 2024-03-29 03:49
Please try b128

**Comment by marcelveldt** [comment] 2024-03-29 10:37
Overlapping players in the same group??!!! That will NEVER work!
Again, "continue on error" applies to HA services. If something crashes, a script will never ever be able to continue.

Its the same as riding a bike and get back up when you fall. If the bike breaks entirely you wont be able to get back up and continue the ride.

You should do tests by sending a command to ONE SINGLE player or group player at once.

If you want announcements send to multiple speakers at once, I suggest you either direct the individual players OR create a extra cast group with those players in it. Targeting multiple cast speakers with overlapping groups is just a mess.

**Comment by marcelveldt** [comment] 2024-03-30 09:55
When you test in the dev tools, is that addressing a single player, a single cast group or a few single players at once ?

**Comment by jazzyisj** [comment] 2024-03-30 16:38
Always a single cast group or a single media player.  Groups do seem to cause the error more often than a single player.
I don't think I've ever tried a few single players at once!  I have a cast group for any possible combination of speakers I might use.

**Comment by jazzyisj** [comment] 2024-04-11 01:57
On 2.0.0b134 - Still getting it , but anecdotally - less frequently.  I thought you had it licked at first, it took a few tries going from group to group to get it.  Error is a little bit different now though.

[mass log.txt](https://github.com/music-assistant/hass-music-assistant/files/14940228/mass.log.txt)

[ha log.txt](https://github.com/music-assistant/hass-music-assistant/files/14940234/ha.log.txt)

I also noticed I can't get a single cast player to play now.  Definitely a new issue.  I've rebooted HA and the restarted the addon and rechecked.  Not sure if related or totally different issue.  Really weird because groups are playing fine.  This is the error when I try play on a single cast player.  I can open a separate issue if required.

`2024-04-10 21:54:45.514 ERROR (Thread-22) [homeassistant.components.cast.media_player] Failed to cast media http://192.168.1.100:8097/single/5f5eb57b-a1b2-eb39-1836-e829b7684df4/d614a8990a0543b09e0d6e1fb3c9cf29.flac?ts=1712800481. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
`

**Comment by OzGav** [comment] 2024-04-11 02:19
That seems to be a networking problem. Review the troubleshooting steps in the docs

**Comment by OzGav** [comment] 2024-04-11 02:28
Also note there is a chromecast problem with the latest beta.

**Comment by OzGav** [comment] 2024-04-13 02:35
beta136 is released which fixed the chromecast problem. We will close this soon unless there is further follow up.

**Closed** 2024-04-13 12:32 UTC
Labels: More info, triage
