### ISSUE TITLE
Multiple duplicate entries in Browse(r)

### ISSUE THREAD

**Issue by jonwaland** [music-assistant/hass-music-assistant#2296] opened 2024-05-15 05:56 UTC
### What version of Music Assistant has the issue?

2.0.3

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When "browse"ing, I get (currently) 203 entries - multiple instances of Music Assistant, Spotify, and Radio Browser.
Then when entering Music Assistant, I get 153 entries - ..., Tracks, Playlists, Radio etc.

![1](https://github.com/music-assistant/hass-music-assistant/assets/33437424/8b54e920-51f3-42a9-aa19-18863f24e86f)
![2](https://github.com/music-assistant/hass-music-assistant/assets/33437424/5760c8cb-230e-40a0-8fb2-642979c2857c)

### How to reproduce

??

### Music Providers

NA.,

(Spotify, RadioBrowser)

### Player Providers

Chromecast

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15316815/log.txt)

### Additional information

na

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Linux

**Comment by erkr** [comment] 2024-05-15 07:21
Sorry you have this issue, issue is a duplicate of https://github.com/music-assistant/hass-music-assistant/issues/2270.
I close this one and please check if it is fixed for you version v2.0.4 (report back on other issue please)

**Closed** 2024-05-15 07:21 UTC
Labels: triage

**Comment by jonwaland** [comment] 2024-05-16 01:30
apologies - I did see #2270 but didn't' realize it was the same issue.
