### ISSUE TITLE
Track progress isn't in sync when using Player Groups (Slimproto)

### ISSUE THREAD

**Issue by Alundran** [music-assistant/hass-music-assistant#3063] opened 2024-10-21 20:24 UTC
### What version of Music Assistant has the issue?

2.3.0b33

### What version of the Home Assistant Integration have you got installed?

2024.10.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Using the newest beta with the refactored player groups, when playing a song to a group that contains my Slimproto devices, the track progress isn't in sync. You need to pause and play the song for the track progress to correct itself. In some cases the track progress is way past the duration of the song, almost as if the counter continues even when music is paused / off.

### How to reproduce

1. Have a Player Group of Slimproto devices (I do not have any other devices types to try to see if this is also problematic there)
2. Play a song
3. Play the next track
4. Observe the progress continues to count instead of resetting
5. Pause the song, see the track progress corrects itself

https://github.com/user-attachments/assets/ac3641d1-ab3a-4308-9b73-469479785539

### Music Providers

Spotify (don't use any others)

### Player Providers

Player Group - Slimproto Devices (don't use any other types)

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17466582/music-assistant.log)

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by Alundran** [comment] 2024-10-21 20:29
Was testing the theory that the track progress continues even if the song is paused and it seems possible. I had a song paused, waited a bit, pressed play and MA thinks the next track is playing but it's the same song that was paused (playing from the position it was paused at).

**Comment by OzGav** [comment] 2024-10-21 23:02
Is this the same as #2852

**Comment by Alundran** [comment] 2024-10-22 08:52
It's similar but not the same, the previous issue was that there was no progress tracking at all. It does now sort of work, just the wrong progress being tracked.

**Comment by OzGav** [comment] 2024-10-22 14:40
Unfortunately I can't seem to get your video to play and I have just joined two picoreplayers together using the manual sync method and it is working fine. How are you grouping the players?

**Comment by Alundran** [comment] 2024-10-22 15:03
These were existing grouped players. I've just tried creating a new group player (Settings -> Players -> Add Group Player -> Slimproto as Group Type) with two picore players (that's what I use too) and it's the same issue. That being said, I've done what I think you're doing which is ticking the box next to another player when playing on one player and that seems to work fine - the progress is in sync so it seems when using an actual Group Player that's where the sync issue comes in

**Comment by OzGav** [comment] 2024-10-23 02:04
Yes I can reproduce this. It will get looked at soon

**Comment by OzGav** [comment] 2024-10-24 14:54
Please check this with 2.3.0rc2

**Comment by marcelveldt** [comment] 2024-10-24 18:49
can you retry with rc3 ?

**Comment by OzGav** [comment] 2024-10-26 10:28
We will close this soon due to no follow up

**Comment by Alundran** [comment] 2024-10-26 10:33
Sorry for the delay, I think this is good to close as it works on rc3 much better.

**Closed** 2024-10-26 10:41 UTC
Labels: bug, More info, Slimproto, Groups
