### ISSUE TITLE
HA BETA - 2022.7.0b0 - Deprecation Warnings

### ISSUE THREAD

**Issue by jazzyisj** [music-assistant/hass-music-assistant#556] opened 2022-06-29 23:50 UTC
### What version of Music Assistant has the issue?

2022.6.9

### The problem

Warnings in HA log with v2022.7.0b0.

### How to reproduce

Install HA 2022.7.0b0

### Relevant log output

```
2022-06-29 19:45:06 WARNING (MainThread) [homeassistant.components.number] custom_components.mass.number is setting deprecated attributes on an instance of NumberEntityDescription, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
2022-06-29 19:45:06 WARNING (MainThread) [homeassistant.components.number] custom_components.mass.number::CrossfadeDurationEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
2022-06-29 19:45:06 WARNING (MainThread) [homeassistant.components.number] custom_components.mass.number::VolumeNormalizationTargetEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
```

### What version of Home Assistant Core are your running

2022.7.0b0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by erkr** [comment] 2022-06-30 10:29
Thanks for informing us! This one was reported earlier: Duplicate of #387

**Comment by marcelveldt** [comment] 2022-06-30 15:31
duplicate indeed. I will provide beta 2022.7 later today or tomorrow with a fix for this

**Closed by marcelveldt** 2022-06-30 15:31 UTC
Labels: duplicate, deprecated
