### ISSUE TITLE
Playlist "500 Random Tracks (from library)" is not random

### ISSUE THREAD

**Issue by mikeb9x** [music-assistant/hass-music-assistant#2286] opened 2024-05-14 11:16 UTC
### What version of Music Assistant has the issue?

2.0.3

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Playlist "500 Random Tracks (from library)" is not random, it contains the first 500 tracks from the library sorted by "Date added". Confirmed on 2 instances of HA+MA.

### How to reproduce

Add tracks to library. Check the playlist "500 Random Tracks (from library)".

### Music Providers

Tidal

### Player Providers

-

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by erkr** [comment] 2024-05-14 16:33
Yep, can confirm it is not random. For me it is grouped by albums, so by 'date added' make sense

**Comment by marcelveldt** [comment] 2024-05-14 19:17
Confirmed bug - fixed in the next patch release.

**Comment by OzGav** [comment] 2024-06-07 14:24
This is fixed in 2.1.0b2

**Comment by OzGav** [comment] 2024-07-22 12:29
Yes something has regressed here. Will look into it

**Comment by ulipo** [comment] 2024-08-03 16:07
MA 2.2.0b3 here, 500 random tracks playlist items are all greyed out and none is playable.
Refreshing the playlist or even removing it from config and adding back doesn't change the song listed, it looks like the playlist is "static".
I use Jellyfin provider but at the beginning I was using local files provider (now removed), maybe the playlist is stuck with that old provider.

**Comment by ray154856235** [comment] 2024-08-06 05:22
I have a quessistion Playlist "500 Random Tracks (from library)" is not daily random,it will not change everyday, if that is a bug?

> Yes something has regressed here. Will look into it

**Comment by OzGav** [comment] 2024-08-13 12:08
We will update here when there is something to say

**Comment by iw1gfv** [comment] 2024-08-15 15:43
> It updates every time you press refresh button

It's possibe to refresh with homeassistant automation?

**Comment by OzGav** [comment] 2024-08-15 21:33
> It's possibe to refresh with homeassistant automation?

Not at the moment

**Comment by ray154856235** [comment] 2024-08-16 10:33
maybe add a daily random palylist is a good jod.

**Comment by OzGav** [comment] 2024-08-21 04:38
This has been fixed in 2.2.0RC1

**Closed by OzGav** 2024-08-21 04:38 UTC
Labels: bug
