### ISSUE TITLE
Kodi output not working?

### ISSUE THREAD

**Issue by OliPassey** [music-assistant/hass-music-assistant#450] opened 2022-06-19 11:12 UTC
First off, thanks for this app - amazing work!

On first try i am unable to get any stream going, i've auth'd with spotify and some local files - both are sent to Kodi but neither play.

Kodi log shows:
2022-06-19 12:07:19.603 T:10880   ERROR <general>: CCurlFile::FillBuffer - Failed: Transferred a partial file(18)
2022-06-19 12:07:19.604 T:10880    INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder flac
2022-06-19 12:07:19.628 T:10880   ERROR <general>: CCurlFile::FillBuffer - Failed: Transferred a partial file(18)
2022-06-19 12:07:19.630 T:10880    INFO <general>: PAPlayer::QueueNextFileEx - Error reading samples
2022-06-19 12:07:19.906 T:11452    INFO <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10

Using the music browser / explorer within HA i am able to get Kodi to play the same local file no problem, from the same location. (/media) in homeassistant.

2022-06-19 12:10:34.714 T:11452    INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder mp3float
2022-06-19 12:10:34.826 T:11452    INFO <general>: AudioDecoder: File is queued
2022-06-19 12:10:34.838 T:11452    INFO <general>: PAPlayer::PrepareStream - Ready
2022-06-19 12:10:34.839 T:9976     INFO <general>: CActiveAESink::OpenSink - initialize sink
2022-06-19 12:10:37.552 T:10344    INFO <general>: PAPlayer::ProcessStream - Stream Finished
2022-06-19 12:10:38.114 T:22844    INFO <general>: CDVDVideoCodecFFmpeg::Open() Using codec: HEVC (High Efficiency Video Coding)

Any ideas? Can i provide logs from HA somewhere to assist in troubleshooting?

**Comment by marcelveldt** [comment] 2022-06-19 11:46
duplicate of #358

**Closed** 2022-06-19 11:46 UTC

**Comment by erkr** [comment] 2022-06-19 11:47
If there are related logs, you find them in the normal home assistant log. Please add related errors if you see them
