### ISSUE TITLE
Apple Music: Not all albums of an artist show up in the artist overview 

### ISSUE THREAD

**Issue by togart80** [music-assistant/hass-music-assistant#2832] opened 2024-08-29 09:20 UTC
### What version of Music Assistant has the issue?

2.2.2

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When searching in MA, the artist (e.g. Benjamin Blümchen) is found both on the NAS and in Apple Music. From the NAS, all available albums (6 albums) are displayed in the search result, but from Apple Music only 25 albums (instead of the 170 actually available).
At the moment I'm using the provider link (in this example: (https://music.apple.com/de/artist/benjamin-bl%C3%BCmchen/215716521/see-all?section=full-albums) from the MA search, making a note of the desired album title there and then searching for this artist and album in MA.

### How to reproduce

Every search in MA for Benjamin Blümchen over the last three MA versions always leads to the same limited result on Apple Music. However, if you search for an album by this artist that is not listed in the MA search results, it will still be found and can be played. 

### Music Providers

Apple Music

### Player Providers

The albums found can be played via all player providers.

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16796650/music-assistant.log)

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment] 2024-08-29 09:24
Results are limited to a maximum of 50 items in any one category. So if there are 25 other results then this is normal https://music-assistant.io/ui/?h=limited#global-search

**Comment by marcelveldt** [comment] 2024-08-29 09:27
Are we talking about search or the albums listing on the artist page ? That makes a whole lot of difference.
The global search is indeed limited but the artist details page should list all albums

**Comment by togart80** [comment] 2024-08-29 09:49
Hi,

I have the limited search result both in the global search (but OzGav has just pointed out the 50 limit to me) and on the artist page. Here are two screenshots.

Best regards

Thomas
________________________________
Von: Marcel van der Veldt ***@***.***>
Gesendet: Donnerstag, 29. August 2024 11:27
An: music-assistant/hass-music-assistant ***@***.***>
Cc: togart80 ***@***.***>; Author ***@***.***>
Betreff: Re: [music-assistant/hass-music-assistant] Apple Music: Not all albums of an artist from Apple Music are displayed in the search result of Music Assistant. (Issue #2832)


Are we talking about search or the albums listing on the artist page ? That makes a whole lot of difference.
The global search is indeed limited but the artist details page should list all albums

**Comment by togart80** [comment] 2024-08-29 09:52
![Screenshot 2024-08-29 113942](https://github.com/user-attachments/assets/8ade7143-fcff-48ce-82ce-be9ad49b77ee)
![Screenshot 2024-08-29 114107](https://github.com/user-attachments/assets/f2e3766e-8fa7-4705-87ea-f813c93c7306)

**Comment by OzGav** [comment] 2024-08-29 09:57
Is there any change on the artist page if you actually scroll to the bottom of the view?

**Comment by togart80** [comment] 2024-08-29 10:02
No, the result ends after 31 Albums. Then the section with the titles starts.

![Screenshot 2024-08-29 120028](https://github.com/user-attachments/assets/bcf1f595-7102-45e1-819b-9e1236cbdcf1)

**Comment by OzGav** [comment] 2024-08-29 10:04
@MarvinSchenkel any idea why the provider is not returning all results here?

**Comment by OzGav** [comment] 2024-08-29 10:05
@togart80 just confirming you can search for an album which is not listed above in the global search and find it?

**Comment by togart80** [comment] 2024-08-29 10:19
Yes, that is correct. I'm looking for an album on Apple Music that MA can't find or doesn't list in the search. (as an example in this case, search in MA for: Benjamin Blümchen Folge 81: Das Geheimnis der Tempelkatze)

![Screenshot 2024-08-29 121937](https://github.com/user-attachments/assets/6960944b-91ee-484e-b22e-70c8ca42940e)

**Comment by MarvinSchenkel** [comment] 2024-08-29 12:24
Like mentioned above, the search limits are "by design". However, it is weird that only 31 albums show up on the artist page. Had a look in the apple music app and I can definitely see more than 31 there when I browse the artist. Will have a look when I'm back from holiday why this is happening.

**Comment by OzGav** [comment] 2024-09-09 03:04
Please check if this has been fixed in the next beta

**Comment by OzGav** [comment] 2024-09-12 00:55
This will be closed soon assuming fixed

**Closed** 2024-09-14 10:12 UTC
Labels: bug, More info, Fix to be Confirmed, Apple Music
