### ISSUE TITLE
Soundcloud music provider causes high cpu load

### ISSUE THREAD

**Issue by firefrei** [music-assistant/hass-music-assistant#2258] opened 2024-05-12 09:16 UTC
### What version of Music Assistant has the issue?

2.0.1

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When Soundcloud music provider is enabled, CPU load increases to and stays at 70-100% after some minutes. Even after hours, the load has not automatically decreased anymore. When disabling the music provider, the CPU load immediately drops down to 0-1%.
The behavior is reproducible.
I am using the docker image tagged with "stable". There is no message indicating an issue in the docker logs.

### How to reproduce

1. Check CPU load (0~1%)
2. Enable Soudcloud music provider
3. Wait couple of minutes (maybe open Titles pages or others to reduce waiting time)
4. Check CPU load (70-100%)
5. Disable Soudcloud music provider
6. Check CPU load (0~1%)

### Music Providers

Soundcloud

### Player Providers

-

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by firefrei** [comment] 2024-05-12 09:30
<img width="974" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/12660103/203f945d-110a-4013-9c4f-6aa7687d2299">
`htop` executed within the container.

No music is playing.

**Comment by marcelveldt** [comment] 2024-05-12 09:30
Sounds like the soundcloud provider is doing some sort of infinite loop, consuming all/most cpu cycles.

**Comment by firefrei** [comment] 2024-05-12 09:38
Looks like it. I just also noticed constantly high disk write rates when this happens. Probably a hint where the problem could be located.

<img width="975" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/12660103/865caf69-aa90-48f3-8bc0-ece78c50b3c8">

**Comment by OzGav** [comment] 2024-05-12 12:21
@gieljnssns

**Comment by marcelveldt** [comment] 2024-05-14 19:25
I think this was a side effect of something else and had not particularly had anything to do with soundcloud. It would just happen with large playlists.

Please test again with the next patch release (2.0.4) - If it still happens we need to further investigate your setup

**Comment by firefrei** [comment] 2024-05-15 05:59
I pulled the latest stable docker release and verified its version 2.0.4 on the server info page.
Unfortunately, the problem still exists. Also the high write rates are still there.

**Comment by firefrei** [comment] 2024-05-22 13:47
Is there any other information that I can provide?

**Comment by OzGav** [comment] 2024-05-23 02:06
Not for now. This will be looked at in due course. If you discover anything more please add it here

**Comment by marcelveldt** [comment] 2024-05-24 20:38
I am not able to reproduce any of this. Please test if disabling SoundCloud provider fixes it so we can at least confirm wether this is a SoundCloud specific issue or not

**Comment by OzGav** [comment] 2024-05-27 03:43
@firefrei please confirm whether this is a Soundcloud specific issue as per Marcel’s request above or we will have to close this.

**Comment by firefrei** [comment] 2024-05-27 07:05
I did some additional testing, sorry for the late reply. However, I couldn't fully isolate the issue.
My default setup: Three additional music providers enabled (RadioBrowser, Spotify, Soundcloud + MASS).

My findings:
- All the above mentioned is still true. In my default setup, I can easily reproduce the high cpu load and high write rates.
- When the issue occurs, I can disable ANY of the music providers and the issue is gone.
- I couldn't reproduce it with only Soundcloud enabled, nor Soundcloud + another (2+MASS).
- With disabled Soundcloud I had it running now for days/weeks without the issue occurring.

So, I cannot finally validate that the root cause is the Soundcloud music provider. The provider can be the cause, or the trigger. Or it is related to the plain number of music providers enabled that causes the issue.

If there is anything else that I can test, please let me know.

**Comment by OzGav** [comment] 2024-05-27 12:04
Thanks for the good info. This will get looked at again when workload permits.

**Comment by OzGav** [comment] 2024-06-11 23:05
@firefrei we will close this soon assuming fixed

**Comment by firefrei** [comment] 2024-06-12 07:05
I have updated now to 2.1.0b4 and am going to verify, whether the issue occurs again (first I need to figure out why the snapcast integration isn‘t working probably anymore after the upgrade).
I‘ll keep you updated in this issue.

**Comment by firefrei** [comment] 2024-06-12 20:29
Unfortunately, the persistently high load and write rates are back. I made some further investigations and used sysdig to identify files with high i/o:
```bash
sudo sysdig -pc -c topfiles_bytes container.name=mass
```

The screenshot shows htop (upper) and sysdig (lower) outputs. Adding the rates of both files in the sysdig output could match the rate reported by htop. 
I also manually re-checked using `stat`: The file `library.db-journal` is created and removed many times per second. `library.db` exists persistently, however, the Access/Modify/Change dates are continuously and very frequently (<1s) updated.
The size of the files is not increasing, so their content just seems to be exchanged/updated.

Music is not actively played. The waiting queue has been cleared before the test.
![image](https://github.com/music-assistant/hass-music-assistant/assets/12660103/260ec72d-84ce-4b57-a3d0-2f1ee4519d90)

**Comment by marcelveldt** [comment] 2024-06-15 16:25
We fixed a potential race condition in the MA core yesterday that could lead to an infinite loop. While not directly related to Soundcloud this could have been triggered when trying to grab a soundcloud performer/artist now that I'm reading the code a couple of times. 

So, question is if you can test this again on version 2.0.7 (or beta version 2.1.0b6)

**Comment by firefrei** [comment] 2024-06-16 09:40
Okay, I am going to test it with 2.1.0b6 now. I'll let you know when it occurs again!

**Comment by firefrei** [comment] 2024-06-19 09:40
Until now it looks good 👍🏻 
I‘ll check again when the 2.1.0 stable release is published.

**Comment by OzGav** [comment] 2024-06-19 09:53
We can reopen if it reoccurs

**Closed by OzGav** 2024-06-19 09:53 UTC
Labels: bug, Fix to be Confirmed, Soundcloud
