### ISSUE TITLE
Images for mediaitems HTTP instead of HTTPS - causing browser warnings

### ISSUE THREAD

**Issue by asjmcguire** [music-assistant/hass-music-assistant#402] opened 2022-06-18 00:37 UTC
Home Assistant is installed as a PWA. It is accessed over HTTPS.
Because the logos for TuneIn radio are being served over HTTP, Chrome pops up the not secure banner.

![2022-06-18](https://user-images.githubusercontent.com/45770738/174415274-5f027d08-6ff6-4f48-a509-8e3c4a8b908a.png)

![2022-06-18 (1)](https://user-images.githubusercontent.com/45770738/174415289-f08480ba-f765-484a-ba3b-3366d53f20c2.png)

The channel logo definitely exists on the https URL https://cdn-profiles.tunein.com/s6954/images/logoq.jpg - so this is hopefully a simple fix.

**Comment by asjmcguire** [comment] 2022-06-18 01:03
Playing something on Spotify caused the same thing to happen - and a quick check of the Network tab showed it loaded more http content from fanart: http://assets.fanart.tv/fanart/music/5b9890b9-a2e8-4768-ad70-9f28bb81fc00/artistbackground/avidan-asaf-51052b9b36527.jpg again this is available over https - https://assets.fanart.tv/fanart/music/5b9890b9-a2e8-4768-ad70-9f28bb81fc00/artistbackground/avidan-asaf-51052b9b36527.jpg

**Comment by marcelveldt** [comment] 2022-06-18 11:21
I consider this a bug as we do not want these security errors popping up. It did not yet catch my attention as my development machine runs HA (and MA) on localhost. I will fix this in the frontend app itself.

**Comment by marcelveldt** [comment] 2022-06-18 12:34
Fixed in 2022.6.2

**Comment by asjmcguire** [comment] 2022-06-18 13:22
![2022-06-18 (2)](https://user-images.githubusercontent.com/45770738/174439538-d854be88-3853-49a5-882b-8cc4f6d1654c.png)

Fanart is still being served over http.

**Comment by marcelveldt** [comment] 2022-06-18 13:24
OK, thanks, I must have forgotten a place then. Did you force refresh the browser as I patched this in the Vue frontend app.
I will have another look at this tonight/tomorrow. Now family duties :-)

**Comment by asjmcguire** [comment] 2022-06-18 13:28
Yup, I did a CTRL + SHIFT + R on the PWA window, the usual force I force a full reload. It's not the end of the world, and will obviously be fully fixed with a built in image proxy (I see in the code that is temporarily disabled). Sadly Python is not my language, (I really need to sit down and learn it one day) - or I would have been able to help fix this.

**Comment by asjmcguire** [comment] 2022-06-18 14:20
OK - when you get a moment:
```
        url = f"http://webservice.fanart.tv/v3/{endpoint}"
```
Line 85 of
music-assistant-lib/music_assistant/controllers/metadata/fanarttv.py

**Comment by marcelveldt** [comment] 2022-06-18 16:17
That is the api connection and not the image URL itself. Besides that I don't want to alter the source material itself and instead just let the frontend handle it. Use https if that is available, otherwise redirect to the image proxy.

**Comment by marcelveldt** [comment] 2022-06-19 23:00
Should be fixed in 2022.6.3 (I couldn't reproduce anymore) - If not please reopen. Thanks!

**Closed by marcelveldt** 2022-06-19 23:00 UTC
Labels: bug
