### ISSUE TITLE
Spotify/Sonos skipping tracks

### ISSUE THREAD

**Issue by jstebbins** [music-assistant/hass-music-assistant#2321] opened 2024-05-17 17:15 UTC
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Sometimes, when starting playback of the next track in a spotify playlist, the next track only plays for about 1 second then skips to the next track. Sometimes this will happen several times consecutively. Sometimes it will start the next track correctly several times consecutively.

I was previously using the HACS Sonos Card and did not experience this problem. So it's something particular to MA.

### How to reproduce

Start playback of a spotify playlist over Sonos (I'm using sonos amp and and port devices). Wait for it to eventually skip a track.

### Music Providers

Sonos

### Player Providers

Spotify

### Full log output

2024-05-15 08:10:04.665 INFO (MainThread) [music_assistant] Starting Music Assistant Server (59c8f5ec2fd5409286340bede8ed8b93) version 2.0.4 - HA add-on: True - Safe mode: False
2024-05-15 08:10:04.691 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-05-15 08:10:04.787 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-05-15 08:10:05.591 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.0.1 with libsoxr support
2024-05-15 08:10:05.591 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.4.138:8097
2024-05-15 08:10:05.607 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-05-15 08:10:06.211 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-05-15 08:10:06.212 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-05-15 08:10:06.212 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-05-15 08:10:06.212 INFO (MainThread) [music_assistant] Loaded music provider Music Assistant
2024-05-15 08:10:06.340 INFO (MainThread) [music_assistant] Loaded player provider SONOS
2024-05-15 08:10:06.536 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-15 08:10:06.679 INFO (MainThread) [music_assistant.players] Player registered: RINCON_347E5C0707B201400/Office
2024-05-15 08:10:06.684 WARNING (MainThread) [soco.events_asyncio] Could not bind to 192.168.4.138:1400: [Errno 98] Address already in use
2024-05-15 08:10:06.789 INFO (MainThread) [music_assistant.players] Player registered: RINCON_C438755B67FF01400/Office
2024-05-15 08:10:06.917 INFO (MainThread) [music_assistant.players] Player registered: RINCON_347E5C0708F901400/Bunk Room
2024-05-15 08:10:07.038 INFO (MainThread) [music_assistant.players] Player registered: RINCON_C438755B676301400/Sherri's Studio
2024-05-15 08:10:07.160 INFO (MainThread) [music_assistant.players] Player registered: RINCON_38420B83677601400/Common Areas
2024-05-15 08:10:07.872 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-15 08:10:07.873 INFO (MainThread) [music_assistant] Loaded music provider Spotify
2024-05-15 08:10:19.813 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-15 08:36:07.566 WARNING (MainThread) [music_assistant.providers.sonos] No recent activity and cannot reach D's Office, marking unavailable
2024-05-15 10:17:59.357 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-15 11:10:04.908 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-15 11:10:05.989 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-15 11:10:15.430 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-15 13:04:30.869 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-15 13:56:04.059 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-15 14:10:04.910 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-15 14:10:15.246 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-15 14:47:40.086 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-15 15:39:57.893 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-15 17:10:04.912 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-15 17:10:05.936 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-15 17:10:15.326 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-15 20:10:04.915 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-15 20:10:05.837 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-15 20:10:15.371 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-15 23:10:04.915 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-15 23:10:05.921 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-15 23:10:15.379 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 02:10:04.920 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-16 02:10:05.967 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 02:10:15.375 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 05:04:29.124 WARNING (MainThread) [music_assistant.providers.sonos] No recent activity and cannot reach D's Office, marking unavailable
2024-05-16 05:04:40.899 WARNING (MainThread) [music_assistant.providers.sonos] No recent activity and cannot reach Office, marking unavailable
2024-05-16 05:10:04.927 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-16 05:10:05.969 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 05:10:15.344 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 07:42:26.074 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 07:42:26.075 INFO (MainThread) [music_assistant] Loaded music provider Spotify
2024-05-16 07:42:36.362 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 08:10:04.936 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-16 08:10:05.902 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 08:10:15.308 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 08:10:25.557 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 09:00:24.661 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 09:50:40.584 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 10:42:51.806 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 11:10:04.991 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-16 11:10:17.452 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 11:10:20.200 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 11:10:27.684 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 11:33:06.014 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 12:26:36.251 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 13:18:53.224 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 13:51:39.395 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.4.138:8095
2024-05-16 14:10:04.922 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-16 14:10:05.853 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 14:10:15.436 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 14:10:18.189 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 14:10:25.675 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 15:01:24.700 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 17:10:04.914 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-16 17:10:05.940 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 17:10:15.258 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 17:10:17.990 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 17:10:25.730 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 20:10:04.923 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-16 20:10:05.853 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 20:10:15.377 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 20:10:20.190 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 20:10:26.816 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 23:10:04.919 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-16 23:10:05.878 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 23:10:15.268 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-16 23:10:18.069 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-16 23:10:25.585 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-17 02:10:04.926 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-17 02:10:05.951 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-17 02:10:15.323 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-17 02:10:18.201 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-17 02:10:25.524 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-17 05:10:04.928 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-17 05:10:05.852 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-17 05:10:15.345 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-17 05:10:18.115 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-17 05:10:25.549 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-17 07:45:09.902 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-17 08:10:05.000 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-17 08:10:15.431 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-17 08:10:18.108 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-17 08:10:25.719 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-17 08:35:20.819 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-17 09:26:45.028 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX
2024-05-17 10:18:46.697 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as XXX

### What version of Home Assistant Core are your running

2024.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment] 2024-05-17 22:52
Firstly can you PLEASE follow the instructions and not paste the log but attach it!

Now do you see QUEUE FLOW MODE in the settings for the player? If so try enabling that and see if that fixes it.

**Comment by jstebbins** [comment] 2024-05-18 20:27
queue flow mode does seem to work around the problem. 

But... the display of the currently playing item is severely out of sync with the audio that is currently playing. There appears to be several minutes of buffering happening somewhere and the item being displayed is ahead of the audio by a song or two (depending on how long the songs are).

Aside, I find Music Assistant *very* usable. I'm impressed with what you've done. I'm just reporting the issues I see so that they may someday be addressed.

**Comment by Sorjak** [comment] 2024-05-19 02:46
> But... the display of the currently playing item is severely out of sync with the audio that is currently playing. There appears to be several minutes of buffering happening somewhere and the item being displayed is ahead of the audio by a song or two (depending on how long the songs are).


I'm experiencing this exact same issue, it's almost like it's moving the next track in the queue to "played" while the track is playing, which then desyncs from the song that's actually playing.

**Comment by PyrusofImpetus** [comment] 2024-05-23 21:16
> > But... the display of the currently playing item is severely out of sync with the audio that is currently playing. There appears to be several minutes of buffering happening somewhere and the item being displayed is ahead of the audio by a song or two (depending on how long the songs are).
> 
> I'm experiencing this exact same issue, it's almost like it's moving the next track in the queue to "played" while the track is playing, which then desyncs from the song that's actually playing.

Seconding as I have this issue. I also have the skipping issue when playing from my SMB-mounted UnRaid NAS. Enabling flow mode helped, but occasionally MA seems to skip back to the first song I queued. Also facing the really rough GUI desync when playing. Pausing the active song sometimes snaps it back to the actually active track, but not always.

**Comment by OzGav** [comment] 2024-05-23 23:52
All those reporting this please advise if this is only a Spotify / Sonos combination (as that is the issue title) So check with Spotify and some other player and check with some other music provider and Sonos

**Comment by PyrusofImpetus** [comment] 2024-05-24 00:01
> All those reporting this please advise if this is only a Spotify / Sonos combination

I only have Sonos players, so no other candidates to demo on there. I primarily play music off my NAS mounted via SMB in MA, where I ran into this issue. If I try to play from a Spotify-provided playlist, I have the same problematic behavior. It appears to not be a problem specifically with Spotify and Sonos, but perhaps Sonos in general?

**Comment by jstebbins** [comment] 2024-05-26 17:25
> @jstebbins can you confirm if this is actually a Sonos problem?

I installed HA's Denon Heos integration to test this. So playing through the HA provider to the Heos media player. I have queue flow mode off.

I can not confirm if the problem exists with this setup because the behavior is much much worse. Here's what I see.

- 1st song gets cut short by a couple of seconds
- 2nd song shows correct duration, but current time doesn't reset to 0, keeps running
- At 3rd song, playback stops, display transistion from showing pause button to showing play button. Queue display shows it is ready to play 3rd song.
- Press play button and the 1st song plays again, while the queue shows it skipped one song and is playing the 4th in the queue.
- 1st song gets cut short by a few seconds again.
- Starts playing the 5th queue song, and correctly displays that it is playing the 5th song.
- 5th song gets cut short.
- 6th song plays. Current time display doesn't reset again.
- 2nd song in queue plays again. Queue display shows it is still playing 6th.
- Playback stops again. Queue display shows it is ready to play 7th song.
- Press play and it starts the 1st song again. Queue display shows it is playing the 8th song.

I see a pattern developing here...

**Comment by PyrusofImpetus** [comment] 2024-05-26 17:44
To add additional data for the desyncing, Here's an example in my setup. I'm playing queue flow mode on, an album from my SMB share on my NAS to one of my Sonos beam soundbars: 

1. Play Now (clear queue)
2. First song begins playing on the speaker, but shows the second song as playing ~20 seconds in. The first song is already in the "played" part of the queue despite still playing on the speaker.
3. ~15 seconds later, MA realizes and updates back to the first song, but about 30 seconds too far into the song.
4. If I hit the pause button, MA correctly syncs back up to the correct timestamp in the correct song.
5. When I hit play again, the queue song advances, while the first one continues on the speaker. Pausing no longer resyncs the queue unless I wait ~30 seconds.
6. If I hit the Next button while desynced, I expect the second song to begin, but instead MA seems to think it's already playing the second song, so the queue and the speaker jump to the third song.
7. While synced, if I hit the next button I do get the second song on the speaker, but the queue skips to the third before snapping back to the second ~5 seconds later. 
8. If I touch the timestamp and move it manually, the queue advances every single time, and the song on the speaker changes to the next, but neither are in sync with the other (wrong song and timestamp)

I've yet to be able to reproduce the "reset" back to the first song on command, it is still random for me.

**Comment by marcelveldt** [comment] 2024-06-14 22:15
Only use the HA MediaPlayer provider as last resort when there is no native player provider in MA.
Players that are forwarded from HA will suffer from issues decribed in this post , like metadata out of sync etc.

Can you conform you are using the Sonos player provider in MA ? Dont forward the sons players from HA, it WILL be buggy due to the fact that none of the code in HA is optimized for high quality playback, its more aimed on automating.

That said, can this be re-tested using the latest version (2.0.6 stable version or 2.1.0b5 beta version) ?

**Comment by PyrusofImpetus** [comment] 2024-06-15 16:58
Confirming that I'm using the Sonos player provider. When i first set up MA, I did connect through HA, but reverted that quite a while back (prior to finding this post). While I'm not home this weekend to test this newest version, I'll update next week to update.

Running 2.1.0b5.

**Comment by PyrusofImpetus** [comment] 2024-06-17 19:16
Upon returning and updating to the available 2.1.0b6, I'm in a way worse state than before. Now unable to play nearly anything directly to the Sonos players, I'm getting many HTTPConnectionPool errors. Attempting to play an album off my NAS, or from spotify has the same behavior. I can play individual tracks off my NAS from the MA GUI through my desktop, but attempting to play through the speakers is totally broken now. 

No network changes were made that I'm aware of since the last time I used MA that was (mostly) working.

**Comment by OzGav** [comment] 2024-06-17 22:39
FYI the Sonos provider is being rewritten so standby for that.

**Comment by marcelveldt** [comment] 2024-06-19 23:13
You cant use flow mode on Sonos - I have actually removed it now from its options in 2.1.0b7

**Comment by PyrusofImpetus** [comment] 2024-07-01 21:10
Just a status update. Seems I'm not out of the woods quite yet. Running 2.1.0b8 and the track playing briefly and then skipping to the next queue item has been acting up badly today.

Looking forward to the rewrite coming down the pipe! Thanks for all you guys do.

**Comment by MelHarbour** [comment] 2024-07-18 12:30
Just commenting for reference that I'm also experiencing the same slight problem I think. When getting to the last few seconds of a track on Sonos players it sometimes (not always) lops it off and you get a few seconds of silence, then starts the next track (I think) correctly.

Anyway, holding off until new provider!

**Comment by Geweldich** [comment] 2024-08-07 10:14
Hi. Just chiming in: I just started using MA and notice skipping and (in the case of streaming radio) (short) pauses on all my configured music providers (Spotify, Filesystem (NAS) and MA) using the Sonos player provider. This only happens when using MA. I guess this will all be solved by the aforementioned Sonos player provider rewrite?

**Comment by marcelveldt** [comment] 2024-08-21 16:36
> Hi. Just chiming in: I just started using MA and notice skipping and (in the case of streaming radio) (short) pauses on all my configured music providers (Spotify, Filesystem (NAS) and MA) using the Sonos player provider. This only happens when using MA. I guess this will all be solved by the aforementioned Sonos player provider rewrite?

That does not sound like a known issue so maybe you should create your own issue report to track that issue.

**Comment by Geweldich** [comment] 2024-08-21 17:12
> > Hi. Just chiming in: I just started using MA and notice skipping and (in the case of streaming radio) (short) pauses on all my configured music providers (Spotify, Filesystem (NAS) and MA) using the Sonos player provider. This only happens when using MA. I guess this will all be solved by the aforementioned Sonos player provider rewrite?
> 
> That does not sound like a known issue so maybe you should create your own issue report to track that issue.

Hi Marcel. I totally forgot this comment. I’ve since found out that the streams I was using were not reliable. It had nothing to do with MA!

**Comment by OzGav** [comment] 2024-08-24 04:37
Please confirm this has been fixed with the release of the new Sonos provider in 2.2.0 beta 3

**Comment by PyrusofImpetus** [comment] 2024-08-24 21:24
So far so good! I've listened to over an hour of music off my NAS and it's felt far less flakey than it used to. I'll keep using it and watching for more odd behavior and will report back soon.

**Comment by OzGav** [comment] 2024-08-24 22:33
@PyrusofImpetus Yes it is unusual that a browser refresh would cause that. Please see if you can recreate it.

**Comment by PyrusofImpetus** [comment] 2024-08-27 22:04
So far I've been running 2.3.0b6 for the last day or so and its been far more solid than it used too. I didnt notice any abnomral skipping in my 5+ hours of listening while working today.

**Comment by OzGav** [comment] 2024-08-27 23:03
Ok then I’m inclined to close this?

**Closed** 2024-08-29 08:24 UTC
Labels: bug, More info, Fix to be Confirmed, Sonos

**Comment by motoridersd** [comment] 2024-09-20 19:30
I've had a similar issue before, but I stopped using MA for a while. I am back to trying it again, and found that the stable version of the server (2.2.5) still has issues with Tidal playback on Sonos skipping early. This was my issue back in January. Looks like I had the same problem in May but the codec option was gone then and is gone now.

I tried the latest beta 2.3.0b25 and I'm having the same issue.

It seems this happens when this Error log shows up in the Music Assistant Server logs:

2024-09-20 12:29:12.631 ERROR (MainThread) [aiosonos.api] Received error message without cmdId: {'namespace': 'playback:1', 'householdId': 'Sonos_kkkpKt6HkYZz4MrNoknTCbbRJD.Rfy8TGruRt84lcfg4qay', 'locationId': 'lc_e9366d5b1e314af3a561a85789035712', 'groupId': 'RINCON_5CAAFD0BD07001400:2957984318', 'name': 'playbackError', 'type': 'playbackError'}
2024-09-20 12:29:12.634 ERROR (MainThread) [aiosonos.api] Received error message without cmdId: {'namespace': 'playback:1', 'householdId': 'Sonos_kkkpKt6HkYZz4MrNoknTCbbRJD.Rfy8TGruRt84lcfg4qay', 'locationId': 'lc_e9366d5b1e314af3a561a85789035712', 'groupId': 'RINCON_5CAAFD0BD07001400:2957984318', 'name': 'playbackError', 'type': 'playbackError'}

**Comment by djansen1987** [comment] 2024-09-24 07:39
Have the same problem with 2.2.5, sonos, spotify. Will try to install the beta  today

**Comment by bakaschwarz** [comment] 2024-10-08 14:26
I can report i have the problem with a Sonos / Youtube Music combination. Mostly just 15 - 20 seconds into a track. I am running MA 2.3.0b29

**Comment by motoridersd** [comment] 2024-10-08 14:47
We've tracked the issue to Gen1 speakers running S2 software, this is due to bandwidth limitations on older speakers. At least in my case, this happens on an older Play:5. On WiFi, it can only do 54 Mbps at best with 802.11b, so there's not enough bandwidth to play FLAC streams (I use Tidal). Even wired at 100 Mbps I have problems. If I only play on a Move 2, I don't have an issue.

The plan is to bring back the option to force mp3 playback which should solve the issue with lower bandwidth speakers. This hasn't made it to the beta yet, but it should be coming.

**Comment by geurtsd** [comment] 2024-11-04 16:47
to add to the scoping: I have the same issue with playback of a radio stream on SONOS (actually IKEA Symfonisk).... :

2024-11-04 17:36:48.264 ERROR (MainThread) [aiosonos.api] Received error message without cmdId: {'namespace': 'playback:1', 'householdId': 'Sonos_u0ejWqkgWqaB1HyUx9CqafXLsp.wBjPSaQ5FBET1In5I3Or', 'locationId': 'lc_52b431106c634618a5dbb9124a782858', 'groupId': 'RINCON_7828CAD351EC01400:2839661921', 'name': 'playbackError', 'type': 'playbackError'}

PS running version 2.3.2 of MA.....

I have it regularly at start of a playback..... its tops 2 or 3 times and then after that plays stable........ 
I had a hunch that it maybe related to the (sometimes) introduced commercial message at the start of a stream (redirect or something) .... but this is just a hunch, non-tested / non-confimed

I can provide logs if needed (DEBUG level)

besides this: loving the tool.... finally brings what a lot of us have been missing on .... ;-) (integrated music universe...)

**Comment by OzGav** [comment] 2024-11-04 18:01
@geurtsd you are commenting on a closed issue

**Comment by geurtsd** [comment] 2024-11-05 07:35
> @geurtsd you are commenting on a closed issue

@OzGav ... oops slight oversight...... I'll see if there is a related open issue, if not... I'll first gather some info / input / tests before posting a new one
