### ISSUE TITLE
Tidal - playlists do not auto populate

### ISSUE THREAD

**Issue by oneofthemany** [music-assistant/hass-music-assistant#1428] opened 2023-08-02 12:24 UTC
### What version of Music Assistant has the issue?

2.0.0b63

### The problem

Unless you manually refresh playlists, they do not populate

### How to reproduce

Create Tidal Music Provider > Access Playlists > empty

### Relevant log output

2023-08-02 12:04:36.664 INFO (MainThread) [music_assistant] Starting Music Assistant Server (43e3c1c93182490890b7f8e9f191223c) version 2.0.0b63 - uvloop: False
2023-08-02 12:04:36.706 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.1.1:8095
2023-08-02 12:04:36.871 INFO (MainThread) [music_assistant.music] Setting up the sync interval to 180 minutes.
2023-08-02 12:04:37.025 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.3 with libsoxr support
2023-08-02 12:04:37.026 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8096 - base url: http://192.168.1.1:8096
2023-08-02 12:04:37.560 INFO (MainThread) [music_assistant] Loaded player provider SONOS
2023-08-02 12:04:37.561 INFO (MainThread) [music_assistant] Loaded music provider URL
2023-08-02 12:04:37.563 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2023-08-02 12:04:37.564 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2023-08-02 12:04:37.564 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2023-08-02 12:04:37.565 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2023-08-02 12:04:37.566 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider
2023-08-02 12:04:37.573 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-02 12:04:37.582 INFO (MainThread) [music_assistant.providers.slimproto] Started SLIMProto server on port 3483
2023-08-02 12:04:37.583 INFO (MainThread) [music_assistant.providers.slimproto.cli] Registering jsonrpc endpoints on the webserver
2023-08-02 12:04:37.588 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2023-08-02 12:04:37.599 INFO (MainThread) [music_assistant.providers.slimproto.cli] Starting (telnet) CLI on port 9090
2023-08-02 12:04:37.610 INFO (MainThread) [music_assistant] Loaded player provider Slimproto
2023-08-02 12:04:37.620 ERROR (MainThread) [music_assistant.webserver] [547692953552] Error handling message: CommandMessage(message_id=30, command='music/artists/get_artist', args={'item_id': '1', 'provider_instance_id_or_domain': 'library'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 165, in get
    library_item = await self.get_library_item_by_prov_id(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 303, in get_library_item_by_prov_id
    return await self.get_library_item(item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 292, in get_library_item
    raise MediaNotFoundError(f"{self.media_type.value} not found in library: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: artist not found in library: 1
2023-08-02 12:04:37.768 INFO (MainThread) [music_assistant.players] Player registered: b2fe7f85-1797-44f8-957f-1747cf58a76f/Quadrophonic
2023-08-02 12:04:37.927 INFO (MainThread) [music_assistant.players] Player registered: c94acc21-d7ce-4a0d-bca4-1d2167f03302/Elena Broadcast
2023-08-02 12:04:38.088 INFO (MainThread) [music_assistant.players] Player registered: 7af6343c-8e4a-4d96-a6d6-cf971853cc0e/Home
2023-08-02 12:04:38.259 INFO (MainThread) [music_assistant.players] Player registered: c7c621ce-aa0b-44b1-8317-60cd92af9eba/Living Room Speaker
2023-08-02 12:04:38.426 INFO (MainThread) [music_assistant.players] Player registered: e62fde05-9013-ae07-21a8-832b81cbfae0/Speaker - Desk
2023-08-02 12:04:38.569 INFO (MainThread) [music_assistant] Loaded player provider Airplay
2023-08-02 12:04:38.590 INFO (MainThread) [music_assistant.players] Player registered: 4150f58d-0b98-4083-9c78-68df23829d32/Stereo Kitchen Pair
2023-08-02 12:04:38.754 INFO (MainThread) [music_assistant.players] Player registered: 7462796e-c3bf-4e19-925d-7d9f6508b938/Alarm Group
2023-08-02 12:04:38.907 INFO (MainThread) [music_assistant.players] Player registered: 1c16f7cc-add3-c994-ba77-ff709a72817c/Speaker - Master Bedroom
2023-08-02 12:04:38.981 INFO (MainThread) [music_assistant.players] Player registered: f65e5e5f-b6da-0b86-303c-87e3383e3888/Speaker - Elena's Room
2023-08-02 12:05:34.973 INFO (MainThread) [music_assistant] Loaded music provider Tidal
2023-08-02 12:05:39.001 WARNING (ThreadPoolExecutor-0_1) [tidalapi.request] HTTP error on 404
2023-08-02 12:05:39.003 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/279205265: album://279205262 not found on provider tidal
2023-08-02 12:06:00.942 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Various Artists
 - using lookup-album(s): Más Peruanos Que el Rock, Vol. 2/Brasil... Como Te Estranho!/Pluie relaxante/Pluies De Sommeil (Sons De Pluie Pour S'endormir)/Lofi Christmas/Classical Christmas/Background Music for Kids (Nursery rhymes to play or sleep)/Best Christmas Songs/Classical Christmas/Christmas Meditations/37 Electronic Soundtracks for Unrivaled Focus, Managing Tasks, and Accomplishing Milestones/Naglleng/Northern Wind/Nostalgia Fire/Neon Nostalgia/Nigde/Oasis/Niamh/Na/Nerida/Ocean's Horizon/Ocean Dreams/Neon Nirvana/Oceandrilla/Ocean Breeze/Nus/Nightfall Serenade/Neon Nights/Neon Nectar/Neon Nightscape/Narthur/Ocean Odyssey/Ocean View/Ocean's Embrace/Ocean Blue/Neon Nebula/Moonlit Meadow/Muslus/Moments of Happiness/Moon Reflections/Misty Memories/Morgana/Morrigan/Moonlit Serenade/Mystical Dreamscape/Misty Mountainside/Mystical Mirage/Moonlit Bay/Moonlit Oasis/Midnight Symphony/4 for the Floor, Vol. 24/Chave de Torpedão/Tambor de 40/No Zap (Remix Brega Funk)/Ritmo Acelerado/The Past Keeps Moving/La Vida Vol.7/Na Tum Jano Na Hum (From "Kaho Naa Pyar Hai") (Hip Hop Mix)/Só de Quebradinha/Telephone/Consensus/Set Minha Dama/Hard EP2/PHONK MASIVO/Pase/Raakadhan (Original Motion Picture Soundtrack)/Eclética/Quer Se Envolver/Vaa Vaa Poove Vaa (From "Rishi") (Chill Lofi)/London/Perunthil Nee Enakku Jannal Oram (From "Pori") (Lofi)/Allives Music Summer 2023/NYXVA01/La Terraza/Nakushukuru/Back in town/V.A July 2023/Know About That/Meeting Place, Vol. 19/Sicarios/La Elegida/Marlboro (Remastered)/Mix It Up Vol. 2/Bheegi Bheegi Raaton Mein (From "Ajanabee") (Knockwell Remix)/Pas Kompilasi/Tu Me Dices (Remix)/We Are Techno Vol. 2/Aos 21/Historinha/Mere Mehboob Qayamat Hogi (From "Mr. X in Bombay") (Afro Mix)/SUMMER VIBEZ - EP/Vuka, Vukadão/Porsche Macan/Rico Maloka 2/Vol 3/Galactic Antics Va Ep/Toke Niye Jabo (Fom "Dear Diary")/O Traje Ta de Bandido/BLACKCOMBAT: CIVIL WAR (Original Television Soundtrack)/Desespero/Skåne åt danskarna/BLUETOOTH/TQG (Tik Tok Edit) (Tik Tok Edit)/El Cielo (Tik Tok Edit)/Mala (Tik Tok Edit)/PROVENZA (Tik Tok Edit) (Tik Tok Edit)/La Jumpa (Tik Tok Edit)/La Bebe (Tik Tok Edit) (Tik Tok Edit)/La Inocente (Tik Tok Edit)/Ojitos Lindos (Tik Tok Edit)/Me Porto Bonito (Tik Tok Edit)/Despechá (Tik Tok Edit)/Ella Baila Sola (Tik Tok Edit) Remix (Tik Tok Edit)/BESO (Tik Tok Edit) (Tik Tok Edit)/Gasolina (Tik Tok Edit) (Tik Tok Edit)/This Year Blessing - Speed Up/Electronic Music Vol 2/God of All Grace/Just Dance (Speed Up)/Liên Khúc Giáng Sinh/Hibernation Season/another guy/Por un Corazón/NGN the Album (CD1)/Madre de la Iglesia/AQUECIMENTO DO NEYMAR  PIQUE FAVELA/ELA SE JOGA PRA TROPA DO RAFODA TROPA DA ARÁBIA/BEAT RUGAL TOCA AQUELA/Home Coming/Vibra Positiva Remix (Remix)/PTSD/Sunnerdahl på liv och död/Silver Hill/Sunnerdahl på liv och död/På farfars tid/Högt flygande planer/Regnbågen/Agnes/Game Aficionado/Calchin canta (cover)/Till We Meet Again/Calchin canta/Café 22°N Musical Soundtrack/Nuestra Vida/EarPlug RollerCoaster/The Box Mouth Project/Turn The Beat Around/Lyrikalische Lesung Episode 24/Lyrikalische Lesung Episode 26/Bumpmix, 002
 - using lookup-track(s): Afrika/Moving Weight Pt. 1/Percocet/Interlude/Take a Breath/Du Er Super, Vi Er Show!/Dusk 2 Dusk/Stand By Me/Dies irae/Violin Sonata No. 3 in C major, BWV 1005: III. Largo (arr. for 8-string guitar)

2023-08-02 12:06:12.317 WARNING (MainThread) [music_assistant.music] Sync task for Tidal completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 571, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 418, in sync_library
    library_item = await controller.add_item_to_library(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 172, in add_item_to_library
    item.metadata.images.append(item.album.image)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append'
2023-08-02 12:06:38.375 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-02 12:06:38.598 WARNING (ThreadPoolExecutor-0_2) [tidalapi.request] HTTP error on 404
2023-08-02 12:06:38.600 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/279205265: album://279205262 not found on provider tidal
2023-08-02 12:06:38.608 WARNING (MainThread) [music_assistant.music] Sync task for Tidal completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 571, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 418, in sync_library
    library_item = await controller.add_item_to_library(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 172, in add_item_to_library
    item.metadata.images.append(item.album.image)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append'
2023-08-02 12:06:40.100 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-02 12:06:40.361 WARNING (ThreadPoolExecutor-0_3) [tidalapi.request] HTTP error on 404
2023-08-02 12:06:40.362 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/279205265: album://279205262 not found on provider tidal
2023-08-02 12:06:40.370 WARNING (MainThread) [music_assistant.music] Sync task for Tidal completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 571, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 418, in sync_library
    library_item = await controller.add_item_to_library(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 172, in add_item_to_library
    item.metadata.images.append(item.album.image)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append'
2023-08-02 12:06:42.220 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-02 12:06:42.437 WARNING (ThreadPoolExecutor-0_2) [tidalapi.request] HTTP error on 404
2023-08-02 12:06:42.439 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/279205265: album://279205262 not found on provider tidal
2023-08-02 12:06:42.447 WARNING (MainThread) [music_assistant.music] Sync task for Tidal completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 571, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 418, in sync_library
    library_item = await controller.add_item_to_library(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 172, in add_item_to_library
    item.metadata.images.append(item.album.image)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append'
2023-08-02 12:06:52.731 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-02 12:06:53.043 INFO (MainThread) [music_assistant.music] Sync task for Tidal completed

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by oneofthemany** [comment] 2023-08-02 16:32
ah apologies forgot to paste in

**Comment by jozefKruszynski** [comment] 2023-08-02 16:45
No worries, from the looks of it, this is already fixed in the next release and was caused by the small bugfix I mentioned in my previous comment.

**Comment by OzGav** [comment] 2023-08-03 11:24
@oneofthemany Please confirm this has been fixed

**Comment by oneofthemany** [comment] 2023-08-03 13:08
> That error is not the same as you posted before. So confirm if there is actually a noticable problem in the frontend. What you see above might just be a typo in the code actually. Does debg = debug @jozefKruszynski ??

If this is directed to me,  I am still having to manually sync to pull in playlists - however I have noticed that when you go to artists it auto populates tracks without having to go to specific albums for that function to happen so that seems to be fixed.

In terms of the logs, I separated the logs from before and after I manually synced to perhaps give an insight as to what was happening.

If there is another error, that is out of my control sadly

**Comment by OzGav** [comment] 2023-08-03 13:09
Sync will be done on server start and then every three hours. Are you saying that the playlist doesn't get pulled down after the initial start?

**Comment by oneofthemany** [comment] 2023-08-03 13:17
> Sync will be done on server start and then every three hours. Are you saying that the playlist doesn't get pulled down after the initial start? It is possible that typo is the problem but just trying to get all the needed info.

Yes

**Comment by marcelveldt** [comment] 2023-08-03 13:20
The typo is causing the sync to crash. Typo fixed in next beta build

**Comment by oneofthemany** [comment] 2023-08-03 13:24
> The typo is causing the sync to crash. Typo fixed in next beta build

Cool let me know if you would like me to test and verify

**Comment by OzGav** [comment] 2023-08-04 05:53
@oneofthemany please confirm this has been fixed

**Comment by oneofthemany** [comment] 2023-08-04 16:49
Fixed

Many thanks

**Closed** 2023-08-04 16:49 UTC
Labels: bug, More info
