### ISSUE TITLE
Music Assistant addon fails to start on when running on VM

### ISSUE THREAD

**Issue by jtary** [music-assistant/hass-music-assistant#1254] opened 2023-05-19 18:52 UTC
### What version of Music Assistant has the issue?

 2.0.0b30

### The problem

The Music Assistant beta addon fails to start when running Home Assistant OS on a virtual machine (VM) using Proxmox. The message displayed in the logs do not show any crashes or expectations. The docker container simply exists after loading the steam controller.

### How to reproduce

1. Set up a virtual machine using Proxmox.
2. Install Home Assistant OS on the VM.
3. Install the Music Assistant beta addon.
4. Start the Music Assistant addon.

### Relevant log output

```
2023-05-19 11:40:52 DEBUG aiorun  -- Entering run()
2023-05-19 11:40:52 DEBUG aiorun  -- Creating default executor
2023-05-19 11:40:52 DEBUG music_assistant.server.controllers.config  -- Started with empty storage: No persistent storage file found.
2023-05-19 11:40:52 DEBUG music_assistant.server.controllers.config  -- Started.
2023-05-19 11:40:52 INFO  music_assistant  -- Starting Music Assistant Server (082241e6f4734040bd62075ac3d85ae0) - autodetected IP-address: 192.168.1.100
2023-05-19 11:40:52 INFO  music_assistant.web  -- Starting webserver on port 8095
```

### Additional information

VM status for the HA install:

<img width="535" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/79639/eef7b9fc-7784-4cdb-9a95-8f8ba021d4db">

### What version of Home Assistant Core are your running

2023.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by Lucho99se** [comment] 2023-05-19 20:49
Same issue in home assistant supervised.

2023-05-19 17:48:28 DEBUG aiorun  -- Entering run()
2023-05-19 17:48:28 DEBUG aiorun  -- Creating default executor
2023-05-19 17:48:28 DEBUG music_assistant.server.controllers.config  -- Started with empty storage: No persistent storage file found.
2023-05-19 17:48:28 DEBUG music_assistant.server.controllers.config  -- Started.
2023-05-19 17:48:28 INFO  music_assistant  -- Starting Music Assistant Server (cc51957717104084b1f189796a6c8a56) - autodetected IP-address: 192.168.0.150
2023-05-19 17:48:28 INFO  music_assistant.web  -- Starting webserver on port 8095
2023-05-19 17:48:29 INFO  music_assistant.streams  -- Started stream controller (using ffmpeg version 4.3.6 with libsoxr support)

**Comment by marcelveldt** [comment] 2023-05-20 21:39
Somehow this must be related to virtualization or maybe even Proxmox as I can not reproduce this on any of my test environments, not we have received any reports of this issues from people that are not running virtualized.

At this time I do not have time to follow up on this as I'm busy writing the HA integration but I'll try to create a test setup with proxmox next week to see if I can reproduce.

**Comment by habitats-tech** [comment] 2023-05-22 02:28
I am running several HAOS instances on Proxmox (both 5.x and 6.x kernel) and I have not experienced the described issues with MA. Are you on the latest Proxmox VE 7.4-3. Does the issue manifest only on newly created HAOS instances?

**Comment by habitats-tech** [comment] 2023-05-22 06:39
I can safely state MA 2.0.0b30 has no issues operating in Proxmox VE 7.4-3 with either kernel 5.x or 6.x.

I created a new instance of HAOS 10.1 with all default and just added MA 2.0.0b30, then added Spotify as a provider. No issues MA starting following installation and no issues syncing to Spotify.

I believe the issues @jtary reported are either specific to his Proxmox VE setup or most likely some other issue unrelated to Proxmox VE.

For whatever is worth try my guide below and let us know if you have been successful or not.

https://portal.habitats.tech/Home+Assistant+(HA)/3.+HAOS+-+Install+VM

**Comment by marcelveldt** [comment] 2023-05-29 11:27
@jtary any progress on this one ? I have never been able to reproduce this one and also others have reported that Proxmox is working fine so a bit clueless how to help you.

**Comment by glutfloc** [comment] 2023-05-31 09:20
I can confirm it works on proxmox 7.4-3 with kernel 6.x, OS 10.2, HA 2023.5.4 and MA 2.0.0b32 (installed through HACS) with Deezer as provider and Chromecast as player.
On my side it worked also previously on proxmox 7.4-3 with kernel 5.x, OS 10.1, HA 2023.5.3 and MA 2.0.0b30.
I guess this issue is not regarding MA.

**Comment by OzGav** [comment] 2023-05-31 09:25
@jtary Given the number of people confirming no issues I will close this soon unless you are able to provide some more info as it is difficult to see how this is an issue for MA

**Comment by jtary** [comment] 2023-06-05 17:11
@OzGav You can go ahead and close this issue. I am still encountering the problem -- but I don't have the time currently to isolate a more reliable reproduction method. If I am able to find one in the future, I can open a new one since likely the cause is more complex than what was originally reported here anyways.

**Comment by OzGav** [comment] 2023-06-05 20:55
Ok thanks. Hope you can find the root cause.

**Closed by OzGav** 2023-06-05 20:55 UTC
Labels: bug

**Comment by Tomasinjo** [comment] 2023-06-29 09:13
I had same issue with:
PVE 6.2-11
HA version: 2023.5.2
OS version: 6.5

Upgraded to OS 7.5 and HA 2023.6.3 and now the problem is gone! I don't think this is related to PVE.

**Comment by OzGav** [comment] 2023-06-29 10:50
Thanks @Tomasinjo this will hopefully help others.

**Comment by jtary** [comment] 2023-07-05 20:17
Issue also seems to have self-resolved after update for me.
