### ISSUE TITLE
Youtube music provider HTTP 401: Unauthorized

### ISSUE THREAD

**Issue by michaeldufour** [music-assistant/hass-music-assistant#1203] opened 2023-04-20 16:30 UTC
### What version of Music Assistant has the issue?

2.0.0b28

### The problem

When I playing an album of youtube music, suddenly the music stop after few played track.
I genereted new cookie but same problem

### How to reproduce

I select play now album and after few tracks the music stop

### Relevant log output

2023-04-20 11:10:34 ERROR asyncio  -- Task exception was never retrieved
future: <Task finished name='Task-8' coro=<MetaDataController.start_scan.<locals>.scan_artist_metadata() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py:82> exception=Exception('Server returned HTTP 401: Unauthorized.\nYou must be signed in to perform this operation.') created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:252>
source_traceback: Object created at (most recent call last):
  File "/usr/local/bin/mass", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 108, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 273, in run
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1914, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 99, in start_sync
    self.mass.metadata.start_scan()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 105, in start_scan
    self.mass.create_task(scan_artist_metadata)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 252, in create_task
    task = self.loop.create_task(target(*args, **kwargs))
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 99, in scan_artist_metadata
    await self.mass.music.artists.get(artist.item_id, artist.provider, lazy=False)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 168, in get
    details = await self.get_provider_item(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 416, in get_provider_item
    if item := await provider.get_item(self.media_type, item_id):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 253, in get_item
    return await self.get_artist(prov_item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 248, in get_artist
    if artist_obj := await get_artist(prov_artist_id=prov_artist_id):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 30, in get_artist
    return await asyncio.to_thread(_get_artist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 22, in _get_artist
    artist = ytm.get_artist(channelId=prov_artist_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/browsing.py", line 210, in get_artist
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 146, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 401: Unauthorized.
You must be signed in to perform this operation.
2023-04-20 11:11:11 ERROR pychromecast.socket_client  -- [All Google Device(192.168.0.132):32248] Error reading from socket.

### What version of Home Assistant Core are your running

2023.4.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment] 2023-04-21 12:58
@MarvinSchenkel ??

**Comment by OzGav** [comment] 2023-04-22 11:52
Do you have another player you can try this on? Just want to check that it is indeed an issue with the music provider and not the player...

**Comment by michaeldufour** [comment] 2023-04-22 20:05
> Do you have another player you can try this on? Just want to check that it is indeed an issue with the music provider and not the player...

Hi, this morning I disable YM provider and I play 40 tracks from files system provider with no error. Normally with YM for 12 tracks I need to press play 2 or 3 time to listen all tracks :)

**Comment by OzGav** [comment] 2023-04-22 21:48
Ok in an upcoming release the cookie method of authentication is being replaced so let’s see if that fixes it.

**Comment by OzGav** [comment] 2023-05-14 10:07
Please try this again with beta 30

**Comment by michaeldufour** [comment] 2023-05-15 19:49
Same issue

2023-05-15 12:24:20 ERROR asyncio  -- Task exception was never retrieved
future: <Task finished name='Task-34' coro=<MetaDataController.start_scan.<locals>.scan_artist_metadata() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py:82> exception=Exception('Server returned HTTP 401: Unauthorized.\nYou must be signed in to perform this operation.') created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:252>
source_traceback: Object created at (most recent call last):
  File "/usr/local/bin/mass", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 108, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 273, in run
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1914, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 562, in on_sync_task_done
    self.mass.metadata.start_scan()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 105, in start_scan
    self.mass.create_task(scan_artist_metadata)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 252, in create_task
    task = self.loop.create_task(target(*args, **kwargs))
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 99, in scan_artist_metadata
    await self.mass.music.artists.get(artist.item_id, artist.provider, lazy=False)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 166, in get
    details = await self.get_provider_item(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 435, in get_provider_item
    if item := await provider.get_item(self.media_type, item_id):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 253, in get_item
    return await self.get_artist(prov_item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 284, in get_artist
    if artist_obj := await get_artist(prov_artist_id=prov_artist_id):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 41, in get_artist
    return await asyncio.to_thread(_get_artist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 33, in _get_artist
    artist = ytm.get_artist(channelId=prov_artist_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/browsing.py", line 210, in get_artist
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 132, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 401: Unauthorized.
You must be signed in to perform this operation.

**Comment by OzGav** [comment] 2023-05-15 21:12
Can you remove the YTM provider and re-add and confirm the OAUTH flow appears to work correctly. If it does and you still have this issue then think about what you might have that is non standard in your install or network setup (eg. Behind a VPN) as you seem to be the only person with this problem.

**Comment by OzGav** [comment] 2023-05-15 21:14
Also please confirm you are using YouTube music premium

**Comment by MarvinSchenkel** [comment] 2023-05-18 09:57
Could not reproduce this locally, but I added authentication while receiving artist information. This _should_ not be required, since artist information can be retrieved without authentication, but I guess you have added some private artists / users / pages in your library.

Should be resolved in the next beta (31), so let's verify that when it is released.

**Comment by OzGav** [comment] 2023-05-30 07:16
@michaeldufour has this been resolved in the latest beta?

**Comment by michaeldufour** [comment] 2023-05-30 21:04
@OzGav @MarvinSchenkel Since the last beta so far we don't have any issue with the YT provider, no authentification error in the MA log.

Thanks for your help

**Closed** 2023-05-30 21:29 UTC
Labels: bug, More info
