### ISSUE TITLE
Album art for many tracks not showing in Tracks and Album view

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#639] opened 2022-07-11 01:33 UTC
### What version of Music Assistant has the issue?

2022.7.0.b3

### The problem

The Album art for many tracks not showing in Tracks and Album view. Here is one example.

ID3 and Album art setup in Picard - not I only have one track from this album

![Image 013](https://user-images.githubusercontent.com/22878629/178172091-95d9b60d-ea59-4b68-b5bd-25a7d9b2e2c9.jpg)

The Track's art displays fine in Album view:

![Image 011](https://user-images.githubusercontent.com/22878629/178172178-a99acf62-3736-42e2-9ddf-6f7979e24b00.jpg)

And it displays fine in the player:

![Image 010](https://user-images.githubusercontent.com/22878629/178172202-d9638598-2379-47b1-841f-f2dbd19e7b17.jpg)

However in Artist view and Track view there's no album art for the track:

![Image 012](https://user-images.githubusercontent.com/22878629/178172269-71a9ca6d-a5d8-4187-a619-5a67b6fca90e.jpg)

![Image 009](https://user-images.githubusercontent.com/22878629/178172292-65ecaaa9-a2dc-4a68-977a-734623426413.jpg)

### How to reproduce

I've tried resetting cache and tried different browsers with same result

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment] 2022-07-11 10:35
Yes I can confirm I see the same behaviour

**Comment by marcelveldt** [comment] 2022-07-12 22:12
Can you please check if this is fixed in the 2022.7 beta 4 ?

**Comment by vk2him** [comment] 2022-07-13 02:10
Hi Marcel - sorry, no it's the same

**Comment by OzGav** [comment] 2022-07-13 03:49
Yeah I have a couple that are showing but generally not.

**Comment by OzGav** [comment] 2022-07-13 05:23
What I have also noticed which may be related is if you are in the artist view and have an artist with no thumbnail you can click on the artist and in the top left there will by the default person icon. If you then go back to the Artist view there will now be an thumbnail against the artist and if you click back on the artist now there will be the artist thumbnail in the top left. So it appears that MA is correctly downloading the thumbnail but isn't updating the artist view unless you change views? Hopefully that make sense.

**Comment by marcelveldt** [comment] 2022-07-13 09:48
@OzGav if the info is not present locally (as in real files on disk), MA will query metadata providers for that info.
This is done in a "lazy" manner so when you click an artist/album/track for the **first time** (or play it), it will return quickly with the "lazy" object without all metadata present and in the meanwhile a background process will fill in the blanks and upgrade the artist/album/track object in the db with all metadata it can find online, this is the part where also the "track linking" takes place meaning an object from multiple musicproviders get linked.

The only thing it (currently) doesn't do is refresh the interface when it is done grabbing the full object.
I had that before but that UX was also a bit weird where you were looking at some info and several seconds later (or more on slow connections), the page refreshes and there is additional info.

So I'm a bit in doubt to what behavior is best here. 
If you click an item for the first time you get to see whatever info is present on the musicprovider. So for files on disk this means info from ID3 tags and/or images/nfo in the folder structure and for streaming providers whatever metadata the provider has to offer, mostly just the thumbnail but some (e.g. Qobuz) offer really rich metadata already at this stage.

If the item is added to the database, all other info is retrieved and you get a much richer experience.

- This metadata is not retrieved beforehand (at library sync) because it slows the scanning down too much and because it causes a real burden on those metadata providers, which are also community projects which have to pay for their server costs with donations.

- I'm thinking about a background task that slowly loads the missing metadata into the db 

- I'd like to hear some opinions about refreshing the UI once full info is loaded

**Comment by OzGav** [comment] 2022-07-13 09:52
Thanks Marcel. That all makes sense. It is the very last point which hopefully we will get some opinions on. Obviously I haven’t seen what it looks like when it refreshes but that is the behaviour I was expecting…

**Comment by marcelveldt** [comment] 2022-07-13 09:54
@vk2him in your case you mention that the missing artwork is in fact embedded into the files. Can you confirm that the only missing artwork is what is embedded in the ID3 tags ? In other words: Does artwork that exists in the disk folders (such as folder.jpg in albumfolder etc) work ?

Also I'd like to know if a "refresh" solves the issue:
Open Artist/Album/Track info --> Click contextmenu button top right --> Click Refresh info

**Comment by marcelveldt** [comment] 2022-07-13 09:57
> Thanks Marcel. That all makes sense. It is the very last point which hopefully we will get some opinions on. Obviously I haven’t seen what it looks like when it refreshes but that is the behavior I was expecting…

I can put it back in tonight's release to compare. Do note that also the listings refreshed with the previous behavior.
Because after the "full metadata fetch" the listings will also include the objects of all providers.

**Comment by OzGav** [comment] 2022-07-13 10:12
For me Album view is fine.
Artist view some thumbnails are shown and some aren’t l for those that aren’t refreshing doesn’t fix it
In track view sometimes show info fixes it, sometimes show info results in the Spotify thumbnail shown and just then I had the same named track (Abacab again!) with one thumbnail showing and one not and when I did a show info and then went back the one without the info was gone and I now have a duplicate of the one with the thumbnail 😭

**Comment by marcelveldt** [comment] 2022-07-13 10:31
OK, some observations:

1) Artist missing thumb --> This will only show if the artist has artwork on disk (Artist\Album\Track.mp3 structure) with the folder.jpg in the Artist folder as per Kodi instructions.

2) Artist thumb showing up after view/play --> correct because the missing info gets filled by the metadata background process.

3) Tracks missing thumb --> Thumbs for tracks are retrieved from the ID3 tag with fallback to album art.


My conclusion is that the ID3 tag parser fails to retrieve the images for embedded images only. Artwork on disk seems to be working correctly, as well as retrieving it online. Am I correct ?

If you open the tracks in Picard, can you spot any difference between a working and non working track there ? I believe Picard let's you see the details of the embedded image somewhere/somehow (I'm at work so can't look now).

**Comment by OzGav** [comment] 2022-07-13 10:35
The artist thumb is working fine. It is the album cover thumbs against the tracks listed when you click on an artist that is the issue.

**Comment by marcelveldt** [comment] 2022-07-13 10:37
A small thing to check... Do the offending tracks show the artwork when you view them from the "library" Tracks view ?
So just click the "Tracks" button on the homepage and lookup the tracks there

**Comment by OzGav** [comment] 2022-07-13 10:38
Generally no. They are only working well in the album view

**Comment by marcelveldt** [comment] 2022-07-13 10:39
> Generally no. They are only working well in the album view

That is valid info! In albums view the artwork gets filled by the album info.
So the thing to look now is if these tracks have embedded artwork in the ID3 tag. If not, MA should have assigned the album's image to the track. If they do, why does it not load the image

**Comment by OzGav** [comment] 2022-07-13 10:40
To be 100% sure I will have to get back to you tomorrow when I’m home

**Comment by vk2him** [comment] 2022-07-13 10:58
> That is valid info! In albums view the artwork gets filled by the album info.
> So the thing to look now is if these tracks have embedded artwork in the ID3 tag. If not, MA should have assigned the album's

Marcel - per my initial report and screenshots above - the offending tracks that don't display artwork have the artwork embedded in the id3 data - the first screenshot shows the track in pickard and you can see its album art in the bottom right corner. In MA library tracks view you can see it's not displaying the artwork. Hope that helps clarify?

**Comment by vk2him** [comment] 2022-07-13 11:49
I can't see anything unique to non working tracks - all are using jpeg - i couldn't find any using png  .. and no errors at all .... Mystery !!

**Comment by marcelveldt** [comment] 2022-07-13 11:50
yikes that is not the response I hoped for :-)

**Comment by vk2him** [comment] 2022-07-13 11:53
I can send you the BTO track "You aint seen nothing yet" that refuses to show artwork in the tracks view if you want

**Comment by marcelveldt** [comment] 2022-07-13 14:22
![Schermafbeelding 2022-07-13 om 16 21 49](https://user-images.githubusercontent.com/6389780/178756859-590940b8-65ea-4cd6-9764-513c2ac3c59c.png)

reproduced!

**Comment by marcelveldt** [comment] 2022-07-13 14:23
Ok so this is in fact a frontend issue as it seems

Look at the playing item thumb....

**Comment by vk2him** [comment] 2022-07-15 08:33
This is fixed for me in Beta6 - many thanks Marcel!! I'll await confirmation from @OzGav if it's also fixed for him before closing

**Comment by OzGav** [comment] 2022-07-15 09:54
Sadly still no go for me. I can recreate my db again (I know you hate that Marcel!) just to see if it is something at my end. You will see I also have Spotify which does seem to work ok I don't know if that is anything. @vk2him do you use the Spotify source as well?
![image](https://user-images.githubusercontent.com/19848947/179199985-ed2d50c5-efe6-4b46-aaaf-43cba89ca745.png)

**Comment by OzGav** [comment] 2022-07-15 11:36
I hadn't cleared the cache and cookie data but I just did and seemed to make no difference. 

I'm actually not seeing the refresh info menu anywhere. If I click on the dots against the track the option there is SHOW INFO. In the top right corner the three dots are only visible when viewing an album...?

I have uploaded the DB to Google Drive.

**Comment by marcelveldt** [comment] 2022-07-15 14:12
Thanks for the db and video. Now it makes more sense. 

1) The missing context menu will be fixed soon.
2) I am going to auto refresh the frontend when the full data was loaded.
3) I am going to reset a cache attribute in your db and send it back, I hope this will fix it.

**Comment by marcelveldt** [comment] 2022-07-15 15:48
@OzGav I've re-uploaded your db file back. Can you replace the file on disk and then reload the integration?
Let's see if that brings back the missing thumbs

**Comment by OzGav** [comment] 2022-07-16 07:26
Hi @marcelveldt Yep that works 1000% better. Just two questions. Should my local artwork be used instead of Spotify. Sometimes I see the Spotify album art when I would prefer mine. Second, I sometimes find when I click into a track that my local version isn't shown in the list of versions even though the local media source icon was shown? That is a different issue so I could start a different thread for that?

**Comment by marcelveldt** [comment] 2022-07-16 07:31
@OzGav 
1) If the local file existed on disk then, yes the local artwork should be preferred. 
2) Please start a new issue for that but maybe wait until I fixed all that "frontend should refresh issues" in the next version.

To correct number 1 you could try to force refresh a track (that should also refresh the attached album).

**Comment by OzGav** [comment] 2022-07-16 11:29
2. Roger that!
1. As the context menu is only available in the album I went and did the refresh in an album that has some incorrect artwork but it makes no difference. I see this:
![image](https://user-images.githubusercontent.com/19848947/179352816-d31f6cac-bff3-4c07-8292-c37866d04daf.png)
Maybe this is not right so please confirm what should happen. The first track in the picture above is by Queen. I have that same song on Queen's Greatest Hits which is track 9. The thumbnail above is from that album. I expected that when I SHOW INFO on that track I would see both of my local files and then how many ever versions Spotify has. Is that what should happen? Because I don't, I only see the Greatest Hits entry in the tracks list even though the track is shown in the album list? This is what the tracks list shows:
![image](https://user-images.githubusercontent.com/19848947/179352998-6dcd3fc4-8d4c-408c-9594-8f7ff05e71d5.png)

**Comment by marcelveldt** [comment] 2022-07-21 06:38
closing this one as the original issue is resolved. To keep my mind sane, please open a new issue if there are any leftover issues.

**Closed** 2022-07-21 06:43 UTC
Labels: bug
