### ISSUE TITLE
Errors during NAS sleeptime on Network Mount

### ISSUE THREAD

**Issue by Mariusthvdb** [music-assistant/hass-music-assistant#489] opened 2022-06-22 05:54 UTC
### What version of Music Assistant has the issue?

2022.6.4

### The problem

running the shell_command to mount my Nas drive (testing that functionality) works just fine. But.... my Nas is turned down to sleepmode each night for power savings.

I didnt realize that could inhibit the Music Assistant install using that Mount until now.

this morning I see below errors in the logs, which of course relate to that. To my surprise the actual files in the mount are still visible, via the Media/Local files browser, and, more surprisingly after reading that error in the log, to Music Assistant!

I would have expected Music Assistant, sensing the drive had disappeared, to update the DB and delete those files in a whim. It didnt.

Only posting it here as a FYI, and maybe for others to test this functionality.

There's no use in automating some kind of re-mount in the morning, because this is a) a temporary configuration, and b) it wont prevent MA from wiping during the Sleep time.

Yet is is something to consider going forward, in designing the MA's core support for NAS drives, and not delete the DB during sleep time

### How to reproduce

mount a nas drive with the known shell command

auto sleep the Nas

### Relevant log output

<img width="977" alt="Schermafbeelding 2022-06-22 om 07 44 42" src="https://user-images.githubusercontent.com/33354141/174952725-32c35ae0-bb3a-496c-b302-4ab53f069e57.png">

```
Logger: music_assistant
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:244 
First occurred: 02:22:24 (2 occurrences) 
Last logged: 05:22:25

Job [Library sync for provider Filesystem] failed with error [Errno 112] Host is down: '/media/music/nas/mp3/Wagner'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 155, in sync_library
    async for entry in scantree(self.config.path):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 67, in scantree
    async for subitem in scantree(entry.path):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 67, in scantree
    async for subitem in scantree(entry.path):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 67, in scantree
    async for subitem in scantree(entry.path):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/filesystem.py", line 65, in scantree
    for entry in await loop.run_in_executor(None, os.scandir, path):
OSError: [Errno 112] Host is down: '/media/music/nas/mp3/Wagner'

```

### What version of Home Assistant Core are your running

2022.7.0.dev20220621

### What type of installation are you running?

Home Assistant OS

**Comment by erkr** [comment] 2022-06-22 07:50
Thank you Marius for sharing these observations

**Comment by marcelveldt** [comment] 2022-06-22 08:08
MA will only delete entries from the db if the file is actually deleted from disk. The whole disk (or streaming provider) not available will just error the sync but not trigger any deletions.

So in fact this is all good behavior. Good thing it errors the sync when the NAS is sleeping and good thing that it cancels the sync and not trigger any deletes.

I'd classify this as "by design"

**Comment by Mariusthvdb** [comment] 2022-06-22 08:20
Add it to the docs, as being smart about it ;-)

**Comment by erkr** [comment] 2022-06-22 11:18
And close this issue for now 😎

**Comment by Mariusthvdb** [comment] 2022-06-28 05:31
so this is still happening after all:

restart Home Assistant (Including Music Assistant) before power NAS, fails the mount shell_command.

After some time (7:15 ;-) ) my NAS awakes and restarts once again, seeing:
```
2022-06-28 07:26:48 WARNING (MainThread) [music_assistant.music.file] /media/music/nas/mp3/Wagner/Walkure - Stein, Bayreuth 1970, 11597-3/Walkuere - Disc 2/02. Was verlangst du.mp3 is missing ID3 tag [albumartist], using Various Artists as fallback
2022-06-28 07:26:48 WARNING (MainThread) [music_assistant.music.file] /media/music/nas/mp3/Wagner/Walkure - Stein, Bayreuth 1970, 11597-3/Walkuere - Disc 2/05. Ein andres ist's.mp3 is missing ID3 tag [albumartist], using Various Artists as fallback
2022-06-28 07:26:48 WARNING (MainThread) [music_assistant.music.file] /media/music/nas/mp3/Wagner/Walkure - Stein, Bayreuth 1970, 11597-3/Walkuere - Disc 2/10. So grüße mir Walhall, grüße mir Wotan.mp3 is missing ID3 tag [albumartist], using Various Artists as fallback
2022-06-28 07:26:48 WARNING (MainThread) [music_assistant.music.file] /media/music/nas/mp3/Wagner/Walkure - Stein, Bayreuth 1970, 11597-3/Walkuere - Disc 2/09. Siegmund! Sieh auf mich!.mp3 is missing ID3 tag [albumartist], using Various Artists as fallback
2022-06-28 07:26:49 WARNING (MainThread) [music_assistant.music.file] /media/music/nas/mp3/Wagner/Walkure - Stein, Bayreuth 1970, 11597-3/Walkuere - Disc 2/07. So sah ich Siegvater nie.mp3 is missing ID3 tag [albumartist], using Various Artists as fallback```

etc etc.

Appears not to be as obvious as we thought it was. Apparently all tracks are re-indexed/added to the DB. So they must have been deleted too? Dont think that deletion is logged, so I cant tell.

Since I dont have a large Mount yet (only testing for now), this doesnt take too long, but it still is something to think about going forward

**Comment by Mariusthvdb** [comment] 2022-06-28 05:40
what's more, when I click the Various Artists tab on Albums:

<img width="1379" alt="Schermafbeelding 2022-06-28 om 07 37 14" src="https://user-images.githubusercontent.com/33354141/176101411-27e9aa8d-a97f-4ca8-8e5d-a1bb70ff2353.png">

and then an Album in that:

<img width="808" alt="Schermafbeelding 2022-06-28 om 07 37 01" src="https://user-images.githubusercontent.com/33354141/176101463-09dfa295-a698-4a32-b2e2-96fd211edc58.png">

there are no Tracks...

**Comment by Mariusthvdb** [comment] 2022-06-28 07:03
@erkr Eric, please re-open

**Comment by marcelveldt** [comment] 2022-06-28 23:48
I think the only proper way to solve this is when MA directly talks to the samba share and "known" when its not available.
Current approach with mounting is just too risky. BTW: a small tip could be to have the files in a subfolder on the NAS.

So e.g. mount //nas/data to /media/data but have the music files in //nas/data/music. If you add /media/data/music to MA it will error on the directory not existing (/media/data/music) and skip the sync

**Comment by vk2him** [comment] 2022-06-29 09:59
I'm wondering if sending a Wake on Lan command will wake up the NAS as I'm sure my NAS responds to that if asleep - FYI my NAS is on 24/7 as it hosting a security camera NVR system. 

Perhaps @Mariusthvdb could test this theory by sending a WOL command (there's a number of free utilities that will do this). If it wakes, could the WOL command be sent preceding all MA commands?

**Comment by Mariusthvdb** [comment] 2022-06-29 11:31
Well not sure I like that approach .
Sure I have the Wol service, but I don’t want to wake the Nas during those off hours.

I agee with Marcel this should be a integration feature and not rely on external mount commands.

if the source is offline, just wait until it’s back online again and continue. Don’t manipulate the Db if source is offline

**Comment by marcelveldt** [comment] 2022-07-27 13:30
I'm going to close this issue report as it's a non-issue:

- If you want to guard against the NAS in standby, make sure to add a subfolder to MA config so that folder itself will become unavailable. That will skip the scan.

- Mounting the NAS in a folder is a workaround for the missing direct smb support in MA

**Closed by marcelveldt** 2022-07-27 13:30 UTC
Labels: documentation, enhancement
