### ISSUE TITLE
Music assistant does not show what's currently playing after playlist's 1st song ends.

### ISSUE THREAD

**Issue by ronluna** [music-assistant/hass-music-assistant#2489] opened 2024-06-15 23:43 UTC
### What version of Music Assistant has the issue?

2.1.0b6

### What version of the Home Assistant Integration have you got installed?

2024.6.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Music Assistant keeps showing the 1st song of a playlist even after a few songs have been played. 

### How to reproduce

add a playlist into the queue, start playing the playlist and lets a few song get by... Music assistant will continue to show the 1st track on the playlist

### Music Providers

Spotify
Deezer

### Player Providers

Snapcast

### Full log output

Not relevant info

### Additional information

n/a

### What version of Home Assistant Core are your running

2024.2.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment] 2024-06-15 23:46
Is ENABLE CROSSFADE on or off?

**Comment by SantiagoSotoC** [comment] 2024-06-15 23:52
Did it happen before or only since this beta ?

**Comment by ronluna** [comment] 2024-06-15 23:55
> Did it happen before or only since this beta ?

OFF.

**Comment by ronluna** [comment] 2024-06-16 00:02
> Did it happen before or only since this beta ?

Since before... I just didn't report it as I thought someone else knew about it and a fix was in the queue.

**Comment by ronluna** [comment] 2024-06-16 00:43
Digging a little deeper, it appears the grouping bug also affect this. 

The artwork updates correctly on single player or groups with up to two players anything grouped above two players the currently playing artwork and info does not get updated .

**Comment by SantiagoSotoC** [comment] 2024-07-01 22:21
I think I found the bug, for the next beta it should be fixed

**Comment by ronluna** [comment] 2024-07-05 12:37
Hello @SantiagoSotoC , Just installed 2.1.0b10 and snapcast is behaving much better although while playing tracks in a playlist they do change but the artwork showing is one track behind from what's being playing.

**Comment by SantiagoSotoC** [comment] 2024-07-05 13:03
> Hello @SantiagoSotoC , Just installed 2.1.0b10 and snapcast is behaving much better although while playing tracks in a playlist they do change but the artwork showing is one track behind from what's being playing. 
> 
> No errors in the logs. 

Yes, I know, it still gives problems as a workaround while I finish fixing it, you can enable crossfade.
With the crossfade it should not give problems, the problem is the silence in the stream.

**Comment by SantiagoSotoC** [comment] 2024-07-07 03:36
[This repairs it ](https://github.com/music-assistant/server/pull/1460)

**Comment by ronluna** [comment] 2024-07-07 14:02
Nice, waiting to be added to the next beta for testing!

**Comment by OzGav** [comment] 2024-07-09 01:29
@ronluna beta 14 has been released

**Comment by ronluna** [comment] 2024-07-09 02:27
Testing... Artwork seems to be updating correctly, even after disabling crossfade... Nice!!!!

**Closed** 2024-07-09 02:36 UTC
Labels: bug, Snapcast, Fix to be Confirmed
