### ISSUE TITLE
YT Music - Job [Library sync for provider Youtube Music] failed with error 'musicShelfRenderer'.

### ISSUE THREAD

**Issue by OldShaterhan** [music-assistant/hass-music-assistant#1058] opened 2023-01-09 00:08 UTC
### What version of Music Assistant has the issue?

2022.12.1

### The problem

I'm trying to use YT Music, but without a success for now.

### How to reproduce

Configuring YT Music.

### Relevant log output

Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:232
First occurred: 00:48:05 (3 occurrences)
Last logged: 01:03:58

Job [Library sync for provider Youtube Music] failed with error 'musicShelfRenderer'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 402, in sync_library
    async for prov_item in self._get_library_gen(media_type)():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 133, in get_library_artists
    artists_obj = await get_library_artists(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 105, in get_library_artists
    return await loop.run_in_executor(None, _get_library_artists)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 95, in _get_library_artists
    artists = ytm.get_library_subscriptions(limit=9999)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 178, in get_library_subscriptions
    return parse_library_artists(
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/library.py", line 84, in parse_library_artists
    results = get_library_contents(response, MUSIC_SHELF)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/library.py", line 113, in get_library_contents
    return nav(results, ITEM_SECTION + renderer)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 76, in nav
    raise err
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 70, in nav
    root = root[k]
KeyError: 'musicShelfRenderer'

### What version of Home Assistant Core are your running

2023.1.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment] 2023-01-09 14:47
Hi @OldShaterhan 
Just a trivial question first: you have a premium account and followed the instructions for installing YT: https://github.com/music-assistant/hass-music-assistant/discussions/606 ?
Best Eric

**Comment by OldShaterhan** [comment] 2023-01-09 14:59
Hi @erkr,
Yes, I have YouTube Premium and cookie (one thing here - mine cookie is starting with VISITOR_ something, not LOGIN Info, but I have been logged to the YT, so I have no idea why

**Comment by erkr** [comment] 2023-01-10 10:24
Did you explicitly log in with your browser (not only the app)?
Also make sure you select the right message that is representing the cookie after the login (the first one the list is probably before you logged in)
Best Eric

**Comment by OldShaterhan** [comment] 2023-01-11 00:18
I'm using the music.youtube.com and the I have copied cookie from POST requests there (while playing some song as a logged user - I have "constant" session - I'm not logging out from YT).

**Comment by OzGav** [comment] 2023-01-11 13:27
That doesnt seem to match what the guide says to expect https://github.com/music-assistant/hass-music-assistant/discussions/606

**Comment by OldShaterhan** [comment] 2023-01-11 13:34
@OzGav it doesn't start with LOGIN_INFO, but LOGIN_INFO is third part of cookie (note that I changed value not to provide values here). I'm not sure why this starts different for me, but finally main part is there.

**Comment by OzGav** [comment] 2023-01-11 13:37
OK sorry I didn't know you modified the string. Are you copying it from the devtools as per here: https://github.com/music-assistant/hass-music-assistant/discussions/606#discussioncomment-3227576

**Comment by OldShaterhan** [comment] 2023-01-11 22:48
Yes, as mentioned in reply to @erkr

**Comment by OzGav** [comment] 2023-01-11 23:36
OK @MarvinSchenkel any ideas?

**Comment by MarvinSchenkel** [comment] 2023-01-12 08:33
I think your error is caused by an incompatible version of ytmusicapi. We seem to have some issues with dependencies to the ytmusicapi library. Theoretically, users of MA could have a different version of that library depending on when they reboot HA. This will be solved in the upcoming 2.0 release, so we have to be a bit more patient until Marcel releases 2.0 :-)

**Comment by OzGav** [comment] 2023-03-17 21:58
Please confirm if this still an issue with MA 2.0.0b7 (or later depending upon when you test)

**Comment by OzGav** [comment] 2023-03-28 12:42
Closing due to no follow up. Can reopen if this is still an issue.

**Closed by OzGav** 2023-03-28 12:42 UTC
Labels: bug, music provider
