### ISSUE TITLE
Back button Display issue

### ISSUE THREAD

**Issue by darrenblanchard** [music-assistant/hass-music-assistant#208] opened 2022-05-21 11:04 UTC
This is happening in latest 1.1.13 with Chrome and Edge, if you select artist and once they are viewed hit the "Back" in browser the page included two sidebars in HA,  hitting refresh seemed to correct as a work around. this happens with any of the selections in Music Assistant.

![image](https://user-images.githubusercontent.com/71443530/169648796-15b3e6e9-7ad8-4465-8fd9-8567e5132113.png)

**Comment by marcelveldt** [comment] 2022-05-21 11:11
Yes, that is unavoidable I'm afraid because the MA frontend is loaded as iframe in HA.
That's why there is a separate back button in the MA header...

I'll have a look if we can intercept the browser back button...

**Comment by darrenblanchard** [comment] 2022-05-21 11:24
Thanks really just an annoyance, I'm waiting for the latest resync but have a database issue where filesystem artist that are in spotify playlist, are hidden in the artist by default, their albums are displaying under albums, I've been drilling into the album and artist and manually adding to Library. Once sync is done, I will create an issue if it's still happening.

**Comment by marcelveldt** [comment] 2022-05-21 22:57
Artists are only added to the library if you actually have albums for that albumartist on disk OR you have the artist as "favorite" on the streaming provider(s).

So artists from songs within playlists are not added as library/favorite artist otherwise you'll end up with 1000s of artists that are just on some playlists. Of course you can just press that heart button/icon to add the artist to the library.

**Comment by darrenblanchard** [comment] 2022-05-22 16:54
the artist I have missing, I do have the actual albums on the filesystem provider, they also appear on Spotify maybe spotify first before the filesystem refresh has been done.

**Comment by marcelveldt** [comment] 2022-05-22 17:46
@darrenblanchard that is strange. An artist marked as "followed" on Spotify or album artist on your disk should really show up in the library artists. Are you testing with the latest version (1.1.14) ? especially the last 2 versions had some big improvements regarding the library matching/linking.

**Closed** 2022-05-23 11:30 UTC

**Comment by dasfuu** [comment] 2022-06-17 20:52
I have Grocy and Zigbee2Mqtt in iframes in a dashboard. The back button works as intended in both cases. I don't know if they do anything special.
