### ISSUE TITLE
Seeking Pauses Playback

### ISSUE THREAD

**Issue by a-pir1** [music-assistant/hass-music-assistant#299] opened 2022-06-03 18:04 UTC
Attempting to tap/click anywhere on the seekbar will pause my playback and set it back to 0:00 when I try to resume it.  I am running 2022.6 BETA 2.

**Comment by marcelveldt** [comment] 2022-06-05 12:44
Can you tell me which device you are testing this with ?
At the moment there are some issues with Sonos devices which should be fixed in next release

**Comment by erkr** [comment] 2022-06-11 18:50
@a-pir1, in the latest v06b3 Marcel made changes in the seek functionality. Could you paarse have a look of this issue is solved. Thanks Eric

**Comment by erkr** [comment] 2022-06-14 18:05
I verified this issue. It works, but the behavior is still awkward: 
When pressing the seek bar, the player still goes back to 0:00 shortly, then it jumps to the selected time, and resumes.
So the issue is solved. usability can be enhanced though

**Closed by erkr** 2022-06-14 18:05 UTC
Labels: bug, Completed

**Comment by marcelveldt** [comment] 2022-06-14 18:08
I can try to allow for an optimistic state for x seconds while its receiving the new stream (seeking starts a new stream request)
