### ISSUE TITLE
Job failed with error 

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#581] opened 2022-07-03 11:12 UTC
### What version of Music Assistant has the issue?

2022.6.10

### The problem

Saw the following in the logs. Not sure if it is a fanart.tv issue. Not sure where the 48 comes from either as I don’t have an album or artist by that name?

### How to reproduce

So far this is a one off

### Relevant log output

```
Logger: music_assistant
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:244 
First occurred: July 2, 2022, 5:05:01 PM (2 occurrences) 
Last logged: July 2, 2022, 5:05:01 PM

Job [Add database://album/48 to database] failed with error 'e2996feb-86b9-3550-88ec-f1c9c9af3961/details'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 99, in add
    await self.mass.metadata.get_album_metadata(item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/metadata/__init__.py", line 83, in get_album_metadata
    if metadata := await self.fanarttv.get_album_metadata(album):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/metadata/fanarttv.py", line 70, in get_album_metadata
    data = data["albums"][album.musicbrainz_id]
KeyError: 'e2996feb-86b9-3550-88ec-f1c9c9af3961/details'
```

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment] 2022-07-04 15:30
@OzGav 
Is this a duplicate of your issue #566 raised a few days ago?

**Comment by OzGav** [comment] 2022-07-04 21:25
Not sure. The error is different but it might be related?

**Comment by erkr** [comment] 2022-07-05 08:58
Thanks. As the issues are linked now, I close this one

**Closed** 2022-07-05 08:58 UTC
Labels: duplicate, related
