### ISSUE TITLE
Can't authenticate Spotify

### ISSUE THREAD

**Issue by Fatalmose** [music-assistant/hass-music-assistant#2784] opened 2024-08-20 18:17 UTC
### What version of Music Assistant has the issue?

2024.8.0

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

With the latest music assistant server update we need to authenticate Spotify again.
The process will open in a new popup window it says , but nothing happens , after 30 sec. I get a window with 999 in it , when you click ok nothing happens and Spotify is not authenticated.
When I open up Spotify during the process , music assistant doesn't show up either.
I don't have popup blockers installed.

### How to reproduce

I'ff installed the previous backup to make it work again.

### Music Providers

Spotify

### Player Providers

All of my media players because of Spotify not authenticated. 

### What version of Home Assistant Core are your running

2024.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment] 2024-08-20 20:53
The MA version you have listed is not correct. Please look in MA SETTINGS>>CORE and update the report.

**Comment by marcelveldt** [comment] 2024-08-21 00:03
I assume you are trying this from an iOS device ?
The next beta has a small workaround for that (as it blocks the whole tab)

**Comment by Fatalmose** [comment] 2024-08-21 04:21
Hello.

Yes indeed.
But also tried it on my Mac.
Same problem…
When I update with the 2.2.0rc1 server update I need to authenticate
Spotify again and that is not working…
Nothing happens…

Regards.

JS.

**Comment by OzGav** [comment] 2024-08-21 04:33
Then the pop up must be getting blocked. What browser are you using on your Mac?

**Comment by Fatalmose** [comment] 2024-08-21 05:00
Hello.

I’m using Safari as default browser.

Regards.

JS.

**Comment by OzGav** [comment] 2024-08-21 05:13
Yeah we have seen issues with Safari. Please try Chrome

**Comment by Fatalmose** [comment] 2024-08-21 05:15
Ok…
Thanks for the reply and input…

**Comment by Fatalmose** [comment] 2024-08-21 06:21
I just tried using Chrome , Edge and Safari on my iPhone.
But still nothing happens.
I click on Authentificate the blue wheel turns and after a while I get as
shown on the foto…
And Authetification with Spotify fails.

Regards.

JS.

**Comment by OzGav** [comment] 2024-08-21 06:51
The trouble is iOS uses the same underlying browser engine for all browsers. That's why I mentioned using your Mac above. To rule out all these variables please try Chrome on your Mac and let us know how you go.

**Comment by Fatalmose** [comment] 2024-08-21 06:53
Ok…
As soon as I get home this will be done.
I will keep you informed…
Many thanks for the help and reply.

Regards.

JS.

**Comment by marcelveldt** [comment] 2024-08-21 08:19
In the 2.2.0 RC1 version I added a workaround for iOS where you get an additional button to click to continue

**Comment by Fatalmose** [comment] 2024-08-21 08:44
I’f got the 2.2.rC1 installed.
I’m sorry but I don’t see an additional button to click on…
I can only click on , « Authenticate with Spotify »
And when I do nothing happens when using iPhone.
Will try this evening using Chrome in my Mac.

**Comment by marcelveldt** [comment] 2024-08-21 08:48
This is what you should see from an iPhone (tested with safari)

![Image](https://github.com/user-attachments/assets/681a6982-8b04-4e0b-95db-bceda65f198c)

**Comment by marcelveldt** [comment] 2024-08-21 08:49
argh... I now see it doesn't work with the HA companion app, sigh..
I'll add some more bandaid

**Comment by dblanc42** [comment] 2024-08-21 08:52
@marcelveldt - sorry to jump on this, but found the thread as I was looking for help on a similar issue.
I have what seems to be the same issue: click on authenticate, and the new window does not launch , but I use windows and chrome, no popup blockers.
Server v2.1.4
It is made more complicated by the fact that I had changed my spotify password, so I thought this was the cause of re-authentication required.
Is there any information I can get to help ? (relative newbie here, so may need a bit of guidance...)

What version of Music Assistant has the issue?
2.1.4

What version of the Home Assistant Integration have you got installed?
Core
2024.8.2
Supervisor
2024.08.0
Operating System
13.0
Frontend
20240809.0

Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?
 Yes
The problem
With the latest music assistant server update we need to authenticate Spotify again.
The process will open in a new popup window it says , but nothing happens , after 30 sec. I get a window with 999 in it , when you click ok nothing happens and Spotify is not authenticated.
When I open up Spotify during the process , music assistant doesn't show up either.
I don't have popup blockers installed.

How to reproduce
re-start HA and try to add spotify as provider

Music Providers
Spotify

Player Providers
N/A

Full log output
No response

Additional information
No response

What version of Home Assistant Core are your running
Core
2024.8.2


What type of installation are you running?
Home Assistant OS

On what type of hardware are you running?
Raspberry Pi 4

**Comment by dblanc42** [comment] 2024-08-21 09:26
> @dblanc42 wait for the next 2.2.0 release please. You are still running the stable version which uses spotify connect auth (there is no popup)

Thank you, and sorry for the interruption... I will check with 2.2.0 indeed. I followed the info in the config page (FYI)
![image](https://github.com/user-attachments/assets/44a83209-3c17-42e3-ab85-fd93307705e7)

**Comment by marcelveldt** [comment] 2024-08-21 10:10
Ah, yeah we have been a bit too fanatic with updating the docs. That info is already for the 2.2 release (some folks are testing the beta). If you are still on 2.1.x stable, then clicking the button results in a Spotify connect auth session: you need to open the Spotify app and select music assistant as speaker to play something.

But 2.2 will be released later today so you can also just wait a little bit ;-)

**Comment by Fatalmose** [comment] 2024-08-21 10:28
Don’t worry Marcel I’ll wait….

**Comment by dblanc42** [comment] 2024-08-21 11:05
same here, no rush... thanks for all the great work.

**Comment by tbrasser** [comment] 2024-08-21 18:48
The new spotify auth has worked for me, but broke in either RC1 or RC2, at least now on RC2, no popup appears

**Comment by marcelveldt** [comment] 2024-08-21 21:47
> The new spotify auth has worked for me, but broke in either RC1 or RC2, at least now on RC2, no popup appears (android, chrome)

2.2.0 stable has landed (with the -final- new spotify auth flow) - we also released 2.3.0 beta 0 with these fixes included

**Comment by codemonkey2k5** [comment] 2024-08-21 23:39
I just upgraded to version: 2.2.0.  I cannot get the authentication to do anything but give me a 999 error after a few minutes.
No pop-up ever appears.  I have tried on Android, PC using Chrome, Edge, and Firefox.  None of them work.

I'm running HA Ver: 13.1.

**Comment by philadou** [comment] 2024-08-21 23:45
the same here... 2.2.0 and getting the 999 error on a Mac with Safari, Firefox and Chrome :(

**Comment by 1joneselliot** [comment] 2024-08-22 00:49
Same here. On HAOS 13.1, MA 2.2.0. Tried on Chrome (Windows) and iOS, Authenticate times out with 999. 

Logs show 
2024-08-21 15:03:48.035 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)

**Fix: ** Delete the Spotify music provider and re-add it. Authentication popup works as expected after re-adding.

**Comment by OzGav** [comment] 2024-08-22 01:39
@1joneselliot thanks for identifying a fix. We will see if we can work out why that happened in the first place. Only thing I would say is wait until the log says the provider has been removed before adding it again

**Comment by mrcushing** [comment] 2024-08-22 01:52
I had the same problems as others here.

If you delete spotify as a music provider then re-add it, however, it worked just fine.

**Comment by OzGav** [comment] 2024-08-22 06:22
I believe this can be resolved with re-addon the provider. If there are any other problems with logging in to Spotify add to this other issue https://github.com/music-assistant/hass-music-assistant/issues/2754

**Closed by OzGav** 2024-08-22 06:22 UTC
Labels: Fix to be Confirmed

**Comment by OzGav** [comment] 2024-08-22 08:38
A new update will be available in the next 30mins which will mean you no longer need to remove the provider to get the authentication to work.

**Comment by Fatalmose** [comment] 2024-08-22 11:49
Hello.

It works again…
Many thanks for all the work…
Respect….

Regards.

JS.
