### ISSUE TITLE
Tune-In plugin adding multiple streams for certain radio stations which fail to work, while single stream stations do work

### ISSUE THREAD

**Issue by ufankhau** [music-assistant/hass-music-assistant#2386] opened 2024-05-29 09:01 UTC
### What version of Music Assistant has the issue?

2.1.0b1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Tune-In provides for some radio stations (e.g. Radio Swiss Classic or Radio Swiss Pop) several streams. Such entries do not work, while stations with a single stream do work correctly.
![Image](https://github.com/music-assistant/hass-music-assistant/assets/53044741/5660d953-acd1-4cdf-8892-975d57458aa0)
![Image 29 05 2024 at 10 54](https://github.com/music-assistant/hass-music-assistant/assets/53044741/8186cd98-8405-4b2f-a0a5-8a98a693d2aa)

### How to reproduce

select in your tune-in account Radio Swiss Classic

### Music Providers

tune-in

### Player Providers

Airplay

### What version of Home Assistant Core are your running

2024.4.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment] 2024-05-29 16:26
Do not try to fill in the conclusion yourself. The problem is that Radio Swiss is not working on Tune-In. 
If that has anything to do with the fact that multiple streams are offered is to be seen later.

**Comment by ufankhau** [comment] 2024-05-29 17:05
I politely disagree with your reply, Marcel. Radio Swiss Classic (shown radio station on the screen shot) does perfectly work on Tune-In, Radio Swiss might not exit and might hence not work.

**Comment by marcelveldt** [comment] 2024-06-15 05:19
Investigated the issue, like I suspected it had nothing to do with the fact that there were multiple streams in the radio station. In fact it was a codec detection issue which I just fixed. Next update (2.0.7 or 2.1.0b6) contains this fix.

**Comment by OzGav** [comment] 2024-06-15 14:35
@ufankhau Please confirm this has been fixed.

**Comment by ufankhau** [comment] 2024-06-16 09:03
Thx Marcel for fixing the issue with no stream being picked up when several streams are offered by Tune-In Radio for a specific radio station. It is still unclear to me, which stream music-assistant does pick up by default (acc or mp3), when several streams are available. The UI does furthermore not always show the "type" of stream (see ? in screen shot attached). I have so far not identified a pattern of when the type is shown correctly and when a "?" is showing up.
Last but not least music-assistant shows sometimes 2 streams in the "Queue" section (see attached screen prints), even for a radio station with a single stream offered by Tune-In Radio (e.g. Radio Beach Westkust).

So, overall a great step in the right direction with some glitches remaining to be fixed (e.g. "?" in UI and double entry in Queue)

![Image 16 06 2024 at 10 44](https://github.com/music-assistant/hass-music-assistant/assets/53044741/34c60337-59e8-4e72-97e1-4f94bc98f822)
![Image 16 06 2024 at 10 44](https://github.com/music-assistant/hass-music-assistant/assets/53044741/f189179c-36a9-4553-8e12-db5694e7cfec)

PS: I like very much the changes brought to the volume bar with the - and + buttons .... for the time being the default step change seems to be +/- 5% .... could this value be defined by the user in future? I personally prefer +/- 2% changes in volume ....

**Comment by OzGav** [comment] 2024-06-16 11:38
On the second image that just looks like you have added it twice

**Comment by ufankhau** [comment] 2024-06-16 12:36
Sorry, but I did not add it twice .... I have repeated the steps and cleared the queue ... 

![Image 16 06 2024 at 14 27](https://github.com/music-assistant/hass-music-assistant/assets/53044741/0c21c083-0d37-44d7-b2b3-f3b4b82b5d14)

.. selected the desired radio station and started it with "Play Now (clear queue)" 

![Image 16 06 2024 at 14 31](https://github.com/music-assistant/hass-music-assistant/assets/53044741/8e4ee065-46d9-4c27-b58a-a78abd214615)


... the stream starts correctly, the queue shows 1, but in fact it lists two items .....

![Image 16 06 2024 at 14 32](https://github.com/music-assistant/hass-music-assistant/assets/53044741/19001cf0-6f1d-4ad6-a091-1dcc38aef057)

... sorry for being such a pain .....

**Comment by marcelveldt** [comment] 2024-07-22 19:50
I really can not reproduce this bug. Can somebody else try to reproduce it otherwise we will close this.

**Comment by OzGav** [comment] 2024-07-22 21:26
I had seen it before but it’s not happening now so has possibly been fixed by other changes.

**Closed** 2024-07-27 01:58 UTC
Labels: bug, More info
