### ISSUE TITLE
Cannot add Ytube Music to Music Assistant

### ISSUE THREAD

**Issue by cherryocola** [music-assistant/hass-music-assistant#3138] opened 2024-11-06 14:49 UTC
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

2024.11.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When authenticating Youtube music and saving the token generated, the following error was produced

ERROR: [youtube+yt_access_token] dQw4w9WgXcQ: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

### How to reproduce

1. Authenticate ytube music
2. Save

### Music Providers

Ytube Music

### Player Providers

Google Cast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17648745/music-assistant.log)

### What version of Home Assistant Core are your running

2024.10.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by contactnat** [comment] 2024-11-07 00:52
yeah mine has stopped working after yesterdays update - I have not tried to trouble shoot or reauthenticate or anything, just acknowledging that it stopped.

**Comment by OzGav** [comment] 2024-11-10 13:03
People are finding a solution is to create another brand account. https://sproutsocial.com/glossary/youtube-brand-account/

**Comment by contactnat** [comment] 2024-11-11 01:39
> People are finding a solution is to create another brand account. https://sproutsocial.com/glossary/youtube-brand-account/

ah that does seem to work, although now my playlists need to be moved over, bit annoying LOL, I understand YT Music is best efforts, so just happy to have it working again! thanks.

**Comment by OzGav** [comment] 2024-11-11 01:41
Our best guess is YouTube is doing something deliberate to deny access.

**Comment by contactnat** [comment] 2024-11-11 03:06
> Our best guess is YouTube is doing something deliberate to deny access.

all the more reason to work towards not being dependent on them, and google in general - that's my home lab driver at the moment..

**Comment by Dion-HA** [comment] 2024-11-11 09:28
I'm having the same issue, e.g. ERROR: [youtube+yt_access_token]... 

I can't connect my Youtube (personal) account with Music Assistance any more, that was previously working.

**Comment by OzGav** [comment] 2024-11-11 09:34
@Dion-HA read this issue for the workaround….

**Comment by Dion-HA** [comment] 2024-11-11 09:41
> @Dion-HA read this issue for the workaround….

@OzGav  read what for a workaround? 

I looked at the Youtube brand accounts, we should not need to create a new Youtube brand account, just to link Youtube Music with Music Assistant, it was working previously. 

I tried linking Spotify and that worked without any issues, but I don't use Spotify, I ony use Youtube Music :)

**Comment by OzGav** [comment] 2024-11-11 10:23
@Dion-HA Do you understand this is Google's doing? Please contact them with your frsutrations.

**Comment by cherryocola** [comment] 2024-11-11 10:25
Sigh... looks like I have to go back to ytubemediaplayer

**Comment by OzGav** [comment] 2024-11-11 10:59
@cherryocola So the workaround is not working for you?

**Comment by cherryocola** [comment] 2024-11-11 11:33
> @cherryocola So the workaround is not working for you?

Apologies, I havent tried it I am sure it works, I just didnt want another google account. thanks.

**Comment by OzGav** [comment] 2024-11-11 11:39
@cherryocola It isn't another Google account. It is a "brand" within your Google account.

**Comment by OzGav** [comment] 2024-11-11 12:03
@cherryocola Not at this time. You are the first person to say they tried creating a brand account and it didn't work...

**Comment by cherryocola** [comment] 2024-11-11 12:14
> @cherryocola Not at this time. You are the first person to say they tried creating a brand account and it didn't work...
> 
> edit: Keep an eye on things as sometimes Google reverts these changes and everything just starts working again...

maybe because I always had a channel and I only added a branding? I probably need another account.

**Comment by devedsmith** [comment] 2024-11-11 17:16
Mine just stopped working with the same error

**Comment by zed0** [comment] 2024-11-11 19:16
yt-dlp is having the same issue: https://github.com/yt-dlp/yt-dlp/issues/11503

**Comment by Peyto79** [comment] 2024-11-12 06:08
I just tried the workaround but I get the same error. The workaround seems not to work anymore. I get the same HTTP400 error with the new "brand account"

**Comment by Orsonorix** [comment] 2024-11-12 11:32
Any other solutions other than brand account?

**Comment by zed0** [comment] 2024-11-12 11:56
From the yt-dlp thread it seems like the real fix is to store a cookie to use for Auth. Unfortunately this will require rewriting the music-assistant YouTube auth code and a much more complicated user flow involving extracting cookies from a browser

**Comment by EvanWasHere-zz** [comment] 2024-11-12 17:46
I already had a brand account.  But I created another one to try the solution above.  And I got the same error.

**Comment by OzGav** [comment] 2024-11-12 18:52
It appears that OAUTH support has been removed. An alternate method of logging in is being investigated. This will take some time.

**Comment by Dion-HA** [comment] 2024-11-13 01:57
My Youtube Music is still working with Music Assistant since I set in up yesterday using the Youtube Brand account work around with my existing personal Google account, I'm reluctant to remove this connection and set it up again as it's still working for me now :)

**Comment by SIR-Inc** [comment] 2024-11-13 20:24
I doubt it adds any value to resolving this issue but I'm curious if anyone else is experiencing numerous Home Assistant failed login attempts from Google datacenters since the YouTube Music issue started in Music Assistant. Here is an example:
Login attempt failed
Login attempt or request with invalid authentication from 51.150.48.34.bc.googleusercontent.com (34.48.150.51). See the log for details.

What surprises me is that this has continued even after I removed YouTube Music as a provider in Music Assistant. Oh well.

**Comment by grainsoflight** [comment] 2024-11-14 05:10
You can contact google about this and give them your thoughts here https://support.google.com/youtube/gethelp

**Comment by bazsc20ne** [comment] 2024-11-14 16:59
> Sigh... looks like I have to go back to ytubemediaplayer

that doesn't work for me either :(

**Comment by Zsoltt-dom** [comment] 2024-11-14 17:14
Same issue here. Adding a Brand account won't work.
`ERROR: [youtube+yt_access_token] dQw4w9WgXcQ: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)`

**Comment by TheWebMachine** [comment] 2024-11-14 18:10
So, everything was working perfectly fine for me until last night when I updated the HA Integration (not the add-on). Suddenly, both MA *AND* my YT Music app on my phone started throwing a ton of errors. On the YTM app, it would just keep skipping through tracks as unavailable until hitting the end of the queue. During this period, I saw various errors on MA about unavailable/invalid tokens, API availability, etc. 

Hours later, YTM app slowly regained the ability to start playing tracks again, albeit with some random track skips, until it finally regained full function this morning. YTM now can play music again, but even after fully removing and trying to re-add YTM to MA, I get the following errors:

````
WARNING: [youtube+yt_access_token] Incomplete data received in embedded initial data; re-fetching using API.
WARNING: [youtube+yt_access_token] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+yt_access_token] HTTP Error 400: Bad Request. Retrying (1/3)...
WARNING: [youtube+yt_access_token] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+yt_access_token] HTTP Error 400: Bad Request. Retrying (2/3)...
WARNING: [youtube+yt_access_token] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+yt_access_token] HTTP Error 400: Bad Request. Retrying (3/3)...
WARNING: [youtube+yt_access_token] YouTube said: ERROR - Request contains an invalid argument.
ERROR: [youtube+yt_access_token] dQw4w9WgXcQ: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
2024-11-14 11:58:16.256 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/save: ERROR: [youtube+yt_access_token] dQw4w9WgXcQ: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
````

To be clear, I already have multiple brand accounts on my main account and none of them work. So, I have two theories at this time:

1. YTM implemented some new rate limiting and MA's syncing is now hitting this limit (which is why a new brand account worked for some; because a sync on a new clean brand would not hit the rate limit on initial sync)
2. YTM has decided to break or change some bit that our current YTM sync engine relies on; perhaps accidentally, perhaps intentionally (MA has massively gained in popularity in recent months and Google may have finally noticed the uptick in our traffic)

Let me know if there is any testing I can help perform from my end.

**Comment by afs5327** [comment] 2024-11-14 21:35
I'm not sure if it helps, or if this wouldn't work with MA, but the [HA-Google-Home](https://github.com/leikoilja/ha-google-home/blob/master/README.md#prerequisites) uses [Google Authentication Tokens](https://github.com/leikoilja/glocaltokens#quickstart) for access to Google accounts, and that add-on is still working for me.

There are tons of forum posts about folks having issues with using the tokens, so they can be a bit fiddly, but once I got it working for the HA-Google-Home add-on, it's been solid for months now.

**Comment by feinadam** [comment] 2024-11-15 06:10
Same issue at me :(

**Comment by TheWebMachine** [comment] 2024-11-15 06:39
> I'm not sure if it helps, or if this wouldn't work with MA, but the [HA-Google-Home](https://github.com/leikoilja/ha-google-home/blob/master/README.md#prerequisites) uses [Google Authentication Tokens](https://github.com/leikoilja/glocaltokens#quickstart) for access to Google accounts, and that add-on is still working for me.
> 
> There are tons of forum posts about folks having issues with using the tokens, so they can be a bit fiddly, but once I got it working for the HA-Google-Home add-on, it's been solid for months now.

I don't think it's the tokens themselves in this case. I think the change is in how the API is parsing requests against YTM. Perhaps a slow server-side rollout across all YTM accounts, which would explain why it has seemingly affected us in waves over the last week or so. Mine worked flawlessly until last night while some have been having the issue for a week or more.

**Comment by EFH52** [comment] 2024-11-15 16:03
Brand account alternative solution failed to resolve the issue here.

**Comment by ufondu88** [comment] 2024-11-15 18:16
Brand account failed for me too

**Comment by Vergil365** [comment] 2024-11-15 19:19
Brand account failed for me as well

**Comment by mterry63** [comment] 2024-11-15 20:37
Just for clarity for anyone that created a brand account as a solution, are you supposed to somehow authenticate with that account? I just created the brand account but authenticated with my normal account.

**Comment by leolionart** [comment] 2024-11-16 01:14
<img width="865" alt="image" src="https://github.com/user-attachments/assets/39217a55-3feb-4daf-99ec-26ddc1f6ecee">
I created a new brand account on the old account, even created a completely new google account. But it seems nothing has changed. Still ERROR 400 when Add Youtube Music

**Comment by Dion-HA** [comment] 2024-11-16 02:33
> > I'm not sure if it helps, or if this wouldn't work with MA, but the [HA-Google-Home](https://github.com/leikoilja/ha-google-home/blob/master/README.md#prerequisites) uses [Google Authentication Tokens](https://github.com/leikoilja/glocaltokens#quickstart) for access to Google accounts, and that add-on is still working for me.
> > There are tons of forum posts about folks having issues with using the tokens, so they can be a bit fiddly, but once I got it working for the HA-Google-Home add-on, it's been solid for months now.
> 
> I don't think it's the tokens themselves in this case. I think the change is in how the API is parsing requests against YTM. Perhaps a slow server-side rollout across all YTM accounts, which would explain why it has seemingly affected us in waves over the last week or so. Mine worked flawlessly until last night while some have been having the issue for a week or more.

I'm now having the same issue using the YT Brand account to authenticate with MA, e.g. 
ERROR: [youtube+yt_access_token] dQw4w9WgXcQ: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

**Comment by TheWebMachine** [comment] 2024-11-16 03:23
> I'm now having the same issue using the YT Brand account to authenticate with MA, e.g. ERROR: [youtube+yt_access_token] dQw4w9WgXcQ: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

It's almost certainly an API change and this means we'd have to wait for the maintainer of the Python library MA is depending on (yt-dlp) to find and correct accordingly. This will take time. I'm lowkey sad that every time I get used to using YTM again, it breaks again.

**Comment by CappyT** [comment] 2024-11-16 10:54
Youtube dropped support for OAuth as described in yt-dlp comment [here](https://github.com/yt-dlp/yt-dlp/issues/11462#issuecomment-2471703090). Music assistant needs to rework the login to intercept user cookies instead, which is painful, but is the only way forward.

Yt-dlp [already works with cookies](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp).

**Comment by OzGav** [comment] 2024-11-16 13:14
Progress has been made. Expect more info in the next couple of days,

**Comment by shaiger** [comment] 2024-11-16 13:27
The documentation page provides instructions for heading down the "cookie path", yet the UI does not provide the option to paste the cookie info. I can only take the "token path" using the UI.
Is there a manual way to enter the cookie data?

**Comment by shaiger** [comment] 2024-11-16 20:09
Thanks for the UI update!
I can play music now, though uploaded music is not working.

**Comment by OzGav** [comment] 2024-11-16 22:32
Try 2.4.0b5 which has the cookie solution

**Comment by shaiger** [comment] 2024-11-16 22:39
So I did. Everything seems to be working now. 
Perhaps the sync was partial when I first tried.

**Comment by TheWebMachine** [comment] 2024-11-16 22:59
> Try 2.4.0b5 which has the cookie solution

Cookie solution is working for me. It also seems Google is locking down on multi-device playback because YTM stopped on my phone with a "you're using this on another device" error when MA began syncing YTM for the first time. I've previously been able to play different YTM streams (directy, not via MA) on 6+ devices at the same time in my house (all one external IP) without issue, so this is definitely a new change. I wonder if upgrading to a YT Family Plan loosens this restriction back to the old limits. 

I was able to immediately resume my music on the phone while MA is syncing (my initial library sync takes over 10 minutes due to amount of content). But I can already see that YTMs new restrictions are targeted at folks like us. I doubt this will be the last change coming to make our lives difficult. With all the pricing changes lately, they may be preparing to launch a new higher Premium tier for YT/YTM.

**Comment by drewgourley** [comment] 2024-11-16 23:23
Using the cookie method, the interface sends a popup that claims I do not have YouTube Music Premium. This is technically correct, since I have YouTube premium, which includes all the benefits of YouTube Music Premium, which evidently somewhere deep within their system makes some sort of difference. I have no way through their spaghetti to make any kind of distinction between the two products. Is this something that can even be handled on the Music Assistant side?

**Comment by infotechjrf** [comment] 2024-11-16 23:45
Cookie login method works perfectly fine for me with branded account.

Thanks to everybody involved in the Music Assistant project for your hard work and dedication. Much appreciated! 

Respectfully,
JR

**Comment by afs5327** [comment] 2024-11-16 23:55
> Try 2.4.0b5 which has the cookie solution

Tested and working for me so far. Thank you!
 
> Cookie solution is working for me. It also seems Google is locking down on multi-device playback because YTM stopped on my phone with a "you're using this on another device" error when MA began syncing YTM for the first time. I've previously been able to play different YTM streams (directy, not via MA) on 6+ devices at the same time in my house (all one external IP) without issue, so this is definitely a new change. I wonder if upgrading to a YT Family Plan loosens this restriction back to the old limits.

I've tested, and am able to playback different streams on multiple devices right now. I'm only testing 2 concurrent, but no issues so far. I do use a separate account I made for HA stuff that is connected to my family plan though.

> Using the cookie method, the interface sends a popup that claims I do not have YouTube Music Premium. This is technically correct, since I have YouTube premium, which includes all the benefits of YouTube Music Premium, which evidently somewhere deep within their system makes some sort of difference. I have no way through their spaghetti to make any kind of distinction between the two products. Is this something that can even be handled on the Music Assistant side?

I have YTP vs YTM as well. It's a family plan, not sure if that matters for this. Maybe try using a private window to generate a cookie, and see if that one give better success?

**Comment by pldcanfly** [comment] 2024-11-16 23:59
Beware! 
The Cookie method worked for me, but not with a cookie copied out of Firefox. Needed to be chromium like Brave.

**Comment by TheWebMachine** [comment] 2024-11-17 00:02
> Using the cookie method, the interface sends a popup that claims I do not have YouTube Music Premium. This is technically correct, since I have YouTube premium, which includes all the benefits of YouTube Music Premium, which evidently somewhere deep within their system makes some sort of difference. I have no way through their spaghetti to make any kind of distinction between the two products. Is this something that can even be handled on the Music Assistant side?

Did you pull the cookie from youtube.com or music.youtube.com?

**Comment by drewgourley** [comment] 2024-11-17 00:03
I had to use a private window to log in directly to music.youtube.com and pull that new cookie, worked great. You guys are wizards.

**Comment by TheWebMachine** [comment] 2024-11-17 00:06
> > Try 2.4.0b5 which has the cookie solution
> 
> Tested and working for me so far. Thank you!
> 
> > Cookie solution is working for me. It also seems Google is locking down on multi-device playback because YTM stopped on my phone with a "you're using this on another device" error when MA began syncing YTM for the first time. I've previously been able to play different YTM streams (directy, not via MA) on 6+ devices at the same time in my house (all one external IP) without issue, so this is definitely a new change. I wonder if upgrading to a YT Family Plan loosens this restriction back to the old limits.
> 
> I've tested, and am able to playback different streams on multiple devices right now. I'm only testing 2 concurrent, but no issues so far. I do use a separate account I made for HA stuff that is connected to my family plan though.
> 
> > Using the cookie method, the interface sends a popup that claims I do not have YouTube Music Premium. This is technically correct, since I have YouTube premium, which includes all the benefits of YouTube Music Premium, which evidently somewhere deep within their system makes some sort of difference. I have no way through their spaghetti to make any kind of distinction between the two products. Is this something that can even be handled on the Music Assistant side?
> 
> I have YTP vs YTM as well. It's a family plan, not sure if that matters for this. Maybe try using a private window to generate a cookie, and see if that one give better success?

A family plan would absolutely have to grant more simultaneous streams than an individual plan. I'm on an individual plan. It appears that while I can play streams simultaneously on the app on my phone and via MA, the MY YTM sync task seems to be what causes a simultaneous account error on any other YouTube app that is playing music at the time the sync is started. At least, that's been my observations thus far. Or perhaps it's only during the initial account setup and sync in MA that the interruption occurs. I'm not entirely certain; I'll have to do more testing to see if the issue reoccurs outside of initial setup.

**Comment by afs5327** [comment] 2024-11-17 00:50
> The Cookie method worked for me, but not with a cookie copied out of Firefox. Needed to be chromium like Brave.
I was able to use a cookie from FF without issue. It's been working for ~1H now, but I'll report back if it stops.

**Comment by bitsalive-ron** [comment] 2024-11-17 16:07
Whenever a try to enter a cookie in the Login-Cookie field my browser opens a popup with the message:
"__Secure-3PAPISID"

Any idea how to get the correct one / fix this error?

**Comment by TheWebMachine** [comment] 2024-11-17 16:30
> Whenever a try to enter a cookie in the Login-Cookie field my browser opens a popup with the message: "__Secure-3PAPISID"
> 
> Any idea how to get the correct one / fix this error?

Make sure you are copying the full Request Headers > Cookie value. It starts with `VISITOR_INFO1_LIVE=` and is *very* long. If you miss any of it, or include any additional text beyond the actual value, you will get random errors as MA tries to parse the input for what it needs to extract from it. 

The best way to ensure you get the whole value properly is to maximize your browser, open the Dev tools (F12), then drag the divider bar (between page and Dev tools) to make the Dev tools panel wider so the Cookie value is all showing on the screen at once. Don't try to select while scrolling, as this increases the likelihood of errors.

**Comment by afs5327** [comment] 2024-11-17 19:06
If it helps, Firefox has a "Copy Value" option when you right-click on the cookie key value:

![image](https://github.com/user-attachments/assets/2994a186-5fbf-41c7-8abf-f33a4c96e928)

**Comment by shawndeegee** [comment] 2024-11-18 02:38
This broke for me too -- confirming that cookies worked for some browsers. For me chrome did *not* work on Windows 10 or Windows 11 but IE did. Huge props to the team supporting this for coming up with a solution! <3

**Comment by szemod** [comment] 2024-11-18 10:07
The cookie-based identification works, and the cookie can be easily extracted through the Dev Tools (I did it using Edge). However, when I restart the MA Addon, I have to reconfigure the YouTube Music provider among the Music Providers and extract a new cookie from the browser again to input it. This is a bit of a hassle, but at least it works...

**Comment by EvanWasHere-zz** [comment] 2024-11-19 22:13
Actually.... I spoke too soon.  Music Assistant accepts my cookie text.. but it's not showing me my playlists or favorited music.  Like I don't see anything from my profile.  

I have a personal and business profile on YouTube.  My content is all on the business profile.  I've tried putting the exact name in "username" as well as adding an "@" to the beginning of it.  Nada.

I also noticed that I could type anything under "username" and it accepts it along with the cookie text.  It doesn't work, but it doesn't log an error.

What am I doing wrong?

**Comment by grainsoflight** [comment] 2024-11-27 08:28
Running into issues with the cookie. On edge I get "user does not have a youtube music premium account" error, chrome I get "ERROR: [youtube] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats", and on Brave it will accept the cookie, but all content from youtube music is greyed out. I am logged in on each browser and obtaining the cookie from the playlist page

**Comment by OzGav** [comment] 2024-11-27 11:44
@grainsoflight look here https://github.com/orgs/music-assistant/discussions/1551#discussioncomment-11323331 and in the docs for more info that may help.

**Comment by grainsoflight** [comment] 2024-11-27 17:36
> @grainsoflight look here https://github.com/orgs/music-assistant/discussions/1551#discussioncomment-11323331 and in the docs for more info that may help.

I am using neither a brand account nor a family account.

**Comment by OzGav** [comment] 2024-11-27 22:33
@grainsoflight make sure you are running the latest beta of the server

**Comment by grainsoflight** [comment] 2024-11-28 03:01
@OzGav Updated to latest beta, did not resolve the problem

**Comment by OzGav** [comment] 2024-11-28 03:17
@grainsoflight where did you get that log excerpt you show above? It doesn’t look like something from music assistant?

**Comment by grainsoflight** [comment] 2024-11-28 04:16
@OzGav from the logs section of the add on backend

**Comment by OzGav** [comment] 2024-11-28 05:17
@MarvinSchenkel any idea about the 400s above?

**Comment by MarvinSchenkel** [comment] 2024-11-28 06:27
> Refreshing individual items makes the album art come back and the content selectable, but it still wont play.
> 
> Edit: nothing from my Plex or Local media appears to be playing either, so Im not sure what the issue is. In addition to nothing playing on any speaker, youtube is still logging:
> 
> WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument. WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)... 2024-11-27 12:01:02.871 INFO (MainThread) [music_assistant.players] Player registered: 455bae44-cb9a-17be-93e8-f790a8ae57ae/Living Room speaker WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument. WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)... WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument. WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)... WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument. WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

Just double checking. Did you completely remove the YTM integration and logged in again using the cookie method using the latest beta?

**Comment by grainsoflight** [comment] 2024-11-28 07:59
@MarvinSchenkel I am not sure what that topic is referring to as far as exporting a cookie after closing the youtube tab. I cant find a way to export a cookie from the blank tab.

**Comment by OzGav** [comment] 2024-11-28 13:41
First thing that Marvin asked is have you completely removed the YouTube provider since the change to the cookie method?

**Comment by grainsoflight** [comment] 2024-11-28 13:46
@OzGav yes, i have

**Comment by grainsoflight** [comment] 2024-12-01 08:12
Reinstalling the Cast integration in HA fixed my speaker issue, and after that Youtube Music started playing nicely again, both correctly authorizing and (at least at this point) not crashing.

**Comment by OzGav** [comment] 2024-12-01 11:49
We recommend you do not use the cast integration. If MA has a native player you should be using that.

**Comment by grainsoflight** [comment] 2024-12-01 17:54
@OzGav I'm not sure what you mean by that

**Comment by grainsoflight** [comment] 2024-12-01 18:50
@OzGav its back to not playing anything from any source at all

**Comment by OzGav** [comment] 2024-12-01 22:09
You said 

> Reinstalling the Cast integration in HA

but that should not be installed. You should have added the cast provider in Music Assistant and be using the players that are discovered by that.

**Comment by grainsoflight** [comment] 2024-12-01 23:13
@OzGav Ive completely removed all cast devices from HA, uninstalled and removed data from MA, restarted, reinstalled MA, added the chromecast source provider, and it still doesnt play media from any source. It establishes a connection to the speaker, but will not play.

**Comment by grainsoflight** [comment] 2024-12-02 01:03
@OzGav it is occasionally playing now, but regardless of whether it plays or not, HA logs an out of memory error. Is there a specific amount of memory MA needs?

**Comment by OzGav** [comment] 2024-12-02 01:04
https://music-assistant.io/installation/?h=ram#server-notes

**Comment by grainsoflight** [comment] 2024-12-02 01:12
@OzGav increasing RAM to 8GB from 2 seems to have fixed all the issues I was having, will monitor

**Comment by TheWebMachine** [comment] 2024-12-05 19:07
> https://music-assistant.io/installation/?h=ram#server-notes

> @OzGav increasing RAM to 8GB from 2 seems to have fixed all the issues I was having, will monitor

To be clear, that 2GB requirement on RAM is just for MA, itself. If you are running MA as an Add-on within HA, you'll need at least 4GB for a small HA install and much more if you are running a large HA deployment with lots of other add-ons, etc.

Each Add-on is a docker container, so the RAM requirements of each should be tallied up to help determine an appropriate amount for your entire HA server/VM. Of course, all add-ons aren't going to use the max RAM all the time, but any one of them could demand it...and OOM panic if it doesn't get it.

Further still, some add-ons could require a lot more than the recommended RAM under some circumstances. A good example of this is the ESPHome Device Compiler. It could gobble up as much as 8GB RAM if you are compiling devices like the Atom Echo, which compiles tensorflow components, while only needing sub-2GB RAM for compiling most other ESPHome devices. 

My HA VM has MA, ESPHome, Whisper, OpenWakeWord and I had to allocate 32GB RAM to my VM to ensure everything had enough headroom during peak usage spikes (like transcribing the audio of HA Assist requests in multiple rooms at once or compiling ESPHome firmware). Sure, I'm a bit of a superuser, but as one continues to build out the perfect HA smart home, resource requirements are going to climb. I started my HA VM with just 4GB RAM back in 2022. As I write this, my HA VM is using 3GB RAM *at idle.*

**Comment by OzGav** [comment] 2024-12-08 11:18
The cookie method is working and additional information has been added to the docs.

**Closed by OzGav** 2024-12-08 11:18 UTC
Labels: upstream issue, Fix to be Confirmed, YouTube

**Comment by Grim73** [comment] 2024-12-19 06:36
getting the same error again actually

**Comment by cherryocola** [comment] 2024-12-19 06:50
> getting the same error again actually

Same here

**Comment by ragaimeena** [comment] 2024-12-19 12:25
cannot add YT music
getting this error
User does not have Youtube Music Premium

**Comment by CappyT** [comment] 2024-12-19 12:47
> cannot add YT music
> getting this error
> User does not have Youtube Music Premium

Free accounts are not supported anymore. You need to have a YouTube music premium subscription.

**Comment by ragaimeena** [comment] 2024-12-19 13:08
I DO have a premium account but I am getting this message for some reason

**Comment by cherryocola** [comment] 2024-12-19 13:11
> > cannot add YT music
> > getting this error
> > User does not have Youtube Music Premium
> 
> Free accounts are not supported anymore. You need to have a YouTube music premium subscription.

Premium as well, not working.

**Comment by JulesAU** [comment] 2024-12-19 21:55
I see that @MarvinSchenkel has already committed a fix to master; but meanwhile a workaround I have been using for a few days is to simply remove the `cookiefile` param from ytdl by [commenting out this line](https://github.com/music-assistant/server/blob/73545eef0d98383d79c89ee9a09bda586eeeba78/music_assistant/providers/ytmusic/__init__.py#L748) in my installation.

**Comment by cherryocola** [comment] 2024-12-19 23:31
> I see that @MarvinSchenkel has already committed a fix to master; but meanwhile a workaround I have been using for a few days is to simply remove the `cookiefile` param from ytdl by [commenting out this line](https://github.com/music-assistant/server/blob/73545eef0d98383d79c89ee9a09bda586eeeba78/music_assistant/providers/ytmusic/__init__.py#L748) in my installation.

Hi Jules, where may I find this file?

**Comment by MarvinSchenkel** [comment] 2024-12-20 05:16
> I see that @MarvinSchenkel has already committed a fix to master; but meanwhile a workaround I have been using for a few days is to simply remove the `cookiefile` param from ytdl by [commenting out this line](https://github.com/music-assistant/server/blob/73545eef0d98383d79c89ee9a09bda586eeeba78/music_assistant/providers/ytmusic/__init__.py#L748) in my installation.

Interesting.. Two questions from my side about this 
1. Did you apply this on the current main branch (eg on top of my fix) or on the current stable version? The latter still has the quick ios client that can quickly resolve steam  urls 
2. I expect you won't be able to retrieve high quality streams without the cookie (ie logging in). Didn't you run into the error "User does not have YT Music premium" error after removing the cookie line?

**Comment by cherryocola** [comment] 2024-12-28 08:22
I think Google changed it so you cant play your personal playlists

**Comment by grainsoflight** [comment] 2025-02-22 04:11
> [@OzGav](https://github.com/OzGav) increasing RAM to 8GB from 2 seems to have fixed all the issues I was having, will monitor

Did not work, still rarely makes it through a song. To be honest I dont even remember the last time MA worked flawlessly with out stuttering or dropping out, maybe 2 years?
