### ISSUE TITLE
stuttering and soft playback from spotify to Sonos speaker

### ISSUE THREAD

**Issue by DutchJaFO** [music-assistant/hass-music-assistant#287] opened 2022-06-02 13:30 UTC
version : 2022.6.0 BETA 0 / HA 2022.6.0 
The integration finds all my spotify songs and suchm but I haven't had a good playback yet.

(1) Sound volume is low compared to regular spotify -> sonos on the same system.
I've got it set to '5 (which is more than sufficient  )', but needed to increase it to '17' ... which is quite loud when I use my sonos app to play something else.

(2) For some reason the active song on Sonos is listed as "mediaplayer.hobbyruimte.flac' or "mediaplayer.hobbyruimte.ogg" ('hobbyruimte' being the name of the Sonos speaker I'm trying to use as a target.

(3) I've only ever get a few seconds of playback before the sound stops for a few seconds and continues.
It is as if music assistant is trying to transcode and/or the buffer used to stream the music from spotify to sonos is too small to allow the stream to work.

System : virtual pc environment (Proxmox) using 4 out of 8 cores and 8 Gb memory.
CPU: Intel i7
The same system is running a PiHole with 2 cores assigned.

Note :  I am running Folding@Home which uses +/- 50% of available CPU capacity ...  disabling that add-on did not apear to resolve the stutter.

**Comment by marcelveldt** [comment] 2022-06-02 13:38
1) Volume normalization is enabled by default and set to the EBU-R recommendation of -23 LUFS. So yes, audio will sound a bit less loud but benefit is that all audio will have equal loudness. You can disable or increase the normalization gain in the queue settings.

from within the Music Assistant panel, click Queue in the bottom bar. Click the menu button (3 dots top right). Increase the volume level so it better suits the level of other sources you play on the same speaker.

2) That is correct. If you really want the complete metadata shown in your HA interface, you can choose to export the players back to HA but this time including the metadata. We're investigating options to improve this in the future.

3) Seems like a buffering issue. What is your internet connection like ? Can you also observe cpu usage while starting playback of a stream ?

**Comment by DutchJaFO** [comment] 2022-06-02 15:11
(1) ah ... I will try that. Wasn't expecting anything to happen to the sound as I only had Spotify as the source.
I can understand why you'd want it enabled with multiple sources. 

(2) so the only way to see what is playing is inside HA itself ? I hope you can fix that in the future

(3) it's cable internet (300 Mb/s up and 30 Mb/s down according to a speed test.) and as I said I have zero issues playing back Spotify streams using the built-in features of the Sonos speaker system.
I was doing everything on my own local network (5Ghz WiFi, 1000 Gigabit cable), so no outside route needed.

Looking at cpu/network stats in ProxMox I'm seeing significant increase in network traffic (200 Kb in and out, CPU usage doubled)...  This does make sense if the add-on is reading data from spotify and then streaming it to the internal network.
Doesn't look too bad for a 1000Gigabyte network but that's just me.

![image](https://user-images.githubusercontent.com/39138434/171660674-d7481ab3-5189-4dc2-a141-1d26b02aecb1.png)

**Comment by marcelveldt** [comment] 2022-06-02 15:20
1) You'd be surprised how different all music sounds in the current "loudness war". Normalizing audio according to EBU-R means volume leveling to reach the same perceived loudness. Setting it to -17 means there is enough headroom left. Your sound may actually sound better. The only downside is that you have to turn the volume knob a bitter higher than you're used to.

2) Where else do you want to see what's playing? On the speaker/player/hardware itself is not going to happen I'm afraid. 

3) Both network/internet bandwidth and cpu seem fine to me, that's not the issue. I will try to tune the internal buffer sizes a bit and let you know once I have something ready to test. Do you have the chance to test playback on any other device by any chance ?

**Comment by DutchJaFO** [comment] 2022-06-02 15:32
1) I know nothing about audio theory so ... that all sounds like magic to me. It will have to be something to think about when switching sources as the volume needs to be reduced by a significant margin unless I want to annoy my neighbours.  

2) I thought internet radio streams could also show artist+song but not sure what kind of magic is needed for that sort of stuff.

3) I was thinking buffer-size as well. Shouldn't the buffer be big enough for a single (3 minute?) song or something ?
The cost will be a delay when skipping songs, but the overall stability might be worth it.
The net-in behavour looks almost like it is loading the first second ... and then not doing anything until it needs the next bit.
Net-out is more stable.

I will try a different output and report back.

**Comment by marcelveldt** [comment] 2022-06-02 15:50
1) In your case I'd suggest to change the target volume to better match the other content you play.

2) yes, but that means embedding it into the stream. Not sure if that is going to work with our lossless flac stream. Something to test one day.

3) Well, it's not as easy as that. There's also OS-level buffers, memory consumption, seek speed etc.
Buffer is about 15 seconds but my guess now is that it is not filled quick enough from the source, hence the stutter

Are you perhaps available on discord for a quick chat ? I'd like to perform a few easy tests to tweak the buffer?

**Comment by DutchJaFO** [comment] 2022-06-02 15:55
Of course things aren't as easy as that 😁 

- Xbox One as output : xbox show white screen, it probably wants an app that I don't have ?

- Devon AVR-1912 : no output? 
but given that I've got a Sonos Port connected I have never needed the internet radio feature or whatever the system

I've just logged into discord.

**Comment by DutchJaFO** [comment] 2022-06-02 16:30
update after chat on discord : 
= enabling 'crossfade' (type : smart) and extending the length of crossfade to 10 seconds appeared to improve the initial bit of music, but after that initial success I was back to the 'normal' 2-3 second bits of music.

**Comment by DutchJaFO** [comment] 2022-06-02 19:41
updated ... and soo close, but no cigar.
playback has improved a lot though.
Instead of a few seconds playback and a hole lot of nothing I've got bits of 10-20 seconds music with 4 second pauzes.
It's not as bad as the previous version, but it is not flawless either.
I need 10 seconds of (smart) crossfade to get to this state.

I've also noticed that the time indicator for track remains at 0:00

**Comment by marcelveldt** [comment] 2022-06-02 22:39
This triggers me: the time indicator remains at 0:00
Can you please play something else from HA (such as radio stream) on the Sonos speaker and check if the time is counting up within HA ?

**Comment by marcelveldt** [comment] 2022-06-03 00:36
I've release 2022.6 beta 2 - please give that another testdrive, thanks!

**Comment by DutchJaFO** [comment] 2022-06-03 07:54
No real improvement. I'm tempted to say it is worse, but.
There is no time indicator in the standard media player controls, so I can't see if it is counting up like it should.
In the Sonos App I do see the information tag displaying current song/artist 

Source playing : Internet-radio integration from HA 
Target : Sonos speaker
![image](https://user-images.githubusercontent.com/39138434/171812075-4c3ccf37-f0c7-4570-9b7c-43c94a7f3b30.png)
(note the .aac extension ... )

I don't have access to the internet radio integration from inside Music Assistant, so can't double check.

Theory :
You are relying on the progress indicator to refill your buffer.
As there is no progress (or the feature responsible causes an error) the buffer doesn't get a refill.
Maybe an actual internet radio stream is the way to go ?

**Comment by marcelveldt** [comment] 2022-06-03 07:56
Yes, that is indeed the issue. The fulness of the buffer is determined on base of how much the player has actually played.
It seems that this info is lost/broken for Sonos somehow.

**Comment by DutchJaFO** [comment] 2022-06-03 08:04
just check internet radio vs regular playlist in HA again.
I only get a progress indicator with regular playlists.
There is no progress indicator the moment I switch to the internet radio ('radio 538 top 50' using internet radio integration in HA)

**Comment by marcelveldt** [comment] 2022-06-03 08:10
So my best guess for now is that Sonos is treating the url sent by MA as a radio stream.
Can you conform that when you're trying to stream from MA that there is no progress on the "real" player ?

**Comment by Mariusthvdb** [comment] 2022-06-03 08:16
I quickly checked, and there was a progress bar moving, but the music stops playing.... even when I click > in Mass, and not touch the handle at all

playing to a Google Home als stutters now and then, but plays nicely and doesnt stop


<img width="655" alt="Schermafbeelding 2022-06-03 om 10 14 37" src="https://user-images.githubusercontent.com/33354141/171816225-6019985b-0772-42ba-a1ca-f9b8706f547c.png">

**Comment by DutchJaFO** [comment] 2022-06-03 08:27
Kind of makes sense doesn't it ?
a URL is likely to be 'internet radio'  because what else could it be ?
There is no need for any 'progress' as you can't scroll forward in an active stream.
Scrolling back may be the only action available, but that only works if that stream has been buffered somewhere.

**Comment by marcelveldt** [comment] 2022-06-03 08:29
Uhm, no there is is progress as from how many seconds has played.

**Comment by Mariusthvdb** [comment] 2022-06-03 08:31
On a radio stream that might be the case, but my tests where with a playlist in spotify, and one should be able to progress in that track, thats what the handles for

check what is does on a google home:

<img width="673" alt="Schermafbeelding 2022-06-03 om 10 30 25" src="https://user-images.githubusercontent.com/33354141/171818555-6665bac4-e302-4313-8f9b-a61ed732cf4f.png">


nicely jumps to the spot in the same track

**Comment by marcelveldt** [comment] 2022-06-03 08:33
We're talking 2 different things here.
I mean with progress that the player reports how many seconds it has played. This should be visible as "media_position attribute on the source/original player entity in HA (other with a last updated at attribute).

In MA itself you have the progress bar where you can also seek within a track.
Ofcourse that will not work for a radio station ;-)

**Comment by Mariusthvdb** [comment] 2022-06-03 08:40
in the states, there is a media_position_updated_at: 2022-06-03T08:37:08.816902+00:00 for the Symfonisk/Sonos on the Mass player, but not on the HA player for the same device:

<img width="1024" alt="Schermafbeelding 2022-06-03 om 10 38 13" src="https://user-images.githubusercontent.com/33354141/171819919-012b92d3-130b-4213-bad0-5aede158ac18.png">

note the media_position is indeed 0...
nothing on the HA device , which only has:
```
queue_position: 1
queue_size: 1
```

**Comment by marcelveldt** [comment] 2022-06-03 08:41
OK thanks, that confirms my suspicion. I will work on a fix for this. 
I'll go to the "mediamarkt" later today to pick up a Sonos speaker so I can better diagnose.

**Comment by Mariusthvdb** [comment] 2022-06-03 08:42
this must be some regression, because I have listened to my full playlists on that same Sonos/Symfonisk before without it stopping once

**Comment by DutchJaFO** [comment] 2022-06-03 08:43
makes sense ... you're the one streaming the tracks, so your server knows exactly where you are.
if that info isn't available at the client side then there is no way for the client to either show where it is use that info to move forward/backward

@marcelveldt the Ikea Symfonysk is a Sonos Speaker too and it should be cheaper (at least it was)

**Comment by Mariusthvdb** [comment] 2022-06-03 08:46
hmm, does not make sense to me really... compare the googlehome: the base player has a position alright, while the ms player still shows position 0. 


<img width="1011" alt="Schermafbeelding 2022-06-03 om 10 36 09" src="https://user-images.githubusercontent.com/33354141/171821125-740950fd-72bd-4500-8b25-c724f7fc632d.png">

**Comment by marcelveldt** [comment] 2022-06-03 08:48
> this must be some regression, because I have listened to my full playlists on that same Sonos/Symfonisk before without it stopping once. ION fact, it was my testing device, next to a single Google Home ;-)

There have been some changes to the Sonos integration too so just maybe this regression is in fact within Sonos integration and pops up now. We will know this afternoon once I have my hands on an actual device :-)

The media_position set to 0 on the "mass player" is in fact a small bug I keep forgetting to fix. On it right now :-)

**Comment by Mariusthvdb** [comment] 2022-06-03 08:55
not sure about that. 
if I select the browse button on a media_player card and select a favorite album in the Sonos, it plays, and keeps playing.

If II do the same, browse Music Assistant and select a playlists, it briefly plays, and then stops

**Comment by marcelveldt** [comment] 2022-06-03 08:57
That is not what I mean. The whole point is the missing "media_position". Without that MA will stop playing within 10 seconds

**Comment by Mariusthvdb** [comment] 2022-06-03 09:08
yeah, well, as said it is there, but remains on 0

full disclosure, playing the same playlist directly from the Spotify source (top right in the screenshot) on the Sonos and not the Music Assistant source works fine, and keeps playing. 

<img width="533" alt="Schermafbeelding 2022-06-03 om 11 07 05" src="https://user-images.githubusercontent.com/33354141/171824674-3713ed93-e3b1-4b2e-a771-34753e8cfeac.png">


Note that in this case the media_position does change on the mass player, even while I play via the non mass media_playern and its browser button!

<img width="1001" alt="Schermafbeelding 2022-06-03 om 11 05 32" src="https://user-images.githubusercontent.com/33354141/171824550-46492d72-b619-488c-8ec1-fd0d4c48d0a3.png">

**Comment by marcelveldt** [comment] 2022-06-03 09:12
Thanks for all the testing guys. I should have my hands on an actual Sonos speaker this afternoon so I will investigate and fix this issue.

**Comment by DutchJaFO** [comment] 2022-06-03 09:25
nothing beats having access to the actual hardware 😁 
(and I bet you were just looking for an excuse to buy one 😉  )

**Comment by marcelveldt** [comment] 2022-06-03 09:29
hahaha not exactly (my wife will probably hunt me now) because I already have a lot of gadgets that I still need to find a purpose for ;-)

**Comment by marcelveldt** [comment] 2022-06-03 22:00
Fix is on the way for the Sonos integration, which in turn fixes this issue in MA.

https://github.com/home-assistant/core/pull/73001

with a big thanks to @jjlawren for the real quick diagnose and fix

**Comment by DutchJaFO** [comment] 2022-06-05 10:11
status update : still not functioning
I did see the progress bar and timer change for a few seconds since updating HA to 2022.6.2
However the music still stops playing 😢 

2nd test shows this in the status for the (grouped) sonos speaker that I had used as a target :
media_duration: 0
media_position: 1
media_position_updated_at: 2022-06-05T10:00:58.865559+00:00

music is still playing, but no position updates ... after restarting playback things appeared to be playing, but after the crossfade playback stopped again.

comparing this to 'standard' playback of single song using sonos I noticed two things :
- media_duration does get a value 
- media_position_updated_at remains fixed after initial update

**Comment by marcelveldt** [comment] 2022-06-05 12:23
@DutchJaFO there's a small follow-up change need in my code too. I'll hope to push out another update later today.

**Comment by erkr** [comment] 2022-06-11 18:52
@DutchJaFO, and @Mariusthvdb in the latest v06b3 Marcel made changes in the buffering functionality. Could you please have a look if this issue is solved. Thanks Eric

**Comment by DutchJaFO** [comment] 2022-06-11 20:21
HA itself updated to latest version (core-2022.6.5)
v06b03 installed
for some reason the entire 'music assistant' tab is empty.
I was able to start playback using mass as a source. 
So far so good, no buffer/stutter issues.

**Comment by marcelveldt** [comment] 2022-06-11 20:22
Looks like the frontend app has an issue somehow, I'll have a look at that

**Comment by DutchJaFO** [comment] 2022-06-11 20:37
Sonos is displaying the streamname as 'streaming from Music-Assistant'
As is the mediaplayer in HA :
![image](https://user-images.githubusercontent.com/39138434/173204083-e6a51021-e445-4a11-9bf3-1f8256d39ebc.png)
(top is regular 'Sonos' mediaplayer, bottom is the music assistant version of the same output)

fun fact : I shut down the virutal machine running HA  (I wanted a fresh start) ... and the active song kept playing and even did a bit of the next song. I guess the Sonos buffered more than I was expecting it to do.

**Comment by marcelveldt** [comment] 2022-06-11 20:39
Yeah, Sonos is really fanatic as it comes to buffering. It buffers an entire track in my experience.
I will have a look at the media player outputs. That should ofcourse display the correct metadata :-)

**Comment by DutchJaFO** [comment] 2022-06-11 20:42
just one more bug to fix 😁

**Comment by Mariusthvdb** [comment] 2022-06-11 21:50
on it, just not have had opportunity to fully test, will be back !
thanks Marcel for the update

**Comment by Mariusthvdb** [comment] 2022-06-11 21:51
> Looks like the frontend app has an issue somehow, I'll have a look at that

yep, empty too on dev nightly 2022.7.0.dev20220611
I did get some initial TTS messages though ;-)

**Closed** 2022-06-12 22:10 UTC
Labels: bug, Completed

**Comment by Mariusthvdb** [comment] 2022-06-13 06:58
Marcel, shouldn't we keep this open?
The stuttering is way from gone in the latest b4.

Unless you say thats is a core HA issue (or, not specifically bound to Sonos, as this issue is about)

I could open a dedicated thread on that if you prefer
cheers!

**Comment by marcelveldt** [comment] 2022-06-13 06:59
TTS --> not yet fixed
playback to Sonos --> should be fixed without any hiccups

**Comment by Mariusthvdb** [comment] 2022-06-13 07:09
right. Ill followup on that in https://github.com/music-assistant/hass-music-assistant/issues/315 then ok? As that title seems adequate ;-)
