### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by sneedster** [music-assistant/hass-music-assistant#75] opened 2022-05-08 01:53 UTC
Just tried to install this integration, but I get an error right off the bat. I only enabled Tune-in.

Here is the trace from HA logs:
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:57
Integration: Music Assistant (documentation, issues)
First occurred: 6:38:38 PM (2 occurrences)
Last logged: 6:44:00 PM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 89, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 57, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/mass.py", line 80, in setup
    await self.database.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 46, in setup
    await self._migrate()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 158, in _migrate
    prev_version = int(prev_version["value"])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by rmiles7721** [comment] 2022-05-08 01:59
Getting the same thing here with 1.09

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 89, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 57, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/mass.py", line 80, in setup
    await self.database.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 46, in setup
    await self._migrate()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 158, in _migrate
    prev_version = int(prev_version["value"])
TypeError: 'NoneType' object is not subscriptable

**Comment by marcelveldt** [comment] 2022-05-08 05:54
Thanks for reporting. I will provide a new version within an hour

**Comment by dom2587** [comment] 2022-05-08 09:07
getting the same error, only trying to set up a local path "/media"

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 89, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 57, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/mass.py", line 80, in setup
    await self.database.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 46, in setup
    await self._migrate()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 158, in _migrate
    prev_version = int(prev_version["value"])
TypeError: 'NoneType' object is not subscriptable

**Comment by PrzemekSkw** [comment] 2022-05-08 09:46
I install and configure few minutes ago and have the same error:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 89, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 57, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/mass.py", line 80, in setup
    await self.database.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 46, in setup
    await self._migrate()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 158, in _migrate
    prev_version = int(prev_version["value"])
TypeError: 'NoneType' object is not subscriptable
```
Regards.

**Comment by marcelveldt** [comment] 2022-05-08 10:30
New version is not yet available, I'm about to publish it now (version 1.0.10)

**Comment by marcelveldt** [comment] 2022-05-08 11:44
Version 1.0.10 published, should be available in HACS soon!

**Comment by schoeyuk10** [comment] 2022-05-08 13:47
Hi, i installed this, and added some songs into media folder but they don't show in the integration.
My tunein favourites don't show up either. Any ideas what i'm doing wrong ?
Thanks in advance
Lee

**Comment by marcelveldt** [comment] 2022-05-08 13:59
In the top right you can track progress of any running tasks. The first start might take a few minutes. Any errors or warnings in the log?

**Comment by schoeyuk10** [comment] 2022-05-08 14:03
I'm getting this, which i didn't get before installing the integration.....I'll be hones, it means absolutely nothing to me lol
Thanks for your reply BTW

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/media_player.py:283
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:35:03 (7 occurrences)
Last logged: 14:42:57

[547839327632] not enough values to unpack (expected 3, got 1)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/config/custom_components/mass/media_player.py", line 283, in async_play_media
    await self.player.active_queue.play_media(media_id, queue_opt)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 416, in play_media
    media_item = await self.mass.music.get_item_by_uri(uri)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 156, in get_item_by_uri
    provider, media_type, item_id = uri.split(":")
ValueError: not enough values to unpack (expected 3, got 1)

**Comment by marcelveldt** [comment] 2022-05-08 17:15
@sneedster @rmiles7721 @dom2587 @PrzemekSkw is the error now resolved in recent version ?

@schoeyuk10 can you open a new issue report with your findings ? Then we can close this one because the original issue is now resolved. Thanks! BTW: The error you mention above means that something was sent to the "play_media" service which could not be parsed at all. Did you try to play something manually or did this issue popup by itself ? Please mention that in your new issue report ;-)

**Comment by PrzemekSkw** [comment] 2022-05-08 17:51
Hi @marcelveldt thank You for fast fox. I don't have error now. Addon works but have problem with Spotify (shows error about wrong credentials) and local folder with music (I have docker HA core installation and try `/mnt/dietpi_userdata/Music` and /storage/Music/`) where I don't see anything. Only TuneIn shows mu favorite stations 
Regards.

**Comment by sneedster** [comment] 2022-05-08 18:20
@marcelveldt Thank you for the quick fix for this installation issue. I have now been able to install, however, I am now seeing the same error as @schoeyuk10

**Comment by marcelveldt** [comment] 2022-05-08 18:21
@sneedster what action did you perform to get that error. ?
Can you browse your media with the Music Assistant panel and start playback on one of your players ?

**Comment by sneedster** [comment] 2022-05-08 18:51
@marcelveldt I actually opened a new issue #83 for the new error. The error installing has been resolved for me.

**Comment by marcelveldt** [comment] 2022-05-09 14:22
@PrzemekSkw can you tell me what platform you're running Home Assistant on ?
So, what kind of device, architecture, OS etc ?

**Comment by schoeyuk10** [comment] 2022-05-09 14:27
i'me using a pi 4

Version | core-2022.5.2
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.10.103-v8
CPU Architecture | aarch64
Timezone | Europe/London

The radio stations now work (kinda), i'm getting the tts not supported on alexa etc, but i've read you're working on that :)

Still can't get my local files working though. They're not 'seen' in MA

Thanks for all your work on this, it's gonna be awesome when it's all sorted

**Comment by PrzemekSkw** [comment] 2022-05-09 20:19
Hello, @marcelveldt  I have HA core installed with Dockstarter (docker-compose) on Intel minipc x64. DietpiOS (Debian 11).
Now I see all my music but don't see any players. 
![Screenshot_2022-05-09-22-13-37-37_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/25219988/167490545-311a1f7b-009e-4ea2-98d8-d83bbd09be1a.jpg)
I choose many players like  mobile phone, Emby on laptop or android box and my Samsung tv.
I have also problem with Spotify. I put wright username and login but have login failed error.
Regards

**Comment by marcelveldt** [comment] 2022-05-09 20:35
Go to the Settings --> Integrations --> Press options 
In the first screen select all players you want to use with MA
Save
Try again if you can start playback to any of the players

Hmmm Docker on DietPi, should work I guess, especially x86-64 arch.
Please have a good look in the logs and send me the full error or make a screenshot.

**Comment by PrzemekSkw** [comment] 2022-05-09 20:41
@marcelveldt I make that configuration all the time with many players and don't see any if I start play. I reboot home assistant many times.

**Comment by marcelveldt** [comment] 2022-05-09 20:52
Can you please share your full Home assistant log with me ?

**Comment by PrzemekSkw** [comment] 2022-05-09 21:25
I have some progress. I add manually Gogle Cast integration for my Google nest mini 2 speaker and put manually entity name to HA Music because it don't show it on list. I can turn it on and use volume but don't play music on it. I have still that loading circle. Meybe because my library is large?
![Screenshot_2022-05-09-23-24-04-30_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/25219988/167501006-9db90b8f-81ee-4240-998d-c08822a28676.jpg)
I can hear volume up sounds on that speaker when I rise in HAMusic but cannot click play.
Regards

**Comment by marcelveldt** [comment] 2022-05-09 22:49
players should show, regardless if the initial sync is still busy.
Not sure what's going on in your case. I really need to see the logfile for that....

Settings --> System --> Logbook --> View full log
paste in a textfile and upload it here

Or other way is to grab the homeassistant.log from your /config directory

**Comment by PrzemekSkw** [comment] 2022-05-10 05:35
Hi @marcelveldt I see now in logs errors why it don't play on my google Nest mini speaker but how can I fix that?

```
Error updating sensor: disk_free (/mnt/Toshiba)
07:30:44 – (BŁĘDY) systemmonitor - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 22:29:56 i powtarzała się 8656 razy
http://192.168.0.19:8123/lovelace/0?external_auth=1:0:0 Uncaught
07:30:43 – (BŁĘDY) components/system_log/__init__.py - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 22:39:52 i powtarzała się 10 razy
Error handling request
07:30:42 – (BŁĘDY) components/image/__init__.py - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 22:39:51 i powtarzała się 7 razy
Mi Air Purifier 3/3H(zhimi.airpurifier.mb3): Got MiioException while fetching the state: Unable to discover the device 192.168.0.16, mapping: {'air_purifier.fault': {'siid': 2, 'piid': 1}, 'air_purifier.on': {'siid': 2, 'piid': 2}, 'air_purifier.fan_level': {'siid': 2, 'piid': 4}, 'air_purifier.mode': {'siid': 2, 'piid': 5}, 'aqi.purify_volume': {'siid': 13, 'piid': 1}, 'aqi.average_aqi': {'siid': 13, 'piid': 2}, 'aqi.average_aqi_cnt': {'siid': 13, 'piid': 3}, 'aqi.aqi_zone': {'siid': 13, 'piid': 4}, 'aqi.sensor_state': {'siid': 13, 'piid': 5}, 'aqi.aqi_goodh': {'siid': 13, 'piid': 6}, 'aqi.aqi_runstate': {'siid': 13, 'piid': 7}, 'aqi.aqi_state': {'siid': 13, 'piid': 8}, 'aqi.aqi_updata_heartbeat': {'siid': 13, 'piid': 9}, 'filter_time.filter_max_time': {'siid': 9, 'piid': 1}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'indicator_light.brightness': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 6, 'piid': 6}, 'alarm': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 3}, 'filter.filter_used_time': {'siid': 4, 'piid': 5}, 'environment.pm2_5_density': {'siid': 3, 'piid': 6}, 'environment.relative_humidity': {'siid': 3, 'piid': 7}, 'environment.temperature': {'siid': 3, 'piid': 8}}, max_properties: 8/23
07:30:41 – (BŁĘDY) Xiaomi Miot Auto (niestandardowa integracja) - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 22:30:03 i powtarzała się 1082 razy
Kamera(chuangmi.camera.ipc016): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1651555560000, 'isContinue': True}, 'description': '成功', 'ts': 1652160360854}
07:30:00 – (OSTRZEŻENIA) Xiaomi Miot Auto (niestandardowa integracja) - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 22:30:58 i powtarzała się 540 razy
Update of binary_sensor.antistorm_136_storm_alarm is taking over 10 seconds
06:25:39 – (OSTRZEŻENIA) helpers/entity.py - wiadomość pojawiła się po raz pierwszy 00:10:37 i powtarzała się 4 razy
Job [Library sync of albums for provider Filesystem] failed with error 'NoneType' object has no attribute 'musicbrainz_id'.
05:16:12 – (BŁĘDY) /usr/local/lib/python3.9/site-packages/music_assistant/mass.py - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 22:31:11 i powtarzała się 10 razy
Skipping track due to invalid ID3 tags: /storage/Music/Kazik na żywo/Na żywo, ale w studio (1994)/Kazik Na Żywo - Na żywo, ale w studio - 14 - Świadomość.mp3
05:16:07 – (OSTRZEŻENIA) /usr/local/lib/python3.9/site-packages/music_assistant/providers/filesystem.py - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 22:30:01 i powtarzała się 5559 razy
[(192.168.0.106):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.0.106', 8009)), retrying in 5.0s
03:04:09 – (BŁĘDY) /usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py
[(192.168.0.106):8009] Heartbeat timeout, resetting connection
03:03:53 – (OSTRZEŻENIA) /usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py
Error executing service: <ServiceCall media_player.play_media (c:0180aac03673ee38db3e5912429f4f96): entity_id=['media_player.salon'], extra=, media_type=music, media_id=http://172.19.0.6:8095/media_player.salon.flac>
9 maja 2022, 23:37:38 – (BŁĘDY) components/cast/media_player.py - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 23:16:36 i powtarzała się 12 razy
Failed to cast media http://172.19.0.6:8095/media_player.salon.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
9 maja 2022, 23:36:46 – (BŁĘDY) Google Cast - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 23:18:35 i powtarzała się 3 razy
Job [Add filesystem://album/Greatest Ever Car Songs to database] failed with error .
9 maja 2022, 23:35:19 – (BŁĘDY) /usr/local/lib/python3.9/site-packages/music_assistant/mass.py - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 23:35:03 i powtarzała się 6 razy
[140576085262144] Error handling message: Unknown error (unknown_error)
9 maja 2022, 23:35:19 – (BŁĘDY) Home Assistant WebSocket API (niestandardowa integracja) - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 23:35:05 i powtarzała się 2 razy
[140576085262144] Error handling message: Unknown error (unknown_error)
9 maja 2022, 23:35:18 – (BŁĘDY) Home Assistant WebSocket API (niestandardowa integracja) - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 23:35:03 i powtarzała się 4 razy
Unexpectedly disconnected from Roomba 192.168.0.137, code The connection was lost
9 maja 2022, 22:58:24 – (OSTRZEŻENIA) /usr/local/lib/python3.9/site-packages/roombapy/roomba.py
Unable to find referenced entities climate.pokoj_emilki_mts100v3
9 maja 2022, 22:31:43 – (OSTRZEŻENIA) helpers/service.py
Error initializing 'Uruchom Oczyszczacz' trigger: In 'numeric_state' condition: unknown entity sensor.mi_air_purifier_3_3h_pm2_5
9 maja 2022, 22:30:21 – (OSTRZEŻENIA) Home Assistant Core Integration - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 22:30:21 i powtarzała się 2 razy
Template warning: 'int' got invalid input 'unknown' when rendering template '{% if states('sensor.mi_air_purifier_3_3h_pm2_5') | int > 30 %} {{ 'critical' }} {% elif states('sensor.mi_air_purifier_3_3h_pm2_5') | int > 15 %} {{ 'polluted' }} {% else %} {{ 'clean' }} {% endif %}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.6
9 maja 2022, 22:30:21 – (OSTRZEŻENIA) helpers/template.py - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 22:30:21 i powtarzała się 14 razy
Unable to connect to 192.168.0.137
9 maja 2022, 22:30:09 – (BŁĘDY) /usr/local/lib/python3.9/site-packages/roombapy/remote_client.py
Can't connect to 192.168.0.137, error: timed out
9 maja 2022, 22:30:09 – (BŁĘDY) /usr/local/lib/python3.9/site-packages/roombapy/remote_client.py - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 22:29:59 i powtarzała się 3 razy
Config entry 'jimmy joe' for roomba integration not ready yet; Retrying in background
9 maja 2022, 22:30:04 – (OSTRZEŻENIA) config_entries.py
[140576058987184] Received invalid command: mass/subscribe
9 maja 2022, 22:29:58 – (BŁĘDY) Home Assistant WebSocket API
Error adding entities for domain sensor with platform radarr_upcoming_media
9 maja 2022, 22:29:57 – (BŁĘDY) Sensor (niestandardowa integracja) - wiadomość pojawiła się po raz pierwszy 9 maja 2022, 22:29:57 i powtarzała się 2 razy
Invalid config 'OrderedDict([('host', '192.168.1.106')])': extra keys not allowed @ data['host']
9 maja 2022, 22:29:57 – (OSTRZEŻENIA) Google Cast
The 'cast' option near /config/configuration.yaml:2 has been removed, please remove it from your configuration
9 maja 2022, 22:29:57 – (BŁĘDY) Google Cast
```
The full log is too big to put it here.
Regards

**Comment by marcelveldt** [comment] 2022-05-10 08:21
You should not paste a log as text but instead attach a file ;-)

Are you running Home Assistant container in host network mode ?
There's a network port used for streaming audio from HA to the player, defaults to TCP 8095

**Comment by PrzemekSkw** [comment] 2022-05-10 10:35
Hi, that is full log:
https://logpaste.com/eVno4etE

I don't know is it host network mode. I'm not really good at docker.

Regards.

**Comment by PrzemekSkw** [comment] 2022-05-10 17:13
I see in .env file that:
`HOMEASSISTANT_NETWORK_MODE=' '`

**Comment by marcelveldt** [comment] 2022-05-10 17:24
> Hi, that is full log: https://logpaste.com/eVno4etE
> 
> I don't know is it host network mode. I'm not really good at docker.
> 
> Regards.

Thanks for the log. Unfortunately there are so many errors in there from all sorts that its like searching for a needle in a haystack. If I may give you some advice it would be to take a look, there are some serious issues in your logfile from incompatible and crashing integrations.

That said. I think the issue is the networking. With regular HomeAssistant OS this is all handled by default but when you're running the docker image yourself this becomes your own responsibility. The clue is that HomeAssistant should always run in "host" networking mode. If that is not possible you'll have to open all ports manually. Music Assistant requires port 8095 but when that port is taken it takes the next port (e.g. 8096) and so on.

BTW: here's the documentation about running Home Assistant Container. Not sure if that is of any help but maybe ther'es a clue in there. 

https://www.home-assistant.io/installation/linux#docker-compose

**Comment by PrzemekSkw** [comment] 2022-05-10 18:53
Hi @marcelveldt I install Radio Stations from official integrations and it stream stations from media player card.

**Comment by marcelveldt** [comment] 2022-05-10 19:30
Ah, I think I see what's going on....
The auto detected IP is 172.19.0.6 which is the internal docker IP.... that is not going to work.
I will try to workaround that and let you know once I found something

**Comment by PrzemekSkw** [comment] 2022-05-11 08:47
Hi, @marcelveldt I install HAcore with dockstarter, it's one-click istallation for docker apps. I can enable network host mode in .env file I think but I don't know if that will not broke enything.
Regards.

**Comment by marcelveldt** [comment] 2022-05-11 11:43
> Hi, @marcelveldt I install HAcore with dockstarter, it's one-click istallation for docker apps. I can enable network host mode in .env file I think but I don't know if that will not broke enything. Regards.

No that will not break anything but fix stuff. Host network mode is a requirement for running Home Assistant

**Comment by PrzemekSkw** [comment] 2022-05-11 12:07
I try to change but now my HA don't work.
I put `host` in Enter new field:
![Zrzut ekranu z 2022-05-11 13-59-50](https://user-images.githubusercontent.com/25219988/167845117-cc70f810-775a-46b9-9b68-d2adb1acb7fe.png)

**Comment by marcelveldt** [comment] 2022-05-11 12:08
You should enter host 

BTW: I have no idea about DOCKstarter

**Comment by PrzemekSkw** [comment] 2022-05-11 14:00
I'm home now and testing. Music assistant works perfect with Tunein radio streaming but failed with local media:
```
Logger: aiohttp.server
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py:405
First occurred: 15:53:36 (6 occurrences)
Last logged: 15:57:24

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 154, in get_item_by_uri
    media_type = MediaType(uri.split("/")[-2])
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'Dunkirk- Original Motion Picture Soundtrack (2017)' is not a valid MediaType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/stream.py", line 136, in serve_queue_stream
    start_streamdetails = await queue.queue_stream_prepare()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 730, in queue_stream_prepare
    return await get_stream_details(self.mass, next_item, self.queue_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 199, in get_stream_details
    full_item = await mass.music.get_item_by_uri(queue_item.uri)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 160, in get_item_by_uri
    raise MusicAssistantError(
music_assistant.models.errors.MusicAssistantError: Not a valid Music Assistant uri: filesystem://track/Hans Zimmer/Dunkirk- Original Motion Picture Soundtrack (2017)/Hans Zimmer - Dunkirk- Original Motion Picture Soundtrack - 01 - The Mole.mp3
```

**Comment by marcelveldt** [comment] 2022-05-11 20:32
@PrzemekSkw I have just released version 1.0.16 which should also fix the playback of filesystem sources

**Comment by marcelveldt** [comment] 2022-05-11 20:33
I'm closing this issue now that it should be resolved. Please open a new issue if you may still experience any issues!

**Closed by marcelveldt** 2022-05-11 20:33 UTC

**Comment by PrzemekSkw** [comment] 2022-05-12 05:34
Hi, @marcelveldt that upgrade broke Music-Assistant 😕 it don't work at all.
Regards.

**Comment by marcelveldt** [comment] 2022-05-12 05:53
Maybe there's a clue in here:

`music_assistant.models.errors.SetupFailedError: Setup failed of provider tunein: You must provide the TuneIn username, not email`

**Comment by marcelveldt** [comment] 2022-05-12 05:54
Are you saying that it worked before with your email instead of username ?
Because so far users have reported it to be only working with the username

**Comment by PrzemekSkw** [comment] 2022-05-12 06:13
I change now to name and everything works. Before it works with email fine.
Now there's only problem with Spotify. Do I have to get premium?

**Comment by marcelveldt** [comment] 2022-05-12 06:15
> I change now to name and everything works. Before it works with email fine. Now there's only problem with Spotify. Do I have to get premium?

OK, great! And good to know that it worked with email before. Did you see your TuneIn favorites then ?
Yes, Premium is required as is stated in the readme.

**Comment by PrzemekSkw** [comment] 2022-05-12 06:27
> Did you see your TuneIn favorites then ?
Yes, I see my favourites radio stations but when I add another one and restart HA it don't show.
