### ISSUE TITLE
HASS fails to load MA integration

### ISSUE THREAD

**Issue by X-dark** [music-assistant/hass-music-assistant#3031] opened 2024-10-14 09:59 UTC
### What version of Music Assistant has the issue?

2.2.7

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

HASS cannot load MA Integration. It fails at HASS start with:

```
2024-10-14 11:43:30.983 DEBUG (SyncWorker_4) [homeassistant.util.package] Running uv pip command: args=['uv', 'pip', 'install', '--quiet', 'music-assistant==2.2.4', '--index-strategy', 'unsafe-first-match', '--upgrade', '--constraint', '/usr/src/homeassistant/homeassistant/package_constraints.txt', '--target', '/config/deps']
2024-10-14 11:43:32.586 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration mass: No module named 'music_assistant'
```

### How to reproduce

- Run HASS from official container image
- Run MASS from official container image
- Install MA Integration from HACS
- Restart HASS container

### Music Providers

Not relevant

### Player Providers

Not relevant

### What version of Home Assistant Core are your running

2024.10.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by X-dark** [comment] 2024-10-14 10:08
Complete error stack:

```
2024-10-14 11:43:32.586 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration mass: No module named 'music_assistant'
2024-10-14 11:43:32.587 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2943, in _load_integration
    await integration.async_get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1100, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1147, in async_get_platforms
    await self.hass.async_add_import_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/mass/__init__.py", line 20, in <module>
    from music_assistant.client import MusicAssistantClient
ModuleNotFoundError: No module named 'music_assistant'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 135, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 114, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 112, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1287, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1312, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1499, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2964, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2950, in _load_integration
    raise data_entry_flow.UnknownHandler from err
homeassistant.data_entry_flow.UnknownHandler
```

**Comment by X-dark** [comment] 2024-10-14 10:11
And here is the debug log of manually running uv command from HASS container (same as the one HASS runs with debug instead of quiet)

```sh
uv pip install -v music-assistant==2.2.4 --index-strategy unsafe-first-match --upgrade --constraint /usr/src/homeassistant/homeassistant/package_constraints.txt --target  /config/deps
```
[uv.log](https://github.com/user-attachments/files/17362379/uv.log)

**Comment by danielgoepp** [comment] 2024-10-14 10:28
Same problem. Watching this issue to see what folks have to say.

**Comment by OzGav** [comment] 2024-10-14 10:45
Have you used the docker compose from the docs? https://music-assistant.io/installation/

**Comment by X-dark** [comment] 2024-10-14 12:18
The issue is on HomeAssistant container. Not sure how the launch option of the MusicAssistant will have an impact. Or am I missing something?

Anyway, I am using similar option (except I am not using apparmor nor Samba).

**Comment by marcelveldt** [comment] 2024-10-14 12:47
This issue does not exist on the normal HAOS version of HA so there must be something specific then in the Container install somehow. Anything special about your setup that stands out ? Running HA as a special user maybe ?

**Comment by marcelveldt** [comment] 2024-10-15 22:02
Most probably you guys are running the Home Assistant container with a non-root user, which is not officially supported. It causes issues with uv. Basically you're running an unsupported setup, sorry.

**Comment by marcelveldt** [comment] 2024-10-15 22:11
See here for some more info btw: https://github.com/home-assistant/core/issues/128214

**Comment by marcelveldt** [comment] 2024-10-15 22:13
closing here as this is not a MA issue (and debatable if its a HA issue, due to the fact that running as non-root docker is officially not supported by HA).

**Closed by marcelveldt** 2024-10-15 22:13 UTC
Labels: triage

**Comment by danielgoepp** [comment] 2024-10-15 22:33
@marcelveldt interesting theory, but don't think that is the issue. I do not set the user, it defaults to root. I'd be happy to share my full manifest with you if that helps.

```
╰─○ kubectl exec pods/homeassistant-565d69646c-qcr2v -c homeassistant --  id

uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
```

Also, no other integrations I have installed seem to have a problem installing necessary underlying packages.

Do you have any other input on this one? It would seem a real shame to not be able to run this at all :(

**Comment by OzGav** [comment] 2024-10-15 23:01
Sorry we don’t provide support for kubernetes.

**Comment by danielgoepp** [comment] 2024-10-15 23:20
Thanks @OzGav. Not necessarily looking for direct support, it just would be nice if there were any ideas here. But I get it. I'll do some more digging to see what's up. I mean, there has to be some reason this integration won't install this package :)

**Comment by danielgoepp** [comment] 2024-10-16 00:26
Also, for what it is worth for anyone else that might be coming here looking for info. The package is installing for me anyway, as root, so it is not necessarily the same issue as above with permissions. It just looks like the integration is not seeing the package in the correct location. It's getting installed just fine to the deps folder:

```
k3s-prod-01:/config/deps# ls -al | grep music
drwxr-xr-x    5 root     root             7 Oct 14 05:26 music_assistant
drwxr-xr-x    2 root     root             8 Oct 14 05:26 music_assistant-2.2.4.dist-info
```

I will look into the code next to see if I can tell why it doesn't see the package.

**Comment by danielgoepp** [comment] 2024-10-16 01:06
Last post, and I'm done. I have it working now. It will persist a delete of the container, which is all I wanted to make sure of since the work around of doing a pip install manually would not. I also acknowledge that I believe this is an HA issue with recent changes to python package management. I don't know what changed exactly, but it broke things. This post is informational for future readers that might stumble on this with similar issues.

The new HA package install puts the packages in:
```
/config/deps
```
but previously it was putting them in:
```
/config/deps/lib/python3.12/site-packages
```
I just moved the music assistant package and it all works fine now:
```
k3s-prod-03:/config/deps/lib/python3.12/site-packages# ls -al | grep music_assistant
drwxr-xr-x    6 root     root             8 Oct 15 20:55 music_assistant
drwxr-xr-x    2 root     root             8 Oct 14 05:26 music_assistant-2.2.4.dist-info
```

**Comment by X-dark** [comment] 2024-10-16 09:55
Hi,
In my case this is neither related to K8s nor non-root user running in container as this is not my setup.

Anyway, symlinking `/config/deps/lib/python3.12/site-packages` to `/config/deps` fixes this integration and another one that had a similar issue.

I guess this is related to `uv` not installing dependencies in expected location, so maybe more a HA issue.

**Comment by marcelveldt** [comment] 2024-10-16 10:32
Maybe it will be good to report your findings to the HA core devs through this report or a new one ?
https://github.com/home-assistant/core/issues/128214

**Comment by danielgoepp** [comment] 2024-10-16 10:43
@marcelveldt yes, I was going to update that. I was playing around a bit more here on the HA side to see if I could break / fix things further before updating there, so as to provide better details. It is true this thread is dead here as the problem is not music assistant. I will definitely bring this up in the HA world. Thanks.
