### ISSUE TITLE
MA Keeps reloading possibly due to unusually named Spotify track

### ISSUE THREAD

**Issue by bruvv** [music-assistant/hass-music-assistant#2674] opened 2024-07-24 21:42 UTC
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I had my spotify connected first, that worked fine. I then added Tune-In and youtube music and since then I can not load my spotify liked playlist it just keeps refreshing, please see screen recording:
https://photos.app.goo.gl/HqqVZqj69bYH2zxH7
This happens in firefox on my macos device.

### How to reproduce

Link spotify, then youtube music and tune-in and see that the liked playlist is not working.

### Music Providers

Spotify
Youtube music
Tune-in

### Player Providers

Chromecast (n.a.)

### Full log output

[music-assistant.log.log](https://github.com/user-attachments/files/16367704/music-assistant.log.log)

### What version of Home Assistant Core are your running

2024.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment] 2024-07-26 02:56
Please review the troubleshooting page again and supply all requested information

**Comment by bruvv** [comment] 2024-07-27 13:46
Thanks anything in specific that you are revering to? I did read it and did provide as much info I think was relevant. What I did not mention is that this is after a fresh installation this happens.

**Comment by OzGav** [comment] 2024-07-27 22:28
Your title suggests MA doesn’t work at all. The report though makes me think you are only having issues with Spotify. Please detail what does work and what you have done to narrow down the problem, specifically what you have tried on the troubleshooting page that hasn’t helped.

**Comment by bruvv** [comment] 2024-07-28 09:02
@OzGav i changed the title, did you watch the screen recording at all? It is pretty clear in my opinion what is going on. My setup is straight forward, it is home assistant OS, nothing special and no special networking stuff going on. Just plain simple, installed MA, connected spotify and I cannot open my liked playlist. I tried clearing the cache but that did not work. I removed the provider, cleared cache, reloggedin to spotify provider and did not work either. While going through the log I also found some yt music errors and posted another issue: https://github.com/music-assistant/hass-music-assistant/issues/2694

**Comment by OzGav** [comment] 2024-07-28 09:11
Yes but you said 
> Link spotify, then youtube music and tune-in and see that the liked playlist is not working.

so it seems like YouTube music and TuneIn need to be also added before this occurs. So is that the case or is it only a Spotify issue that is not dependant on any other music provider being installed,

**Comment by bruvv** [comment] 2024-07-28 09:47
I see what you mean, i just did a fresh installation with only spotify and still the same thing is happening... anything else I can do to debug this?

**Comment by OzGav** [comment] 2024-07-28 09:56
Try a different playlist, try a different browser. All my playlists load fine. I went to check your log but you have enabled debug mode which we ask that you don’t do unless asked. So you can attach the full log without debug mode.

**Comment by bruvv** [comment] 2024-07-28 10:12
As can be seen in the video other playlists work fine, it is just my liked playlist from spotify. I tried chrome and safari too and even the macos companion app it is all the same result. I enabled debug mode only to show case this issue, disabled it afterwards.

**Comment by OzGav** [comment] 2024-07-28 10:22
Then probably go to Spotify and look at what tracks are in there. 
What was going on though when you looked at a different playlist and went back and it jumped back to the ADDON view of HA?

**Comment by bruvv** [comment] 2024-07-28 10:33
Very good question for some reason it jumped me back to the addon page instead of the ingress page... did not happen afterwards. Alright issue found, it was a specific song I guess, i just moved the order around in my spotify app and now it is working just fine... I guess a spotify error ?

**Comment by bruvv** [comment] 2024-07-28 11:26
Ps i think it was this song: https://open.spotify.com/track/55meeb1WffJW16DfMnWVi0?si=UFe31sQiQsycO9rPHO-FRA&nd=1&dlsi=4a6e1cbbf734427b it has some weird characters could that be it?

**Comment by OzGav** [comment] 2024-07-28 17:04
I’ll keep this open for Marcel to have a look at eventually as ideally MA would handle this edge case.

**Comment by OzGav** [comment] 2024-08-20 22:36
Hi @bruvv just wanted to check in whether this is still an issue on the latest MA version?

**Comment by marcelveldt** [comment] 2024-08-21 00:10
This is a duplicate of https://github.com/music-assistant/hass-music-assistant/issues/2704

**Comment by bruvv** [comment] 2024-08-21 06:21
Yes still an issue. And i think Marcel is very right. When i just use Firefox on my phone to access it. It works fine. So this looks like a websocket issue. Shall we close this one in favor of the other ticket ?

**Comment by OzGav** [comment] 2024-08-21 06:52
What browser is causing the issue?

**Comment by bruvv** [comment] 2024-08-21 06:55
It's the home assistant android app. When accessing ma via ha ingress and my playlist is more than 1300 songs it will start flashing and reloading the page. When using a browsers to access ma directly it works just fine. So it has to do something with ingress. Instead of MA.

**Comment by OzGav** [comment] 2024-08-21 06:55
OK then this is a duplicate and I think we can close this one?

**Closed** 2024-08-21 07:43 UTC
Labels: duplicate
