### ISSUE TITLE
volume button in phone

### ISSUE THREAD

**Issue by LukaszP2** [music-assistant/hass-music-assistant#350] opened 2022-06-15 22:41 UTC
Can you add volume control from mobile app by volume button?

**Comment by erkr** [comment] 2022-06-16 07:56
Thanks for the suggestion! If you rotate the screen it probably will be there already.
It's only missing in portrait mode on my phone

**Comment by marcelveldt** [comment] 2022-06-16 07:57
I think he means to actually use the volume controls (the physical buttons) to control volume of the active player in MA

**Comment by LukaszP2** [comment] 2022-06-16 10:09
> I think he means to actually use the volume controls (the physical buttons) to control volume of the active player in MA

Yes, physical buttons. It's natural I think

**Comment by erkr** [comment] 2022-06-18 17:52
This request is a duplicate of the linked discussion #378

**Closed by erkr** 2022-06-18 17:52 UTC
Labels: enhancement
