### ISSUE TITLE
Sonos speakers regularly not found/not available

### ISSUE THREAD

**Issue by HA-TB303** [music-assistant/hass-music-assistant#2257] opened 2024-05-12 09:04 UTC
### What version of Music Assistant has the issue?

2.0.2

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Sonos speakers are either regularly not found or appear "not (yet) available" in MA. 

This mostly happens on battery powered speakers, but I can also easily reproduce on a normal speaker and even on ethernet connected speakers.

### How to reproduce

Unplug/Turn off a speaker, want 10 minutes, check: httpp://ha_ip:8123/d5369777_music_assistant_beta/ingress
One or more speakers appear like:
![CleanShot 2024-05-12 at 10 58 26](https://github.com/music-assistant/hass-music-assistant/assets/9609805/2354440b-71ce-4a26-a90b-a9001d13536f)

Then check the home assistant sonos integration if speakers are actually offline:
![CleanShot 2024-05-12 at 10 59 20](https://github.com/music-assistant/hass-music-assistant/assets/9609805/809102af-703a-4c7f-98f1-b3db5a4cdc57)

In this case all speakers appeared unavailable in MA, when in fact only the 'logeerkamer' (A Sonos Roam) was unavailable at that time (turned off). The rest appeared **ONLINE** in the HA integration.
Even woonkamer (a ethernet connected Sonos ARC) appeared offline in MA, but was online in the HA integration.

Disabling the speaker in MA and then enabling it again mostly "fixes"  it.

This makes Sonos quit unusable within MA.

### Music Providers

Youtube music
RadioBrowser
Music Assistant

### Player Providers

(only) Sonos

### Full log output

N/A (I can send on request, too much private information in there)

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by HA-TB303** [comment] 2024-05-12 09:17
Some extra info:

**Reproduction path:**
All speakers are turned on and everything works well:
![CleanShot 2024-05-12 at 11 13 54](https://github.com/music-assistant/hass-music-assistant/assets/9609805/e5f44f89-37d7-4f9a-b173-2079df8a32b8)
I then physically turn off The Sonos Roam (logeerkamer):
Within 3 seconds:
![CleanShot 2024-05-12 at 11 15 07](https://github.com/music-assistant/hass-music-assistant/assets/9609805/efbd4c4e-edef-40cb-ab04-934a630d411f)
I then turn on the logeerkamer (sonos roam) again:
![CleanShot 2024-05-12 at 11 16 18](https://github.com/music-assistant/hass-music-assistant/assets/9609805/6e9c1967-255a-47d8-bb38-9e6f0d0616af)
This took only 1t5 seconds.....

Sometimes it takes longer and then disabling and enabling each speaker within MA resolves the issue.

**Comment by HA-TB303** [comment] 2024-05-12 09:23
Just repeated the exact same proces but now checked the Home Assistant Music Assistant addons logs:

I did so at 11:19h.

2024-05-12 11:20:14.812 WARNING (MainThread) [music_assistant.providers.sonos] No recent activity and cannot reach Logeerkamer, marking unavailable
2024-05-12 11:20:25.395 WARNING (MainThread) [soco.events_asyncio] Could not bind to 192.168.207.101:1400: [Errno 98] Address already in use
2024-05-12 11:22:25.542 WARNING (MainThread) [soco.events_asyncio] Could not bind to 192.168.207.101:1400: [Errno 98] Address already in use

**Comment by marcelveldt** [comment] 2024-05-12 09:34
Looks like you have both the Sonos integration in HA active as the Sonos provider in MA, so only one of the 2 actually gets devices updates, causing issues like you describe here (as both are based on the same library). We are however going to switch MA to the new Sonos API due to more reports we're seeing (and because the old API is going to be deprecated by Sonos).

Temporary solution could be to not use the Sonos integration in HA (and only/just) use MA's players.
Switching over the Sonos API is one of the important things for the next release btw.

**Comment by HA-TB303** [comment] 2024-05-12 09:40
Ah ok, I was totally unaware those should not be used at the same time. I even thought having the speakers working within HA was a requirement for MA to be able to use them.

I'll try disabling it in HA.

**Comment by HA-TB303** [comment] 2024-05-12 09:43
After removing the Sonos integration in HA ,restarting HA and reproducing it the same way, I so not notice any difference. Still the same issue. :(

I am glad to read Sonos is getting some extra love in MA soon :)

**Comment by HA-TB303** [comment] 2024-05-12 10:04
Some important thing to add:

When turning off the Sonos roam speaker and then disabling/enabling all other (unavailable) speakers in MA, WON'T fix the issue and all speakers remain unusable, even though those are physically switched on and available in the Sonos app.
The only way to get all other speakers working again is to turn on the battery powered Sonos Roam.

**Comment by HA-TB303** [comment] 2024-05-12 10:20
I tried reproducing the issues the same way, but then with the ERA100 mains powered speaker. 

If I unplug that speaker all speakers remain available, on y the ERA 100 (Badkamer) goes offline after approximately 1 minute after unplugging it.

![CleanShot 2024-05-12 at 12 13 58](https://github.com/music-assistant/hass-music-assistant/assets/9609805/e91f52a9-6fb3-4fed-9073-ba0f2009cf32)

So I repeated this with one other battery powered speaker (the Sonos Move 2). If I physically turn off the Move 2 (keuken), all other speakers go offline. If I turn it on after some time all speaker go back online.

So it is safe to say this issue only appears when switching off a battery powered speaker and the issue must be within MA, since this does work correctly with the HA sonos integration. 

It seems best to retest this after you guys switch to the new Sonos API and this issues get's parked until then.

**Comment by Thyraz** [comment] 2024-05-13 11:06
Discovered exactly the same behavior with a Sonos Move here.
Thanks for the testing and the outlook to the new Sonos API. 🙂

**Comment by MuscleGeek69** [comment] 2024-07-11 13:09
I have the same or similar problem.

Env:

Sonos Arc
HA VM on ESXI
UniFi equipment with mDNS and IGMP snooping turned on
HA and sonos are on different networks
HA detects and works with my Sonos speaker just fine, networks are not filtered for now

**Comment by goobags** [comment] 2024-07-14 07:48
I also unknowingly replicated this fault when my Roam went offline. Every 2 minutes the other devices would come back online for a very short period of time then back off again.

**Comment by Herazio** [comment] 2024-07-16 16:14
I've had this issue for quite a while now, also in the Beta versions, but I'm glad someone was able to reproduce it. 
Is there currently a way to exempt certain players from being discovered on the network as a workaround, so that we can exclude the battery powered devices, based on ID or MAC or? 

If I remove the Sonos Roam, obviously it will get picked up again once it actually comes back online so it gets added automagically towards MA. Just looking for a quick-fix for now so that we can enjoy MA ;).

Thanks!

**Comment by marcelveldt** [comment] 2024-07-21 22:42
The new Sonos implementation is still WIP and should land in the new 2.2 beta very soon.
In the meanwhile did you check if enabling "allow network scan" in the Sonos provider settings makes any impact ?
I believe HA has that one enabled by default (and we dont)

**Comment by HA-TB303** [comment] 2024-08-21 04:19
Please keep this open as it’s not resolved.yet.

**Comment by OzGav** [comment] 2024-08-21 04:34
You didn't answer Marcel's question

**Comment by goobags** [comment] 2024-08-21 08:15
I had this issue previously. I removed the Sonos integration and relied solely on the MA/Sonos integration. I enabled the network scan as suggested by @marcelveldt and tested it over the weekend. Sonos Roam was not on the network as it had gone to sleep, and was not visible in MA however the other speakers continued to function. I would suggest checking that option and trying again.

**Comment by HA-TB303** [comment] 2024-08-21 11:38
> The new Sonos implementation is still WIP and should land in the new 2.2 beta very soon. In the meanwhile did you check if enabling "allow network scan" in the Sonos provider settings makes any impact ? I believe HA has that one enabled by default (and we dont)

Sorry, missed this question.
Yes it is/was on:
![CleanShot 2024-08-21 at 13 36 58](https://github.com/user-attachments/assets/cf3a468e-2070-48c4-aea6-85f2a046c54c)

Issue still remains.
![CleanShot 2024-08-21 at 13 38 01](https://github.com/user-attachments/assets/1ff1da19-63eb-479d-8aca-0cc89f558279)

**Comment by OzGav** [comment] 2024-08-24 04:37
Please confirm this has been fixed with the release of the new Sonos provider in 2.2.0 beta 3

**Comment by HA-TB303** [comment] 2024-08-24 06:45
Hi, Im running version: 2.2.2 (no beta). Does that contain the fix?

**Comment by OzGav** [comment] 2024-08-24 08:02
@HA-TB303 No it is beta only

**Comment by HA-TB303** [comment] 2024-08-24 08:13
Ok, can I switch from release to beta without loosing settings and playlists?

**Comment by HA-TB303** [comment] 2024-08-24 08:56
Hi, it's not fixed in beta. Some result.

Starting point:
![CleanShot 2024-08-24 at 10 46 10](https://github.com/user-attachments/assets/ef177b32-3e6c-48ee-acfa-19fa5c70d030)

I then switch on the Sonos Roam (logeerkamer). Nothing happens, HA and The Sonos App have allready detected the speaker.
Only when I refresh the page above, I get:
![CleanShot 2024-08-24 at 10 48 14](https://github.com/user-attachments/assets/e7b97b93-e7d2-495c-9a97-b75d9d95eec6)

I then try playing A Song from YouTube Music to the "Test Group" which contains the Sonos "Kantoor", "Keuken" and "Logeerkamer".

Does not work (on any speaker).

So I turn off the group:
![CleanShot 2024-08-24 at 10 50 48](https://github.com/user-attachments/assets/c1f76600-5ae2-46df-9578-069d91810bc3)

And the play to the "Logeerkamer"  (sonos roam) only:

Works.

The speakers availability and grouping works fine from Home Assistant and the Sonos app.

So it's still pretty much unusable :(

**Comment by HA-TB303** [comment] 2024-08-24 08:59
I forgot to mention that when tuning the Sonos Roam (logeerkamer) off, this is not detected at all by MA in contrast to the HA integration that has the updated state right away.
![CleanShot 2024-08-24 at 10 59 03](https://github.com/user-attachments/assets/ae5c61b8-a0ce-441b-ad3e-e1017b2908aa)

**Comment by HA-TB303** [comment] 2024-08-24 09:01
Same thing when turning the speaker on again:
![CleanShot 2024-08-24 at 11 00 51](https://github.com/user-attachments/assets/e0d58cc4-f6f5-4571-917b-c41fed58d667)

**Comment by HA-TB303** [comment] 2024-08-24 09:11
Maybe park this issue until this is implemented:
https://github.com/orgs/music-assistant/projects/2?pane=issue&itemId=59022273
 and then retest?

**Comment by OzGav** [comment] 2024-08-26 00:25
@HA-TB303 That has been completed. Please check if this is still an issue with 2.3.0 beta 5 (or above)

**Comment by HA-TB303** [comment] 2024-08-26 11:06
Hi, I repeated the same test. When switching the Sonos Roam off, this is noticed right away. 

I then turned it off I waited 3 minutes and refreshed the page, but the speaker still appears online.

I then turned it on again and played some song to the test group (which contains the sonos roam). This now works.

When then again switching the Sonos Roam off, it still appears online in MA. Even after 3 minutes and refreshing the UI.

**Comment by OzGav** [comment] 2024-08-26 11:19
OK that doesn't seem to be related to your intial report. The initial report is about speakers being unavailable. If that aspect is fixed then this report can be closed. 

Players taking a little time to be detected as offline is to be somewhat expected.

**Comment by OzGav** [comment] 2024-09-02 11:57
@HA-TB303 Is the topic of your original report resolved or is it covered by one of the other open issues?

**Comment by HA-TB303** [comment] 2024-09-03 08:21
I have to retest with the lastest version, but I am abroad now and not able to retest before Wednesday.

**Comment by HA-TB303** [comment] 2024-09-04 16:38
Hi, yes this seems to be resolved!

**Comment by marcelveldt** [comment] 2024-09-04 16:52
OK great, so the original issue is resolved now with the new S2 provider. Now just focus on the handful of leftover issues with that, such as the battery powered speaker going online-offline-online you reported.

**Closed by marcelveldt** 2024-09-04 16:52 UTC
Labels: bug, More info, Fix to be Confirmed, Sonos
