### ISSUE TITLE
Radio stations on homescreen - maybe a question, not an error

### ISSUE THREAD

**Issue by melwinek** [music-assistant/hass-music-assistant#1756] opened 2024-01-03 09:36 UTC
### What version of Music Assistant has the issue?

2.0.0b80

### The problem

The home screen shows radio stations that no longer exist.
![image](https://github.com/music-assistant/hass-music-assistant/assets/10649327/d90e66d4-685f-4d20-a4da-1dbe28cd4d68)
![image](https://github.com/music-assistant/hass-music-assistant/assets/10649327/cd90cf8b-853e-4c4d-a8c6-d39fba7eda38)

### How to reproduce

Add a radio station and then delete it.

### What version of Home Assistant Core are your running

2023.12.4

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment] 2024-01-03 11:22
They are pulled from your favourites, I'm guessing TuneIn?

**Comment by OzGav** [comment] 2024-01-03 12:19
How are you adding and deleting these stations?

**Comment by melwinek** [comment] 2024-01-03 15:30
From Radio browser
![Screenshot_20240103-162737_Pixel Launcher~2](https://github.com/music-assistant/hass-music-assistant/assets/10649327/93a80274-7812-4d36-95a4-b0a12d738987)

**Comment by OzGav** [comment] 2024-01-06 09:52
I was unable to reproduce this. The station disappeared from the Home Screen as soon as I removed it from the library. 

Can you try adding those stations back into your library and then once the Home Screen and the radio screen look the same then try removing one and see if it is removed correctly.

**Comment by melwinek** [comment] 2024-01-06 10:09
It doesn't remove itself from the home screen.

Log:
`2024-01-06 10:03:12.319 ERROR (MainThread) [music_assistant.webserver] [140450274436368] Error handling message: CommandMessage(message_id=22, command='music/favorites/remove_item', args={'media_type': 'radio', 'library_item_id': '38996cf5-f44c-470e-b7d7-59ea9fa8c298'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 373, in remove_item_from_favorites
    await ctrl.set_favorite(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 412, in set_favorite
    db_id = int(item_id)  # ensure integer
            ^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '38996cf5-f44c-470e-b7d7-59ea9fa8c298'
2024-01-06 10:04:16.941 INFO (MainThread) [music_assistant.providers.radiobrowser] Provider RadioBrowser does not support library edit, the action will only be performed in the local database.`

**Comment by OzGav** [comment] 2024-01-06 10:11
You screenshot above shows me how you are adding the station to the library. Please show a screenshot of how you are removing the station

**Comment by melwinek** [comment] 2024-01-08 08:00
In the same way. Using "remove from library". At this point I dealt with it the brute force way, I opened library.db in HeidiSQL and cleaned up the tables.

**Comment by OzGav** [comment] 2024-01-08 08:04
Yeah OK I don't think you can remove it from the browse view...I can't. I remove it via the RADIO view

**Comment by OzGav** [comment] 2024-01-08 08:05
Unless of course all this happened during the recent DB upgrade and something got messed up

**Comment by melwinek** [comment] 2024-01-08 09:10
I'm not entirely sure yet. But I think I know what the problem is. I had RadioBrowser added in MA and in HA integrations. When I removed it from HA, the problems seemed to go away.

**Comment by OzGav** [comment] 2024-01-08 10:31
Weird as there is no link that way that I know of but if this is resolved we might close it?

**Comment by melwinek** [comment] 2024-01-10 06:45
However, the above was not a problem.
But I think I found a mistake.
If table "playlog" is empty. Radio stations on homescreen are correct.
![image](https://github.com/music-assistant/hass-music-assistant/assets/10649327/d80138e1-8fd0-4be7-98c5-42a254b9d359)
Then if I turn on each station one by one and the "playlog" table will be filled with entries.
![image](https://github.com/music-assistant/hass-music-assistant/assets/10649327/cde9a521-1104-4bd2-9ea7-76f6b676552c)
The stations on the homescreen are duplicated.
![image](https://github.com/music-assistant/hass-music-assistant/assets/10649327/36a6b04f-900b-4888-ab11-9826d27dafab)
After clearing the "playlog" table again, everything is fine again. And it stays like this all the time.

This is my station list:
![image](https://github.com/music-assistant/hass-music-assistant/assets/10649327/ceafc695-d266-4a94-b5dc-bbf747b27051)

**Comment by marcelveldt** [comment] 2024-01-14 00:22
The homescreen shows a list a list of items based on what was recently played AND what's in the library.
But I agree that is a bit strange, we should limit to library items only and filter on what has recently been played.

**Comment by marcelveldt** [comment] 2024-02-21 10:41
This one is fixed in b103

**Closed by marcelveldt** 2024-02-21 10:41 UTC
Labels: enhancement
