### ISSUE TITLE
New to MASS, End of song doesnt actually end on Fully Kiosk 

### ISSUE THREAD

**Issue by Sineater224** [music-assistant/hass-music-assistant#2367] opened 2024-05-26 16:15 UTC
### What version of Music Assistant has the issue?

2024.4.0

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Im trying to get Music Assistant playing out of a Fire Tablet I have configured with Fully Kiosk Browser. When I play it, it plays fine, but it wont progress to the next song. When I output the audio to any chromecast device, it works fine and plays an entire playlist. 

When I try to play a playlist on the fully kiosk tablet, it will not end the song and move on to the next. Like, if the song is 4:30 long, it will reach 4:30 and the sound will stop, but the play bar still keeps counting until I manually switch songs. 

I left it for 10 minutes on the 4:30 song, and it said 14:30/4:30

https://github.com/music-assistant/hass-music-assistant/assets/39151233/ef0dbb04-5c8d-4054-a73c-6f923e74a34b

. It just keeps counting without playing or progressing to the next song. Any ideas? Again, this is ONLY on Fully Kiosk Browser

### How to reproduce

Use the newest BETA version, trying to play music THROUGH the fully kiosk player as a "player". Pick any song and it will not properly finish the song

### Music Providers

Spotify

### Player Providers

Spotify, but playing it as a Chromecast "Player"

### What version of Home Assistant Core are your running

2024.5.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment] 2024-05-26 22:26
Is QUEUE FLOW MODE enabled in the player settings?

**Comment by Sineater224** [comment] 2024-05-26 23:06
> Is QUEUE FLOW MODE enabled in the player settings?

Yes Ive tried with it on and with it off, and it still does the same thing

**Comment by OzGav** [comment] 2024-05-26 23:57
Ok confirmed. This will get looked at in due course

**Comment by jaynis** [comment] 2024-05-27 10:27
I am experiencing the same behavior on latest HA / latest MA when playing songs via the YouTube Music provider on a HA media player. So I guess the problem is not limited to the kiosk browser. Furthermore, it seems to happen intermittently: Sometimes MA smoothly progresses through a playlist without interruptions and sometimes I have the faulty behavior. Havent figured out yet when exactly it happens.

**Comment by pgale** [comment] 2024-06-04 08:03
This is a duplicate of #2274 

Hopefully this is actually being looked at as it prevents MA from being used.

**Closed** 2024-06-04 22:26 UTC
Labels: bug
